#!/bin/sh
# Regression tests for the rebuilt cofdmp: compares it with the original.
# Run from tests/cofdmp after building build/cofdmp.exe:
#   sh run.sh            (inputs are regenerated by mkinputs.sh / mkcoff.py)
# x_stbig, x_stwrap (malloc of ~2 GB: fails in the original depending on the
# address space) and x_rawbig (original prints heap memory) are not compared.
# Prints one OK line per test, or the differences; exit status = failures.

C="python ../compare.py"
fail=0
t() {
    r=$($C "$@" 2>&1)
    echo "$r" | head -40
    case "$r" in OK*) ;; *) fail=$((fail + 1)) ;; esac
}

ASM="r1.cln r2.cln r3.cln t2.cln t2g.cln lnki.cln lnk3i.cln ovlr.cln t1.cld t2g.cld lnk.cld lnkg.cld lnk3.cld ovl.cld ovll.cld strip.cld"

# every option alone and symbolic, on every assembler/linker output
for f in $ASM; do
    t cofdmp $f
    t cofdmp -v $f
    for o in c f h l o r s t; do
        t cofdmp -q -$o $f
        t cofdmp -q -$o -v $f
    done
    t cofdmp -q -x -v $f
done

# option handling
t cofdmp
t cofdmp -q
t cofdmp -v
t cofdmp -e r1.cln
t cofdmp -q -e r1.cln
t cofdmp -: r1.cln
t cofdmp -d
t cofdmp -q -d
t cofdmp -fz r1.cln
t cofdmp -dout.txt r1.cln
t cofdmp -d out.txt -v r1.cln t1.cld
t cofdmp -D out.txt -F r1.cln
t cofdmp -q -d out.txt
t cofdmp -d nodir/out.txt r1.cln
t cofdmp -d . r1.cln
t cofdmp -FHV r1.cln
t cofdmp -fhv r1.cln
t cofdmp -vf r1.cln
t cofdmp -v -f -f r1.cln
t cofdmp -q -Q -X -V r1.cln
t cofdmp -xq r1.cln
t cofdmp -dq r1.cln
t cofdmp -o -- r1.cln
t cofdmp -o -- -q
t cofdmp -- r1.cln t1.cld
t cofdmp -q r1.cln -v
t cofdmp -q -c r1.cln t1.cld strip.cld
t cofdmp -q -c -v strip.cld r1.cln
t cofdmp -q -t -v r1.cln strip.cld t2g.cln
t cofdmp -q -v r1.cln missing.cln t1.cld
t cofdmp -q missing.cln
t cofdmp -q x_text.txt
t cofdmp -q x_short.bin
t cofdmp -q x_empty.bin
t cofdmp -q r1.asm
t cofdmp -q -v r1.cln r3.cln r2.cln t1.cld t2g.cld lnkg.cld
t cofdmp -q -v -x r1.cln r3.cln r2.cln t1.cld t2g.cld lnkg.cld
t --stdin r1.cln cofdmp -q -
t --stdin r1.cln cofdmp -q -f -o -
t --stdin t1.cld cofdmp -q -v -
t --stdin r1.cln cofdmp -q -- -
t --stdin x_text.txt cofdmp -q -

# hand-made files (mkcoff.py)
for f in x_*.cl?; do
    case $f in x_stbig.cln|x_stwrap.cln|x_rawbig.cln) continue ;; esac
    t cofdmp -q $f
    t cofdmp -q -v $f
    t cofdmp -q -x -v $f
    t cofdmp -q -t -v $f
    t cofdmp -q -h -o -f $f
done
t cofdmp -q -h -v -x x_misc.cln
t cofdmp -q -t -c -v -x x_misc.cln
t cofdmp -q -o r1.cln x_old1.cln r2.cln
t cofdmp -q -v -o -t x_ovfa.cld r1.cln x_ovfa.cld
t cofdmp -q -v r1.cln x_ovfl.cln
t cofdmp -q -v -c r1.cln x_stnone.cln x_st0.cln x_old3.cln
t cofdmp -q -v -f x_t0.cln x_t1.cln x_t2.cln x_t3.cln x_t4.cln x_t5.cln x_t6.cln x_t7.cln x_t8.cln x_t9.cln x_t10.cln x_t11.cln
t cofdmp -q -v -f -x x_t6.cln
t cofdmp -q -s -v x_rawsk.cln
t cofdmp -q -h -v x_nscns.cln
t cofdmp -q -h -v x_nscneg.cln

echo "failures: $fail"
exit $fail
