/* alu.c - SIM56000.EXE v6.3 (CLAS56), ALU of the core simulator and the peripheral lookup helpers (module alu).
 * The ALU works on the core register file `alu_core`; the original addresses it by byte offset (+0x45c/+0x460/+0x464
 * operand 1 ext:hi:lo... see re/notes/SIM56000/devinit_asm.md), here it is an array of 32-bit words: W(offset).
 * Most functions are generated by re/scripts/g2c_alu.py from the Ghidra output.  Words hold 32-bit values in an
 * unsigned long; SI() reads one as a signed int, ST() truncates a result to 32 bits. */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "sim56000.h"
#include "simdata.h"
#include "simproto.h"

unsigned long *alu_core;            /* 0x4dc144 core register file being operated on */
unsigned long alu_ccr;              /* 0x4dc13c CCR collected by the operation */
long alu_flag;                      /* 0x4dc140 0 = the handler took care of the CCR write back */

#define W(off) (alu_core[(off) >> 2])
#define ST(x) ((unsigned long)(x) & 0xffffffffUL)
#define SI(x) ((long)(((unsigned long)(x) & 0xffffffffUL) ^ 0x80000000UL) - 0x80000000L)
#define SC(x) ((long)(((unsigned long)(x) & 0xffUL) ^ 0x80UL) - 0x80L)

void alu_h_4325f0(void);
void alu_h_432a70(void);

/* opcode validity: 0 = invalid, 1 = valid, 2 = valid without further checks */
long insn_validate(unsigned long opw, unsigned long devflags)
{
    long r;

    r = ((long (*)(unsigned long))insn_valid_handlers[opclass_lookup(opw, devflags)])(opw);
    if (r == 2)
        return 2;
    return r == 0;
}

/* sign extension word of the 24 bit word in core word src -> core word dst */
void sign_ext_word(long src, long dst)
{
    if (0x7fffffL < SI(alu_core[src]))
        alu_core[dst] = 0xff;
    else
        alu_core[dst] = 0;
}

void alu_load_src(long mode)
{
    unsigned long src;

    if (SI(W(0x1c8)) == 300 || SI(W(0x1c8)) == 2) {
        core_read_copy(1, 0x11a);
        core_read_copy(2, 0x11b);
        src = 3;
    } else {
        core_read_copy(5, 0x11a);
        core_read_copy(6, 0x11b);
        src = 7;
    }
    core_read_copy(src, 0x11c);
    if (mode == 0)
        core_read_copy(W(0x1c0), 0x117);
    else
        W(0x45c) = ST(d_4c4e50[(SI(W(0x1c0)) >> 8) & 0x1f]);
    core_read_copy(W(0x1c4), 0x118);
}

/* one bit shift of the accumulator (ASL/ASR family; called with the core directly) */
void alu_shift1(void *core)
{
    unsigned long uVar1, uVar2;
    long src;

    alu_core = (unsigned long *)core;
    alu_ccr = W(0x9c);
    uVar2 = (unsigned long)((SI(W(0x184)) >> 8) & 7);
    src = (uVar2 > 3) + 0x4d;
    W(0x1c8) = ST(((W(0x184) & 8) | 0x960) >> 3);
    uVar1 = alu_ccr;
    alu_ccr = ST(alu_ccr & 0xffffffc1UL);
    alu_load_acc();
    if ((uVar1 & 0x20) == 0) {
        if ((uVar1 & 0x10) == 0 || (uVar1 & 4) != 0) {
            W(0x474) = W(0x468);
            W(0x478) = W(0x46c);
            W(0x47c) = W(0x470);
        } else {
            W(0x474) = ST(SI(W(0x468)) << 1);
            W(0x478) = ST(SI(W(0x46c)) << 1);
            W(0x47c) = ST(SI(W(0x470)) << 1);
            alu_norm_res();
            alu_core[src] = ST(SI(alu_core[src]) - 1UL) & 0xffff;
            core_copy_reg((long)uVar2 + 0x1e, src);
            uVar1 = W(0x47c) & 0x180;
            if (uVar1 == 0x100 || uVar1 == 0x80)
                alu_ccr = ST(alu_ccr | 2);
        }
    } else {
        W(0x47c) = ST(SI(W(0x470)) / 2);
        if ((W(0x470) & 0x80) != 0)
            W(0x47c) = ST(W(0x47c) | 0x80);
        uVar1 = W(0x46c);
        if ((W(0x470) & 1) == 1)
            uVar1 |= 0x1000000UL;
        W(0x478) = ST(SI(uVar1) / 2);
        uVar1 = W(0x468);
        if ((W(0x46c) & 1) == 1)
            uVar1 |= 0x1000000UL;
        W(0x474) = ST(SI(uVar1) / 2);
        alu_core[src] = ST(SI(alu_core[src]) + 1UL) & 0xffff;
        core_copy_reg((long)uVar2 + 0x1e, src);
    }
    W(0x47c) = W(0x47c) & 0xff;
    W(0x480) = W(0x474);
    W(0x484) = W(0x478);
    W(0x488) = W(0x47c);
    alu_set_ccr();
    alu_store_ext();
}

/* run the ALU operation of the instruction: alu_handlers[core word 0x1b8] */
void alu_execute(void *core)
{
    alu_core = (unsigned long *)core;
    alu_ccr = W(0x9c);
    alu_flag = 1;
    ((void (*)(void))((simfn *)&alu_handlers[0].w1)[SI(W(0x1b8)) - 1])();
    if (SI(W(0x1bc)) != 1 && alu_flag != 0) {
        W(0x9c) = alu_ccr;
        core_touch_reg(0x27);
    }
}

/* ALU alu_handlers[0x18-word] table entry i of the decode tables (the words after the handler functions) */
static long alu_tab(long i)
{
    if (i < 24)
        return ((long *)alu_handlers)[40 + i];
    return d_4c4fb0[i - 24];
}

/* ALU decode: opcode word -> {handler index, 1, operand id, operand 2 id, destination accumulator, flag} */
void alu_decode(unsigned long opw, long *out)
{
    unsigned long uVar1, uVar2, uVar4, uVar6, uVar7, uVar8, uVar9;
    long lVar5, iVar3;

    uVar1 = opw;
    uVar2 = opw & 0xff;
    uVar7 = opw & 8;
    uVar4 = (uVar2 >> 4) & 7;
    if ((opw & 0x80) == 0) {
        uVar8 = opw & 0xfffffe;
        if (cur_dtype->family < 4 || (uVar8 != 8 && uVar8 != 10)) {
            iVar3 = (long)((opw & 7) + uVar4 * 8);
            if (uVar2 == 4 || uVar2 == 8 || uVar2 == 0xc)
                iVar3 = 0x40;
            uVar6 = ST(d_4c5068[uVar2]);
            uVar9 = ST(alu_tab(iVar3));
            if (d_4c5268[iVar3] == 0) {
                uVar4 = 0xfffffffeUL;
                uVar2 = 0;
                lVar5 = -2;
                opw = uVar9;
            } else if (uVar7 == 0) {
                lVar5 = -2;
                uVar4 = ST(((0UL - (d_4c52b0[opw & 0x7f] != 0)) & 0xfffffed6UL) + 300);
                uVar2 = 0;
                opw = uVar9;
            } else {
                lVar5 = -2;
                uVar4 = ST(((0UL - (d_4c52b0[opw & 0x7f] != 0)) & 0xfffffed9UL) + 0x12d);
                uVar2 = 0;
                opw = uVar9;
            }
        } else {
            lVar5 = -2;
            uVar4 = (opw & 1) | 300;
            uVar2 = 0;
            uVar6 = uVar4;
            opw = (uVar8 != 8) + 0x22;
        }
    } else {
        uVar2 = ((~opw) & 4) >> 2;
        if ((opw & 0xff00c0UL) == 0x100c0UL) {
            uVar6 = opw;
            opw = ST(d_4c54f0[opw & 3]);
        } else {
            uVar6 = ST(d_4c54b0[uVar4]);
            opw = ST(d_4c5058[opw & 3]);
        }
        lVar5 = d_4c54d0[uVar4];
        uVar4 = (uVar7 != 0) + 300;
    }
    uVar9 = 0xc;
    if ((uVar1 & 0xffc0c0UL) != 0x18040UL)
        uVar9 = opw;
    out[0] = SI(uVar9);
    out[1] = 1;
    out[2] = SI(uVar6);
    out[3] = lVar5;
    out[4] = SI(uVar4);
    out[5] = SI(uVar2);
}

/* remaining ALU handlers whose entry points Ghidra had folded into a neighbour */
void alu_op_h432120(void)
{
    if (SI(W(0x1bc)) == 1) {
        alu_load_src(1);
        return;
    }
    alu_h_4325f0();
}

void alu_op_h432140(void)
{
    if (SI(W(0x1bc)) == 1) {
        alu_load_src(1);
        return;
    }
    alu_h_432a70();
}

/* alu_h_432160 @ 00432160: subtract (CMP without the CCR carry) */
void alu_h_432160(void)
{
    if (SI(W(0x1bc)) == 1) {
        alu_load_ops();
        return;
    }
    W(0x474) = W(0x468);
    W(0x478) = W(0x46c);
    W(0x47c) = W(0x470);
    W(0x490) = W(0x460);
    W(0x48c) = W(0x45c);
    W(0x494) = W(0x464);
    W(0x480) = ST((~W(0x460) & 0xffffff) + 1);
    W(0x484) = ST(~W(0x45c) & 0xffffff);
    W(0x488) = ST(~W(0x464) & 0xff);
    W(0x480) = ST(W(0x480) + W(0x474));
    W(0x484) = ST(W(0x484) + W(0x478));
    W(0x488) = ST(W(0x488) + W(0x47c));
    alu_norm_sum();
    alu_ccr = ST(alu_ccr & 0xffffffc0UL);
    alu_ovf_c();
    alu_ovf_d();
    alu_set_ccr();
    alu_store_ext();
}

/* ---- peripheral helpers ---- */
void periph_reset(void)
{
    long i, j, n;
    struct periph_desc *pd;
    unsigned long *fl;

    cur_dev->flags = 0;
    cur_sim->var24 = 0;
    n = cur_dtype->n_map;
    for (i = 0; i < n; i++) {
        cur_sim->rstat[i].rd.total = 0;
        cur_sim->rstat[i].wr.total = 0;
    }
    n = cur_dtype->n_periph;
    for (i = 0; i < n; i++) {
        pd = &cur_dtype->periph[i];
        fl = cur_sim->regflags[i].flags;
        for (j = 0; j < pd->def->nreg; j++)
            fl[j] &= ~0x000f0000UL;
    }
}

long periph_call(long devidx, long periph, long a, long b)
{
    cur_dev = dev_tab[devidx];
    cur_dtype = chiptype_tab[cur_dev->type];
    ((void (*)(long, long, long))cur_dtype->periph[periph].def->peek)(periph, a, b);
    return 1;
}

/* find a peripheral register by name: exact match, else "<name><group letter>" where the last character selects
 * the group (its `enable` string starts with that letter) */
long periph_find_reg(long devidx, char *name, long *periph, long *reg)
{
    long i, j, n, len;
    struct periph_desc *pd;
    struct group_def *g;
    char last;

    cur_dev = dev_tab[devidx];
    cur_dtype = chiptype_tab[cur_dev->type];
    n = cur_dtype->n_periph;
    for (i = 0; i < n; i++) {
        pd = &cur_dtype->periph[i];
        if (*(char *)pd->enable == '\0') {
            g = pd->def;
            for (j = 0; j < g->nreg; j++) {
                if (str_icmp((char *)g->regs[j].name, name) == 0) {
                    *periph = i;
                    *reg = j;
                    return 1;
                }
            }
        }
    }
    len = (long)strlen(name) - 1;
    last = name[len];
    for (i = 0; i < n; i++) {
        pd = &cur_dtype->periph[i];
        if (last == *(char *)pd->enable) {
            g = pd->def;
            for (j = 0; j < g->nreg; j++) {
                if ((long)strlen(g->regs[j].name) == len && str_nicmp((char *)g->regs[j].name, name, len) == 0) {
                    *periph = i;
                    *reg = j;
                    return 1;
                }
            }
        }
    }
    return 0;
}

/* ---- ALU primitives and handlers (generated) ---- */
/* alu_op_h430880 @ 00430880 */
void alu_op_h430880(void)
{
  if (SI(W(0x1bc)) == 1) {
    alu_load_acc();
    return;
  }
  W(0x48c) = ST(0);
  W(0x494) = ST(0);
  if (((W(0x470) & 0xff) & 0x80) == 0) {
    W(0x474) = ST(W(0x468));
    W(0x478) = ST(W(0x46c));
    W(0x47c) = ST(W(0x470));
    W(0x490) = ST(0);
  }
  else {
    W(0x474) = ST(~W(0x468) & 0xffffff);
    W(0x478) = ST(~W(0x46c) & 0xffffff);
    W(0x47c) = ST(~W(0x470) & 0xff);
    W(0x490) = ST(1);
  }
  W(0x480) = ST(SI(W(0x490)) + SI(W(0x474)));
  W(0x484) = ST(SI(W(0x48c)) + SI(W(0x478)));
  W(0x488) = ST(SI(W(0x494)) + SI(W(0x47c)));
  alu_norm_sum();
  alu_ccr = ST(alu_ccr & 0xffffffc1);
  alu_ovf_add();
  alu_set_ccr();
  alu_store_ext();
  return;
}

/* alu_ovf_add @ 004309c0 */
void alu_ovf_add(void)
{
  unsigned long uVar1;
  
  uVar1 = ST(W(0x47c) & 0x80);
  if ((((uVar1 == 0) && (((W(0x494) & 0xff) & 0x80) == 0)) &&
      (((W(0x488) & 0xff) & 0x80) != 0)) ||
     (((uVar1 != 0 && (((W(0x494) & 0xff) & 0x80) != 0)) &&
      (((W(0x488) & 0xff) & 0x80) == 0)))) {
    alu_ccr = ST(alu_ccr | 2);
  }
  return;
}

/* alu_norm_sum @ 00430a10 */
void alu_norm_sum(void)
{
  unsigned long uVar1;
  
  uVar1 = ST(W(0x480));
  if (0xffffff < SI(uVar1)) {
    W(0x480) = ST(uVar1 & 0xffffff);
    W(0x484) = ST(SI(W(0x484)) + (SI(uVar1 + (SI(uVar1) >> 0x1f & 0xffffffU)) >> 0x18));
  }
  uVar1 = ST(W(0x484));
  if (0xffffff < SI(uVar1)) {
    W(0x484) = ST(uVar1 & 0xffffff);
    W(0x488) = ST(SI(W(0x488)) + (SI(uVar1 + (SI(uVar1) >> 0x1f & 0xffffffU)) >> 0x18));
  }
  return;
}

/* alu_op_h430a90 @ 00430a90 */
void alu_op_h430a90(void)
{
  if (SI(W(0x1bc)) == 1) {
    alu_load_ops();
    return;
  }
  W(0x474) = ST(W(0x468));
  W(0x478) = ST(W(0x46c));
  W(0x47c) = ST(W(0x470));
  W(0x490) = ST(W(0x460));
  W(0x48c) = ST(W(0x45c));
  W(0x494) = ST(W(0x464));
  W(0x480) = ST(SI(W(0x460)) + SI(W(0x474)));
  W(0x484) = ST(SI(W(0x45c)) + SI(W(0x478)));
  W(0x488) = ST(SI(W(0x464)) + SI(W(0x47c)));
  if ((alu_ccr & 1) != 0) {
    W(0x480) = ST(SI(W(0x480)) + 1);
  }
  alu_norm_sum();
  alu_ccr = ST(alu_ccr & 0xffffffc0);
  alu_ovf_sub();
  alu_ovf_add();
  alu_set_ccr();
  alu_store_ext();
  return;
}

/* alu_ovf_sub @ 00430b90 */
void alu_ovf_sub(void)
{
  if (((W(0x488) & 0xff) & 0x80) == 0) {
    if (((W(0x494) & 0xff) & 0x80) == 0) {
      if (((W(0x47c) & 0xff) & 0x80) == 0) {
        return;
      }
      alu_ccr = ST(alu_ccr | 1);
      return;
    }
  }
  else {
    if (((W(0x494) & 0xff) & 0x80) == 0) {
      return;
    }
    if (((W(0x47c) & 0xff) & 0x80) == 0) {
      return;
    }
  }
  alu_ccr = ST(alu_ccr | 1);
  return;
}

/* alu_add56 @ 00430be0 */
void alu_add56(void)
{
  if (SI(W(0x1bc)) == 1) {
    alu_load_ops();
    return;
  }
  W(0x474) = ST(W(0x468));
  W(0x478) = ST(W(0x46c));
  W(0x47c) = ST(W(0x470));
  W(0x490) = ST(W(0x460));
  W(0x48c) = ST(W(0x45c));
  W(0x494) = ST(W(0x464));
  W(0x480) = ST(SI(W(0x460)) + SI(W(0x474)));
  W(0x484) = ST(SI(W(0x45c)) + SI(W(0x478)));
  W(0x488) = ST(SI(W(0x464)) + SI(W(0x47c)));
  alu_norm_sum();
  alu_ccr = ST(alu_ccr & 0xffffffc0);
  alu_ovf_sub();
  alu_ovf_add();
  alu_set_ccr();
  alu_store_ext();
  return;
}

/* alu_op_h430cd0 @ 00430cd0 */
void alu_op_h430cd0(void)
{
  unsigned long uVar1;
  
  if (SI(W(0x1bc)) == 1) {
    alu_load_ops();
    return;
  }
  alu_ccr = ST(alu_ccr & 0xffffffc0);
  W(0x474) = ST(SI(W(0x468)) << 1);
  W(0x478) = ST(SI(W(0x46c)) << 1);
  W(0x47c) = ST(SI(W(0x470)) << 1);
  alu_norm_res();
  W(0x490) = ST(W(0x460));
  W(0x48c) = ST(W(0x45c));
  W(0x494) = ST(W(0x464));
  uVar1 = ST(W(0x47c) & 0x180);
  if ((uVar1 == 0x100) || (uVar1 == 0x80)) {
    alu_ccr = ST(alu_ccr | 2);
  }
  W(0x47c) = ST(W(0x47c) & 0xff);
  W(0x480) = ST(SI(W(0x460)) + SI(W(0x474)));
  W(0x484) = ST(SI(W(0x45c)) + SI(W(0x478)));
  W(0x488) = ST(SI(W(0x464)) + SI(W(0x47c)));
  alu_norm_sum();
  alu_ovf_sub();
  alu_ovf_add();
  alu_set_ccr();
  alu_store_ext();
  return;
}

/* alu_norm_res @ 00430e00 */
void alu_norm_res(void)
{
  unsigned long uVar1;
  
  uVar1 = ST(W(0x474));
  if (0xffffff < SI(uVar1)) {
    W(0x474) = ST(uVar1 & 0xffffff);
    W(0x478) = ST(SI(W(0x478)) + (SI(uVar1 + (SI(uVar1) >> 0x1f & 0xffffffU)) >> 0x18));
  }
  uVar1 = ST(W(0x478));
  if (0xffffff < SI(uVar1)) {
    W(0x478) = ST(uVar1 & 0xffffff);
    W(0x47c) = ST(SI(W(0x47c)) + (SI(uVar1 + (SI(uVar1) >> 0x1f & 0xffffffU)) >> 0x18));
  }
  return;
}

/* alu_op_h430e80 @ 00430e80 */
void alu_op_h430e80(void)
{
  unsigned long uVar1;
  
  if (SI(W(0x1bc)) == 1) {
    alu_load_ops();
    return;
  }
  W(0x47c) = ST(SI(W(0x470)) / 2);
  if (((W(0x470) & 0xff) & 0x80) != 0) {
    W(0x47c) = ST(W(0x47c) | 0x80);
  }
  uVar1 = ST(W(0x46c));
  if (((W(0x470) & 0xff) & 1) == 1) {
    uVar1 = ST(uVar1 | 0x1000000);
  }
  W(0x478) = ST(SI(uVar1) / 2);
  uVar1 = ST(W(0x468));
  if (((W(0x46c) & 0xff) & 1) == 1) {
    uVar1 = ST(uVar1 | 0x1000000);
  }
  W(0x474) = ST(SI(uVar1) / 2);
  W(0x490) = ST(W(0x460));
  W(0x48c) = ST(W(0x45c));
  W(0x494) = ST(W(0x464));
  W(0x480) = ST(SI(W(0x490)) + SI(W(0x474)));
  W(0x484) = ST(SI(W(0x48c)) + SI(W(0x478)));
  W(0x488) = ST(SI(W(0x494)) + SI(W(0x47c)));
  alu_norm_sum();
  alu_ccr = ST(alu_ccr & 0xffffffc0);
  alu_ovf_sub();
  alu_ovf_add();
  alu_set_ccr();
  alu_store_ext();
  return;
}

/* alu_op_h430fc0 @ 00430fc0 */
void alu_op_h430fc0(void)
{
  if (SI(W(0x1bc)) == 1) {
    alu_load_ops();
    return;
  }
  W(0x474) = ST(W(0x468));
  W(0x478) = ST(W(0x46c));
  W(0x47c) = ST(W(0x470));
  W(0x484) = ST(W(0x45c) & W(0x478));
  W(0x480) = ST(W(0x474));
  W(0x488) = ST(W(0x47c));
  alu_ccr = ST(alu_ccr & 0xfffffff1);
  if (SI(W(0x484)) == 0) {
    alu_ccr = ST(alu_ccr | 4);
  }
  if ((W(0x484) & 0x800000) != 0) {
    alu_ccr = ST(alu_ccr | 8);
  }
  alu_store_ext();
  return;
}

/* alu_op_h431090 @ 00431090 */
void alu_op_h431090(void)
{
  unsigned long uVar1;
  
  if (SI(W(0x1bc)) == 1) {
    alu_load_acc();
    return;
  }
  W(0x474) = ST(SI(W(0x468)) << 1);
  W(0x478) = ST(SI(W(0x46c)) << 1);
  W(0x47c) = ST(SI(W(0x470)) << 1);
  W(0x480) = ST(W(0x474));
  W(0x484) = ST(W(0x478));
  W(0x488) = ST(W(0x47c));
  alu_norm_sum();
  alu_ccr = ST(alu_ccr & 0xffffffc0);
  if ((W(0x47c) & 0x100) != 0) {
    alu_ccr = ST(alu_ccr | 1);
  }
  uVar1 = ST(W(0x47c) & 0x180);
  if ((uVar1 == 0x100) || (uVar1 == 0x80)) {
    alu_ccr = ST(alu_ccr | 2);
  }
  alu_set_ccr();
  alu_store_ext();
  return;
}

/* alu_op_h431170 @ 00431170 */
void alu_op_h431170(void)
{
  unsigned long uVar1;
  
  if (SI(W(0x1bc)) == 1) {
    alu_load_acc();
    return;
  }
  W(0x47c) = ST(SI(W(0x470)) / 2);
  if (((W(0x470) & 0xff) & 0x80) != 0) {
    W(0x47c) = ST(W(0x47c) | 0x80);
  }
  uVar1 = ST(W(0x46c));
  if (((W(0x470) & 0xff) & 1) == 1) {
    uVar1 = ST(uVar1 | 0x1000000);
  }
  W(0x478) = ST(SI(uVar1) / 2);
  uVar1 = ST(W(0x468));
  if (((W(0x46c) & 0xff) & 1) == 1) {
    uVar1 = ST(uVar1 | 0x1000000);
  }
  W(0x474) = ST(SI(uVar1) / 2);
  alu_ccr = ST(alu_ccr & 0xffffffc0);
  if (((W(0x468) & 0xff) & 1) != 0) {
    alu_ccr = ST(alu_ccr | 1);
  }
  W(0x480) = ST(W(0x474));
  W(0x484) = ST(W(0x478));
  W(0x488) = ST(W(0x47c));
  alu_set_ccr();
  alu_store_ext();
  return;
}

/* alu_op_h431270 @ 00431270 */
void alu_op_h431270(void)
{
  if (SI(W(0x1bc)) == 1) {
    alu_load_src(1);
    return;
  }
  alu_mpy();
  return;
}

/* alu_op_h431290 @ 00431290 */
void alu_op_h431290(void)
{
  if (SI(W(0x1bc)) == 1) {
    alu_load_src(1);
    return;
  }
  alu_mac();
  return;
}

/* alu_op_h4312b0 @ 004312b0 */
void alu_op_h4312b0(void)
{
  if (SI(W(0x1bc)) != 1) {
    W(0x480) = ST(0);
    W(0x484) = ST(0);
    W(0x488) = ST(0);
    alu_ccr = ST(alu_ccr & 0xffffffc1);
    alu_set_ccr();
    alu_store_ext();
    return;
  }
  return;
}

/* alu_op_h431300 @ 00431300 */
void alu_op_h431300(void)
{
  if (SI(W(0x1bc)) == 1) {
    alu_load_ops();
    return;
  }
  W(0x474) = ST(W(0x468));
  W(0x478) = ST(W(0x46c));
  W(0x47c) = ST(W(0x470));
  W(0x490) = ST(W(0x460));
  W(0x48c) = ST(W(0x45c));
  W(0x494) = ST(W(0x464));
  W(0x480) = ST((~W(0x460) & 0xffffff) + 1 + SI(W(0x474)));
  W(0x484) = ST((~W(0x45c) & 0xffffff) + SI(W(0x478)));
  W(0x488) = ST((~W(0x464) & 0xff) + SI(W(0x47c)));
  alu_norm_sum();
  alu_ccr = ST(alu_ccr & 0xffffffc0);
  alu_ovf_c();
  alu_ovf_d();
  alu_set_ccr();
  return;
}

/* alu_ovf_c @ 00431400 */
void alu_ovf_c(void)
{
  if (((W(0x488) & 0xff) & 0x80) == 0) {
    if ((((W(0x494) & 0xff) & 0x80) != 0) && (((W(0x47c) & 0xff) & 0x80) == 0))
    {
      alu_ccr = ST(alu_ccr | 1);
      return;
    }
  }
  else if ((((W(0x494) & 0xff) & 0x80) != 0) ||
          (((W(0x47c) & 0xff) & 0x80) == 0)) {
    alu_ccr = ST(alu_ccr | 1);
  }
  return;
}

/* alu_ovf_d @ 00431450 */
void alu_ovf_d(void)
{
  unsigned long uVar1;
  
  uVar1 = ST(W(0x47c) & 0x80);
  if ((((uVar1 != 0) && (((W(0x494) & 0xff) & 0x80) == 0)) &&
      (((W(0x488) & 0xff) & 0x80) == 0)) ||
     (((uVar1 == 0 && (((W(0x494) & 0xff) & 0x80) != 0)) &&
      (((W(0x488) & 0xff) & 0x80) != 0)))) {
    alu_ccr = ST(alu_ccr | 2);
  }
  return;
}

/* alu_op_h4314a0 @ 004314a0 */
void alu_op_h4314a0(void)
{
  if (SI(W(0x1bc)) == 1) {
    alu_load_ops();
    return;
  }
  if (((W(0x464) & 0xff) & 0x80) == 0) {
    W(0x490) = ST(W(0x460));
    W(0x48c) = ST(W(0x45c));
    W(0x494) = ST(W(0x464));
  }
  else {
    W(0x490) = ST((~W(0x460) & 0xffffff) + 1);
    W(0x48c) = ST(~W(0x45c) & 0xffffff);
    W(0x494) = ST(~W(0x464) & 0xff);
    alu_norm_abs();
  }
  if (((W(0x470) & 0xff) & 0x80) == 0) {
    W(0x474) = ST(W(0x468));
    W(0x478) = ST(W(0x46c));
    W(0x47c) = ST(W(0x470));
  }
  else {
    W(0x474) = ST((~W(0x468) & 0xffffff) + 1);
    W(0x478) = ST(~W(0x46c) & 0xffffff);
    W(0x47c) = ST(~W(0x470) & 0xff);
    alu_norm_res();
  }
  W(0x480) = ST((~W(0x490) & 0xffffff) + 1 + SI(W(0x474)));
  W(0x484) = ST((~W(0x48c) & 0xffffff) + SI(W(0x478)));
  W(0x488) = ST(SI(W(0x47c)) + (~W(0x494) & 0x1ff));
  alu_norm_sum();
  alu_ccr = ST(alu_ccr & 0xffffffc0);
  alu_ovf_c();
  if ((((SC(W(0x488)) == -0x80) && (SI(W(0x484)) == 0)) &&
      (SI(W(0x480)) == 0)) && (SI(W(0x47c)) != 0)) {
    alu_ccr = ST(alu_ccr | 2);
  }
  alu_set_ccr();
  return;
}

/* alu_norm_abs @ 00431680 */
void alu_norm_abs(void)
{
  unsigned long uVar1;
  
  uVar1 = ST(W(0x490));
  if (0xffffff < SI(uVar1)) {
    W(0x490) = ST(uVar1 & 0xffffff);
    W(0x48c) = ST(SI(W(0x48c)) + (SI(uVar1 + (SI(uVar1) >> 0x1f & 0xffffffU)) >> 0x18));
  }
  uVar1 = ST(W(0x48c));
  if (0xffffff < SI(uVar1)) {
    W(0x48c) = ST(uVar1 & 0xffffff);
    W(0x494) = ST(SI(W(0x494)) + (SI(uVar1 + (SI(uVar1) >> 0x1f & 0xffffffU)) >> 0x18));
  }
  return;
}

/* alu_op_h431700 @ 00431700 */
void alu_op_h431700(void)
{
  unsigned long uVar1;
  
  if (SI(W(0x1bc)) == 1) {
    alu_load_ops();
    return;
  }
  W(0x474) = ST((alu_ccr & 1) + SI(W(0x468)) * 2);
  W(0x478) = ST(SI(W(0x46c)) << 1);
  W(0x47c) = ST(SI(W(0x470)) << 1);
  alu_norm_res();
  alu_ccr = ST(alu_ccr & 0xfffffffc);
  uVar1 = ST(W(0x47c) & 0x180);
  if ((uVar1 != 0) && (uVar1 != 0x180)) {
    alu_ccr = ST(alu_ccr | 0x42);
  }
  W(0x47c) = ST(W(0x47c) & 0xff);
  uVar1 = ST(W(0x45c));
  if (((W(0x470) & 0xff) & 0x80) != 0) {
    uVar1 = ST(~uVar1);
  }
  if ((uVar1 >> 0x17 & 1) == 0) {
    W(0x490) = ST((~W(0x460) & 0xffffff) + 1);
    W(0x48c) = ST(~W(0x45c) & 0xffffff);
    uVar1 = ST(~W(0x464) & 0xff);
  }
  else {
    W(0x490) = ST(W(0x460));
    W(0x48c) = ST(W(0x45c));
    uVar1 = ST(W(0x464));
  }
  W(0x494) = ST(uVar1);
  W(0x480) = ST(SI(W(0x490)) + SI(W(0x474)));
  W(0x484) = ST(SI(W(0x48c)) + SI(W(0x478)));
  W(0x488) = ST(SI(W(0x494)) + SI(W(0x47c)));
  alu_norm_sum();
  if (((W(0x488) & 0xff) & 0x80) == 0) {
    alu_ccr = ST(alu_ccr | 1);
  }
  alu_store_ext();
  return;
}

/* alu_op_h4318a0 @ 004318a0 */
void alu_op_h4318a0(void)
{
  if (SI(W(0x1bc)) == 1) {
    alu_load_acc();
    return;
  }
  W(0x460) = ST(1);
  W(0x45c) = ST(0);
  W(0x464) = ST(0);
  if (SI(W(0x1bc)) == 1) {
    alu_load_ops();
    return;
  }
  W(0x474) = ST(W(0x468));
  W(0x478) = ST(W(0x46c));
  W(0x47c) = ST(W(0x470));
  W(0x490) = ST(W(0x460));
  W(0x48c) = ST(W(0x45c));
  W(0x494) = ST(W(0x464));
  W(0x480) = ST((~W(0x460) & 0xffffff) + 1);
  W(0x484) = ST(~W(0x45c) & 0xffffff);
  W(0x488) = ST(~W(0x464) & 0xff);
  W(0x480) = ST(SI(W(0x480)) + SI(W(0x474)));
  W(0x484) = ST(SI(W(0x484)) + SI(W(0x478)));
  W(0x488) = ST(SI(W(0x488)) + SI(W(0x47c)));
  alu_norm_sum();
  alu_ccr = ST(alu_ccr & 0xffffffc0);
  alu_ovf_c();
  alu_ovf_d();
  alu_set_ccr();
  alu_store_ext();
  return;
}

/* alu_op_h4318e0 @ 004318e0 */
void alu_op_h4318e0(void)
{
  if (SI(W(0x1bc)) == 1) {
    alu_load_acc();
    return;
  }
  W(0x460) = ST(1);
  W(0x45c) = ST(0);
  W(0x464) = ST(0);
  alu_add56();
  return;
}

/* alu_op_h431920 @ 00431920 */
void alu_op_h431920(void)
{
  if (SI(W(0x1bc)) == 1) {
    alu_load_ops();
    return;
  }
  W(0x474) = ST(W(0x468));
  W(0x478) = ST(W(0x46c));
  W(0x47c) = ST(W(0x470));
  W(0x484) = ST(W(0x45c) ^ W(0x478));
  W(0x480) = ST(W(0x474));
  W(0x488) = ST(W(0x47c));
  alu_ccr = ST(alu_ccr & 0xfffffff1);
  if (SI(W(0x484)) == 0) {
    alu_ccr = ST(alu_ccr | 4);
  }
  if ((W(0x484) & 0x800000) != 0) {
    alu_ccr = ST(alu_ccr | 8);
  }
  alu_store_ext();
  return;
}

/* alu_op_h4319f0 @ 004319f0 */
void alu_op_h4319f0(void)
{
  if (SI(W(0x1bc)) == 1) {
    alu_load_acc();
    return;
  }
  W(0x474) = ST(W(0x468));
  W(0x478) = ST(SI(W(0x46c)) << 1);
  W(0x47c) = ST(W(0x470));
  W(0x480) = ST(W(0x474));
  W(0x484) = ST(W(0x478) & 0xffffff);
  W(0x488) = ST(W(0x47c));
  alu_ccr = ST(alu_ccr & 0xfffffff0);
  if (0x7fffff < SI(W(0x46c))) {
    alu_ccr = ST(alu_ccr | 1);
  }
  if (SI(W(0x484)) == 0) {
    alu_ccr = ST(alu_ccr | 4);
  }
  if (0x7fffff < SI(W(0x484))) {
    alu_ccr = ST(alu_ccr | 8);
  }
  alu_store_ext();
  return;
}

/* alu_op_h431ac0 @ 00431ac0 */
void alu_op_h431ac0(void)
{
  if (SI(W(0x1bc)) == 1) {
    alu_load_acc();
    return;
  }
  W(0x474) = ST(W(0x468));
  W(0x478) = ST(SI(W(0x46c)) / 2);
  W(0x47c) = ST(W(0x470));
  W(0x480) = ST(W(0x474));
  W(0x484) = ST(W(0x478));
  W(0x488) = ST(W(0x47c));
  alu_ccr = ST(alu_ccr & 0xfffffff0);
  if (SI(W(0x484)) == 0) {
    alu_ccr = ST(alu_ccr | 4);
  }
  if (((W(0x46c) & 0xff) & 1) != 0) {
    alu_ccr = ST(alu_ccr | 1);
  }
  alu_store_ext();
  return;
}

/* alu_op_h431b80 @ 00431b80 */
void alu_op_h431b80(void)
{
  alu_flag = 0;
  return;
}

/* alu_op_h431b90 @ 00431b90 */
void alu_op_h431b90(void)
{
  if (SI(W(0x1bc)) == 1) {
    alu_load_acc();
    return;
  }
  W(0x474) = ST(~W(0x468) & 0xffffff);
  W(0x478) = ST(~W(0x46c) & 0xffffff);
  W(0x47c) = ST(~W(0x470) & 0xff);
  W(0x494) = ST(0);
  W(0x480) = ST(SI(W(0x474)) + 1);
  W(0x484) = ST(W(0x478));
  W(0x488) = ST(W(0x47c));
  alu_norm_sum();
  alu_ccr = ST(alu_ccr & 0xffffffc1);
  if ((((W(0x470) & 0xff) & 0x80) != 0) && (((W(0x488) & 0xff) & 0x80) != 0)) {
    alu_ccr = ST(alu_ccr | 2);
  }
  alu_set_ccr();
  alu_store_ext();
  return;
}

/* alu_op_h431c70 @ 00431c70 */
void alu_op_h431c70(void)
{
  if (SI(W(0x1bc)) == 1) {
    alu_load_acc();
    return;
  }
  W(0x474) = ST(W(0x468));
  W(0x478) = ST(W(0x46c));
  W(0x47c) = ST(W(0x470));
  W(0x484) = ST(~W(0x478) & 0xffffff);
  W(0x480) = ST(W(0x474));
  W(0x488) = ST(W(0x47c));
  alu_ccr = ST(alu_ccr & 0xfffffff1);
  if (SI(W(0x484)) == 0) {
    alu_ccr = ST(alu_ccr | 4);
  }
  if (0x7fffff < SI(W(0x484))) {
    alu_ccr = ST(alu_ccr | 8);
  }
  alu_store_ext();
  return;
}

/* alu_op_h431d40 @ 00431d40 */
void alu_op_h431d40(void)
{
  if (SI(W(0x1bc)) == 1) {
    alu_load_ops();
    return;
  }
  W(0x474) = ST(W(0x468));
  W(0x478) = ST(W(0x46c));
  W(0x47c) = ST(W(0x470));
  W(0x484) = ST(W(0x45c) | W(0x478));
  W(0x480) = ST(W(0x474));
  W(0x488) = ST(W(0x47c));
  alu_ccr = ST(alu_ccr & 0xfffffff1);
  if (SI(W(0x484)) == 0) {
    alu_ccr = ST(alu_ccr | 4);
  }
  if (0x7fffff < SI(W(0x484))) {
    alu_ccr = ST(alu_ccr | 8);
  }
  alu_store_ext();
  return;
}

/* alu_op_h431e10 @ 00431e10 */
void alu_op_h431e10(void)
{
  if (SI(W(0x1bc)) == 1) {
    alu_load_acc();
    return;
  }
  W(0x474) = ST(W(0x468));
  W(0x478) = ST(W(0x46c));
  W(0x47c) = ST(W(0x470));
  W(0x484) = ST((alu_ccr & 1) + SI(W(0x478)) * 2 & 0xffffff);
  W(0x480) = ST(W(0x474));
  W(0x488) = ST(W(0x47c));
  alu_ccr = ST(alu_ccr & 0xfffffff0);
  if (0x7fffff < SI(W(0x478))) {
    alu_ccr = ST(alu_ccr | 1);
  }
  if (SI(W(0x484)) == 0) {
    alu_ccr = ST(alu_ccr | 4);
  }
  if (0x7fffff < SI(W(0x484))) {
    alu_ccr = ST(alu_ccr | 8);
  }
  alu_store_ext();
  return;
}

/* alu_op_h431ef0 @ 00431ef0 */
void alu_op_h431ef0(void)
{
  if (SI(W(0x1bc)) == 1) {
    alu_load_acc();
    return;
  }
  W(0x474) = ST(W(0x468));
  W(0x478) = ST(W(0x46c));
  W(0x47c) = ST(W(0x470));
  W(0x484) = ST(SI(W(0x478)) / 2 | (alu_ccr & 1UL) << 0x17);
  W(0x480) = ST(W(0x474));
  W(0x488) = ST(W(0x47c));
  alu_ccr = ST(alu_ccr & 0xfffffff0);
  if (((W(0x478) & 0xff) & 1) != 0) {
    alu_ccr = ST(alu_ccr | 1);
  }
  if (SI(W(0x484)) == 0) {
    alu_ccr = ST(alu_ccr | 4);
  }
  if (0x7fffff < SI(W(0x484))) {
    alu_ccr = ST(alu_ccr | 8);
  }
  alu_store_ext();
  return;
}

/* alu_op_h431fe0 @ 00431fe0 */
void alu_op_h431fe0(void)
{
  if (SI(W(0x1bc)) == 1) {
    alu_load_ops();
    return;
  }
  W(0x474) = ST(W(0x468));
  W(0x478) = ST(W(0x46c));
  W(0x47c) = ST(W(0x470));
  W(0x490) = ST(W(0x460));
  W(0x48c) = ST(W(0x45c));
  W(0x494) = ST(W(0x464));
  W(0x480) = ST(((~W(0x460) & 0xffffff) - (alu_ccr & 1)) + 1);
  W(0x484) = ST(~W(0x45c) & 0xffffff);
  W(0x488) = ST(~W(0x464) & 0xff);
  W(0x480) = ST(SI(W(0x480)) + SI(W(0x474)));
  W(0x484) = ST(SI(W(0x484)) + SI(W(0x478)));
  W(0x488) = ST(SI(W(0x488)) + SI(W(0x47c)));
  alu_norm_sum();
  alu_ccr = ST(alu_ccr & 0xffffffc0);
  alu_ovf_c();
  alu_ovf_d();
  alu_set_ccr();
  alu_store_ext();
  return;
}

/* alu_h_4325f0 @ 4325f0 */
void alu_h_4325f0(void)
{
  long iVar1;
  long bVar2;
  long bVar3;
  long bVar4;
  unsigned long uVar5;
  unsigned long uVar6;
  unsigned long uVar7;
  unsigned long uVar8;
  unsigned long uVar9;
  long bVar10;
  long iVar11;
  
  if (SI(W(0x1bc)) == 1) {
    alu_load_src(0);
    return;
  }
  bVar3 = 0;
  bVar4 = 0;
  iVar11 = 0;
  bVar10 = 0;
  if ((cur_dtype->family < 4) || ((alu_ccr & 0x4000) == 0)) {
    bVar2 = 0;
  }
  else {
    bVar2 = 1;
  }
  if (bVar2) {
    iVar1 = SI(W(0x1c0));
    if (iVar1 == 0x2c) {
      bVar3 = 1;
    }
    else if (iVar1 == 0x2b) {
      bVar10 = (W(0x45c) & 0x800000) != 0;
      if ((W(0xb8) & 0x800000) != 0) {
        bVar4 = 1;
      }
    }
    else if ((iVar1 == 0x2f) && (bVar3 = 1, (W(0xb8) & 0x800000) != 0)) {
      iVar11 = 1;
    }
  }
  if (bVar3) {
    W(0x474) = ST(W(0x46c));
    W(0x478) = ST(W(0x470));
    if (((W(0x470) & 0xff) & 0x80) == 0) {
      W(0x47c) = ST(0);
      W(0x478) = ST(W(0x478) & 0xff);
    }
    else {
      W(0x47c) = ST(0xff);
      W(0x478) = ST(W(0x478) | 0xffff00);
    }
  }
  else {
    W(0x474) = ST(W(0x468));
    W(0x478) = ST(W(0x46c));
    W(0x47c) = ST(W(0x470));
  }
  if (bVar10) {
    W(0x45c) = ST(W(0x45c) & 0x7fffff);
    W(0x478) = ST(SI(W(0x478)) + SI(W(0x460)));
    if ((W(0x460) & 0x800000) != 0) {
      W(0x47c) = ST(SI(W(0x47c)) + 0xff);
    }
  }
  uVar5 = ST(W(0x45c));
  if (0x7fffff < SI(uVar5)) {
    uVar5 = ST((~uVar5 & 0xffffff) + 1);
  }
  W(0x48c) = ST(uVar5);
  uVar5 = ST(W(0x460));
  if (0x7fffff < SI(uVar5)) {
    uVar5 = ST((~uVar5 & 0xffffff) + 1);
  }
  W(0x490) = ST(uVar5);
  uVar5 = ST(W(0x48c));
  iVar1 = SI(W(0x490));
  uVar6 = ST(SI(uVar5) >> 0x1f);
  uVar8 = ST((uVar5 & 0x3f) * iVar1);
  uVar7 = ST((SI(uVar5 + (uVar6 & 0x3ffff)) >> 0x12 & 0x7fU) * iVar1);
  uVar9 = ST((SI(uVar5 + (uVar6 & 0xfff)) >> 0xc & 0x3fU) * iVar1);
  uVar6 = ST((SI(uVar5 + (uVar6 & 0x3f)) >> 6 & 0x3fU) * iVar1);
  uVar5 = ST((((uVar9 & 0xfff) + (uVar7 & 0x3f) * 0x40) * 0x40 + (uVar6 & 0x3ffff)) * 0x40 +
          (uVar8 & 0xffffff));
  uVar6 = ST((SI(uVar9 + (SI(uVar9) >> 0x1f & 0xfffU)) >> 0xc) +
          (SI(uVar8 + (SI(uVar8) >> 0x1f & 0xffffffU)) >> 0x18) +
          (SI(uVar7 + (SI(uVar7) >> 0x1f & 0x3fU)) >> 6) +
          (SI(uVar6 + (SI(uVar6) >> 0x1f & 0x3ffffU)) >> 0x12));
  if (0xffffff < uVar5) {
    uVar6 = ST(uVar6 + (SI(uVar5) >> 0x18));
    uVar5 = ST(uVar5 & 0xffffff);
  }
  uVar7 = ST(W(0x460));
  uVar8 = ST(uVar7);
  if ((W(0x45c) & 0x800000) == 0) {
    uVar8 = ST(~uVar7);
  }
  uVar8 = ST(uVar8 >> 0x17 & 1);
  if (SI(W(0x1cc)) == 0) {
    uVar8 = ST((uVar8 == 0));
  }
  if ((uVar7 == 0) || (W(0x45c) == 0)) {
    uVar8 = ST(1);
  }
  if (uVar8 == 1) {
    W(0x480) = ST(uVar5 * 2);
    W(0x484) = ST(uVar6 * 2);
    alu_norm_sum();
    W(0x488) = ST(0);
    W(0x494) = ST(0);
  }
  else {
    W(0x480) = ST((~uVar5 & 0xffffff) * 2 + 2);
    W(0x484) = ST((~uVar6 & 0xffffff) << 1);
    alu_norm_sum();
    W(0x488) = ST(0xff);
    W(0x494) = ST(0xff);
  }
  W(0x480) = ST(SI(W(0x480)) + SI(W(0x474)));
  W(0x484) = ST(SI(W(0x484)) + SI(W(0x478)));
  W(0x488) = ST(SI(W(0x488)) + SI(W(0x47c)));
  alu_norm_sum();
  if (bVar4) {
    if (bVar10) {
      W(0x484) = ST(SI(W(0x484)) + 1);
    }
    W(0x480) = ST(SI(W(0x480)) + SI(W(0x45c)) * 2);
    alu_norm_sum();
  }
  if (iVar11 != 0) {
    if ((W(0x460) & 0x800000) != 0) {
      W(0x484) = ST(SI(W(0x484)) + 0x1fffffe);
      W(0x488) = ST(SI(W(0x488)) + 0x1fe);
    }
    W(0x480) = ST(SI(W(0x480)) + SI(W(0x460)) * 2);
    alu_norm_sum();
  }
  alu_ccr = ST(alu_ccr & 0xffffffc1);
  alu_ovf_add();
  alu_set_ccr();
  alu_store_ext();
  return;
}

/* alu_h_432a70 @ 432a70 */
void alu_h_432a70(void)
{
  long iVar1;
  unsigned long uVar2;
  unsigned long uVar3;
  unsigned long uVar4;
  unsigned long uVar5;
  unsigned long uVar6;
  
  if (SI(W(0x1bc)) == 1) {
    alu_load_src(0);
    return;
  }
  W(0x474) = ST(W(0x468));
  W(0x478) = ST(W(0x46c));
  W(0x47c) = ST(W(0x470));
  uVar2 = ST(W(0x45c));
  if (0x7fffff < SI(uVar2)) {
    uVar2 = ST((~uVar2 & 0xffffff) + 1);
  }
  W(0x48c) = ST(uVar2);
  uVar2 = ST(W(0x460));
  if (0x7fffff < SI(uVar2)) {
    uVar2 = ST((~uVar2 & 0xffffff) + 1);
  }
  W(0x490) = ST(uVar2);
  uVar2 = ST(W(0x48c));
  iVar1 = SI(W(0x490));
  uVar3 = ST(SI(uVar2) >> 0x1f);
  uVar5 = ST((uVar2 & 0x3f) * iVar1);
  uVar4 = ST((SI(uVar2 + (uVar3 & 0x3ffff)) >> 0x12 & 0x7fU) * iVar1);
  uVar6 = ST((SI(uVar2 + (uVar3 & 0xfff)) >> 0xc & 0x3fU) * iVar1);
  uVar3 = ST((SI(uVar2 + (uVar3 & 0x3f)) >> 6 & 0x3fU) * iVar1);
  uVar2 = ST((((uVar6 & 0xfff) + (uVar4 & 0x3f) * 0x40) * 0x40 + (uVar3 & 0x3ffff)) * 0x40 +
          (uVar5 & 0xffffff));
  uVar3 = ST((SI(uVar6 + (SI(uVar6) >> 0x1f & 0xfffU)) >> 0xc) +
          (SI(uVar5 + (SI(uVar5) >> 0x1f & 0xffffffU)) >> 0x18) +
          (SI(uVar4 + (SI(uVar4) >> 0x1f & 0x3fU)) >> 6) +
          (SI(uVar3 + (SI(uVar3) >> 0x1f & 0x3ffffU)) >> 0x12));
  if (0xffffff < uVar2) {
    uVar3 = ST(uVar3 + (SI(uVar2) >> 0x18));
    uVar2 = ST(uVar2 & 0xffffff);
  }
  uVar4 = ST(W(0x460));
  uVar5 = ST(uVar4);
  if ((W(0x45c) & 0x800000) == 0) {
    uVar5 = ST(~uVar4);
  }
  uVar5 = ST(uVar5 >> 0x17 & 1);
  if (SI(W(0x1cc)) == 0) {
    uVar5 = ST((uVar5 == 0));
  }
  if ((uVar4 == 0) || (SI(W(0x45c)) == 0)) {
    uVar5 = ST(1);
  }
  if (uVar5 == 1) {
    W(0x480) = ST(uVar2 * 2);
    W(0x484) = ST(uVar3 * 2);
    alu_norm_sum();
    W(0x488) = ST(0);
    W(0x494) = ST(0);
  }
  else {
    W(0x480) = ST((~uVar2 & 0xffffff) * 2 + 2);
    W(0x484) = ST((~uVar3 & 0xffffff) << 1);
    alu_norm_sum();
    W(0x488) = ST(0xff);
    W(0x494) = ST(0xff);
  }
  W(0x480) = ST(SI(W(0x480)) + SI(W(0x474)));
  W(0x484) = ST(SI(W(0x484)) + SI(W(0x478)));
  W(0x488) = ST(SI(W(0x488)) + SI(W(0x47c)));
  alu_norm_sum();
  alu_ccr = ST(alu_ccr & 0xffffffc1);
  alu_ovf_add();
  alu_round();
  if (((((W(0x47c) & 0xff) & 0x80) == 0) && (((W(0x494) & 0xff) & 0x80) == 0))
     && (((W(0x488) & 0xff) & 0x80) != 0)) {
    alu_ccr = ST(alu_ccr | 2);
  }
  alu_set_ccr();
  alu_store_ext();
  return;
}

/* alu_op_h432290 @ 00432290 */
void alu_op_h432290(void)
{
  unsigned long uVar1;
  
  if (SI(W(0x1bc)) == 1) {
    alu_load_ops();
    return;
  }
  alu_ccr = ST(alu_ccr & 0xffffffc0);
  W(0x474) = ST(SI(W(0x468)) << 1);
  W(0x478) = ST(SI(W(0x46c)) << 1);
  W(0x47c) = ST(SI(W(0x470)) << 1);
  alu_norm_res();
  W(0x490) = ST(W(0x460));
  W(0x48c) = ST(W(0x45c));
  W(0x494) = ST(W(0x464));
  uVar1 = ST(W(0x47c) & 0x180);
  if ((uVar1 == 0x100) || (uVar1 == 0x80)) {
    alu_ccr = ST(alu_ccr | 2);
  }
  W(0x47c) = ST(W(0x47c) & 0xff);
  W(0x480) = ST((~W(0x460) & 0xffffff) + 1);
  W(0x484) = ST(~W(0x45c) & 0xffffff);
  W(0x488) = ST(~W(0x464) & 0xff);
  W(0x480) = ST(SI(W(0x480)) + SI(W(0x474)));
  W(0x484) = ST(SI(W(0x484)) + SI(W(0x478)));
  W(0x488) = ST(SI(W(0x488)) + SI(W(0x47c)));
  alu_norm_sum();
  alu_ovf_c();
  alu_ovf_d();
  alu_set_ccr();
  alu_store_ext();
  return;
}

/* alu_op_h432410 @ 00432410 */
void alu_op_h432410(void)
{
  unsigned long uVar1;
  
  if (SI(W(0x1bc)) == 1) {
    alu_load_ops();
    return;
  }
  W(0x47c) = ST(SI(W(0x470)) / 2);
  if (((W(0x470) & 0xff) & 0x80) != 0) {
    W(0x47c) = ST(W(0x47c) | 0x80);
  }
  uVar1 = ST(W(0x46c));
  if (((W(0x470) & 0xff) & 1) != 0) {
    uVar1 = ST(uVar1 | 0x1000000);
  }
  W(0x478) = ST(SI(uVar1) / 2);
  uVar1 = ST(W(0x468));
  if (((W(0x46c) & 0xff) & 1) != 0) {
    uVar1 = ST(uVar1 | 0x1000000);
  }
  W(0x474) = ST(SI(uVar1) / 2);
  W(0x490) = ST(W(0x460));
  W(0x48c) = ST(W(0x45c));
  W(0x494) = ST(W(0x464));
  W(0x480) = ST((~W(0x460) & 0xffffff) + 1);
  W(0x484) = ST(~W(0x45c) & 0xffffff);
  W(0x488) = ST(~W(0x464) & 0xff);
  W(0x480) = ST(SI(W(0x480)) + SI(W(0x474)));
  W(0x484) = ST(SI(W(0x484)) + SI(W(0x478)));
  W(0x488) = ST(SI(W(0x488)) + SI(W(0x47c)));
  alu_norm_sum();
  alu_ccr = ST(alu_ccr & 0xffffffc0);
  alu_ovf_c();
  alu_ovf_d();
  alu_set_ccr();
  alu_store_ext();
  return;
}

/* alu_op_h432590 @ 00432590 */
void alu_op_h432590(void)
{
  if (SI(W(0x1bc)) == 1) {
    alu_load_ops();
    alu_flag = 0;
    return;
  }
  W(0x480) = ST(W(0x460));
  W(0x484) = ST(W(0x45c));
  W(0x488) = ST(W(0x464));
  alu_store_ext();
  alu_flag = 0;
  return;
}

/* alu_mpy @ 00432d50 */
void alu_mpy(void)
{
  long iVar1;
  long bVar2;
  unsigned long uVar3;
  unsigned long uVar4;
  unsigned long uVar5;
  unsigned long uVar6;
  unsigned long uVar7;
  
  if (SI(W(0x1bc)) == 1) {
    alu_load_src(0);
    return;
  }
  if ((cur_dtype->family < 4) || ((alu_ccr & 0x4000) == 0)) {
    bVar2 = 0;
  }
  else {
    bVar2 = 1;
  }
  if (((bVar2) && (SI(W(0x1c0)) == 0x2e)) &&
     ((W(0x460) & 0x800000) != 0)) {
    bVar2 = 1;
    W(0x460) = ST(W(0x460) & 0x7fffff);
  }
  else {
    bVar2 = 0;
  }
  W(0x474) = ST(0);
  W(0x478) = ST(0);
  W(0x47c) = ST(0);
  uVar3 = ST(W(0x45c));
  if (0x7fffff < SI(uVar3)) {
    uVar3 = ST((~uVar3 & 0xffffff) + 1);
  }
  W(0x48c) = ST(uVar3);
  uVar3 = ST(W(0x460));
  if (0x7fffff < SI(uVar3)) {
    uVar3 = ST((~uVar3 & 0xffffff) + 1);
  }
  W(0x490) = ST(uVar3);
  uVar3 = ST(W(0x48c));
  iVar1 = SI(W(0x490));
  uVar4 = ST(SI(uVar3) >> 0x1f);
  uVar6 = ST((uVar3 & 0x3f) * iVar1);
  uVar5 = ST((SI(uVar3 + (uVar4 & 0x3ffff)) >> 0x12 & 0x7fU) * iVar1);
  uVar7 = ST((SI(uVar3 + (uVar4 & 0xfff)) >> 0xc & 0x3fU) * iVar1);
  uVar4 = ST((SI(uVar3 + (uVar4 & 0x3f)) >> 6 & 0x3fU) * iVar1);
  uVar3 = ST((((uVar7 & 0xfff) + (uVar5 & 0x3f) * 0x40) * 0x40 + (uVar4 & 0x3ffff)) * 0x40 +
          (uVar6 & 0xffffff));
  uVar4 = ST((SI(uVar7 + (SI(uVar7) >> 0x1f & 0xfffU)) >> 0xc) +
          (SI(uVar6 + (SI(uVar6) >> 0x1f & 0xffffffU)) >> 0x18) +
          (SI(uVar4 + (SI(uVar4) >> 0x1f & 0x3ffffU)) >> 0x12) +
          (SI(uVar5 + (SI(uVar5) >> 0x1f & 0x3fU)) >> 6));
  if (0xffffff < uVar3) {
    uVar4 = ST(uVar4 + (SI(uVar3) >> 0x18));
    uVar3 = ST(uVar3 & 0xffffff);
  }
  uVar5 = ST(W(0x460));
  uVar6 = ST(uVar5);
  if ((W(0x45c) & 0x800000) == 0) {
    uVar6 = ST(~uVar5);
  }
  uVar6 = ST(uVar6 >> 0x17 & 1);
  if (SI(W(0x1cc)) == 0) {
    uVar6 = ST((uVar6 == 0));
  }
  if ((uVar5 == 0) || (W(0x45c) == 0)) {
    uVar6 = ST(1);
  }
  if (uVar6 == 1) {
    W(0x480) = ST(uVar3 * 2);
    W(0x484) = ST(uVar4 * 2);
    alu_norm_sum();
    W(0x488) = ST(0);
  }
  else {
    W(0x480) = ST((~uVar3 & 0xffffff) * 2 + 2);
    W(0x484) = ST((~uVar4 & 0xffffff) << 1);
    alu_norm_sum();
    W(0x488) = ST(0xff);
  }
  if (bVar2) {
    W(0x484) = ST(SI(W(0x484)) + SI(W(0x45c)));
    if ((W(0x45c) & 0x800000) != 0) {
      W(0x488) = ST(SI(W(0x488)) + 0xff);
    }
    alu_norm_sum();
  }
  alu_ccr = ST(alu_ccr & 0xffffffc1);
  alu_set_ccr();
  alu_store_ext();
  return;
}

/* alu_mac @ 00433020 */
void alu_mac(void)
{
  long iVar1;
  unsigned long uVar2;
  unsigned long uVar3;
  unsigned long uVar4;
  unsigned long uVar5;
  unsigned long uVar6;
  
  if (SI(W(0x1bc)) == 1) {
    alu_load_src(0);
    return;
  }
  W(0x474) = ST(0);
  W(0x478) = ST(0);
  W(0x47c) = ST(0);
  uVar2 = ST(W(0x45c));
  if (0x7fffff < SI(uVar2)) {
    uVar2 = ST((~uVar2 & 0xffffff) + 1);
  }
  W(0x48c) = ST(uVar2);
  uVar2 = ST(W(0x460));
  if (0x7fffff < SI(uVar2)) {
    uVar2 = ST((~uVar2 & 0xffffff) + 1);
  }
  W(0x490) = ST(uVar2);
  uVar2 = ST(W(0x48c));
  iVar1 = SI(W(0x490));
  uVar3 = ST(SI(uVar2) >> 0x1f);
  uVar5 = ST((uVar2 & 0x3f) * iVar1);
  uVar4 = ST((SI(uVar2 + (uVar3 & 0x3ffff)) >> 0x12 & 0x7fU) * iVar1);
  uVar6 = ST((SI(uVar2 + (uVar3 & 0xfff)) >> 0xc & 0x3fU) * iVar1);
  uVar3 = ST((SI(uVar2 + (uVar3 & 0x3f)) >> 6 & 0x3fU) * iVar1);
  uVar2 = ST((((uVar6 & 0xfff) + (uVar4 & 0x3f) * 0x40) * 0x40 + (uVar3 & 0x3ffff)) * 0x40 +
          (uVar5 & 0xffffff));
  uVar3 = ST((SI(uVar6 + (SI(uVar6) >> 0x1f & 0xfffU)) >> 0xc) +
          (SI(uVar5 + (SI(uVar5) >> 0x1f & 0xffffffU)) >> 0x18) +
          (SI(uVar3 + (SI(uVar3) >> 0x1f & 0x3ffffU)) >> 0x12) +
          (SI(uVar4 + (SI(uVar4) >> 0x1f & 0x3fU)) >> 6));
  if (0xffffff < uVar2) {
    uVar3 = ST(uVar3 + (SI(uVar2) >> 0x18));
    uVar2 = ST(uVar2 & 0xffffff);
  }
  uVar4 = ST(W(0x460));
  uVar5 = ST(uVar4);
  if ((W(0x45c) & 0x800000) == 0) {
    uVar5 = ST(~uVar4);
  }
  uVar5 = ST(uVar5 >> 0x17 & 1);
  if (SI(W(0x1cc)) == 0) {
    uVar5 = ST((uVar5 == 0));
  }
  if ((uVar4 == 0) || (W(0x45c) == 0)) {
    uVar5 = ST(1);
  }
  if (uVar5 == 1) {
    W(0x480) = ST(uVar2 * 2);
    W(0x484) = ST(uVar3 * 2);
    alu_norm_sum();
    W(0x488) = ST(0);
  }
  else {
    W(0x480) = ST((~uVar2 & 0xffffff) * 2 + 2);
    W(0x484) = ST((~uVar3 & 0xffffff) << 1);
    alu_norm_sum();
    W(0x488) = ST(0xff);
  }
  alu_round();
  alu_ccr = ST(alu_ccr & 0xffffffc1);
  alu_set_ccr();
  alu_store_ext();
  return;
}

/* alu_round @ 00433250 */
void alu_round(void)
{
  alu_norm_sum();
  if ((alu_ccr & 0xc00) == 0x400) {
    alu_norm_sum();
    W(0x484) = ST(SI(W(0x484)) + 1);
    alu_norm_sum();
    if ((SI(W(0x480)) == 0) && ((W(0x484) & 1) == 0)) {
      W(0x484) = ST(W(0x484) & 0xfffffc);
    }
    W(0x480) = ST(0);
    W(0x484) = ST(W(0x484) & 0xfffffe);
    return;
  }
  if ((alu_ccr & 0xc00) != 0x800) {
    W(0x480) = ST(SI(W(0x480)) + 0x800000);
    alu_norm_sum();
    if (SI(W(0x480)) == 0) {
      W(0x484) = ST(W(0x484) & 0xfffffe);
    }
    W(0x480) = ST(0);
    return;
  }
  W(0x480) = ST(SI(W(0x480)) + 0x400000);
  alu_norm_sum();
  if ((W(0x480) & 0x7fffff) == 0) {
    W(0x480) = ST(0);
  }
  W(0x480) = ST(W(0x480) & 0x800000);
  return;
}

/* alu_op_h4335a0 @ 004335a0 */
void alu_op_h4335a0(void)
{
  if (SI(W(0x1bc)) == 1) {
    alu_load_acc();
    return;
  }
  W(0x490) = ST(0);
  W(0x48c) = ST(0);
  W(0x494) = ST(0);
  W(0x474) = ST(W(0x468));
  W(0x478) = ST(W(0x46c));
  W(0x47c) = ST(W(0x470));
  W(0x480) = ST(W(0x474));
  W(0x484) = ST(W(0x478));
  W(0x488) = ST(W(0x47c));
  alu_ccr = ST(alu_ccr & 0xffffffc1);
  alu_set_ccr();
  return;
}

/* alu_op_h433650 @ 00433650 */
void alu_op_h433650(void)
{
  if (SI(W(0x1bc)) == 1) {
    alu_load_acc();
    return;
  }
  W(0x474) = ST(W(0x468));
  W(0x478) = ST(W(0x46c));
  W(0x47c) = ST(W(0x470));
  W(0x494) = ST(0);
  W(0x480) = ST(W(0x474));
  W(0x484) = ST(W(0x478));
  W(0x488) = ST(W(0x47c));
  alu_round();
  alu_ccr = ST(alu_ccr & 0xffffffc1);
  alu_ovf_add();
  alu_set_ccr();
  alu_store_ext();
  return;
}

/* alu_store_ext @ 00433700 */
void alu_store_ext(void)
{
  long iVar1;
  
  W(0x488) = ST(W(0x488) & 0xff);
  iVar1 = SI(W(0x1c8));
  if (iVar1 == 300) {
    core_copy_reg_quiet(1,0x120);
    core_copy_reg_quiet(2,0x121);
    core_copy_reg(3,0x122);
    return;
  }
  if (iVar1 == 2) {
    core_copy_reg(2,0x121);
    return;
  }
  if (iVar1 == 0x12d) {
    core_copy_reg_quiet(5,0x120);
    core_copy_reg_quiet(6,0x121);
    core_copy_reg(7,0x122);
    return;
  }
  if (iVar1 == 6) {
    core_copy_reg(6,0x121);
  }
  return;
}

/* alu_set_ccr @ 00433890 */
void alu_set_ccr(void)
{
  unsigned long uVar1;
  unsigned long uVar2;
  
  if (((SI(W(0x480)) == 0) && (SI(W(0x484)) == 0)) &&
     (SC(W(0x488)) == 0)) {
    alu_ccr = ST(alu_ccr | 4);
  }
  uVar2 = ST(W(0x488));
  if ((uVar2 & 0x80) != 0) {
    alu_ccr = ST(alu_ccr | 8);
  }
  if ((alu_ccr & 2) != 0) {
    alu_ccr = ST(alu_ccr | 0x40);
  }
  if ((alu_ccr & 0xc00) == 0x400) {
    if ((W(0x484) & 0x800000) == 0x800000) {
      if (((uVar2 & 0xff) & 1) == 1) {
LAB_00433978:
        alu_ccr = ST(alu_ccr | 0x10);
      }
    }
    else if ((uVar2 & 1) == 0) goto LAB_00433978;
    uVar2 = ST(uVar2 & 0xff);
    if (uVar2 == 0xff) goto LAB_0043398e;
  }
  else {
    uVar1 = ST(W(0x484));
    if ((alu_ccr & 0xc00) == 0x800) {
      if (((uVar1 & 0x600000) == 0x600000) || ((uVar1 & 0x600000) == 0)) {
        alu_ccr = ST(alu_ccr | 0x10);
      }
      uVar2 = ST((uVar2 & 0xff) + (uVar1 & 0xc00000));
      if (uVar2 == 0xc000ff) goto LAB_0043398e;
    }
    else {
      if (((uVar1 & 0xc00000) == 0xc00000) || ((uVar1 & 0xc00000) == 0)) {
        alu_ccr = ST(alu_ccr | 0x10);
      }
      uVar2 = ST((uVar2 & 0xff) + (uVar1 & 0x800000));
      if (uVar2 == 0x8000ff) goto LAB_0043398e;
    }
  }
  if (uVar2 != 0) {
    alu_ccr = ST(alu_ccr | 0x20);
  }
LAB_0043398e:
  W(0x9c) = ST(alu_ccr);
  core_touch_reg(0x27);
  return;
}

/* alu_load_acc @ 004339b0 */
void alu_load_acc(void)
{
  if ((SI(W(0x1c8)) != 300) && (SI(W(0x1c8)) != 2)) {
    core_read_copy(5,0x11a);
    core_read_copy(6,0x11b);
    core_read_copy(7,0x11c);
    return;
  }
  core_read_copy(1,0x11a);
  core_read_copy(2,0x11b);
  core_read_copy(3,0x11c);
  return;
}

/* alu_load_ops @ 00433a30 */
void alu_load_ops(void)
{
  long iVar1;
  unsigned long uVar2;
  
  if ((SI(W(0x1c8)) == 300) || (SI(W(0x1c8)) == 2)) {
    core_read_copy(1,0x11a);
    core_read_copy(2,0x11b);
    uVar2 = ST(3);
  }
  else {
    core_read_copy(5,0x11a);
    core_read_copy(6,0x11b);
    uVar2 = ST(7);
  }
  core_read_copy(uVar2,0x11c);
  W(0x464) = ST(0);
  iVar1 = SI(W(0x1c0));
  if (iVar1 < 7) {
    if (iVar1 != 6) {
      if (iVar1 != 2) {
        return;
      }
LAB_00433b85:
      core_read_copy(2,0x117);
      core_read_copy(1,0x118);
      core_read_copy(3,0x119);
      return;
    }
  }
  else {
    if (iVar1 < 0x12d) {
      if (iVar1 == 300) goto LAB_00433b85;
      switch(iVar1) {
      case 0x2b:
        uVar2 = ST(0x2b);
        break;
      case 0x2c:
        core_read_copy(0x2c,0x117);
        W(0x460) = ST(0);
        sign_ext_word(0x117,0x119);
        return;
      default:
        goto switchD_00433ae9_caseD_2d;
      case 0x2e:
        core_read_copy(0x2e,0x117);
        W(0x460) = ST(0);
        sign_ext_word(0x117,0x119);
        return;
      case 0x2f:
        uVar2 = ST(0x2f);
      }
      core_read_copy(uVar2,0x117);
      W(0x460) = ST(0);
      sign_ext_word(0x117,0x119);
      return;
    }
    if (iVar1 != 0x12d) {
      if (iVar1 == 0x130) {
        core_read_copy(0x2c,0x117);
        uVar2 = ST(0x2b);
      }
      else {
        if (iVar1 != 0x131) {
          return;
        }
        core_read_copy(0x2f,0x117);
        uVar2 = ST(0x2e);
      }
      core_read_copy(uVar2,0x118);
      sign_ext_word(0x117,0x119);
      return;
    }
  }
  core_read_copy(6,0x117);
  core_read_copy(5,0x118);
  core_read_copy(7,0x119);
switchD_00433ae9_caseD_2d:
  return;
}

