/* insattr.c - SIM56000.EXE v6.3 (CLAS56), instruction attribute tables (module insattr, rev 1.x):
 * per instruction class handlers that turn an opcode word into the index of an execution record,
 * a move record, a class code or a validity flag, plus the opcode class lookup.
 * The handler functions are generated by re/scripts/g2c_attr.py from the Ghidra output.
 * Handler argument convention: (opcode word, device flags, mode, sel). */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "sim56000.h"
#include "simdata.h"
#include "simproto.h"

#define M32(x) ((long)((x) & 0xffffffffUL))

static unsigned long opclass_key;
static unsigned long opclass_key_any;

/* opcode word -> index of its class in opclass_table (56002 and later: entries with a flag are valid) */
long opclass_lookup(unsigned long opw, unsigned long cpu)
{
    long i;
    unsigned long key;

    if (cpu > 3)
        return opclass_lookup_any(opw);
    key = opw & 0xffffffUL;
    if (key == opclass_key)
        return opclass_last;
    i = 0;
    opclass_key = key;
    if (key < opclass_table[0].match) {
        do {
            i++;
        } while (key < opclass_table[i].match);
    }
    while ((opclass_table[i].mask & key) != opclass_table[i].match || opclass_table[i].flag != 0)
        i++;
    opclass_last = opclass_table[i].cls;
    return opclass_last;
}

/* the same lookup, ignoring the flag column */
long opclass_lookup_any(unsigned long opw)
{
    long i;
    unsigned long key;

    key = opw & 0xffffffUL;
    if (key == opclass_key_any)
        return opclass_last_any;
    i = 0;
    opclass_key_any = key;
    if (key < opclass_table[0].match) {
        do {
            i++;
        } while (key < opclass_table[i].match);
    }
    if ((opclass_table[i].mask & key) != opclass_table[i].match) {
        do {
            i++;
        } while ((opclass_table[i].mask & key) != opclass_table[i].match);
    }
    opclass_last_any = opclass_table[i].cls;
    return opclass_last_any;
}

/* index into the addressing mode table of an effective address field; 0 for the modes that are illegal here */
long ea_mode_index(unsigned long opw)
{
    unsigned long f;
    long r;

    f = opw & 0xff;
    if ((opw & 0x80) == 0) {
        if (f == 4 || f == 8 || f == 0xc)
            r = 0x40;
        else
            r = (long)(((f >> 1) & 0x38) + (opw & 7));
    } else {
        r = (long)((opw & 3) + 0x42);
    }
    if (r != 4 && r != 0xd && r != 0x40 && r != 0x41)
        return 1;
    return 0;
}

/* opcode validity: 0 = invalid, 1 = valid, 2 = valid without further checks (alu module) */
long insn_validate(unsigned long opw, unsigned long devflags)
{
    long r;

    r = ((long (*)(unsigned long))insn_valid_handlers[opclass_lookup(opw, devflags)])(opw);
    if (r == 2)
        return 2;
    return r == 0;
}

void insn_exec_info(unsigned long devflags, unsigned long opw, long mode, long sel, void **rec)
{
    long i;

    switch (sel) {
    case 1:
    case 2:
        mode = 0;
    case 0:
        i = opclass_lookup(opw, devflags);
        i = ((long (*)(unsigned long, unsigned long, long, long))insn_exec_handlers[i])(opw, devflags, mode, sel);
        break;
    case 3:
        i = 4;
        break;
    default:
        i = 0;
    }
    *rec = &insn_exec_records[i * 8];
}

/* offsets of the fixed move records inside insn_move_records (3 words each) */
void insn_move_info(unsigned long opw, long mode, long sel, void **rec, unsigned long devflags)
{
    long i;

    i = 0;
    switch (sel) {
    case 0:
        i = opclass_lookup(opw, devflags);
        i = ((long (*)(unsigned long, unsigned long, long, long))insn_move_handlers[i])(opw, devflags,
                                                                                         (long)((opw >> 11) & 7), mode);
        break;
    case 1:
        i = ((opw & 0xf0000UL) != 0 ? 0x15 : 3);
        break;
    case 2: *rec = &insn_move_records[15]; return;
    case 3: *rec = &insn_move_records[45]; return;
    case 4: *rec = &insn_move_records[96]; return;
    case 5: *rec = &insn_move_records[102]; return;
    case 6: *rec = &insn_move_records[120]; return;
    case 7: *rec = &insn_move_records[123]; return;
    case 8: *rec = &insn_move_records[93]; return;
    case 10: *rec = &insn_move_records[117]; return;
    case 0xb: *rec = &insn_move_records[114]; return;
    case 0xc: *rec = &insn_move_records[111]; return;
    case 0xd: *rec = &insn_move_records[108]; return;
    case 0xe: *rec = &insn_move_records[105]; return;
    case 0xf: i = 0x21; break;
    }
    *rec = &insn_move_records[i * 3];
}

unsigned long insn_class_code(unsigned long opw, long mode, long sel, unsigned long devflags)
{
    long i;

    if (sel != 0) {
        if (sel != 1) {
            if (sel != 3)
                return 0;
            return 6;
        }
        mode = 0;
    }
    i = opclass_lookup(opw, devflags);
    return (unsigned long)((long (*)(unsigned long, unsigned long, long, long))insn_class_handlers[i])(opw, devflags, mode, sel)
           & 0xffffffffUL;
}

void insn_ea_class(unsigned long opw, long flag, unsigned long *out, unsigned long devflags)
{
    long i;

    i = opclass_lookup(opw, devflags);
    if (flag != 0)
        *out = (unsigned long)d_4c3ff8[i] & 0xffffffffUL;
    else
        *out = (unsigned long)d_4c3e40[i] & 0xffffffffUL;
}

/* insn_move_h42ef30 @ 0042ef30 */
long insn_move_h42ef30(unsigned long a1, unsigned long a2, long a3, long a4)
{
  return 0x2c;
}

/* insn_move_h42ef40 @ 0042ef40 */
long insn_move_h42ef40(unsigned long a1, unsigned long a2, long a3, long a4)
{
  return 0xf;
}

/* insn_move_h42ef50 @ 0042ef50 */
long insn_move_h42ef50(unsigned long a1, unsigned long a2, long a3, long a4)
{
  if (a3 != 5) {
    if (a3 == 6) {
      return M32((-(unsigned long)(a4 != 0) & 0xfffffff3) + 0xd);
    }
    if (a3 != 7) {
      return 0xf;
    }
  }
  return 2;
}

/* insn_move_h42ef80 @ 0042ef80 */
long insn_move_h42ef80(unsigned long a1, unsigned long a2, long a3, long a4)
{
  
  return M32((-(unsigned long)(a4 != 0) & 0xffffffec) + 0x14);
}

/* insn_move_h42ef90 @ 0042ef90 */
long insn_move_h42ef90(unsigned long a1, unsigned long a2, long a3, long a4)
{
  
  return M32((-(unsigned long)(a4 != 0) & 0xffffffed) + 0x13);
}

/* insn_move_h42efa0 @ 0042efa0 */
long insn_move_h42efa0(unsigned long a1, unsigned long a2, long a3, long a4)
{
  if (a4 != 0) {
    return 0;
  }
  if (a3 != 5) {
    if (a3 == 6) {
      return 0x1d;
    }
    if (a3 != 7) {
      return 0x12;
    }
  }
  return 6;
}

/* insn_move_h42efd0 @ 0042efd0 */
long insn_move_h42efd0(unsigned long a1, unsigned long a2, long a3, long a4)
{
  if (a4 != 0) {
    return 0;
  }
  if (a3 != 5) {
    if (a3 == 6) {
      return 0x1d;
    }
    if (a3 != 7) {
      return 0x13;
    }
  }
  return 6;
}

/* insn_move_h42f000 @ 0042f000 */
long insn_move_h42f000(unsigned long a1, unsigned long a2, long a3, long a4)
{
  
  return M32((-(unsigned long)(a4 != 0) & 0xffffffe4) + 0x1c);
}

/* insn_move_h42f010 @ 0042f010 */
long insn_move_h42f010(unsigned long a1, unsigned long a2, long a3, long a4)
{
  if (a4 != 0) {
    return 0;
  }
  if (a3 != 4) {
    if ((a3 != 5) && (a3 != 7)) {
      return 0x1c;
    }
    return 6;
  }
  return 0x2a;
}

/* insn_move_h42f040 @ 0042f040 */
long insn_move_h42f040(unsigned long a1, unsigned long a2, long a3, long a4)
{
  if (a3 != 5) {
    if (a3 == 6) {
      return M32((-(unsigned long)(a4 != 0) & 0xfffffff2) + 0xe);
    }
    if (a3 != 7) {
      return 0x11;
    }
  }
  return 6;
}

/* insn_move_h42f070 @ 0042f070 */
long insn_move_h42f070(unsigned long a1, unsigned long a2, long a3, long a4)
{
  long cVar1;
  
  if (a3 != 5) {
    if (a3 == 6) {
      if (((a1 & 0x400) == 0) || (a2 < 4)) {
        cVar1 = 0;
      }
      else {
        cVar1 = 1;
      }
      if (a4 != 0) {
        return 0;
      }
      return M32(((0 - (unsigned long)cVar1) & 0x20U) + 0xd);
    }
    if (a3 != 7) {
      return 1;
    }
  }
  return M32('\x02');
}

/* insn_move_h42f0c0 @ 0042f0c0 */
long insn_move_h42f0c0(unsigned long a1, unsigned long a2, long a3, long a4)
{
  if (a3 != 5) {
    if (a3 == 6) {
      return M32((-(unsigned long)(a4 != 0) & 0xfffffff3) + 0xd);
    }
    if (a3 != 7) {
      return 7;
    }
  }
  return 2;
}

/* insn_move_h42f0f0 @ 0042f0f0 */
long insn_move_h42f0f0(unsigned long a1, unsigned long a2, long a3, long a4)
{
  if ((3 < a2) && ((a1 & 0x3000) == 0)) {
    return 0xc;
  }
  return 1;
}

/* insn_move_h42f120 @ 0042f120 */
long insn_move_h42f120(unsigned long a1, unsigned long a2, long a3, long a4)
{
  return 8;
}

/* insn_move_h42f130 @ 0042f130 */
long insn_move_h42f130(unsigned long a1, unsigned long a2, long a3, long a4)
{
  
  return M32((-(unsigned long)(a4 != 0) & 0xffffffe7) + 0x19);
}

/* insn_move_h42f140 @ 0042f140 */
long insn_move_h42f140(unsigned long a1, unsigned long a2, long a3, long a4)
{
  long uVar1;
  
  if (a4 != 0) {
    return 0;
  }
  if ((a3 == 5) || (uVar1 = 0x19, a3 == 7)) {
    uVar1 = 0x18;
  }
  return uVar1;
}

/* insn_move_h42f170 @ 0042f170 */
long insn_move_h42f170(unsigned long a1, unsigned long a2, long a3, long a4)
{
  
  return M32((-(unsigned long)(a4 != 0) & 0xfffffff7) + 9);
}

/* insn_move_h42f180 @ 0042f180 */
long insn_move_h42f180(unsigned long a1, unsigned long a2, long a3, long a4)
{
  long uVar1;
  
  if (a4 != 0) {
    return 0;
  }
  if ((a3 == 5) || (uVar1 = 9, a3 == 7)) {
    uVar1 = 6;
  }
  return uVar1;
}

/* insn_move_h42f1b0 @ 0042f1b0 */
long insn_move_h42f1b0(unsigned long a1, unsigned long a2, long a3, long a4)
{
  return 0xc;
}

/* insn_move_h42f1c0 @ 0042f1c0 */
long insn_move_h42f1c0(unsigned long a1, unsigned long a2, long a3, long a4)
{
  if (a3 != 5) {
    if (a3 == 6) {
      return M32((-(unsigned long)(a4 != 0) & 0xfffffff2) + 0xe);
    }
    if (a3 != 7) {
      return 0xc;
    }
  }
  return 6;
}

/* insn_move_h42f1f0 @ 0042f1f0 */
long insn_move_h42f1f0(unsigned long a1, unsigned long a2, long a3, long a4)
{
  return 4;
}

/* insn_move_h42f200 @ 0042f200 */
long insn_move_h42f200(unsigned long a1, unsigned long a2, long a3, long a4)
{
  return 10;
}

/* insn_move_h42f210 @ 0042f210 */
long insn_move_h42f210(unsigned long a1, unsigned long a2, long a3, long a4)
{
  return 0x10;
}

/* insn_exec_h42f220 @ 0042f220 */
long insn_exec_h42f220(unsigned long a1, unsigned long a2, long a3, long a4)
{
  return 0x2b;
}

/* insn_move_h42f230 @ 0042f230 */
long insn_move_h42f230(unsigned long a1, unsigned long a2, long a3, long a4)
{
  
  return M32((-(unsigned long)(a4 != 0) & 0xffffffe6) + 0x1a);
}

/* insn_move_h42f240 @ 0042f240 */
long insn_move_h42f240(unsigned long a1, unsigned long a2, long a3, long a4)
{
  
  return M32((-(unsigned long)(a4 != 0) & 0xffffffe9) + 0x17);
}

/* insn_move_h42f250 @ 0042f250 */
long insn_move_h42f250(unsigned long a1, unsigned long a2, long a3, long a4)
{
  return 0x1b;
}

/* insn_move_h42f260 @ 0042f260 */
long insn_move_h42f260(unsigned long a1, unsigned long a2, long a3, long a4)
{
  
  return M32((-(unsigned long)(a4 != 0) & 0xfffffff5) + 0xb);
}

/* insn_move_h42f270 @ 0042f270 */
long insn_move_h42f270(unsigned long a1, unsigned long a2, long a3, long a4)
{
  long uVar1;
  
  if ((a3 == 5) || (uVar1 = 0xf, a3 == 7)) {
    uVar1 = 2;
  }
  return uVar1;
}

/* insn_move_h42f290 @ 0042f290 */
long insn_move_h42f290(unsigned long a1, unsigned long a2, long a3, long a4)
{
  return 0x16;
}

/* insn_class_h42f4a0 @ 0042f4a0 */
long insn_class_h42f4a0(unsigned long a1, unsigned long a2, long a3, long a4)
{
  return 0;
}

/* insn_class_h42f4b0 @ 0042f4b0 */
long insn_class_h42f4b0(unsigned long a1, unsigned long a2, long a3, long a4)
{
  return M32((-(unsigned long)((a1 & 0x400) != 0) & 0xe00) + 0x140e);
}

/* insn_class_h42f4d0 @ 0042f4d0 */
long insn_class_h42f4d0(unsigned long a1, unsigned long a2, long a3, long a4)
{
  unsigned long uVar1;
  unsigned long uVar2;
  
  uVar2 = a1 >> 0xb & 7;
  uVar1 = a1 & 0x400;
  if (uVar2 != 5) {
    if (uVar2 == 6) {
      return M32((-(unsigned long)(a3 != 0) & 0xffffffe7) + 0x19);
    }
    if (uVar2 != 7) {
      if ((a1 & 0x80000) != 0) {
        return M32((-(unsigned long)(uVar1 != 0) & 0xe00) + 0x20e);
      }
      return M32((-(unsigned long)(uVar1 != 0) & 0x1c00) + 0x40e);
    }
  }
  return M32((-(unsigned long)(uVar1 != 0) & 0x40) + 0x49);
}

/* insn_class_h42f530 @ 0042f530 */
long insn_class_h42f530(unsigned long a1, unsigned long a2, long a3, long a4)
{
  if ((a1 & 0x80000) != 0) {
    return M32((-(unsigned long)((a1 & 0x400) != 0) & 0xfffff200) + 0x1006);
  }
  return M32((-(unsigned long)((a1 & 0x400) != 0) & 0xffffe400) + 0x2006);
}

/* insn_class_h42f570 @ 0042f570 */
long insn_class_h42f570(unsigned long a1, unsigned long a2, long a3, long a4)
{
  unsigned long uVar1;
  
  uVar1 = a1 >> 0xb & 7;
  if (uVar1 != 5) {
    if (uVar1 == 6) {
      return M32((-(unsigned long)(a3 != 0) & 0xffffffe7) + 0x19);
    }
    if (uVar1 != 7) {
      return M32((-(unsigned long)((a1 & 0x400) != 0) & 0x2a00) + 0x60e);
    }
  }
  return M32((-(unsigned long)((a1 & 0x400) != 0) & 0x40) + 0x49);
}

/* insn_class_h42f5c0 @ 0042f5c0 */
long insn_class_h42f5c0(unsigned long a1, unsigned long a2, long a3, long a4)
{
  return M32((-(unsigned long)((a1 & 0x400) != 0) & 0xffffd600) + 0x3006);
}

/* insn_class_h42f5e0 @ 0042f5e0 */
long insn_class_h42f5e0(unsigned long a1, unsigned long a2, long a3, long a4)
{
  return 0xe;
}

/* insn_class_h42f5f0 @ 0042f5f0 */
long insn_class_h42f5f0(unsigned long a1, unsigned long a2, long a3, long a4)
{
  unsigned long uVar1;
  
  uVar1 = a1 >> 0xb & 7;
  if (uVar1 != 5) {
    if (uVar1 == 6) {
      return M32((-(unsigned long)(a3 != 0) & 0xffffffe7) + 0x19);
    }
    if (uVar1 != 7) {
      return M32((-(unsigned long)((a1 & 0x400) != 0) & 0xe00) + 0x20e);
    }
  }
  return M32((-(unsigned long)((a1 & 0x400) != 0) & 0x40) + 0x49);
}

/* insn_class_h42f640 @ 0042f640 */
long insn_class_h42f640(unsigned long a1, unsigned long a2, long a3, long a4)
{
  unsigned long uVar1;
  
  uVar1 = a1 >> 0xb & 7;
  if (uVar1 != 5) {
    if (uVar1 == 6) {
      return M32((-(unsigned long)(a3 != 0) & 0xffffffe7) + 0x19);
    }
    if (uVar1 != 7) {
      return M32((-(unsigned long)((a1 & 0x400) != 0) & 0x1c00) + 0x40e);
    }
  }
  return M32((-(unsigned long)((a1 & 0x400) != 0) & 0x40) + 0x49);
}

/* insn_class_h42f690 @ 0042f690 */
long insn_class_h42f690(unsigned long a1, unsigned long a2, long a3, long a4)
{
  if (a3 != 0) {
    return 0;
  }
  return M32((-(unsigned long)((a1 & 0x400) != 0) & 0xfffff900) + 0x806);
}

/* insn_class_h42f6c0 @ 0042f6c0 */
long insn_class_h42f6c0(unsigned long a1, unsigned long a2, long a3, long a4)
{
  unsigned long uVar1;
  
  uVar1 = a1 >> 0xb & 7;
  if (a3 != 0) {
    return 0;
  }
  if (uVar1 != 5) {
    if (uVar1 == 6) {
      return 0x19;
    }
    if (uVar1 != 7) {
      return M32((-(unsigned long)((a1 & 0x400) != 0) & 0x700) + 0x10e);
    }
  }
  return M32((-(unsigned long)((a1 & 0x400) != 0) & 0x40) + 0x49);
}

/* insn_class_h42f710 @ 0042f710 */
long insn_class_h42f710(unsigned long a1, unsigned long a2, long a3, long a4)
{
  if (a4 != 0) {
    return M32((-(unsigned long)((a1 & 0x400) != 0) & 0xfffff900) + 0x806);
  }
  if (a3 != 0) {
    return 0;
  }
  if ((a1 & 0x400) != 0) {
    return M32((-(unsigned long)((a1 & 0x40) != 0) & 0xfffffe00) + 0x412);
  }
  return M32((-(unsigned long)((a1 & 0x40) != 0) & 0xfffff000) + 0x2022);
}

/* insn_class_h42f770 @ 0042f770 */
long insn_class_h42f770(unsigned long a1, unsigned long a2, long a3, long a4)
{
  if ((a1 & 0x400) != 0) {
    return M32((-(unsigned long)((a1 & 0x40) != 0) & 0xfffffe00) + 0x406);
  }
  return M32((-(unsigned long)((a1 & 0x40) != 0) & 0xfffff000) + 0x2006);
}

/* insn_class_h42f7a0 @ 0042f7a0 */
long insn_class_h42f7a0(unsigned long a1, unsigned long a2, long a3, long a4)
{
  unsigned long uVar1;
  unsigned long uVar2;
  unsigned long uVar3;
  
  uVar2 = a1 & 0x400;
  uVar1 = a1 & 0x40;
  uVar3 = a1 >> 0xb & 7;
  if (a4 != 0) {
    return M32((-(unsigned long)(uVar2 != 0) & 0xfffff900) + 0x806);
  }
  if (a3 != 0) {
    return 0;
  }
  if (uVar3 == 4) {
    if (uVar2 != 0) {
      return M32((-(unsigned long)(uVar1 != 0) & 0xfffff000) + 0x201b);
    }
    return M32((-(unsigned long)(uVar1 != 0) & 0xfffffe00) + 0x42b);
  }
  if ((uVar3 != 5) && (uVar3 != 7)) {
    if (uVar2 != 0) {
      return M32((-(unsigned long)(uVar1 != 0) & 0xfffff000) + 0x201a);
    }
    return M32((-(unsigned long)(uVar1 != 0) & 0xfffffe00) + 0x42a);
  }
  return M32((-(unsigned long)(uVar2 != 0) & 0x40) + 0x49);
}

/* insn_class_h42f850 @ 0042f850 */
long insn_class_h42f850(unsigned long a1, unsigned long a2, long a3, long a4)
{
  unsigned long uVar1;
  
  uVar1 = a1 >> 0xb & 7;
  if (uVar1 != 5) {
    if (uVar1 == 6) {
      return M32((-(unsigned long)(a3 != 0) & 0xffffffe7) + 0x19);
    }
    if (uVar1 != 7) {
      if ((a1 & 0x400) != 0) {
        return M32((-(unsigned long)((a1 & 0x40) != 0) & 0xfffff000) + 0x200e);
      }
      return M32((-(unsigned long)((a1 & 0x40) != 0) & 0xfffffe00) + 0x40e);
    }
  }
  return M32((-(unsigned long)((a1 & 0x400) != 0) & 0x40) + 0x49);
}

/* insn_class_h42f8b0 @ 0042f8b0 */
long insn_class_h42f8b0(unsigned long a1, unsigned long a2, long a3, long a4)
{
  unsigned long uVar1;
  unsigned long uVar2;
  unsigned long uVar3;
  unsigned long uVar4;
  
  uVar3 = a1 & 0x400;
  uVar1 = a1 >> 0x10 & 1;
  uVar2 = a1 & 0x40;
  uVar4 = a1 >> 0xb & 7;
  a1 = a1 & 0x8000;
  if (a4 == 0) {
    switch(uVar4) {
    case 4:
      goto switchD_0042f958_caseD_4;
    case 5:
    case 7:
      return M32((-(unsigned long)(uVar3 != 0) & 0x40) + 0x49);
    case 6:
      if (a3 != 0) {
        return 0;
      }
      if (uVar3 == 0) {
        return 0x19;
      }
      return M32(0xb - (unsigned long)(a2 < 4));
    default:
      if (a1 == 0) {
        if (uVar3 == 0) {
          return M32((-(unsigned long)(uVar1 != 0) & 0xfffff000) + 0x200a);
        }
        return M32((-(unsigned long)(uVar1 != 0) & 0xfffffe00) + 0x40a);
      }
      if (uVar3 == 0) {
        return M32((-(unsigned long)(uVar2 != 0) & 0xfffffe00) + 0x40a);
      }
      return M32((-(unsigned long)(uVar2 != 0) & 0xfffff000) + 0x200a);
    }
  }
  if (uVar4 == 6) {
    return 3;
  }
  if (a1 == 0) {
    if (uVar3 == 0) {
      return M32((-(unsigned long)(uVar2 != 0) & 0xfffffe00) + 0x406);
    }
    return M32((-(unsigned long)(uVar2 != 0) & 0xfffff000) + 0x2006);
  }
  if (uVar3 == 0) {
    return M32((-(unsigned long)(uVar1 != 0) & 0xfffff000) + 0x2006);
  }
  return M32((-(unsigned long)(uVar1 != 0) & 0xfffffe00) + 0x406);
switchD_0042f958_caseD_4:
  if (a1 == 0) {
    if (uVar3 == 0) {
      return M32((-(unsigned long)(uVar1 != 0) & 0xfffff000) + 0x200b);
    }
    return M32((-(unsigned long)(uVar1 != 0) & 0xfffffe00) + 0x40b);
  }
  if (uVar3 == 0) {
    return M32((-(unsigned long)(uVar2 != 0) & 0xfffffe00) + 0x40b);
  }
  return M32((-(unsigned long)(uVar2 != 0) & 0xfffff000) + 0x200b);
}

/* insn_class_h_42fa60 @ 0042fa60 (not found by the Ghidra analysis; read from the disassembly) */
long insn_class_h_42fa60(unsigned long a1, unsigned long a2, long a3, long a4)
{
    unsigned long u1, mode, b400, b8000;

    u1 = (a1 >> 16) & 1;
    mode = (a1 >> 11) & 7;
    b400 = a1 & 0x400;
    b8000 = a1 & 0x8000;
    if (a4 != 0) {
        if (b8000 == 0)
            return M32((0UL - (b400 != 0) & 0x700) + 0x10e);
        if (b400 == 0)
            return M32((0UL - u1 & 0xfffff000UL) + 0x200e);
        return M32((0UL - u1 & 0xfffffe00UL) + 0x40e);
    }
    switch (mode) {
    case 4:
        if (b8000 != 0)
            return M32((0UL - (b400 != 0) & 0x700) + 0x10b);
        if (b400 == 0)
            return M32((0UL - u1 & 0xfffff000UL) + 0x200b);
        return M32((0UL - u1 & 0xfffffe00UL) + 0x40b);
    case 5:
    case 7:
        return M32((0UL - (b400 != 0) & 0x40) + 0x49);
    case 6:
        if (a3 != 0)
            return 0;
        return M32((0UL - (b400 != 0) & 0xfffffff1UL) + 0x19);
    default:
        if (b8000 != 0)
            return M32((0UL - (b400 != 0) & 0x700) + 0x10a);
        if (b400 == 0)
            return M32((0UL - u1 & 0xfffff000UL) + 0x200a);
        return M32((0UL - u1 & 0xfffffe00UL) + 0x40a);
    }
}

/* insn_class_h42fba0 @ 0042fba0 */
long insn_class_h42fba0(unsigned long a1, unsigned long a2, long a3, long a4)
{
  if ((a1 & 0x10000) != 0) {
    return M32((-(unsigned long)((a1 & 0x400) != 0) & 0xfffff200) + 0x1006);
  }
  return M32((-(unsigned long)((a1 & 0x400) != 0) & 0xffffe400) + 0x2006);
}

/* insn_class_h42fbe0 @ 0042fbe0 */
long insn_class_h42fbe0(unsigned long a1, unsigned long a2, long a3, long a4)
{
  unsigned long uVar1;
  
  uVar1 = a1 >> 0xb & 7;
  if (uVar1 != 5) {
    if (uVar1 == 6) {
      return M32((-(unsigned long)(a3 != 0) & 0xffffffe7) + 0x19);
    }
    if (uVar1 != 7) {
      return M32((-(unsigned long)((a1 & 0x400) != 0) & 0x700) + 0x10e);
    }
  }
  return M32((-(unsigned long)((a1 & 0x400) != 0) & 0x40) + 0x49);
}

/* insn_class_h42fc30 @ 0042fc30 */
long insn_class_h42fc30(unsigned long a1, unsigned long a2, long a3, long a4)
{
  return M32((-(unsigned long)((a1 & 0x400) != 0) & 0xfffff900) + 0x806);
}

/* insn_class_h42fc50 @ 0042fc50 */
long insn_class_h42fc50(unsigned long a1, unsigned long a2, long a3, long a4)
{
  unsigned long uVar1;
  
  uVar1 = a1 >> 0xb & 7;
  if (a3 != 0) {
    return 0;
  }
  if ((uVar1 != 5) && (uVar1 != 7)) {
    if ((a1 & 0x400) != 0) {
      return M32((-(unsigned long)((a1 & 0x40) != 0) & 0xfffff000) + 0x200e);
    }
    return M32((-(unsigned long)((a1 & 0x40) != 0) & 0xfffffe00) + 0x40e);
  }
  return M32((-(unsigned long)((a1 & 0x400) != 0) & 0x40) + 0x49);
}

/* insn_class_h42fcb0 @ 0042fcb0 */
long insn_class_h42fcb0(unsigned long a1, unsigned long a2, long a3, long a4)
{
  return M32((-((a1 & 0x400) != 0) & 0x40U) + 0x46);
}

/* insn_class_h42fcd0 @ 0042fcd0 */
long insn_class_h42fcd0(unsigned long a1, unsigned long a2, long a3, long a4)
{
  if (a4 != 0) {
    return 0;
  }
  if (((a1 & 0x2000) != 0) && ((a1 & 0x800) != 0)) {
    return M32((-(unsigned long)((a1 & 0x400) != 0) & 0x40) + 0x49);
  }
  return M32((-(unsigned long)((a1 & 0x400) != 0) & 0x1c00) + 0x40e);
}

/* insn_class_h42fd20 @ 0042fd20 */
long insn_class_h42fd20(unsigned long a1, unsigned long a2, long a3, long a4)
{
  if (a4 != 0) {
    return 0;
  }
  if (((a1 & 0x2000) != 0) && ((a1 & 0x800) != 0)) {
    return M32((-(unsigned long)((a1 & 0x400) != 0) & 0x40) + 0x49);
  }
  return M32((-(unsigned long)((a1 & 0x400) != 0) & 0xe00) + 0x20e);
}

/* insn_class_h42fd70 @ 0042fd70 */
long insn_class_h42fd70(unsigned long a1, unsigned long a2, long a3, long a4)
{
  if (a4 != 0) {
    return M32((-(unsigned long)((a1 & 0x400) != 0) & 0xfffff900) + 0x806);
  }
  if (a3 != 0) {
    return 0;
  }
  return M32((-(unsigned long)((a1 & 0x400) != 0) & 0xfffffff0) + 0x22);
}

/* insn_valid_h42fe50 @ 0042fe50 */
long insn_valid_h42fe50(unsigned long a1)
{
  return 2;
}

/* insn_valid_h42fe60 @ 0042fe60 */
long insn_valid_h42fe60(unsigned long a1)
{
  long iVar1;
  unsigned long uVar2;
  long bVar3;
  
  uVar2 = (a1 >> 8);
  bVar3 = 1;
  if (((uVar2 & 0xcf80) == 0xcf80) || ((uVar2 & 0xcf80) == 0xca80)) {
    bVar3 = 0;
  }
  if ((((a1 & 0x80) != 0) || (d_4c41b0[(a1 & 0x7f)] != 0)) &&
     ((((((uVar2 & 0x8c80) == 0x8c80 && (((unsigned long)a1 & 8) == 8)) ||
        (((uVar2 & 0xc300) == 0xc300 && (((unsigned long)a1 & 8) == 8)))) ||
       (((uVar2 & 0x8c80) == 0x8880 && ((a1 & 8) == 0)))) ||
      (((uVar2 & 0xc300) == 0xc200 && ((a1 & 8) == 0)))))) {
    bVar3 = 0;
  }
  iVar1 = 0;
  if (bVar3) {
    iVar1 = ea_mode_index(a1);
  }
  return iVar1;
}

/* insn_valid_pm_a @ 0042ff80 */
long insn_valid_pm_a(unsigned long opw)
{
  long iVar1;
  
  iVar1 = ea_mode_index(opw);
  if (((opw & 0x8000) == 0) && ((opw & 0x3f00) == 0x3400)) {
    iVar1 = 0;
  }
  return iVar1;
}

/* insn_valid_h42ffb0 @ 0042ffb0 */
long insn_valid_h42ffb0(unsigned long a1)
{
  return ea_mode_index(a1);
}

/* insn_valid_h42ffc0 @ 0042ffc0 */
long insn_valid_h42ffc0(unsigned long a1)
{
  unsigned long bVar1;
  long iVar2;
  unsigned long uVar3;
  long bVar4;
  
  bVar1 = (unsigned long)(a1 >> 8);
  bVar4 = 1;
  if (((a1 & 0x80) == 0) && (d_4c41b0[(a1 & 0x7f)] == 0))
  goto LAB_0043004c;
  iVar2 = insn_valid_pm_b(a1);
  if (iVar2 == 0) {
    uVar3 = (a1 >> 8) & 0xf180;
    if ((uVar3 != 0x5180) || (((unsigned long)a1 & 8) != 8)) {
      if (uVar3 != 0x5080) goto LAB_0043004c;
      goto joined_r0x00430048;
    }
  }
  else {
    uVar3 = (a1 >> 8) & 0xf580;
    if ((uVar3 != 0x5580) || (((unsigned long)a1 & 8) != 8)) {
      if (uVar3 != 0x5480) goto LAB_0043004c;
joined_r0x00430048:
      if ((a1 & 8) != 0) goto LAB_0043004c;
    }
  }
  bVar4 = 0;
LAB_0043004c:
  iVar2 = 0;
  if (bVar4) {
    iVar2 = ea_mode_index(a1);
  }
  if (((bVar1 & 0xc0) == 0x40) && ((bVar1 & 0x3f) == 0x34)) {
    iVar2 = 0;
  }
  return iVar2;
}

/* insn_valid_pm_b @ 00430080 */
long insn_valid_pm_b(unsigned long opw)
{
  if (((opw & 0x80) == 0) && (d_4c43b0[(opw & 0x7f)] != 0)) {
    return 1;
  }
  return 0;
}

/* insn_valid_h4300a0 @ 004300a0 */
long insn_valid_h4300a0(unsigned long a1)
{
  long iVar1;
  long bVar2;
  unsigned long uVar3;
  
  bVar2 = 1;
  if ((((a1 & 0x80) != 0) || (d_4c41b0[(a1 & 0x7f)] != 0)) &&
     (((((uVar3 = (a1 >> 8) & 0xff80, uVar3 == 0x4b80 || (uVar3 == 0x4a80)) ||
        ((uVar3 == 0x4180 && (((unsigned long)a1 & 8) == 8)))) ||
       ((uVar3 == 0x4080 && ((a1 & 8) == 0)))) ||
      (((uVar3 == 0x4980 && (((unsigned long)a1 & 8) == 8)) ||
       ((uVar3 == 0x4880 && ((a1 & 8) == 0)))))))) {
    bVar2 = 0;
  }
  iVar1 = 0;
  if (bVar2) {
    iVar1 = ea_mode_index(a1);
  }
  if ((((a1 >> 8) & 0x40U) != 0) && (((unsigned long)(a1 >> 8) & 0x3f) == 0x34)) {
    iVar1 = 0;
  }
  return iVar1;
}

/* insn_valid_h430160 @ 00430160 */
long insn_valid_h430160(unsigned long a1)
{
  long iVar1;
  unsigned long uVar2;
  long bVar3;
  
  bVar3 = 1;
  if (((a1 & 0x80) == 0) && (d_4c41b0[(a1 & 0x7f)] == 0))
  goto LAB_004301ef;
  iVar1 = insn_valid_pm_b(a1);
  if (iVar1 == 0) {
    uVar2 = (a1 >> 8) & 0xf900;
    if ((uVar2 != 0x2900) || (((unsigned long)a1 & 8) != 8)) {
      if (uVar2 != 0x2800) goto LAB_004301ef;
      goto joined_r0x004301eb;
    }
  }
  else {
    uVar2 = (a1 >> 8) & 0xfd00;
    if ((uVar2 != 0x2d00) || (((unsigned long)a1 & 8) != 8)) {
      if (uVar2 != 0x2c00) goto LAB_004301ef;
joined_r0x004301eb:
      if ((a1 & 8) != 0) goto LAB_004301ef;
    }
  }
  bVar3 = 0;
LAB_004301ef:
  iVar1 = 0;
  if (bVar3) {
    iVar1 = ea_mode_index(a1);
  }
  return iVar1;
}

/* insn_valid_h430210 @ 00430210 */
long insn_valid_h430210(unsigned long a1)
{
  long iVar1;
  unsigned long uVar2;
  long bVar3;
  
  uVar2 = (a1 >> 8);
  bVar3 = 1;
  if (((a1 & 0x80) == 0) && (d_4c41b0[(a1 & 0x7f)] == 0))
  goto LAB_0043029c;
  iVar1 = insn_valid_pm_b(a1);
  if (iVar1 == 0) {
    if (((uVar2 & 0xfc19) != 0x2009) || (((unsigned long)a1 & 8) != 8)) {
      if ((uVar2 & 0xfc19) != 0x2008) goto LAB_0043029c;
      goto joined_r0x00430298;
    }
  }
  else if (((uVar2 & 0xfc1d) != 0x200d) || (((unsigned long)a1 & 8) != 8)) {
    if ((uVar2 & 0xfc1d) != 0x200c) goto LAB_0043029c;
joined_r0x00430298:
    if ((a1 & 8) != 0) goto LAB_0043029c;
  }
  bVar3 = 0;
LAB_0043029c:
  if (((unsigned long)(a1 >> 8) & 0x1f) < 4) {
    bVar3 = 0;
  }
  if ((uVar2 & 0x3e0) < 0x80) {
    bVar3 = 0;
  }
  iVar1 = 0;
  if (bVar3) {
    iVar1 = ea_mode_index(a1);
  }
  return iVar1;
}

/* insn_valid_pm_c @ 004302d0 */
long insn_valid_pm_c(unsigned long opw)
{
  long iVar1;
  
  iVar1 = ea_mode_index(opw);
  if (((opw & 0xffff00) != 0x200000) || ((opw & 0xff) == 0)) {
    iVar1 = 0;
  }
  return iVar1;
}

/* insn_valid_pm_d @ 00430300 */
long insn_valid_pm_d(unsigned long opw)
{
  long iVar1;
  unsigned long uVar2;
  long bVar3;
  
  bVar3 = 1;
  if ((((opw & 0x80) != 0) || (d_4c41b0[(opw & 0x7f)] != 0)) &&
     (((uVar2 = (opw >> 8) & 0xf3c0, uVar2 == 0x13c0 && (((unsigned long)opw & 8) == 8)) ||
      ((uVar2 == 0x12c0 && ((opw & 8) == 0)))))) {
    bVar3 = 0;
  }
  iVar1 = 0;
  if (bVar3) {
    iVar1 = ea_mode_index(opw);
  }
  if ((((opw >> 8) & 0x80U) == 0) && (((unsigned long)(opw >> 8) & 0x3f) == 0x34)) {
    iVar1 = 0;
  }
  return iVar1;
}

/* insn_valid_pm_e @ 00430390 */
long insn_valid_pm_e(unsigned long opw)
{
  long iVar1;
  unsigned long uVar2;
  long bVar3;
  
  bVar3 = 1;
  if ((((opw & 0x80) != 0) || (d_4c41b0[(opw & 0x7f)] != 0)) &&
     (((uVar2 = (opw >> 8) & 0xfcc0, uVar2 == 0x1c80 && (((unsigned long)opw & 8) == 8)) ||
      ((uVar2 == 0x1880 && ((opw & 8) == 0)))))) {
    bVar3 = 0;
  }
  if ((((opw >> 8) & 0x80U) == 0) && (((unsigned long)(opw >> 8) & 0x3f) == 0x34)) {
    bVar3 = 0;
  }
  iVar1 = 0;
  if (bVar3) {
    iVar1 = ea_mode_index(opw);
  }
  return iVar1;
}

/* insn_valid_h430410 @ 00430410 */
long insn_valid_h430410(unsigned long a1)
{
  return M32((a1 & 0x3f00) != 0x3400);
}

/* insn_valid_h430430 @ 00430430 */
long insn_valid_h430430(unsigned long a1)
{
  return M32((a1 & 0x1f) < 0x18);
}

/* insn_valid_h430450 @ 00430450 */
long insn_valid_h430450(unsigned long a1)
{
  long bVar1;
  
  bVar1 = ((unsigned long)a1 & 0x1f) < 0x18;
  if (((a1 & 0x3f00) == 0x3400) || ((a1 & 0x3f00) == 0x3000)) {
    bVar1 = 0;
  }
  return bVar1;
}

/* insn_valid_h430480 @ 00430480 */
long insn_valid_h430480(unsigned long a1)
{
  return M32((a1 & 0x3f00) != 0x3400 && ((unsigned long)a1 & 0x1f) < 0x18);
}

/* insn_valid_h4304b0 @ 004304b0 */
long insn_valid_h4304b0(unsigned long a1)
{
  long uVar1;
  
  uVar1 = 1;
  if (((a1 & 0x8000) == 0) && ((a1 & 0x3f00) == 0x3400)) {
    uVar1 = 0;
  }
  return uVar1;
}

/* insn_valid_h4304e0 @ 004304e0 */
long insn_valid_h4304e0(unsigned long a1)
{
  if ((a1 & 0x3f00) < 0x400) {
    return 0;
  }
  if ((a1 & 0x3800) == 0x2800) {
    return 0;
  }
  return M32((a1 & 0x3800) != 0x3000);
}

/* insn_valid_h430510 @ 00430510 */
long insn_valid_h430510(unsigned long a1)
{
  long bVar1;
  
  if ((a1 & 0x3f) < 4) {
    bVar1 = 0;
  }
  else if ((a1 & 0x38) == 0x28) {
    bVar1 = 0;
  }
  else {
    bVar1 = (a1 & 0x38) != 0x30;
  }
  if ((a1 & 0x3f00) == 0x3400) {
    bVar1 = 0;
  }
  return bVar1;
}

/* insn_valid_h430550 @ 00430550 */
long insn_valid_h430550(unsigned long a1)
{
  if ((a1 & 0x3f) < 4) {
    return 0;
  }
  if ((a1 & 0x38) == 0x28) {
    return 0;
  }
  return M32((a1 & 0x38) != 0x30);
}

/* insn_valid_h430580 @ 00430580 */
long insn_valid_h430580(unsigned long a1)
{
  if (((a1 & 0x3f00) != 0x3400) && ((a1 & 0x3f00) != 0x3000)) {
    return 1;
  }
  return 0;
}

/* insn_valid_h4305a0 @ 004305a0 */
long insn_valid_h4305a0(unsigned long a1)
{
  if ((a1 & 0x3f00) < 0x400) {
    return 0;
  }
  if ((a1 & 0x3800) == 0x2800) {
    return 0;
  }
  if ((a1 & 0x3800) == 0x3000) {
    return 0;
  }
  return M32((a1 & 0x3f00) != 0x3c00);
}

/* insn_valid_h4305e0 @ 004305e0 */
long insn_valid_h4305e0(unsigned long a1)
{
  if ((a1 & 0x3f00) < 0x400) {
    return 0;
  }
  if ((a1 & 0x3800) == 0x2800) {
    return 0;
  }
  if ((a1 & 0x3800) == 0x3000) {
    return 0;
  }
  if (((a1 & 0x3f00) == 0x3c00) && (((unsigned long)a1 & 7) == 4)) {
    return 0;
  }
  return 1;
}

/* insn_valid_h430630 @ 00430630 */
long insn_valid_h430630(unsigned long a1)
{
  if ((8 < (a1 & 0x78)) && ((a1 & 0x78) < 0x40)) {
    return 0;
  }
  return 1;
}

/* insn_valid_h430650 @ 00430650 */
long insn_valid_h430650(unsigned long a1)
{
  return M32((a1 & 3) != 3);
}

/* insn_valid_pm_f @ 00430670 */
long insn_valid_pm_f(unsigned long opw)
{
  long iVar1;
  long bVar2;
  
  bVar2 = (opw & 0x3f00) != 0x3400;
  if ((((opw & 0x80) != 0) || (d_4c41b0[(opw & 0x7f)] != 0)) &&
     (bVar2 = (opw & 0xf4008) != 0x80000 && bVar2, (opw & 0xf4008) == 0x90008)) {
    bVar2 = 0;
  }
  iVar1 = 0;
  if (bVar2) {
    iVar1 = ea_mode_index(opw);
  }
  return iVar1;
}

/* insn_valid_h4306e0 @ 004306e0 */
long insn_valid_h4306e0(unsigned long a1)
{
  long bVar1;
  
  bVar1 = ((unsigned long)a1 & 0x1f) < 0x18;
  if ((((a1 & 0x3f00) < 0x400) || ((a1 & 0x3800) == 0x2800)) ||
     ((a1 & 0x3800) == 0x3000)) {
    bVar1 = 0;
  }
  return bVar1;
}

/* insn_valid_h430720 @ 00430720 */
long insn_valid_h430720(unsigned long a1)
{
  unsigned long uVar1;
  
  uVar1 = a1 >> 8 & 0x1f;
  if ((uVar1 != 0) && (uVar1 < 0x18)) {
    return 1;
  }
  return 0;
}

