/* insexec.c - SIM56000.EXE v6.3 (CLAS56), tail of module memacc (0x42e5c0-0x42eeb0): execution record index
 * handlers of the instruction classes (see insattr.c for the calling convention).  Generated by
 * re/scripts/g2c_attr.py --tail. */
#include "sim56000.h"
#include "simdata.h"

#define M32(x) ((long)((x) & 0xffffffffUL))

/* insn_exec_h42e5c0 @ 0042e5c0 */
long insn_exec_h42e5c0(unsigned long a1, unsigned long a2, long a3, long a4)
{
  return 1;
}

/* insn_exec_h42e5d0 @ 0042e5d0 */
long insn_exec_h42e5d0(unsigned long a1, unsigned long a2, long a3, long a4)
{
  if ((a1 & 0x400000) != 0) {
    return M32((-(unsigned long)((a1 & 0x8000) != 0) & 0xffffffe8) + 0x37);
  }
  return M32((-(unsigned long)((a1 & 0x8000) != 0) & 0xffffffe8) + 0x38);
}

/* insn_exec_h42e600 @ 0042e600 */
long insn_exec_h42e600(unsigned long a1, unsigned long a2, long a3, long a4)
{
  unsigned long uVar1;
  
  if (a4 != 0) {
    return 0x23;
  }
  uVar1 = a1 >> 0xb & 7;
  if (uVar1 != 5) {
    if (uVar1 == 6) {
      if (a3 != 0) {
        return 0;
      }
      return M32(((a1 & 0x400) != 0) + 2);
    }
    if (uVar1 != 7) {
      uVar1 = a1 >> 0x13 & 1;
      if ((a1 & 0x8000) != 0) {
        return M32(0x25 - (unsigned long)(uVar1 != 0));
      }
      return M32(0x3e - (unsigned long)(uVar1 != 0));
    }
  }
  return 2;
}

/* insn_exec_h42e670 @ 0042e670 */
long insn_exec_h42e670(unsigned long a1, unsigned long a2, long a3, long a4)
{
  unsigned long uVar1;
  
  if (a4 != 0) {
    return 0x23;
  }
  uVar1 = a1 >> 0xb & 7;
  if (uVar1 != 5) {
    if (uVar1 == 6) {
      if (a3 != 0) {
        return 0;
      }
      return M32((unsigned long)(unsigned long)(((unsigned long)(a1 >> 8) & 4 | 8) >> 2));
    }
    if (uVar1 != 7) {
      uVar1 = a1 >> 0x13 & 1;
      if ((a1 & 0x8000) != 0) {
        return M32((-(unsigned long)(uVar1 != 0) & 0xffffffeb) + 0x25);
      }
      return M32((-(unsigned long)(uVar1 != 0) & 0xffffffd3) + 0x3e);
    }
  }
  return 2;
}

/* insn_exec_h42e6e0 @ 0042e6e0 */
long insn_exec_h42e6e0(unsigned long a1, unsigned long a2, long a3, long a4)
{
  unsigned long uVar1;
  
  if (a4 != 0) {
    return 0x23;
  }
  uVar1 = a1 >> 0xb & 7;
  if (uVar1 != 5) {
    if (uVar1 == 6) {
      if (a3 != 0) {
        return 0;
      }
      return M32((unsigned long)(unsigned long)(((unsigned long)(a1 >> 8) & 4 | 8) >> 2));
    }
    if (uVar1 != 7) {
      uVar1 = a1 >> 0x10 & 3;
      if ((a1 & 0x8000) != 0) {
        uVar1 = uVar1 | 8;
      }
      if ((a1 & 0x80000) != 0) {
        uVar1 = uVar1 | 4;
      }
      return M32(d_4c3670[uVar1]);
    }
  }
  return 2;
}

/* insn_exec_h42e750 @ 0042e750 */
long insn_exec_h42e750(unsigned long a1, unsigned long a2, long a3, long a4)
{
  unsigned long uVar1;
  
  uVar1 = a1 >> 0x13 & 1;
  if ((a1 & 0x8000) != 0) {
    return M32(0x25 - (unsigned long)(uVar1 != 0));
  }
  return M32(0x3e - (unsigned long)(uVar1 != 0));
}

/* insn_exec_h42e780 @ 0042e780 */
long insn_exec_h42e780(unsigned long a1, unsigned long a2, long a3, long a4)
{
  unsigned long uVar1;
  
  uVar1 = a1 >> 0x13 & 1;
  if ((a1 & 0x8000) != 0) {
    return M32((-(unsigned long)(uVar1 != 0) & 0xffffffeb) + 0x25);
  }
  return M32((-(unsigned long)(uVar1 != 0) & 0xffffffd3) + 0x3e);
}

/* insn_exec_h42e7b0 @ 0042e7b0 */
long insn_exec_h42e7b0(unsigned long a1, unsigned long a2, long a3, long a4)
{
  unsigned long uVar1;
  
  uVar1 = a1 >> 0x10 & 3;
  if ((a1 & 0x8000) != 0) {
    uVar1 = (unsigned long)(unsigned long)((unsigned long)uVar1 | 8);
  }
  if ((a1 & 0x80000) != 0) {
    uVar1 = uVar1 | 4;
  }
  return M32(d_4c36b0[uVar1]);
}

/* insn_exec_h42e7e0 @ 0042e7e0 */
long insn_exec_h42e7e0(unsigned long a1, unsigned long a2, long a3, long a4)
{
  return 0x27;
}

/* insn_exec_h42e7f0 @ 0042e7f0 */
long insn_exec_h42e7f0(unsigned long a1, unsigned long a2, long a3, long a4)
{
  return M32((((unsigned long)((unsigned long)a1 >> 0x10) & 7) < 6) + '&');
}

/* insn_exec_h42e810 @ 0042e810 */
long insn_exec_h42e810(unsigned long a1, unsigned long a2, long a3, long a4)
{
  return 0x26;
}

/* insn_exec_h42e820 @ 0042e820 */
long insn_exec_h42e820(unsigned long a1, unsigned long a2, long a3, long a4)
{
  return 0x3f;
}

/* insn_exec_h42e830 @ 0042e830 */
long insn_exec_h42e830(unsigned long a1, unsigned long a2, long a3, long a4)
{
  unsigned long uVar1;
  
  if (a4 != 0) {
    return 0x3a;
  }
  uVar1 = a1 >> 0xb & 7;
  if (uVar1 != 5) {
    if (uVar1 == 6) {
      if (a3 != 0) {
        return 0;
      }
      return M32(((a1 & 0x400) != 0) + 2);
    }
    if (uVar1 != 7) {
      return M32(0x3c - (unsigned long)((a1 & 0x8000) != 0));
    }
  }
  return 2;
}

/* insn_exec_h42e890 @ 0042e890 */
long insn_exec_h42e890(unsigned long a1, unsigned long a2, long a3, long a4)
{
  unsigned long uVar1;
  
  if (a4 != 0) {
    return 0x21;
  }
  uVar1 = a1 >> 0xb & 7;
  if (uVar1 != 5) {
    if (uVar1 == 6) {
      if (a3 != 0) {
        return 0;
      }
      return M32(((a1 & 0x400) != 0) + 2);
    }
    if (uVar1 != 7) {
      return M32((-(unsigned long)((a1 & 0x8000) != 0) & 0xffffffe9) + 0x39);
    }
  }
  return 2;
}

/* insn_exec_h42e8f0 @ 0042e8f0 */
long insn_exec_h42e8f0(unsigned long a1, unsigned long a2, long a3, long a4)
{
  if (a3 != 0) {
    return 0;
  }
  return M32((~a1 & 0x40 | 0xb0) >> 4);
}

/* insn_exec_h42e910 @ 0042e910 */
long insn_exec_h42e910(unsigned long a1, unsigned long a2, long a3, long a4)
{
  unsigned long uVar1;
  
  if (a3 != 0) {
    return 0;
  }
  uVar1 = a1 >> 0xb & 7;
  if ((uVar1 != 5) && (uVar1 != 7)) {
    return M32((~(unsigned long)a1 & 0x40 | 0xb0) >> 4);
  }
  return 2;
}

/* insn_exec_h42e950 @ 0042e950 */
long insn_exec_h42e950(unsigned long a1, unsigned long a2, long a3, long a4)
{
  if (a4 != 0) {
    return M32((-(unsigned long)((a1 & 0x40) != 0) & 0xfffffffc) + 0xc);
  }
  return M32((-(unsigned long)((a1 & 0x40) != 0) & 0xfffffffc) + 0xd);
}

/* insn_exec_h42e980 @ 0042e980 */
long insn_exec_h42e980(unsigned long a1, unsigned long a2, long a3, long a4)
{
  unsigned long uVar1;
  unsigned long uVar2;
  
  uVar1 = a1 & 0x40;
  if (a4 != 0) {
    return M32((-(unsigned long)(uVar1 != 0) & 0xfffffffc) + 0xc);
  }
  uVar2 = a1 >> 0xb & 7;
  if ((a3 != 0) && (uVar2 == 6)) {
    return 0;
  }
  if (uVar2 == 4) {
    return M32((-(unsigned long)(uVar1 != 0) & 0xfffffffc) + 0xe);
  }
  if (uVar2 < 4) {
    return M32((-(unsigned long)(uVar1 != 0) & 0xfffffffc) + 0xd);
  }
  return 2;
}

/* insn_exec_h42e9e0 @ 0042e9e0 */
long insn_exec_h42e9e0(unsigned long a1, unsigned long a2, long a3, long a4)
{
  unsigned long uVar1;
  unsigned long uVar2;
  unsigned long uVar3;
  unsigned long uVar4;
  
  uVar1 = a1 >> 0x10 & 1;
  uVar2 = a1 & 0x40;
  uVar4 = a1 & 0x8000;
  uVar3 = a1 >> 0xb & 7;
  if (a4 == 2) {
    return M32((-(unsigned long)(uVar1 != 0) & 0xfffffffc) + 0xc);
  }
  if (a4 == 0) {
    switch(uVar3) {
    case 4:
      goto switchD_0042ea67_caseD_4;
    case 5:
    case 7:
      return 2;
    case 6:
      if (a3 == 0) {
        return M32((unsigned long)(unsigned long)(((unsigned long)(a1 >> 8) & 4 | 8) >> 2));
      }
      return 0;
    default:
      if (uVar4 == 0) {
        return M32((-(unsigned long)(uVar1 != 0) & 0xfffffffc) + 0xd);
      }
      return M32((-(unsigned long)(uVar2 != 0) & 0xfffffffc) + 0xd);
    }
  }
  if (uVar3 != 6) {
    if (uVar4 == 0) {
      return M32((-(unsigned long)(uVar2 != 0) & 0xfffffffc) + 0xc);
    }
    return M32((-(unsigned long)(uVar1 != 0) & 0xfffffffc) + 0xc);
  }
  if (a2 < 4) {
    return 5;
  }
  return M32(0x55 - (uVar1 != 0));
switchD_0042ea67_caseD_4:
  if (uVar4 == 0) {
    return M32((-(unsigned long)(uVar1 != 0) & 0xfffffffc) + 0xe);
  }
  return M32((-(unsigned long)(uVar2 != 0) & 0xfffffffc) + 0xe);
}

/* insn_exec_h42eaf0 @ 0042eaf0 */
long insn_exec_h42eaf0(unsigned long a1, unsigned long a2, long a3, long a4)
{
  unsigned long uVar1;
  unsigned long uVar2;
  
  uVar2 = a1 & 0x8000;
  uVar1 = a1 >> 0x10 & 1;
  if (a4 != 0) {
    if (uVar2 == 0) {
      return 6;
    }
    return M32((-(unsigned long)(uVar1 != 0) & 0xfffffffc) + 0xc);
  }
  switch(a1 >> 0xb & 7) {
  case 4:
    break;
  case 5:
  case 7:
    return 2;
  case 6:
    return M32((-(unsigned long)(a3 != 0) & 0xfffffffe) + 2);
  default:
    if (uVar2 == 0) {
      return M32((-(unsigned long)(uVar1 != 0) & 0xfffffffc) + 0xd);
    }
    return 7;
  }
  if (uVar2 == 0) {
    return M32((-(unsigned long)(uVar1 != 0) & 0xfffffffc) + 0xe);
  }
  return 0x48;
}

/* insn_exec_h42eb90 @ 0042eb90 */
long insn_exec_h42eb90(unsigned long a1, unsigned long a2, long a3, long a4)
{
  long bVar1;
  unsigned long uVar2;
  unsigned long uVar3;
  
  if ((a2 < 4) || ((a1 & 0x3000) != 0)) {
    bVar1 = 0;
  }
  else {
    bVar1 = 1;
  }
  uVar3 = a1 & 0x8000;
  uVar2 = a1 >> 0x10 & 1;
  if (a4 != 0) {
    if (uVar3 != 0) {
      return M32((-(unsigned long)(uVar2 != 0) & 0xfffffffc) + 0xc);
    }
    return 0x28;
  }
  if (!bVar1) {
    if (uVar3 != 0) {
      return 0x40;
    }
    return M32((-(unsigned long)(uVar2 != 0) & 0xfffffffc) + 0xd);
  }
  if (uVar3 != 0) {
    return M32(0x4d - (unsigned long)(uVar2 != 0));
  }
  return M32(0x4f - (unsigned long)(uVar2 != 0));
}

/* insn_exec_h42ec20 @ 0042ec20 */
long insn_exec_h42ec20(unsigned long a1, unsigned long a2, long a3, long a4)
{
  unsigned long uVar1;
  
  uVar1 = a1 & 0x8000;
  if (a4 == 0) {
    switch(a1 >> 0xb & 7) {
    case 4:
      return M32(0x49 - (unsigned long)(uVar1 != 0));
    case 5:
    case 7:
      return 2;
    case 6:
      return M32((-(unsigned long)(a3 != 0) & 0xfffffffe) + 2);
    default:
      return M32((-(unsigned long)(uVar1 != 0) & 0xffffffc4) + 0x43);
    }
  }
  return M32((-(unsigned long)(uVar1 != 0) & 0x23) + 6);
}

/* insn_exec_h42ec90 @ 0042ec90 */
long insn_exec_h42ec90(unsigned long a1, unsigned long a2, long a3, long a4)
{
  if (a4 != 0) {
    return M32((-(unsigned long)((a1 & 0x8000) != 0) & 0x23) + 6);
  }
  return M32((-(unsigned long)((a1 & 0x8000) != 0) & 0xffffffc4) + 0x43);
}

/* insn_exec_h42ecc0 @ 0042ecc0 */
long insn_exec_h42ecc0(unsigned long a1, unsigned long a2, long a3, long a4)
{
  return M32((-(unsigned long)(a3 != 0) & 0xffffffe4) + 0x1c);
}

/* insn_exec_h42ecd0 @ 0042ecd0 */
long insn_exec_h42ecd0(unsigned long a1, unsigned long a2, long a3, long a4)
{
  return M32((-(unsigned long)(a3 != 0) & 0xffffffbf) + 0x41);
}

/* insn_exec_h42ece0 @ 0042ece0 */
long insn_exec_h42ece0(unsigned long a1, unsigned long a2, long a3, long a4)
{
  unsigned long uVar1;
  
  if (a3 != 0) {
    return 0;
  }
  uVar1 = a1 >> 0xb & 7;
  if ((uVar1 != 5) && (uVar1 != 7)) {
    return M32(0x1e - (unsigned long)((a1 & 0x40) != 0));
  }
  return 2;
}

/* insn_exec_h42ed20 @ 0042ed20 */
long insn_exec_h42ed20(unsigned long a1, unsigned long a2, long a3, long a4)
{
  if (a3 != 0) {
    return 0;
  }
  return M32(0x1e - (unsigned long)((a1 & 0x40) != 0));
}

/* insn_exec_h42ed40 @ 0042ed40 */
long insn_exec_h42ed40(unsigned long a1, unsigned long a2, long a3, long a4)
{
  unsigned long uVar1;
  
  if (a4 != 0) {
    return 0x2a;
  }
  uVar1 = a1 >> 0xb & 7;
  if (uVar1 != 5) {
    if (uVar1 == 6) {
      if (a3 != 0) {
        return 0;
      }
      return M32((unsigned long)(unsigned long)(((unsigned long)(a1 >> 8) & 4 | 8) >> 2));
    }
    if (uVar1 != 7) {
      if ((a1 & 0x8000) != 0) {
        return M32(0x2d - ((a1 & 0x40) != 0));
      }
      return M32(0x45 - ((a1 & 0x40) != 0));
    }
  }
  return 2;
}

/* insn_exec_h42eda0 @ 0042eda0 */
long insn_exec_h42eda0(unsigned long a1, unsigned long a2, long a3, long a4)
{
  if ((a1 & 0x8000) != 0) {
    return M32(0x2d - (unsigned long)((a1 & 0x40) != 0));
  }
  return M32(0x45 - (unsigned long)((a1 & 0x40) != 0));
}

/* insn_exec_h42edc0 @ 0042edc0 */
long insn_exec_h42edc0(unsigned long a1, unsigned long a2, long a3, long a4)
{
  return M32((~a1 & 0x8000 | 0x84000) >> 0xd);
}

/* insn_exec_h42ede0 @ 0042ede0 */
long insn_exec_h42ede0(unsigned long a1, unsigned long a2, long a3, long a4)
{
  if (a4 == 1) {
    return M32((-((a1 & 0x400) != 0) & 0x14U) + 0x36);
  }
  return M32('\x03');
}

/* insn_exec_h42ee10 @ 0042ee10 */
long insn_exec_h42ee10(unsigned long a1, unsigned long a2, long a3, long a4)
{
  return 0x47;
}

/* insn_exec_h42ee20 @ 0042ee20 */
long insn_exec_h42ee20(unsigned long a1, unsigned long a2, long a3, long a4)
{
  return M32(0x1b - (unsigned long)((a1 & 3) != 2));
}

/* insn_exec_h42ee40 @ 0042ee40 */
long insn_exec_h42ee40(unsigned long a1, unsigned long a2, long a3, long a4)
{
  if (((a1 & 0x2000) != 0) && ((a1 & 0x800) != 0)) {
    return 2;
  }
  if ((a1 & 0x8000) != 0) {
    return M32(0x51 - (unsigned long)((a1 & 0x10000) != 0));
  }
  return M32(0x53 - (unsigned long)((a1 & 0x10000) != 0));
}

/* insn_exec_h42ee80 @ 0042ee80 */
long insn_exec_h42ee80(unsigned long a1, unsigned long a2, long a3, long a4)
{
  return M32((-(unsigned long)(a3 != 0) & 0xffffffb5) + 0x4b);
}

/* insn_exec_h42ee90 @ 0042ee90 */
long insn_exec_h42ee90(unsigned long a1, unsigned long a2, long a3, long a4)
{
  if ((a1 & 0xfc0e0) == 0xbc060) {
    return 0x4b;
  }
  return M32((-(unsigned long)(a4 != 0) & 0xffffffe8) + 0x40);
}

