/* simbss.c - GENERATED by re/scripts/gentab_sim.py: uninitialized (BSS) objects that initialized data points to.
   Sizes are the gaps to the next such object (lower bounds for pools); the translators give them proper types. */

char bss_4dba88[128]; /* 004dba88 */
char bss_4dbb08[17656]; /* 004dbb08 */
char bss_4e0000[24064]; /* 004e0000 */
char bss_4e5e00[65536]; /* 004e5e00 */
char bss_4f5e00[16128]; /* 004f5e00 */
char bss_4f9d00[19476]; /* 004f9d00 */
char bss_4fe914[5980]; /* 004fe914 */
char bss_500070[21920]; /* 00500070 */
char bss_505610[1680]; /* 00505610 */
char bss_505ca0[352]; /* 00505ca0 */
char bss_505e00[3632]; /* 00505e00 */
