/* simd_c.c - GENERATED by re/scripts/gentab_sim.py from SIM56000.EXE; do not edit. */
#include "simdata.h"

extern void emi2_m_clock();
extern void emi2_m_io_read();
extern void emi2_m_io_write();
extern void emi2_m_irq_ack();
extern void emi2_m_irq_poll();
extern void emi2_m_poke();
extern void emi2_m_reset();
extern void gpio_m_clock();
extern void hi_int_ack();
extern void hi_int_pending();
extern void hi_read_io();
extern void hi_reset();
extern void hi_tick_a();
extern void hi_tick_b();
extern void hi_write_io();
extern void hi_write_reg();
extern void hid_424130();
extern void hid_4243f0();
extern void insn_class_h42f4a0();
extern void iofmt_idle_format();
extern void iofmt_idle_parse();
extern void periph_read_reg();
extern void port_read_io();
extern void port_read_io_c();
extern void port_read_reg();
extern void port_reset();
extern void port_write_io();
extern void port_write_io_c();
extern void port_write_reg();
extern void pwm_int_ack();
extern void pwm_int_pending();
extern void pwm_read_io();
extern void pwm_reset();
extern void pwm_tick();
extern void pwm_write_io();
extern void pwm_write_reg();
extern void sai_int_ack();
extern void sai_int_pending();
extern void sai_read_io();
extern void sai_reset();
extern void sai_tick();
extern void sai_write_io();
extern void sai_write_reg();
extern void sci_int_ack();
extern void sci_int_pending();
extern void sci_iofile_format();
extern void sci_iofile_parse();
extern void sci_read_io();
extern void sci_reset();
extern void sci_tick();
extern void sci_write_io();
extern void sci_write_reg();
extern void shi_m_clock();
extern void shi_m_io_read();
extern void shi_m_io_write();
extern void shi_m_irq_ack();
extern void shi_m_irq_poll();
extern void shi_m_poke();
extern void shi_m_reset();
extern void simvar_read_reg();
extern void simvar_write_io();
extern void simvar_write_reg();
extern void ssi_int_ack();
extern void ssi_int_pending();
extern void ssi_read_io();
extern void ssi_reset();
extern void ssi_tick();
extern void ssi_write_io();
extern void ssi_write_reg();
extern void timer_int_ack();
extern void timer_int_pending();
extern void timer_read_io();
extern void timer_reset();
extern void timer_tick();
extern void timer_write_io();
extern void timer_write_reg();
extern void wdog_int_ack();
extern void wdog_int_pending();
extern void wdog_read_io();
extern void wdog_reset();
extern void wdog_tick();
extern void wdog_write_io();
extern void wdog_write_reg();

long d_4b4378[42] = { /* 004b4378 168 */
    0, 17, 6, 1, 17, 6, 2, 17,
    6, 8, 17, 6, -2, 0, 0, 4,
    17, 6, 5, 17, 6, 6, 17, 6,
    9, 17, 6, -2, 0, 0, 10, 17,
    6, 3, 17, 6, 7, 17, 6, -2,
    0, 0
};

const char *d_4b4420[44] = { /* 004b4420 176 */
    "When assigned to a DSP56004 EMI peripheral, the input file data", "value represents the byte or nibble associated with a single memory", "reference.  Note that in most cases multiple memory references are", "required in order to build a full word for transfer to one of the",
    "EMI data read registers.", (const char *)&empty_str, "A timed input data value with an absolute time value becomes", "available at the cycle count specified in the time value.  A timed",
    "input data value specified with a relative time (+time) becomes", "available at the specified number of transfers since the previous", "word; for example, a relative time count of +2 means that the", "associated data value becomes available for the second transfer",
    "after the preceding word.", (const char *)&empty_str, "If a lower case letter t is placed in a data position of the input", "file, the user will be prompted for the next input data value.",
    (const char *)&empty_str, "Storage of data to an EMI output file occurs each time transmit data", "is transfered to the output shift register, at the start of the", "transmission.  In the timed output mode, the simulator cycle count",
    "and a data value are stored each time a word begins transmission.", "In the untimed output mode, a single data value is stored each time", "a word begins transmission.  The value stored is shifted according", "to the word size selected by the EMI control register.",
    (const char *)&empty_str, "EXAMPLES", (const char *)&empty_str, "The following untimed input file will cause the data sequence",
    "7F 3F 5D C3 to appear on the EMI data bus during consecutive byte", "transfers.", (const char *)&empty_str, "7F 3F 5D C3",
    (const char *)&empty_str, "The following untimed input file will cause the data sequence 1F 01", "to appear repeatedly on consecutive byte reads by the EMI", (const char *)&empty_str,
    "(1F 01)", (const char *)&empty_str, "The following timed input file will cause the byte values 15 and 33", "to be read alternately each 10 transfers.",
    (const char *)&empty_str, "(+10 15 +10 33)", 0, 0
};

const char *d_4b44d0[6] = { /* 004b44d0 24 */
    "emi", (const char *)&d_4b4420, "I/O file format for emi peripheral", 0,
    0, 0
};

struct rec2w_bfa51 d_4b44e8[1] = { /* 004b44e8 8 */
    { 1, (void *)&d_4b44d0 }
};

struct rec2w_bfa51 d_4b44f0[3] = { /* 004b44f0 24 */
    { 14, (void *)&d_4b4378 },
    { 0, 0 },
    { 0, (void *)&d_4b44e8 }
};

const char *d_4b4508[2] = { /* 004b4508 8 */
    "Base Address Register", 0
};

const char *d_4b4510[8] = { /* 004b4510 32 */
    "Control/Status Register", "   E E E E               E", "   S S S S E E E E E E E M E E E E E E E E E E", " E T T T T D R W B B D D W I I I I A A A A W W E",
    " M M M M M T T L S D R W I S S N N M M M M L L B", " E 3 2 1 0 M S 2 Y F F E E 1 0 W R 3 2 1 0 1 0 W", 0, 0
};

const char *d_4b4530[2] = { /* 004b4530 8 */
    "Offset Register", 0
};

const char *d_4b4538[2] = { /* 004b4538 8 */
    "Write Offset Register", 0
};

const char *d_4b4540[2] = { /* 004b4540 8 */
    "Data Write Register", 0
};

const char *d_4b4548[6] = { /* 004b4548 24 */
    "Refresh Control Register", " E E   E E E                     E E E E E E E E", " R R   O P P                     C C C C C C C C", " E E   S S S                     D D D D D D D D",
    " F D   R 1 0                     7 6 5 4 3 2 1 0", 0
};

const char *d_4b4560[2] = { /* 004b4560 8 */
    "Data Read Register", 0
};

struct reg_desc regs_4b4568[11] = { /* 004b4568 312 */
    { "ebar0", 0xffffffUL, 0, 0x4000UL, 0x4001061UL, (void *)&d_4b4508, 0 },
    { "eor0", 0xffffffUL, 1, 0x4000UL, 0x4001061UL, (void *)&d_4b4530, 1 },
    { "edrr0", 0xffffffUL, 2, 0x4000UL, 0x4001021UL, (void *)&d_4b4560, 2 },
    { "ecsr", 0xffffffUL, 3, 0x4000UL, 0x4001061UL, (void *)&d_4b4510, 3 },
    { "ebar1", 0xffffffUL, 4, 0x4000UL, 0x4001061UL, (void *)&d_4b4508, 4 },
    { "eor1", 0xffffffUL, 5, 0x4000UL, 0x4001061UL, (void *)&d_4b4530, 5 },
    { "edrr1", 0xffffffUL, 6, 0x4000UL, 0x4001021UL, (void *)&d_4b4560, 6 },
    { "ercr", 0xdc00ffUL, 7, 0x4000UL, 0x4001061UL, (void *)&d_4b4548, 7 },
    { "edwr0", 0xffffffUL, 2, 0x4000UL, 0x4001041UL, (void *)&d_4b4540, 8 },
    { "edwr1", 0xffffffUL, 6, 0x4000UL, 0x4001041UL, (void *)&d_4b4540, 9 },
    { "ewor", 0xffffffUL, 14, 0x4000UL, 0x4001061UL, (void *)&d_4b4538, 10 }
};
struct flat_4b469c regs_4b4568_tail = { /* 004b469c tail of regs_4b4568 */
    0
};

struct group_def grpdef_4b46a0[1] = { /* 004b46a0 64 */
    { periph_read_reg, emi2_m_poke, emi2_m_io_read, emi2_m_io_write, emi2_m_clock, emi2_m_reset, emi2_m_irq_poll, emi2_m_irq_ack, 36, 41, 11, (struct reg_desc *)&regs_4b4568, { 0 } }
};

long d_4b46e0[16] = { /* 004b46e0 64 */
    2, 1, 4, 2, 6, 3, 4, 2,
    0, 0, 3, 2, 5, 3, 0, 0
};

long d_4b4720[16] = { /* 004b4720 64 */
    0, 0, 0, 0, 2, 1, 4, 2,
    0, 0, 1, 0, 3, 1, 0, 0
};

long d_4b4760[16] = { /* 004b4760 64 */
    16, 16, 8, 8, 0, 0, 8, 8,
    0, 0, 12, 8, 4, 0, 0, 0
};

long emi2_burst_bits_tab[52] = { /* 004b47a0 208 */
    15, 15, 15, 15, 15, 15, 15, 15,
    17, 18, 16, 17, 15, 16, 15, 16,
    17, 18, 16, 17, 15, 16, 15, 16,
    16, 17, 15, 16, 14, 15, 14, 15,
    15, 16, 14, 15, 13, 14, 13, 14,
    17, 18, 16, 17, 15, 16, 15, 16,
    19, 20, 18, 19
};

long emi2_burst_bits_tab2[16] = { /* 004b4870 64 */
    17, 18, 17, 19, 21, 22, 20, 21,
    19, 20, 19, 20, 16, 18, 20, 22
};

long d_4b4998[22] = { /* 004b4998 88 */
    0, 17, 6, 1, 17, 6, 2, 17,
    6, 3, 17, 6, -2, 0, 0, 4,
    17, 6, -2, 0, 0, 0
};

const char *d_4b49f0[64] = { /* 004b49f0 256 */
    "Each input data file value for the SHI peripheral is loaded into", "the SHI input shift register just prior to transfer of the shift", "register to the hrx register.  The data value may be further", "shifted according to the mode specified in the shi control register.",
    "Note that, while the data file provides a simpified method of", "specifying input data values, it is still necessary to apply a baud", "rate clock in order to determine the SHI input rate.", (const char *)&empty_str,
    "Timed or untimed SHI input data values are only scanned from the", "input file when the SHI is enabled and ready for an input transfer.", "Untimed input data values are consumed one for each transfer,", "whereas a timed input data value will be used only if its associated",
    "time value is valid.", (const char *)&empty_str, "A timed input data value with an absolute time value becomes", "available at the cycle count specified in the time value.  A timed",
    "input data value specified with a relative time (+time) becomes", "available at the specified number of transfers since the previous", "word; for example, a relative time count of +2 will cause the", "associated data value to become available on the second following",
    "transfer.", (const char *)&empty_str, "If a lower case letter t is placed in a data position of the input", "file, the user will be prompted for the next input data value.",
    (const char *)&empty_str, "Storage of data to an SHI output file occurs each time transmit", "data is transfered to the output shift register, at the start of", "the transmission.  In the timed output mode, the simulator cycle",
    "count and a data value are stored each time a word begins", "transmission.  In the untimed output mode, a single data value is", "stored each time a word begins transmission.  The value stored is", "shifted according to the word size selected by the SHI control",
    "register.", (const char *)&empty_str, "EXAMPLES", (const char *)&empty_str,
    "The following untimed SHI input file will cause the SHI to receive", "the word sequence 4F30 FF16 C397 2082 during consecutive active", "SHI receptions.", (const char *)&empty_str,
    "4F30 FF16 C397 2082", (const char *)&empty_str, "The following untimed SHI input file will cause the SHI to receive", "the word sequence 4401 4302 4111 3922 repeatedly.",
    (const char *)&empty_str, "(4401 4302 4111 3922)", (const char *)&empty_str, "The following timed SHI input file will cause the SHI to receive",
    "the word 1233 after the SHI is first enabled, followed by reception", "of 00F1 30 transfers later.", (const char *)&empty_str, "+0 1233 +30 F1",
    (const char *)&empty_str, "The following timed SHI input file will cause the SHI to receive", "the word sequence 411 226 236 ten times.", (const char *)&empty_str,
    "(+0 411 +0 226 +0 236)#10", (const char *)&empty_str, "The following timed SHI input file will cause the SHI to receive", "the word 6304 after cycle 2000 and the word 9688 after cycle 12000.",
    (const char *)&empty_str, "2000 6304 12000 9688", 0, 0
};

const char *d_4b4af0[6] = { /* 004b4af0 24 */
    "shi", (const char *)&d_4b49f0, "I/O file format for shi peripheral", 0,
    0, 0
};

struct rec2w_bfa51 d_4b4b08[1] = { /* 004b4b08 8 */
    { 1, (void *)&d_4b4af0 }
};

struct rec2w_bfa51 d_4b4b10[3] = { /* 004b4b10 24 */
    { 7, (void *)&d_4b4998 },
    { 0, 0 },
    { 0, (void *)&d_4b4b08 }
};

const char *d_4b4b28[6] = { /* 004b4b28 24 */
    "Clock Control Register", "               H H H H H H   C C", "               D D D D D D H P P", "               M M M M M M R O H",
    "               5 4 3 2 1 0 S L A", 0
};

const char *d_4b4b40[6] = { /* 004b4b40 24 */
    "Slave Address Register", " H H H H H", " A A A A A", " 6 5 4 3 2",
    0, 0
};

const char *d_4b4b58[2] = { /* 004b4b58 8 */
    "Receive Data Fifo", 0
};

const char *d_4b4b60[2] = { /* 004b4b60 8 */
    "Transmit Data Register", 0
};

const char *d_4b4b68[8] = { /* 004b4b68 32 */
    "Control/Status Register", "   H                 H H     H H H   H          ", " H B H H H   H   H H R R H H I R R H F       H  ", " S U B R R   R   T T I I T B D Q Q M I   H H I H",
    " E S E O F   N   D U E E I I L E E S F   M M 2 E", " C Y R E F   E   E E 1 0 E E E 1 0 T O   1 0 C N", 0, 0
};

struct reg_desc regs_4b4b88[5] = { /* 004b4b88 144 */
    { "hckr", 0x1ffUL, 0, 0x4000UL, 0x4001061UL, (void *)&d_4b4b28, 0 },
    { "hcsr", 0xfaffefUL, 1, 0x4000UL, 0x4001061UL, (void *)&d_4b4b68, 1 },
    { "hsar", 0xf80000UL, 2, 0x4000UL, 0x4001061UL, (void *)&d_4b4b40, 2 },
    { "hrx", 0xffffffUL, 3, 0x4000UL, 0x4001021UL, (void *)&d_4b4b58, 3 },
    { "htx", 0xffffffUL, 3, 0x4000UL, 0x4001041UL, (void *)&d_4b4b60, 4 }
};
struct flat_4b4c14 regs_4b4b88_tail = { /* 004b4c14 tail of regs_4b4b88 */
    0
};

struct group_def grpdef_4b4c18[1] = { /* 004b4c18 64 */
    { periph_read_reg, shi_m_poke, shi_m_io_read, shi_m_io_write, shi_m_clock, shi_m_reset, shi_m_irq_poll, shi_m_irq_ack, 36, 38, 5, (struct reg_desc *)&regs_4b4b88, { 0 } }
};

long d_4b5550[30] = { /* 004b5550 120 */
    0, 17, 6, 1, 17, 6, 2, 17,
    6, 3, 17, 6, -2, 0, 0, 4,
    17, 6, 5, 17, 6, 6, 17, 6,
    7, 17, 6, -2, 0, 0
};

const char *d_4b55c8[58] = { /* 004b55c8 232 */
    "Input data file values for the SAI peripheral must each contain two", "numbers in any specified input radix, separated by a colon.  There", "must be no embedded white space within each data pair.  The pair", "replaces the contents of the input shift registers just prior to",
    "their transfer to the rx0 and rx1 registers.  The data pair is", "scanned in the order rx0:rx1.", (const char *)&empty_str, "Untimed SAI input data pairs are read from the input file only as",
    "the data is needed to fill the shift registers prior to a transfer", "to the rx0 and rx1 registers.", (const char *)&empty_str, "Timed SAI input data pairs are applied to the SAI at the specified",
    "relative time intervals (+time), or at the exact simulator cycle", "indicated by the timing information within the file.  If the first", "timing information in the file is a relative value (+time) the", "simulator will wait until the SAI is enabled before applying the",
    "first data pair.  Otherwise the data application occurs at the", "exact specified cycle.", (const char *)&empty_str, "If a lower case letter t is placed in a data position of the input",
    "file, the user will be prompted for the next input data pair.", "At the prompt the user may enter a new data pair or just enter", "return to repeat the previous data pair.  Typing the escape", "key at the prompt simulates an end-of-file status.",
    (const char *)&empty_str, "SAI output file data is stored as three numbers, in the specified", "output file radix, separated by colons.   The numbers represent", "the values transfered to the output shift registers from the tx0,",
    "tx1 and tx2 registers,  sign extended and shifted according to the", "mode selected by the SAI transmit control register.", (const char *)&empty_str, "In the timed output mode, the simulator cycle count and a data",
    "triplet are stored each time the transfer takes place from the", "tx0, tx1 and tx2 registers to the associated shift registers.", "In the untimed output mode, the simulator cycle count is omitted.", (const char *)&empty_str,
    "EXAMPLES", (const char *)&empty_str, "The following untimed SAI input file will cause rx0 to receive the", "hexadecimal sequence aa bb cc and rx1 to receive the sequence",
    "dd ee ff.", (const char *)&empty_str, "aa:dd bb:ee cc:ff", (const char *)&empty_str,
    "The following untimed SAI input file will cause the rx0 to", "repeatedly receive the sequence 1 2 and rx1 to repeatedly receive", "the sequence 11 22.", (const char *)&empty_str,
    "(1:11 2 :22)", (const char *)&empty_str, "The following timed SAI input file will cause reception of the", "values 23 and 26 by rx0 and rx1 when the SAI is first enabled.",
    "A transfer occurring after 30 cycles will read the value 29 for", "rx0 and 28 for rx1.", (const char *)&empty_str, "+0 23:26 +30 29:28",
    0, 0
};

const char *d_4b56b0[6] = { /* 004b56b0 24 */
    "sai", (const char *)&d_4b55c8, "I/O file format for sai peripheral", 0,
    0, 0
};

struct rec2w_bfa51 d_4b56c8[1] = { /* 004b56c8 8 */
    { 1, (void *)&d_4b56b0 }
};

unsigned short d_4b56d2[11] = { /* 004b56d2 22 */
    0, 21840, 75, 64544, 64, 64640, 64, 65072, 64, 22216, 75
};

const char *d_4b56e8[6] = { /* 004b56e8 24 */
    "Baud Rate Control Register", "               p p p p p p p p p", "               S M M M M M M M M", "               R 7 6 5 4 3 2 1 0",
    0, 0
};

const char *d_4b5700[6] = { /* 004b5700 24 */
    "Receiver Control/Status Register", " R R   R R R R R R R R R R   R R", " R L   X X D R C L D W W M   1 0", " D D   I I W E K R I L L S   E E",
    " F F   L E T L P S R 1 0 T   N N", 0
};

const char *d_4b5718[6] = { /* 004b5718 24 */
    "Transmit Control/Status Register", " T T   T T T T T T T T T T T T T", " R L   X X D R C L D W W M 2 1 0", " D D   I I W E K R I L L S E E E",
    " E E   L E E L P S R 1 0 T N N N", 0
};

const char *d_4b5730[6] = { /* 004b5730 24 */
    "Receiver Control/Status Register", " R R     R R R R R R R R R   R R", " R L     X D R C L D W W M   1 0", " D D     I W E K R I L L S   E E",
    " F F     E T L P S R 1 0 T   N N", 0
};

const char *d_4b5748[6] = { /* 004b5748 24 */
    "Transmit Control/Status Register", " T T     T T T T T T T T T T T T", " R L     X D R C L D W W M 2 1 0", " D D     I W E K R I L L S E E E",
    " E E     E E L P S R 1 0 T N N N", 0
};

const char *d_4b5760[2] = { /* 004b5760 8 */
    "Transmit Data Register", 0
};

const char *d_4b5768[2] = { /* 004b5768 8 */
    "Receive Data Register", 0
};

struct reg_desc regs_4b5770[8] = { /* 004b5770 224 */
    { "brc", 0x1ffUL, 0, 0x4000UL, 0x10001061UL, (void *)&d_4b56e8, 0 },
    { "rcs", 0xdffbUL, 1, 0x4000UL, 0x10001061UL, (void *)&d_4b5700, 1 },
    { "rx0", 0xffffffUL, 2, 0x4000UL, 0x4001021UL, (void *)&d_4b5768, 2 },
    { "rx1", 0xffffffUL, 3, 0x4000UL, 0x4001021UL, (void *)&d_4b5768, 3 },
    { "tcs", 0xdfffUL, 4, 0x4000UL, 0x10001061UL, (void *)&d_4b5718, 4 },
    { "tx0", 0xffffffUL, 5, 0x4000UL, 0x4001041UL, (void *)&d_4b5760, 5 },
    { "tx1", 0xffffffUL, 6, 0x4000UL, 0x4001041UL, (void *)&d_4b5760, 6 },
    { "tx2", 0xffffffUL, 7, 0x4000UL, 0x4001041UL, (void *)&d_4b5760, 7 }
};

struct reg_desc regs_4b5850[8] = { /* 004b5850 224 */
    { "brc", 0x1ffUL, 0, 0x4000UL, 0x10001061UL, (void *)&d_4b56e8, 0 },
    { "rcs", 0xcffbUL, 1, 0x4000UL, 0x10001061UL, (void *)&d_4b5730, 1 },
    { "rx0", 0xffffffUL, 2, 0x4000UL, 0x4001021UL, (void *)&d_4b5768, 2 },
    { "rx1", 0xffffffUL, 3, 0x4000UL, 0x4001021UL, (void *)&d_4b5768, 3 },
    { "tcs", 0xcfffUL, 4, 0x4000UL, 0x10001061UL, (void *)&d_4b5748, 4 },
    { "tx0", 0xffffffUL, 5, 0x4000UL, 0x4001041UL, (void *)&d_4b5760, 5 },
    { "tx1", 0xffffffUL, 6, 0x4000UL, 0x4001041UL, (void *)&d_4b5760, 6 },
    { "tx2", 0xffffffUL, 7, 0x4000UL, 0x4001041UL, (void *)&d_4b5760, 7 }
};

struct group_def grpdef_4b5930[1] = { /* 004b5930 64 */
    { periph_read_reg, sai_write_reg, sai_read_io, sai_write_io, sai_tick, sai_reset, sai_int_pending, sai_int_ack, 36, 112, 8, (struct reg_desc *)&regs_4b5770, { 0 } }
};

struct group_def grpdef_4b5970[1] = { /* 004b5970 64 */
    { periph_read_reg, sai_write_reg, sai_read_io, sai_write_io, sai_tick, sai_reset, sai_int_pending, sai_int_ack, 36, 112, 8, (struct reg_desc *)&regs_4b5850, { 0 } }
};

long d_4b6688[10] = { /* 004b6688 40 */
    0, 13, 4, 1, 15, 6, -2, 0,
    0, 0
};

struct rec2w_bfa51 d_4b66b0[3] = { /* 004b66b0 24 */
    { 3, (void *)&d_4b6688 },
    { 0, 0 },
    { 0, 0 }
};

const char *d_4b66c8[6] = { /* 004b66c8 24 */
    "Timer Control/Status Register.", "           {        G            }", "           {    D   P T T T I T  }", "           {D D I T I C C C N I T}",
    " * * * * * {O I R S O 2 1 0 V E E}", 0
};

const char *d_4b66e0[2] = { /* 004b66e0 8 */
    "Timer Count Register.", 0
};

struct reg_desc regs_4b66e8[2] = { /* 004b66e8 56 */
    { "tcr", 0xffffffUL, 1, 0x4000UL, 0x4001061UL, (void *)&d_4b66e0, 0 },
    { "tcsr", 0x7ffUL, 0, 0x4000UL, 0x4001061UL, (void *)&d_4b66c8, 1 }
};

struct group_def grpdef_4b6720[1] = { /* 004b6720 64 */
    { periph_read_reg, timer_write_reg, timer_read_io, timer_write_io, timer_tick, timer_reset, timer_int_pending, timer_int_ack, 38, 11, 2, (struct reg_desc *)&regs_4b66e8, { 0 } }
};

long pwm_prescale_tab[8] = { /* 004b6838 32 */
    1, 2, 4, 8, 16, 32, 64, 128
};

long d_4b6858[3] = { /* 004b6858 12 */
    64, 128, 256
};

long d_4b6864[3] = { /* 004b6864 12 */
    8192, 8192, 0
};

long d_4b6870[3] = { /* 004b6870 12 */
    1, 2, 4
};

long d_4b687c[3] = { /* 004b687c 12 */
    1, 2, 0
};

long d_4b6888[4] = { /* 004b6888 16 */
    8, 16, 32, 4
};

long d_4b6898[2] = { /* 004b6898 8 */
    8, 0
};

long d_4b68a0[6] = { /* 004b68a0 24 */
    1024, 2048, 4096, 4096, 8192, 0
};

long d_4b68b8[3] = { /* 004b68b8 12 */
    8192, 16384, 32768L
};

long d_4b68c4[3] = { /* 004b68c4 12 */
    16384, 32768L, 0
};

long d_4b68d0[6] = { /* 004b68d0 24 */
    512, 1024, 2048, 0, 0, 0
};

long d_4b68e8[36] = { /* 004b68e8 144 */
    0, 15, 6, 1, 16, 7, 2, 16,
    7, -2, 0, 0, 3, 15, 7, 4,
    16, 8, -2, 0, 0, 5, 15, 6,
    6, 16, 7, 7, 15, 8, 8, 15,
    8, -2, 0, 0
};

struct rec6w_c07c7 d_4b6978[1] = { /* 004b6978 24 */
    { 12, (void *)&d_4b68e8, iofmt_idle_parse, iofmt_idle_format, 0, 0 }
};

const char *d_4b6990[2] = { /* 004b6990 8 */
    "PWMA Count Register.", 0
};

const char *d_4b6998[6] = { /* 004b6998 24 */
    "PWMA Control/Status Register.", " {W W W W W W}       {W W W W W W W}", " {A A A A A A}       {A A A A A A A}", " {R R R S S S}       {W W W C P P P}",
    " {2 1 0 2 1 0}       {2 1 0 K 2 1 0}", 0
};

const char *d_4b69b0[6] = { /* 004b69b0 24 */
    "PWMA Control/Status Register.", " {W}       {W W W W W W W W W W W W}", " {A}       {A A A A A A A A A A A A}", " {E}       {L L L C C C I I I E E E}",
    " {I}       {2 1 0 2 1 0 2 1 0 2 1 0}", 0
};

const char *d_4b69c8[2] = { /* 004b69c8 8 */
    "PWMB Count Register.", 0
};

const char *d_4b69d0[6] = { /* 004b69d0 24 */
    "PWMB Prescaler Register.", " {W W W W}           {W W W W W W W}", " {B B B B}           {B B B B B B B}", " {R R S S}           {W W W C P P P}",
    " {1 0 1 0}           {2 1 0 K 2 1 0}", 0
};

const char *d_4b69e8[6] = { /* 004b69e8 24 */
    "PWMB Control/Status Register.", " {W W W}                   {W W W W}", " {B B B}                   {B B B B}", " {E O C}                   {I I E E}",
    " {I    }                   {1 0 1 0}", 0
};

struct reg_desc regs_4b6a00[9] = { /* 004b6a00 256 */
    { "pwacr0", 0xffff00UL, 6, 0x4000UL, 0x4001061UL, (void *)&d_4b6990, 0 },
    { "pwacr1", 0xffff00UL, 7, 0x4000UL, 0x4001061UL, (void *)&d_4b6990, 1 },
    { "pwacr2", 0xffff00UL, 8, 0x4000UL, 0x4001061UL, (void *)&d_4b6990, 2 },
    { "pwacsr0", 0xfc7fUL, 5, 0x4000UL, 0x10001061UL, (void *)&d_4b6998, 3 },
    { "pwacsr1", 0x8fffUL, 4, 0x4000UL, 0x10001061UL, (void *)&d_4b69b0, 4 },
    { "pwbcr0", 0xffff00UL, 2, 0x4000UL, 0x4001061UL, (void *)&d_4b69c8, 5 },
    { "pwbcr1", 0xffff00UL, 3, 0x4000UL, 0x4001061UL, (void *)&d_4b69c8, 6 },
    { "pwbcsr0", 0xf07fUL, 1, 0x4000UL, 0x10001061UL, (void *)&d_4b69d0, 7 },
    { "pwbcsr1", 0xe00fUL, 0, 0x4000UL, 0x10001061UL, (void *)&d_4b69e8, 8 }
};
struct flat_4b6afc regs_4b6a00_tail = { /* 004b6afc tail of regs_4b6a00 */
    0
};

long d_4b6b00[10] = { /* 004b6b00 40 */
    8, 7, 5, 6, 4, 3, 0, 1,
    2, 0
};

struct group_def grpdef_4b6b28[1] = { /* 004b6b28 64 */
    { periph_read_reg, pwm_write_reg, pwm_read_io, pwm_write_io, pwm_tick, pwm_reset, pwm_int_pending, pwm_int_ack, 38, 98, 9, (struct reg_desc *)&regs_4b6a00, { 0 } }
};

long d_4b6ec4 = 1162626121L; /* 004b6ec4 4 */

unsigned char d_4b6ec8[8] = { /* 004b6ec8 8 */
    0, 0, 0, 0, 0, 0, 0, 0
};

long d_4b6ed0[10] = { /* 004b6ed0 40 */
    0, 11, 4, 1, 11, 4, -2, 0,
    0, 0
};

struct rec2w_bfa51 d_4b6ef8[3] = { /* 004b6ef8 24 */
    { 3, (void *)&d_4b6ed0 },
    { 0, 0 },
    { 0, 0 }
};

const char *d_4b6f10[6] = { /* 004b6f10 24 */
    "Watchdog Control/Status Register.", " {W W W W W W W W}", " {D L E I S P P P}", " {B D   E   2 1 0}",
    0, 0
};

const char *d_4b6f28[2] = { /* 004b6f28 8 */
    "Watchdog Count Register.", 0
};

struct reg_desc regs_4b6f30[2] = { /* 004b6f30 56 */
    { "wcsr", 0xffUL, 0, 0x4000UL, 0x10001061UL, (void *)&d_4b6f10, 0 },
    { "wcr", 0xffffUL, 1, 0x4000UL, 0x10001061UL, (void *)&d_4b6f28, 1 }
};

struct group_def grpdef_4b6f68[1] = { /* 004b6f68 64 */
    { periph_read_reg, wdog_write_reg, wdog_read_io, wdog_write_io, wdog_tick, wdog_reset, wdog_int_pending, wdog_int_ack, 38, 10, 2, (struct reg_desc *)&regs_4b6f30, { 0 } }
};

long d_4b7030[22] = { /* 004b7030 88 */
    4, 10, 3, 6, 14, 6, 0, 16,
    5, 1, 13, 5, 2, 13, 5, 3,
    13, 5, -2, 0, 0, 0
};

struct rec2w_bfa51 d_4b7088[3] = { /* 004b7088 24 */
    { 7, (void *)&d_4b7030 },
    { 0, 0 },
    { 0, 0 }
};

const char *d_4b70a0[2] = { /* 004b70a0 8 */
    "Counter used by the break command", 0
};

const char *d_4b70a8[2] = { /* 004b70a8 8 */
    "Counter for the number of device clock cycles", 0
};

const char *d_4b70b0[2] = { /* 004b70b0 8 */
    "Internal flag that indicates end of input file", 0
};

const char *d_4b70b8[2] = { /* 004b70b8 8 */
    "Counter for the number of instructions executed", 0
};

const char *d_4b70c0[2] = { /* 004b70c0 8 */
    "Internal flag that device is executing stop instruction", 0
};

const char *d_4b70c8[2] = { /* 004b70c8 8 */
    "Internal flag that indicates if a branch or jump is actually executed", 0
};

struct reg_desc regs_4b70d0[9] = { /* 004b70d0 256 */
    { "cnt1", 0xffffffffUL, 0, 0x208010UL, 0x2003001UL, (void *)&d_4b70a0, 0 },
    { "cnt2", 0xffffffffUL, 0, 0x208010UL, 0x2003001UL, (void *)&d_4b70a0, 1 },
    { "cnt3", 0xffffffffUL, 0, 0x208010UL, 0x2003001UL, (void *)&d_4b70a0, 2 },
    { "cnt4", 0xffffffffUL, 0, 0x208010UL, 0x2003001UL, (void *)&d_4b70a0, 3 },
    { "cyc", 0xffffffffUL, 0, 0x208010UL, 0x2003001UL, (void *)&d_4b70a8, 0 },
    { "eof", 0xffffUL, 0, 0x2201000UL, 0x2003011UL, (void *)&d_4b70b0, 0 },
    { "ictr", 0xffffffffUL, 0, 0x208010UL, 0x2003001UL, (void *)&d_4b70b8, 0 },
    { "jump", 0xffffUL, 0, 0x2204000UL, 0x2003011UL, (void *)&d_4b70c8, 0 },
    { "stop", 0xffffUL, 0, 0x2204000UL, 0x2003011UL, (void *)&d_4b70c0, 0 }
};
struct flat_4b71cc regs_4b70d0_tail = { /* 004b71cc tail of regs_4b70d0 */
    0
};

struct group_def grpdef_4b71d0[1] = { /* 004b71d0 64 */
    { simvar_read_reg, simvar_write_reg, gpio_m_clock, insn_class_h42f4a0, simvar_write_io, gpio_m_clock, 0, 0, 0, 9, 9, (struct reg_desc *)&regs_4b70d0, { 0 } }
};

long d_4b7388[12] = { /* 004b7388 48 */
    0, 10, 3, 1, 14, 6, 2, 16,
    5, -2, 0, 0
};

const char *d_4b73b8[58] = { /* 004b73b8 232 */
    "The port input file data value may be represented in hexadecimal,", "binary, decimal or floating point.  The default input radix can", "be specified in the input command.  Floating point input may be", "expressed in the usual methods.  For example,  0.5, 5e-1, and 5.0E-1",
    "are all acceptable data input values.  If a data value contains a", "decimal point, the data will be input as a floating point value,", "overriding the input radix specification.  Likewise, a data", "value preceded by $ will always be input as hexadecimal, a value",
    "preceded by % will be input as binary, and a value preceded by ` will", "always be input as decimal.", (const char *)&empty_str, "Untimed port input data values will be applied only if the port is",
    "configured as an input and the device performs a read operation on", "the port.  In other words, the input file acts like a stack of input", "data; each successive data value is retrieved from the stack file", "when a read operation occurs.",
    (const char *)&empty_str, "Timed port input data values are applied to the port at the specified", "relative time intervals (+time), or at the exact simulator cycle", "indicated by the timing information within the file.  If the first",
    "timing information in the file is a relative value (+time) the", "simulator will wait until the first port read before applying the", "data value.  Otherwise the data application occurs at the exact", "specified cycle.",
    (const char *)&empty_str, "If a lower case letter t is placed in a data position of the input", "file, the user will be prompted for the next input data value.  At", "the prompt the user may enter a new data value or just enter return",
    "to repeat the previous data value.  Typing the escape key at the", "prompt simulates an end-of-file status.", (const char *)&empty_str, "Storage of data to a port output file will occur any time a write",
    "operation occurs to the port.  In the timed output mode, the", "simulator cycle count and a data value are stored each time a word", "is written.  In the untimed output mode, a single data value is", "stored each time a word is written.  No tristate information is",
    "available in this simplified port output mode.  Data bits associated", "with port pins which are tristated or which have peripheral functions", "enabled will be represented by a zero.", (const char *)&empty_str,
    "EXAMPLES", (const char *)&empty_str, "The following untimed input file will cause the data sequence", "7FFF 7F3F 5D3C FC3 to appear on Port B during consecutive port reads.",
    (const char *)&empty_str, "7FFF 7F3F 5D3C FC3", (const char *)&empty_str, "The following untimed input file will cause the data sequence 1FF",
    "000 to appear repeatedly on consecutive reads of Port C.", (const char *)&empty_str, "(1FF 000)", (const char *)&empty_str,
    "The following timed input file will cause the data sequence", "1555 3333 to alternate on Port B at 10 cycle intervals.", (const char *)&empty_str, "(+10 1555 +10 3333)",
    0, 0
};

const char *d_4b74a0[6] = { /* 004b74a0 24 */
    "portio", (const char *)&d_4b73b8, "I/O file format for portb or portc", 0,
    0, 0
};

struct rec2w_bfa51 d_4b74b8[1] = { /* 004b74b8 8 */
    { 1, (void *)&d_4b74a0 }
};

struct rec2w_bfa51 d_4b74c0[3] = { /* 004b74c0 24 */
    { 4, (void *)&d_4b7388 },
    { 0, 0 },
    { 0, (void *)&d_4b74b8 }
};

const char *d_4b74d8[2] = { /* 004b74d8 8 */
    "Control Register", 0
};

const char *d_4b74e0[2] = { /* 004b74e0 8 */
    "Data Direction Register", 0
};

const char *d_4b74e8[2] = { /* 004b74e8 8 */
    "Data Register", 0
};

struct reg_desc regs_4b74f0[3] = { /* 004b74f0 88 */
    { "pbc", 0xffffffUL, 0, 0x4000UL, 0x10001061UL, (void *)&d_4b74d8, 0 },
    { "pbddr", 0xffffffUL, 2, 0x4000UL, 0x10001061UL, (void *)&d_4b74e0, 0 },
    { "pbd", 0xffffffUL, 4, 0x4000UL, 0x10001061UL, (void *)&d_4b74e8, 0 }
};
struct flat_4b7544 regs_4b74f0_tail = { /* 004b7544 tail of regs_4b74f0 */
    0
};

struct reg_desc regs_4b7548[3] = { /* 004b7548 88 */
    { "pbc", 0xffffffUL, 0, 0x4000UL, 0x10001061UL, (void *)&d_4b74d8, 0 },
    { "pbddr", 0xffffffUL, 1, 0x4000UL, 0x10001061UL, (void *)&d_4b74e0, 0 },
    { "pbd", 0xffffffUL, 2, 0x4000UL, 0x10001061UL, (void *)&d_4b74e8, 0 }
};
struct flat_4b759c regs_4b7548_tail = { /* 004b759c tail of regs_4b7548 */
    0
};

struct reg_desc regs_4b75a0[3] = { /* 004b75a0 88 */
    { "pcc", 0xffffffUL, 0, 0x4000UL, 0x10001061UL, (void *)&d_4b74d8, 0 },
    { "pcddr", 0xffffffUL, 2, 0x4000UL, 0x10001061UL, (void *)&d_4b74e0, 0 },
    { "pcd", 0xffffffUL, 4, 0x4000UL, 0x10001061UL, (void *)&d_4b74e8, 0 }
};
struct flat_4b75f4 regs_4b75a0_tail = { /* 004b75f4 tail of regs_4b75a0 */
    0
};

struct group_def grpdef_4b75f8[1] = { /* 004b75f8 64 */
    { port_read_reg, port_write_reg, port_read_io, port_write_io, gpio_m_clock, port_reset, 0, 0, 37, 3, 3, (struct reg_desc *)&regs_4b75a0, { 0 } }
};

struct group_def grpdef_4b7638[1] = { /* 004b7638 64 */
    { port_read_reg, port_write_reg, port_read_io, port_write_io, gpio_m_clock, port_reset, 0, 0, 37, 3, 3, (struct reg_desc *)&regs_4b74f0, { 0 } }
};

struct group_def grpdef_4b7678[1] = { /* 004b7678 64 */
    { port_read_reg, port_write_reg, port_read_io_c, port_write_io_c, gpio_m_clock, port_reset, 0, 0, 37, 3, 3, (struct reg_desc *)&regs_4b7548, { 0 } }
};

long d_4b8020[22] = { /* 004b8020 88 */
    3, 10, 3, 1, 14, 6, 0, 16,
    5, 5, 13, 5, 4, 13, 5, 2,
    13, 5, -2, 0, 0, 0
};

const char *d_4b8078[54] = { /* 004b8078 216 */
    "The SCI peripheral provides a simplified input file data format", "in addition to the pin I/O file format.", "An input file assigned by the statement \"input sci filename\"", "enables the input data to represent an entire transmitted character.",
    "The start, stop, and parity bits are assumed correct for the", "programed SCI receive mode.", (const char *)&empty_str, "Two special input data values, IDLE and BREAK, may be used to generate",
    "a parity error or framing error, or to simulate the idle line condition.", "A special data value, t, in the input data file will result in the user", "being prompted for the next SCI data.", "Untimed SCI input data values will be applied only after the SCI",
    "receive function is enabled.", "Timed SCI input data values begin transfer to the SCI at the specified", "relative time interval (+time) since the completion of the previous", "or at the exact simulator cycle indicated.",
    "If the first timing information in the input file is a relative", "value (+time), the simulator will wait until the SCI receive function", "is enabled before beginning the data transfer.  Otherwise the data", "transfer begins at the exact specified cycle.",
    (const char *)&empty_str, "Each input data value will be received at a rate determined by", "the internal SCI baud rate counter or by the clock signal sequences", "applied to the SCI clock pin, determined by the SCI clock mode.",
    "Storage of data to an SCI output file will begin when the SCI", "transmit function is enabled. In the timed output mode, the simulator", "cycle count and a data value are stored each time a character begins", "transmission.  In the untimed output mode, a single data value is",
    "stored each time a character begins transmission.", (const char *)&empty_str, "EXAMPLES", (const char *)&empty_str,
    "The following untimed SCI input file will cause the SCI to receive", "the word sequence 1 2 11 22 repeatedly.", "(1 2 11 22)", (const char *)&empty_str,
    "The following timed SCI input file will cause the SCI to begin", "receiving the character 23 when the SCI receiver is first enabled,", "followed by reception of F1 30 cycles after completion of the", "when the SCI receiver is first enabled, followed by reception",
    "of the first character.", "+0 23 +30 F1", (const char *)&empty_str, "The following timed SCI input file will cause the SCI to receive",
    "the character sequence 41 26 idle 23 break ten times.", (const char *)&empty_str, "(+0 41 +0 26 +0 idle +0 23 +0 break)#10", (const char *)&empty_str,
    "The following timed SCI input file will cause the SCI to receive", "the character 63 beginning at cycle 2000 and the character 88", "beginning at cycle 12000.", (const char *)&empty_str,
    "2000 63 12000 88", 0
};

const char *d_4b8150[6] = { /* 004b8150 24 */
    "sci", (const char *)&d_4b8078, "I/O file format for sci peripheral", 0,
    0, 0
};

struct rec2w_bfa51 d_4b8168[1] = { /* 004b8168 8 */
    { 1, (void *)&d_4b8150 }
};

struct rec6w_b8d22 d_4b8170[1] = { /* 004b8170 24 */
    { 7, (void *)&d_4b8020, sci_iofile_parse, sci_iofile_format, 0, (void *)&d_4b8168 }
};

const char *d_4b8188[6] = { /* 004b8188 24 */
    "Clock Control Register.", "         C C", " T R S C D D C C C C C C C C C C", " C C C O 1 1 D D D D D D D D D D",
    " M M P D 1 0 9 8 7 6 5 4 3 2 1 0", 0
};

const char *d_4b81a0[8] = { /* 004b81a0 32 */
    "Control Register.", "   S", " S T T     I     W   W   S W W W", " C M M T R L     O R A S H D D D",
    " K I I I I I T R M W K B F S S S", " P R E E E E E E S U E K D 2 1 0", 0, 0
};

const char *d_4b81c0[6] = { /* 004b81c0 24 */
    "Control Register.", " S   T     I     W   W   S W W W", " C   M T R L     O R A S H D D D", " K   I I I I T R M W K B F S S S",
    " P * E E E E E E S U E K D 2 1 0", 0
};

const char *d_4b81d8[2] = { /* 004b81d8 8 */
    "Receive Data Register. (addr=low, addr+1=mid, addr+2=high)", 0
};

const char *d_4b81e0[6] = { /* 004b81e0 24 */
    "Status Register.", "         I R T T", "         D D D R", " R F P O L R R N",
    " 8 E E R E F E E", 0
};

const char *d_4b81f8[2] = { /* 004b81f8 8 */
    "Transmit Data Register. (addr=low, addr+1=mid, addr+2=high)", 0
};

const char *d_4b8200[2] = { /* 004b8200 8 */
    "Transmit Data Register with Address bit.", 0
};

struct reg_desc regs_4b8208[6] = { /* 004b8208 168 */
    { "sccr", 0xffffUL, 2, 0x4000UL, 0x10001061UL, (void *)&d_4b8188, 0 },
    { "scr", 0xffffUL, 0, 0x4000UL, 0x10001061UL, (void *)&d_4b81a0, 1 },
    { "srx", 0xffUL, 4, 0x4000UL, 0x40001021UL, (void *)&d_4b81d8, 2 },
    { "ssr", 0xffUL, 1, 0x4000UL, 0x40001021UL, (void *)&d_4b81e0, 3 },
    { "stx", 0xffUL, 4, 0x4000UL, 0x40001041UL, (void *)&d_4b81f8, 4 },
    { "stxa", 0xffffffUL, 3, 0x4000UL, 0x40001041UL, (void *)&d_4b8200, 5 }
};

struct reg_desc regs_4b82b0[6] = { /* 004b82b0 168 */
    { "sccr", 0xffffUL, 2, 0x4000UL, 0x10001061UL, (void *)&d_4b8188, 0 },
    { "scr", 0xbfffUL, 0, 0x4000UL, 0x10001061UL, (void *)&d_4b81c0, 1 },
    { "srx", 0xffUL, 4, 0x4000UL, 0x40000021UL, (void *)&d_4b81d8, 2 },
    { "ssr", 0xffUL, 1, 0x4000UL, 0x40000021UL, (void *)&d_4b81e0, 3 },
    { "stx", 0xffUL, 4, 0x4000UL, 0x40001041UL, (void *)&d_4b81f8, 4 },
    { "stxa", 0xffffffUL, 3, 0x4000UL, 0x40001041UL, (void *)&d_4b8200, 5 }
};

struct group_def grpdef_4b8358[1] = { /* 004b8358 64 */
    { periph_read_reg, sci_write_reg, sci_read_io, sci_write_io, sci_tick, sci_reset, sci_int_pending, sci_int_ack, 38, 64, 6, (struct reg_desc *)&regs_4b8208, { 0 } }
};

struct group_def grpdef_4b8398[1] = { /* 004b8398 64 */
    { periph_read_reg, sci_write_reg, sci_read_io, sci_write_io, sci_tick, sci_reset, sci_int_pending, sci_int_ack, 6, 64, 6, (struct reg_desc *)&regs_4b82b0, { 0 } }
};

long sci_mode_bits_tab[8] = { /* 004b83d8 32 */
    8, 1, 10, 1, 11, 11, 11, 1
};

long sci_mode_nbits_tab[8] = { /* 004b83f8 32 */
    8, 0, 10, 0, 11, 11, 11, 0
};

long d_4b9024 = 1095062082L; /* 004b9024 4 */

unsigned short d_4b9028[4] = { /* 004b9028 8 */
    75, 0, 0, 0
};

long d_4b9030[24] = { /* 004b9030 96 */
    0, 10, 3, 3, 14, 6, 2, 16,
    5, -2, 0, 0, 1, 10, 3, 4,
    14, 6, 5, 16, 5, -2, 0, 0
};

const char *d_4b9090[68] = { /* 004b9090 272 */
    "The SSI peripheral provides a simplified input file data format", "in addition to the pin I/O file format.", "An input file assigned by the statement \"input ssi filename\"", "enables the input data to represent the word to be transferred",
    "to the SSI receiver during its active timeslot.", (const char *)&empty_str, "The special data value IDLE may be used in the input file to", "represent an empty time slot.",
    (const char *)&empty_str, "Untimed SSI input data values will be applied only after the SSI", "receive function is enabled and will be received back to back at", "the receiver frame rate.",
    (const char *)&empty_str, "Timed SSI input data values begin transfer to the SSI at the", "specified relative time slot interval (+time) since the previous", "word, or at the exact simulator cycle indicated by the timing",
    "information within the file.  If the first timing information in", "the file is a relative value (+time) the simulator will wait until", "the SSI receive function is enabled before beginning the data", "transfer.  Otherwise the data transfer begins at the exact specified",
    "cycle.", (const char *)&empty_str, "Each input data value will be received at a rate determined by the", "internal SSI receive baud and frame rate counters or by clock signal",
    "sequences applied to the SSI clock pins, depending on the SSI", "receive mode.", (const char *)&empty_str, "If a lower case letter t is placed in a data position of the input",
    "file, the user will be prompted for the next input data value.", (const char *)&empty_str, "Storage of data to an SSI output file will begin when the SSI", "transmit function is enabled.  In the timed output mode, the",
    "simulator cycle count and a data value are stored each time a word", "begins transmission.  In the untimed output mode, a single data", "value is stored each time a word begins transmission.", (const char *)&empty_str,
    "EXAMPLES", (const char *)&empty_str, "The following untimed SSI input file will cause the SSI to receive", "the word sequence 4F30 FF16 C397 2082 during consecutive active",
    "SSI receiver time slots.", (const char *)&empty_str, "4F30 FF16 C397 2082", (const char *)&empty_str,
    "The following untimed SSI input file will cause the SSI to receive", "the word sequence 4401 4302 4111 3922 repeatedly during consecutive", "active SSI receiver time slots.", (const char *)&empty_str,
    "(4401 4302 4111 3922)", (const char *)&empty_str, "The following timed SSI input file will cause the SSI to begin", "receiving the word 1233 when the SSI receiver is first enabled,",
    "followed by reception of 00F1 30 time slots after completion of the", "reception of the first word.", (const char *)&empty_str, "+0 1233 +30 F1",
    (const char *)&empty_str, "The following timed SSI input file will cause the SSI to receive", "the word sequence 411 226 236 ten times.", (const char *)&empty_str,
    "(+0 411 +0 226 +0 236)#10", (const char *)&empty_str, "The following timed SSI input file will cause the SSI to receive", "the word 6304 beginning at cycle 2000 and the word 9688 beginning",
    "at cycle 12000.", (const char *)&empty_str, "2000 6304 12000 9688", 0
};

const char *d_4b91a0[6] = { /* 004b91a0 24 */
    "ssi", (const char *)&d_4b9090, "I/O file format for ssi peripheral", 0,
    0, 0
};

struct rec2w_bfa51 d_4b91b8[1] = { /* 004b91b8 8 */
    { 1, (void *)&d_4b91a0 }
};

struct rec6w_b8d22 d_4b91c0[1] = { /* 004b91c0 24 */
    { 8, (void *)&d_4b9030, iofmt_idle_parse, iofmt_idle_format, 0, (void *)&d_4b91b8 }
};

const char *d_4b91d8[6] = { /* 004b91d8 24 */
    "Control Register A.", " P W W D D D D D P P P P P P P P", " S L L C C C C C M M M M M M M M", " R 1 0 4 3 2 1 0 7 6 5 4 3 2 1 0",
    0, 0
};

const char *d_4b91f0[6] = { /* 004b91f0 24 */
    "Control Register B.", "               F F S S S S S", " R T     M G S S S H C C C C O O", " I I R T O C Y L L F K D D D F F",
    " E E E E D K N 1 0 D D 2 1 0 1 0", 0
};

const char *d_4b9208[2] = { /* 004b9208 8 */
    "Serial Receive Register.", 0
};

const char *d_4b9210[2] = { /* 004b9210 8 */
    "Serial Transmit Register.", 0
};

const char *d_4b9218[6] = { /* 004b9218 24 */
    "Status Register.", " R T R T R T I I", " D D O U F F F F", " F E E E S S 1 0",
    0, 0
};

const char *d_4b9230[2] = { /* 004b9230 8 */
    "Time Slot Register.", 0
};

struct reg_desc regs_4b9238[6] = { /* 004b9238 168 */
    { "cra", 0xffffUL, 0, 0x4000UL, 0x10001061UL, (void *)&d_4b91d8, 0 },
    { "crb", 0xffffUL, 1, 0x4000UL, 0x10001061UL, (void *)&d_4b91f0, 1 },
    { "rx", 0xffffffUL, 3, 0x4000UL, 0x1021UL, (void *)&d_4b9208, 2 },
    { "ssisr", 0xffUL, 2, 0x4000UL, 0x40001021UL, (void *)&d_4b9218, 3 },
    { "tsr", 0, 2, 0x4000UL, 0x40001041UL, (void *)&d_4b9230, 4 },
    { "tx", 0xffffffUL, 3, 0x4000UL, 0x1041UL, (void *)&d_4b9210, 5 }
};

struct group_def grpdef_4b92e0[1] = { /* 004b92e0 64 */
    { periph_read_reg, ssi_write_reg, ssi_read_io, ssi_write_io, ssi_tick, ssi_reset, ssi_int_pending, ssi_int_ack, 46, 84, 6, (struct reg_desc *)&regs_4b9238, { 0 } }
};

long d_4b9320[4] = { /* 004b9320 16 */
    16711680L, 16773120L, 16776960L, 16777215L
};

long d_4b9330[4] = { /* 004b9330 16 */
    65536L, 4096, 256, 1
};

long d_4b9340[4] = { /* 004b9340 16 */
    255, 4095, 65535L, 16777215L
};

long d_4b9350[4] = { /* 004b9350 16 */
    16, 12, 8, 0
};

long d_4b9360[4] = { /* 004b9360 16 */
    2, 4, 6, 10
};

long d_4b9370[4] = { /* 004b9370 16 */
    8, 12, 16, 24
};

long d_4b9d50[52] = { /* 004b9d50 208 */
    3, 10, 3, 1, 14, 6, 4, 16,
    5, 2, 16, 5, -2, 0, 0, 8,
    10, 3, 10, 14, 6, 9, 16, 5,
    11, 13, 5, 13, 11, 4, 12, 11,
    4, -2, 0, 0, 5, 10, 3, 0,
    14, 6, 6, 16, 5, 7, 13, 5,
    -2, 0, 0, 0
};

const char *d_4b9e20[84] = { /* 004b9e20 336 */
    "Input data words assigned to the host peripheral contain a host", "control byte and a host data byte.  The control byte represents", "the upper 8 bits of the portb input word and must be one of the", "following hexadecimal values to select the associated host",
    "interface function.  Host accesses should be terminated using the", "term code.", "Control  Term    Host Function", "40       50      ICR Write",
    "48       58      ICR Read", "41       51      CVR Write", "49       59      CVR Read", "4A       5A      ISR Read",
    "43       53      IVR Write", "4B       5B      IVR Read", "45       55      TXH Write", "4D       5D      RXH Read",
    "46       56      TXMWrite", "4E       5E      RXM Read", "47       57      TXL Write", "4F       5F      RXL Read",
    "00       50      DMA strobe or Host IVR Read", (const char *)&empty_str, "Although the input command allows specification of the input radix,", "the requirement that the upper data byte correspond to one of the",
    "previous control bytes makes it difficult in practice to use an", "input radix other than hexadecimal.", (const char *)&empty_str, "Note that for each value written to a host register, two input data",
    "words are required in the input data file.  This is because data", "value latches into the host register on the rising edge of the hen", "signal.  The term control byte in the second word provides the", "positive edge of the hen signal.   The lower byte of terminating",
    "host input word for a write operation should contain the data value", "to be written to the host register.", (const char *)&empty_str, "Although this mode of host port input limits the host data input",
    "rate to one word every two device cycles, a rate of one word per", "device clock can be achieved by using the pin data input mode in", "conjunction with N or P pin clock pulses.", (const char *)&empty_str,
    "Untimed Host Port input data values will be applied only during", "cycles when the Host Port function is enabled.  Each data value is", "applied for a single simulator clock cycle, with the exception that", "the final specified data value will remain applied to the port",
    "indefinitely.  The repeat punctuation and repeat count may be used", "to specify durations of longer than one cycle.", (const char *)&empty_str, "Timed Host Port input data values will be applied to the Host Port",
    "at the time intervals, or at the exact simulator cycles indicated", "by the timing information within the file.  If the first timing", "information in the file is a relative value, (timing preceded by +)", "the simulator will wait until the Host Port function is enabled",
    "before applying the data.", (const char *)&empty_str, "If a lower case letter t is placed in a data position of the input", "file, the user will be prompted for the next input data value.",
    (const char *)&empty_str, "Storage of data to the Host Port output file will begin when the", "Host Port is enabled.  In the timed output mode, the simulator cycle", "count and a data value are stored each time the Host output changes.",
    "In the untimed output mode, a data value and a following repeat", "count are stored each time the data changes.", (const char *)&empty_str, "EXAMPLES",
    (const char *)&empty_str, "The following untimed HOST input file will cause a read of the", "Host ICR, followed by a write of the Host ICR 20 cycles later with", "hexadecimal value 83.  Note that the lower data byte, which",
    "corresponds to the input host data, must be valid in the data word", "in which the hen rising edge occurs.", (const char *)&empty_str, "4800 5800#20 4083 5083",
    (const char *)&empty_str, "The following timed HOST input file will cause a read of the Host", "IVR, followed by a write of the Host IVR 5 cycles later with the", "hexadecimal value 20.",
    (const char *)&empty_str, "+0 4B00 +1 5B00 +5 4320 +1 5320", (const char *)&empty_str, "The following untimed HOST input file will read each Host Port in",
    "sequence repeatedly.", (const char *)&empty_str, "(4800 5800 4900 5900 4A00 5A00 4B00 5B00 4E00 5E00 4F00 5F00)", 0
};

const char *d_4b9f70[6] = { /* 004b9f70 24 */
    "host", (const char *)&d_4b9e20, "I/O file format for host port", 0,
    0, 0
};

struct rec2w_bfa51 d_4b9f88[1] = { /* 004b9f88 8 */
    { 1, (void *)&d_4b9f70 }
};

struct rec2w_bfa51 d_4b9f90[3] = { /* 004b9f90 24 */
    { 17, (void *)&d_4b9d50 },
    { 0, 0 },
    { 0, (void *)&d_4b9f88 }
};

const char *d_4b9fa8[82] = { /* 004b9fa8 328 */
    "Input data words assigned to the host peripheral contain a host", "control byte and a host data byte.  The control byte represents", "the upper 8 bits of the portb input word and must be one of the", "following hexadecimal values to select the associated host",
    "interface function.  Host accesses should be terminated using the", "term code.", "Control  Term    Host Function", "48       58      ICR Write",
    "50       58      ICR Read", "49       59      CVR Write", "51       59      CVR Read", "52       5A      ISR Read",
    "4B       5B      IVR Write", "53       5B      IVR Read", "4D       5D      TXH Write", "55       5D      RXH Read",
    "4E       5E      TXM Write", "56       5E      RXM Read", "4F       5F      TXL Write", "57       5F      RXL Read",
    "10       58      DMA strobe or Host IVR Read", (const char *)&empty_str, "Although the input command allows specification of the input radix,", "the requirement that the upper data byte correspond to one of the",
    "previous control bytes makes it difficult in practice to use an", "input radix other than hexadecimal.", (const char *)&empty_str, "Note that for each value written to a host register, two input data",
    "words are required in the input data file.  This is because data", "value latches into the host register on the rising edge of the hwe", "signal.  The term control byte in the second word provides the", "positive edge of the hwe signal.   The lower byte of terminating",
    "host input word for a write operation should contain the data value", "to be written to the host register.", (const char *)&empty_str, "This mode of host port input limits the host data input",
    "rate to one word every two device cycles.", (const char *)&empty_str, "Untimed Host Port input data values will be applied only during", "cycles when the Host Port function is enabled.  Each data value is",
    "applied for a single simulator clock cycle, with the exception that", "the final specified data value will remain applied to the port", "indefinitely.  The repeat punctuation and repeat count may be used", "to specify durations of longer than one cycle.",
    (const char *)&empty_str, "Timed Host Port input data values will be applied to the Host Port", "at the time intervals, or at the exact simulator cycles indicated", "by the timing information within the file.  If the first timing",
    "information in the file is a relative value, (timing preceded by +)", "the simulator will wait until the Host Port function is enabled", "before applying the data.", (const char *)&empty_str,
    "If a lower case letter t is placed in a data position of the input", "file, the user will be prompted for the next input data value.", (const char *)&empty_str, "Storage of data to the Host Port output file will begin when the",
    "Host Port is enabled.  In the timed output mode, the simulator cycle", "count and a data value are stored each time the Host output changes.", "In the untimed output mode, a data value and a following repeat", "count are stored each time the data changes.",
    (const char *)&empty_str, "EXAMPLES", (const char *)&empty_str, "The following untimed HOST input file will cause a read of the",
    "Host ICR, followed by a write of the Host ICR 20 cycles later with", "hexadecimal value 83.  Note that the lower data byte, which", "corresponds to the input host data, must be valid in the data word", "in which the hen rising edge occurs.",
    (const char *)&empty_str, "5000 5800#20 4883 5883", (const char *)&empty_str, "The following timed HOST input file will cause a read of the Host",
    "IVR, followed by a write of the Host IVR 5 cycles later with the", "hexadecimal value 20.", (const char *)&empty_str, "+0 5300 +1 5B00 +5 4B20 +1 5B20",
    (const char *)&empty_str, "The following untimed HOST input file will read each Host Port", "register in sequence repeatedly.", (const char *)&empty_str,
    "(5000 5800 5100 5900 5200 5A00 5500 5B00 5600 5E00 5700 5F00)", 0
};

const char *d_4ba0f0[6] = { /* 004ba0f0 24 */
    "host", (const char *)&d_4b9fa8, "I/O file format for host port", 0,
    0, 0
};

struct rec2w_bfa51 d_4ba108[1] = { /* 004ba108 8 */
    { 1, (void *)&d_4ba0f0 }
};

struct rec2w_bfa51 d_4ba110[3] = { /* 004ba110 24 */
    { 17, (void *)&d_4b9d50 },
    { 0, 0 },
    { 0, (void *)&d_4ba108 }
};

const char *d_4ba128[4] = { /* 004ba128 16 */
    "Read-Write Command Vector Register. Host Processor Address 1.", " H", " C * {     HV    }", 0
};

const char *d_4ba138[6] = { /* 004ba138 24 */
    "Control Register.", "           {H H H}", "       {H H C T R}", "       {F F I I I}",
    " * * * {3 2 E E E}", 0
};

const char *d_4ba150[2] = { /* 004ba150 8 */
    "Receive Data Register", 0
};

const char *d_4ba158[6] = { /* 004ba158 24 */
    "Status Register.", "             {H H}", " {D}     {H H H T R}", " {M}     {F F C D D}",
    " {A} * * {1 0 P E F}", 0
};

const char *d_4ba170[2] = { /* 004ba170 8 */
    "Transmit Data Register", 0
};

const char *d_4ba178[6] = { /* 004ba178 24 */
    "Read-Write Interrupt Control Register. Host Processor Address 0.", " I           T R", " N H H H H   R R", " I M M F F   E E",
    " T 1 0 1 0 * Q Q", 0
};

const char *d_4ba190[6] = { /* 004ba190 24 */
    "Read-Only Interrupt Status Register. Host Processor Address 2.", " H         T T R", " R D   H H R X X", " E M   F F D D D",
    " Q A * 3 2 Y E F", 0
};

const char *d_4ba1a8[2] = { /* 004ba1a8 8 */
    "Read-Write Interrupt Vector Register. Host Processor Address 3.", 0
};

const char *d_4ba1b0[2] = { /* 004ba1b0 8 */
    "Read-Only Receive Byte Register (High Byte). Host Processor Address 5.", 0
};

const char *d_4ba1b8[2] = { /* 004ba1b8 8 */
    "Read-Only Receive Byte Register (Low Byte). Host Processor Address 7.", 0
};

const char *d_4ba1c0[2] = { /* 004ba1c0 8 */
    "Read-Only Receive Byte Register (Mid Byte). Host Processor Address 6.", 0
};

const char *d_4ba1c8[2] = { /* 004ba1c8 8 */
    "Write-Only Transmit Byte Register (High Byte). Host Processor Address 5.", 0
};

const char *d_4ba1d0[2] = { /* 004ba1d0 8 */
    "Write-Only Transmit Byte Register (Low Byte). Host Processor Address 7.", 0
};

const char *d_4ba1d8[2] = { /* 004ba1d8 8 */
    "Write-Only Transmit Byte Register (Mid Byte). Host Processor Address 6.", 0
};

struct reg_desc regs_4ba1e0[14] = { /* 004ba1e0 392 */
    { "cvr", 0x9fUL, 0, 0x4000UL, 0x40001001UL, (void *)&d_4ba128, 0 },
    { "hcr", 0x1fUL, 0, 0x4000UL, 0x40001061UL, (void *)&d_4ba138, 1 },
    { "hrx", 0xffffffUL, 3, 0x4000UL, 0x4001021UL, (void *)&d_4ba150, 2 },
    { "hsr", 0x9fUL, 1, 0x4000UL, 0x40001021UL, (void *)&d_4ba158, 3 },
    { "htx", 0xffffffUL, 3, 0x4000UL, 0x4001041UL, (void *)&d_4ba170, 4 },
    { "icr", 0xfbUL, 0, 0x4000UL, 0x40001001UL, (void *)&d_4ba178, 0 },
    { "isr", 0xdfUL, 0, 0x4000UL, 0x40001001UL, (void *)&d_4ba190, 0 },
    { "ivr", 0xffUL, 0, 0x4000UL, 0x40001001UL, (void *)&d_4ba1a8, 0 },
    { "rxh", 0xffUL, 0, 0x4000UL, 0x40001001UL, (void *)&d_4ba1b0, 0 },
    { "rxl", 0xffUL, 0, 0x4000UL, 0x40001001UL, (void *)&d_4ba1b8, 0 },
    { "rxm", 0xffUL, 0, 0x4000UL, 0x40001001UL, (void *)&d_4ba1c0, 0 },
    { "txh", 0xffUL, 0, 0x4000UL, 0x40001001UL, (void *)&d_4ba1c8, 0 },
    { "txl", 0xffUL, 0, 0x4000UL, 0x40001001UL, (void *)&d_4ba1d0, 0 },
    { "txm", 0xffUL, 0, 0x4000UL, 0x40001001UL, (void *)&d_4ba1d8, 0 }
};

struct reg_desc regs_4ba368[14] = { /* 004ba368 392 */
    { "cvr", 0xbfUL, 0, 0x4000UL, 0x40001001UL, (void *)&d_4ba128, 0 },
    { "hcr", 0x1fUL, 0, 0x4000UL, 0x40001061UL, (void *)&d_4ba138, 1 },
    { "hrx", 0xffffffUL, 3, 0x4000UL, 0x4001021UL, (void *)&d_4ba150, 2 },
    { "hsr", 0x9fUL, 1, 0x4000UL, 0x40001021UL, (void *)&d_4ba158, 3 },
    { "htx", 0xffffffUL, 3, 0x4000UL, 0x4001041UL, (void *)&d_4ba170, 4 },
    { "icr", 0xfbUL, 0, 0x4000UL, 0x40001001UL, (void *)&d_4ba178, 0 },
    { "isr", 0xdfUL, 0, 0x4000UL, 0x40001001UL, (void *)&d_4ba190, 0 },
    { "ivr", 0xffUL, 0, 0x4000UL, 0x40001001UL, (void *)&d_4ba1a8, 0 },
    { "rxh", 0xffUL, 0, 0x4000UL, 0x40001001UL, (void *)&d_4ba1b0, 0 },
    { "rxl", 0xffUL, 0, 0x4000UL, 0x40001001UL, (void *)&d_4ba1b8, 0 },
    { "rxm", 0xffUL, 0, 0x4000UL, 0x40001001UL, (void *)&d_4ba1c0, 0 },
    { "txh", 0xffUL, 0, 0x4000UL, 0x40001001UL, (void *)&d_4ba1c8, 0 },
    { "txl", 0xffUL, 0, 0x4000UL, 0x40001001UL, (void *)&d_4ba1d0, 0 },
    { "txm", 0xffUL, 0, 0x4000UL, 0x40001001UL, (void *)&d_4ba1d8, 0 }
};

struct reg_desc regs_4ba4f0[14] = { /* 004ba4f0 392 */
    { "cvr", 0xbfUL, 0, 0x4000UL, 0x40001001UL, (void *)&d_4ba128, 0 },
    { "hcr", 0x1fUL, 0, 0x4000UL, 0x40001061UL, (void *)&d_4ba138, 1 },
    { "horx", 0xffffffUL, 3, 0x4000UL, 0x4001021UL, (void *)&d_4ba150, 2 },
    { "hsr", 0x9fUL, 1, 0x4000UL, 0x40001021UL, (void *)&d_4ba158, 3 },
    { "hotx", 0xffffffUL, 3, 0x4000UL, 0x4001041UL, (void *)&d_4ba170, 4 },
    { "icr", 0xfbUL, 0, 0x4000UL, 0x40001001UL, (void *)&d_4ba178, 0 },
    { "isr", 0xdfUL, 0, 0x4000UL, 0x40001001UL, (void *)&d_4ba190, 0 },
    { "ivr", 0xffUL, 0, 0x4000UL, 0x40001001UL, (void *)&d_4ba1a8, 0 },
    { "rxh", 0xffUL, 0, 0x4000UL, 0x40001001UL, (void *)&d_4ba1b0, 0 },
    { "rxl", 0xffUL, 0, 0x4000UL, 0x40001001UL, (void *)&d_4ba1b8, 0 },
    { "rxm", 0xffUL, 0, 0x4000UL, 0x40001001UL, (void *)&d_4ba1c0, 0 },
    { "txh", 0xffUL, 0, 0x4000UL, 0x40001001UL, (void *)&d_4ba1c8, 0 },
    { "txl", 0xffUL, 0, 0x4000UL, 0x40001001UL, (void *)&d_4ba1d0, 0 },
    { "txm", 0xffUL, 0, 0x4000UL, 0x40001001UL, (void *)&d_4ba1d8, 0 }
};

struct group_def grpdef_4ba678[1] = { /* 004ba678 64 */
    { periph_read_reg, hi_write_reg, hi_read_io, hi_write_io, hi_tick_a, hi_reset, hi_int_pending, hi_int_ack, 36, 32, 14, (struct reg_desc *)&regs_4ba1e0, { 0 } }
};

struct group_def grpdef_4ba6b8[1] = { /* 004ba6b8 64 */
    { periph_read_reg, hi_write_reg, hi_read_io, hi_write_io, hi_tick_a, hi_reset, hi_int_pending, hi_int_ack, 36, 32, 14, (struct reg_desc *)&regs_4ba368, { 0 } }
};

struct group_def grpdef_4ba6f8[1] = { /* 004ba6f8 64 */
    { periph_read_reg, hi_write_reg, hi_read_io, hi_write_io, hi_tick_a, hi_reset, hi_int_pending, hi_int_ack, 36, 32, 14, (struct reg_desc *)&regs_4ba4f0, { 0 } }
};

struct group_def grpdef_4ba738[1] = { /* 004ba738 64 */
    { periph_read_reg, hi_write_reg, hi_read_io, hi_write_io, hi_tick_b, hi_reset, hi_int_pending, hi_int_ack, 36, 32, 14, (struct reg_desc *)&regs_4ba368, { 0 } }
};

long hi_cmd_reg_tab[8] = { /* 004ba778 32 */
    5, 0, 20, 7, 20, 11, 13, 12
};

long d_4ba798[8] = { /* 004ba798 32 */
    5, 0, 20, 7, 20, 11, 13, 12
};

struct periph_desc periph_4bbd08[7] = { /* 004bbd08 504 */
    { "core", 0, 0xffffUL, 0, 0, 0, 0, 0, 0, 0, 0, (struct group_def *)&grpdef_4b26c8, (void *)&empty_str, { 0 } },
    { "host", 2, 0x7fffUL, 0, 0, 65504L, 3, 65512L, 32, 0, 3072, (struct group_def *)&grpdef_4ba6b8, (void *)&empty_str, { 0 } },
    { "ssi", 3, 0x1f8UL, 0, 0, 65505L, 504, 65516L, 12, 0, 12288, (struct group_def *)&grpdef_4b92e0, (void *)&empty_str, { 0 } },
    { "sci", 3, 0x207UL, 0, 0, 65505L, 7, 65520L, 20, 0, 49152L, (struct group_def *)&grpdef_4b8358, (void *)&empty_str, { 0 } },
    { "portb", 2, 0x7fffUL, 0, 0, 65504L, 0, 65504L, 0, 0, 0, (struct group_def *)&grpdef_4b7638, (void *)&empty_str, { 0 } },
    { "portc", 3, 0x1ffUL, 0, 0, 65505L, 0, 65505L, 0, 0, 0, (struct group_def *)&grpdef_4b75f8, (void *)&empty_str, { 0 } },
    { "count", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, (struct group_def *)&grpdef_4b71d0, (void *)&empty_str, { 0 } }
};

struct rec6w_eb01e d_4bbf00[81] = { /* 004bbf00 1944 */
    { "reset", 0, 0, 0, 4, 128 },
    { "modc", "nmi", 0, 0, 8, 128 },
    { "modb", "irqb", 0, 0, 2, 128 },
    { "moda", "irqa", 0, 0, 1, 128 },
    { "ps", 0, 0, 0, 32768L, 128 },
    { "ds", 0, 0, 0, 16384, 128 },
    { "rd", 0, 0, 0, 8192, 128 },
    { "wr", 0, 0, 0, 4096, 128 },
    { "xy", 0, 0, 0, 2048, 128 },
    { "br", "wt", 0, 0, 8388608L, 128 },
    { "bg", "bs", 0, 0, 16777216L, 128 },
    { "pc8", "std", 0, 3, 256, 128 },
    { "pc7", "srd", 0, 3, 128, 128 },
    { "pc6", "sck", 0, 3, 64, 128 },
    { "pc5", "sc2", 0, 3, 32, 128 },
    { "pc4", "sc1", 0, 3, 16, 128 },
    { "pc3", "sc0", 0, 3, 8, 128 },
    { "tclk", 0, 0, 3, 512, 128 },
    { "pc2", "rclk", 0, 3, 4, 128 },
    { "pc1", "txd", 0, 3, 2, 128 },
    { "pc0", "rxd", 0, 3, 1, 128 },
    { "pb14", "hack", 0, 2, 16384, 128 },
    { "pb13", "hreq", 0, 2, 8192, 128 },
    { "pb12", "hen", 0, 2, 4096, 128 },
    { "pb11", "hrw", 0, 2, 2048, 128 },
    { "pb10", "ha2", 0, 2, 1024, 128 },
    { "pb9", "ha1", 0, 2, 512, 128 },
    { "pb8", "ha0", 0, 2, 256, 128 },
    { "pb7", "h7", 0, 2, 128, 128 },
    { "pb6", "h6", 0, 2, 64, 128 },
    { "pb5", "h5", 0, 2, 32, 128 },
    { "pb4", "h4", 0, 2, 16, 128 },
    { "pb3", "h3", 0, 2, 8, 128 },
    { "pb2", "h2", 0, 2, 4, 128 },
    { "pb1", "h1", 0, 2, 2, 128 },
    { "pb0", "h0", 0, 2, 1, 128 },
    { "pa15", "a15", 0, 1, 32768L, 128 },
    { "pa14", "a14", 0, 1, 16384, 128 },
    { "pa13", "a13", 0, 1, 8192, 128 },
    { "pa12", "a12", 0, 1, 4096, 128 },
    { "pa11", "a11", 0, 1, 2048, 128 },
    { "pa10", "a10", 0, 1, 1024, 128 },
    { "pa9", "a9", 0, 1, 512, 128 },
    { "pa8", "a8", 0, 1, 256, 128 },
    { "pa7", "a7", 0, 1, 128, 128 },
    { "pa6", "a6", 0, 1, 64, 128 },
    { "pa5", "a5", 0, 1, 32, 128 },
    { "pa4", "a4", 0, 1, 16, 128 },
    { "pa3", "a3", 0, 1, 8, 128 },
    { "pa2", "a2", 0, 1, 4, 128 },
    { "pa1", "a1", 0, 1, 2, 128 },
    { "pa0", "a0", 0, 1, 1, 128 },
    { "pd23", "d23", 0, 4, 8388608L, 128 },
    { "pd22", "d22", 0, 4, 4194304L, 128 },
    { "pd21", "d21", 0, 4, 2097152L, 128 },
    { "pd20", "d20", 0, 4, 1048576L, 128 },
    { "pd19", "d19", 0, 4, 524288L, 128 },
    { "pd18", "d18", 0, 4, 262144L, 128 },
    { "pd17", "d17", 0, 4, 131072L, 128 },
    { "pd16", "d16", 0, 4, 65536L, 128 },
    { "pd15", "d15", 0, 4, 32768L, 128 },
    { "pd14", "d14", 0, 4, 16384, 128 },
    { "pd13", "d13", 0, 4, 8192, 128 },
    { "pd12", "d12", 0, 4, 4096, 128 },
    { "pd11", "d11", 0, 4, 2048, 128 },
    { "pd10", "d10", 0, 4, 1024, 128 },
    { "pd9", "d9", 0, 4, 512, 128 },
    { "pd8", "d8", 0, 4, 256, 128 },
    { "pd7", "d7", 0, 4, 128, 128 },
    { "pd6", "d6", 0, 4, 64, 128 },
    { "pd5", "d5", 0, 4, 32, 128 },
    { "pd4", "d4", 0, 4, 16, 128 },
    { "pd3", "d3", 0, 4, 8, 128 },
    { "pd2", "d2", 0, 4, 4, 128 },
    { "pd1", "d1", 0, 4, 2, 128 },
    { "pd0", "d0", 0, 4, 1, 128 },
    { "de", 0, 0, 0, 128, 128 },
    { "dso", 0, 0, 0, 64, 128 },
    { "dsck", "os1", 0, 0, 32, 128 },
    { "dsi", "os0", 0, 0, 16, 128 },
    { "clk", 0, 0, 0, 524288L, 128 }
};

long d_4bc698[32] = { /* 004bc698 128 */
    3145728L, 5633024L, 512, 719364L, 21, 719361L, 10, 6419456L,
    512, 786689L, 696352L, 445696L, 19, 698755L, 17, 140,
    786452L, 698752L, 13, 546923L, 786688L, 6419456L, 49152L, 445696L,
    30, 394112L, 29, 514442L, 395424L, 2097186L, 481420L, 786688L
};

long d_4bc718[32] = { /* 004bc718 128 */
    3211264L, 327866L, 185, 713088L, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0
};

struct mem_region regions_4bc798[19] = { /* 004bc798 840 */
    { "p", 0, 0x8c300000UL, 0, 65535L, 0, 0x201000UL, 0, 65535L, 0x4000001UL, 1 },
    { "pe", 13, 0xc000000UL, 0, 65535L, 0, 0x1607000UL, 0, 65535L, 0x4000001UL, 1 },
    { "pi", 14, 0x80200000UL, 0, 511, 512, 0x627000UL, 0, 65535L, 0x4000001UL, 1 },
    { "pi", 14, 0x80200000UL, 512, 38911L, 38400L, 0x627008UL, 0, 65535L, 0x4000001UL, 1 },
    { "pr", 15, 0x80100000UL, 0, 31, 32, 0x62f008UL, 4966040L, 65535L, 0x4000001UL, 1 },
    { "pr", 15, 0x80100000UL, 256, 287, 32, 0x62f008UL, 4966168L, 65535L, 0x4000001UL, 1 },
    { "x", 1, 0x43300000UL, 0, 65535L, 0, 0x200000UL, 0, 65535L, 0x4000001UL, 1 },
    { "xe", 18, 0x3000000UL, 0, 65535L, 0, 0x1606000UL, 0, 65535L, 0x4000001UL, 1 },
    { "xi", 19, 0x40200000UL, 0, 2559, 2560, 0x626000UL, 0, 65535L, 0x4000001UL, 1 },
    { "xi", 19, 0x40200000UL, 65472L, 65535L, 0, 0x616000UL, 0, 65535L, 0x4000001UL, 1 },
    { "xr", 20, 0x40100000UL, 2560, 10239, 7680, 0x60e008UL, 0, 65535L, 0x4000001UL, 1 },
    { "y", 2, 0x20f00000UL, 0, 65535L, 0, 0x200000UL, 0, 65535L, 0x4000001UL, 1 },
    { "ye", 23, 0xc00000UL, 0, 65535L, 0, 0x1606000UL, 0, 65535L, 0x4000001UL, 1 },
    { "yi", 24, 0x20200000UL, 0, 2559, 2560, 0x606000UL, 0, 65535L, 0x4000001UL, 1 },
    { "yr", 25, 0x20100000UL, 2560, 10239, 7680, 0x60e008UL, 0, 65535L, 0x4000001UL, 1 },
    { "l", 3, 0x13e00000UL, 0, 65535L, 0, 0x200000UL, 0, 65535L, 0x800002UL, 1 },
    { "le", 9, 0x13c00000UL, 0, 65535L, 0, 0x1602000UL, 0, 65535L, 0x800002UL, 1 },
    { "li", 10, 0x10200000UL, 0, 2559, 0, 0x602000UL, 0, 65535L, 0x800002UL, 1 },
    { "dm", 285, 0x20000UL, 0, 16777215L, 0, 0x1606000UL, 0, 16777215L, 0x4000001UL, 1 }
};
struct flat_4bcadc regions_4bc798_tail = { /* 004bcadc tail of regions_4bc798 */
    0
};

long d_4bcae0[222] = { /* 004bcae0 888 */
    8454159L, 8454159L, 262144L, 262144L, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0
};

struct rec5w_202fb d_4bce58[8] = { /* 004bce58 160 */
    { "ctrl", 0, 25230848L, 0, 0 },
    { "porta", 1, 65535L, 0, 0 },
    { "addr", 1, 65535L, 0, 0 },
    { "abus", 1, 65535L, 0, 0 },
    { "portd", 4, 16777215L, 0, 0 },
    { "dbus", 4, 16777215L, 0, 0 },
    { "data", 4, 16777215L, 0, 0 },
    { "imc", 0, 7, 0, 0 }
};

struct dev_type dev_68356[1] = { /* 004bcef8 1248 */
    { "68356", 709, 128, 67108872L, 2, 7, (struct periph_desc *)&periph_4bbd08, 19, (struct mem_region *)&regions_4bc798, "DSPMEM", (struct core_vtable *)&core_vtable_56000, 29, 6, (void *)&d_4bcae0, 81, (void *)&d_4bbf00, 8, (void *)&d_4bce58, { 0 }, 0 }
};

long d_4bd3d8[4] = { /* 004bd3d8 16 */
    0, 0, 0, 0
};

struct periph_desc periph_4bd3e8[9] = { /* 004bd3e8 648 */
    { "core", 0, 0xffffUL, 0, 0, 0, 0, 0, 0, 0, 0, (struct group_def *)&grpdef_4b2708, (void *)&empty_str, { 0 } },
    { "host", 2, 0xffffUL, 0, 0, 65504L, 3, 65512L, 32, 0, 3072, (struct group_def *)&grpdef_4ba738, (void *)&empty_str, { 0 } },
    { "ssi", 3, 0x1f8UL, 0, 0, 65505L, 504, 65516L, 12, 0, 12288, (struct group_def *)&grpdef_4b92e0, (void *)&empty_str, { 0 } },
    { "sci", 3, 0x207UL, 0, 0, 65505L, 7, 65520L, 20, 0, 49152L, (struct group_def *)&grpdef_4b8358, (void *)&empty_str, { 0 } },
    { "portb", 2, 0x7fffUL, 0, 0, 65504L, 0, 65504L, 0, 0, 0, (struct group_def *)&grpdef_4b7638, (void *)&empty_str, { 0 } },
    { "portc", 3, 0x1ffUL, 0, 0, 65505L, 0, 65505L, 0, 0, 0, (struct group_def *)&grpdef_4b75f8, (void *)&empty_str, { 0 } },
    { "timer0", 5, 1UL, 0, 0, 65502L, 0, 65502L, 60, 0, 196608L, (struct group_def *)&grpdef_4b6720, (void *)"0", { 0 } },
    { "timer1", 5, 2UL, 0, 0, 65500L, 0, 65500L, 58, 0, 786432L, (struct group_def *)&grpdef_4b6720, (void *)"1", { 0 } },
    { "count", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, (struct group_def *)&grpdef_4b71d0, (void *)&empty_str, { 0 } }
};

struct rec6w_eb01e d_4bd670[101] = { /* 004bd670 2424 */
    { "reset", 0, 0, 0, 4, 2048 },
    { "modc", "nmi", 0, 0, 8, 2048 },
    { "modb", "irqb", 0, 0, 2, 2048 },
    { "moda", "irqa", 0, 0, 1, 2048 },
    { "ps", 0, 0, 0, 32768L, 2048 },
    { "ds", 0, 0, 0, 16384, 2048 },
    { "rd", 0, 0, 0, 8192, 2048 },
    { "wr", 0, 0, 0, 4096, 2048 },
    { "xy", 0, 0, 0, 2048, 2048 },
    { "br", 0, 0, 0, 1024, 2048 },
    { "bg", 0, 0, 0, 512, 2048 },
    { "bs", 0, 0, 0, 131072L, 2048 },
    { "wt", 0, 0, 0, 65536L, 2048 },
    { "bn", 0, 0, 0, 262144L, 2048 },
    { "pc8", "std", 0, 3, 256, 2048 },
    { "pc7", "srd", 0, 3, 128, 2048 },
    { "pc6", "sck", 0, 3, 64, 2048 },
    { "pc5", "sc2", 0, 3, 32, 2048 },
    { "pc4", "sc1", 0, 3, 16, 2048 },
    { "pc3", "sc0", 0, 3, 8, 2048 },
    { "tclk", 0, 0, 3, 512, 2048 },
    { "pc2", "rclk", 0, 3, 4, 2048 },
    { "pc1", "txd", 0, 3, 2, 2048 },
    { "pc0", "rxd", 0, 3, 1, 2048 },
    { "hcs", 0, 0, 2, 32768L, 2048 },
    { "pb14", "hack", 0, 2, 16384, 2048 },
    { "pb13", "hreq", 0, 2, 8192, 2048 },
    { "pb12", "hwe", 0, 2, 4096, 2048 },
    { "pb11", "hoe", 0, 2, 2048, 2048 },
    { "pb10", "ha2", 0, 2, 1024, 2048 },
    { "pb9", "ha1", 0, 2, 512, 2048 },
    { "pb8", "ha0", 0, 2, 256, 2048 },
    { "pb7", "h7", 0, 2, 128, 2048 },
    { "pb6", "h6", 0, 2, 64, 2048 },
    { "pb5", "h5", 0, 2, 32, 2048 },
    { "pb4", "h4", 0, 2, 16, 2048 },
    { "pb3", "h3", 0, 2, 8, 2048 },
    { "pb2", "h2", 0, 2, 4, 2048 },
    { "pb1", "h1", 0, 2, 2, 2048 },
    { "pb0", "h0", 0, 2, 1, 2048 },
    { "pa15", "a15", 0, 1, 32768L, 2048 },
    { "pa14", "a14", 0, 1, 16384, 2048 },
    { "pa13", "a13", 0, 1, 8192, 2048 },
    { "pa12", "a12", 0, 1, 4096, 2048 },
    { "pa11", "a11", 0, 1, 2048, 2048 },
    { "pa10", "a10", 0, 1, 1024, 2048 },
    { "pa9", "a9", 0, 1, 512, 2048 },
    { "pa8", "a8", 0, 1, 256, 2048 },
    { "pa7", "a7", 0, 1, 128, 2048 },
    { "pa6", "a6", 0, 1, 64, 2048 },
    { "pa5", "a5", 0, 1, 32, 2048 },
    { "pa4", "a4", 0, 1, 16, 2048 },
    { "pa3", "a3", 0, 1, 8, 2048 },
    { "pa2", "a2", 0, 1, 4, 2048 },
    { "pa1", "a1", 0, 1, 2, 2048 },
    { "pa0", "a0", 0, 1, 1, 2048 },
    { "pd23", "d23", 0, 4, 8388608L, 2048 },
    { "pd22", "d22", 0, 4, 4194304L, 2048 },
    { "pd21", "d21", 0, 4, 2097152L, 2048 },
    { "pd20", "d20", 0, 4, 1048576L, 2048 },
    { "pd19", "d19", 0, 4, 524288L, 2048 },
    { "pd18", "d18", 0, 4, 262144L, 2048 },
    { "pd17", "d17", 0, 4, 131072L, 2048 },
    { "pd16", "d16", 0, 4, 65536L, 2048 },
    { "pd15", "d15", 0, 4, 32768L, 2048 },
    { "pd14", "d14", 0, 4, 16384, 2048 },
    { "pd13", "d13", 0, 4, 8192, 2048 },
    { "pd12", "d12", 0, 4, 4096, 2048 },
    { "pd11", "d11", 0, 4, 2048, 2048 },
    { "pd10", "d10", 0, 4, 1024, 2048 },
    { "pd9", "d9", 0, 4, 512, 2048 },
    { "pd8", "d8", 0, 4, 256, 2048 },
    { "pd7", "d7", 0, 4, 128, 2048 },
    { "pd6", "d6", 0, 4, 64, 2048 },
    { "pd5", "d5", 0, 4, 32, 2048 },
    { "pd4", "d4", 0, 4, 16, 2048 },
    { "pd3", "d3", 0, 4, 8, 2048 },
    { "pd2", "d2", 0, 4, 4, 2048 },
    { "pd1", "d1", 0, 4, 2, 2048 },
    { "pd0", "d0", 0, 4, 1, 2048 },
    { "de", 0, 0, 0, 128, 2048 },
    { "dso", 0, 0, 0, 64, 2048 },
    { "dsck", "os1", 0, 0, 32, 2048 },
    { "dsi", "os0", 0, 0, 16, 2048 },
    { "clk", "ckout", 0, 0, 524288L, 2048 },
    { "pe0", "tioa", 0, 5, 1, 2048 },
    { "pe1", "tiob", 0, 5, 2, 2048 },
    { "pinit", 0, 0, 0, 33554432L, 2048 },
    { "plock", 0, 0, 0, 67108864L, 2048 },
    { "extal", 0, 0, 0, 134217728L, 2048 },
    { "xtal", 0, 0, 0, 268435456L, 2048 },
    { "mcwe", 0, 0, 6, 1, 2048 },
    { "mcbr", 0, 0, 6, 2, 2048 },
    { "mcbgack", 0, 0, 6, 4, 2048 },
    { "mcbg", 0, 0, 6, 8, 2048 },
    { "mcdtack", 0, 0, 6, 16, 2048 },
    { "mcas", 0, 0, 6, 32, 2048 },
    { "mcbclr", 0, 0, 6, 64, 2048 },
    { "mcclk", 0, 0, 6, 128, 2048 },
    { "d20out", 0, 0, 0, 1073741824L, 2048 },
    { "d20in", 0, 0, 0, 536870912L, 2048 }
};

long d_4bdfe8[32] = { /* 004bdfe8 128 */
    719364L, 277, 64698L, 520330L, 65535L, 707072L, 8, 506,
    707073L, 11, 762, 707106L, 23, 719361L, 277, 3211264L,
    719392L, 20, 6419456L, 57344L, 61370L, 0, 713088L, 3145728L,
    6419456L, 512, 719393L, 278, 719360L, 267, 786688L, 0
};

long d_4be068[32] = { /* 004be068 128 */
    696352L, 393346L, 265, 698755L, 263, 140, 786698L, 698752L,
    259, 546923L, 786709L, 6419456L, 49152L, 393346L, 276, 394112L,
    275, 514442L, 395424L, 2097186L, 481420L, 3211264L, 327866L, 185,
    713088L, 0, 0, 0, 0, 0, 0, 0
};

struct mem_region regions_4be0e8[19] = { /* 004be0e8 840 */
    { "p", 0, 0x8c300000UL, 0, 65535L, 0, 0x201000UL, 0, 65535L, 0x4000001UL, 1 },
    { "pe", 13, 0xc000000UL, 0, 65535L, 0, 0x1607000UL, 0, 65535L, 0x4000001UL, 1 },
    { "pi", 14, 0x80200000UL, 0, 511, 512, 0x627000UL, 0, 65535L, 0x4000001UL, 1 },
    { "pi", 14, 0x80200000UL, 512, 38911L, 38400L, 0x627008UL, 0, 65535L, 0x4000001UL, 1 },
    { "pr", 15, 0x80100000UL, 0, 31, 32, 0x62f008UL, 4972520L, 65535L, 0x4000001UL, 1 },
    { "pr", 15, 0x80100000UL, 256, 287, 32, 0x62f008UL, 4972648L, 65535L, 0x4000001UL, 1 },
    { "x", 1, 0x43300000UL, 0, 65535L, 0, 0x200000UL, 0, 65535L, 0x4000001UL, 1 },
    { "xe", 18, 0x3000000UL, 0, 65535L, 0, 0x1606000UL, 0, 65535L, 0x4000001UL, 1 },
    { "xi", 19, 0x40200000UL, 0, 2559, 2560, 0x626000UL, 0, 65535L, 0x4000001UL, 1 },
    { "xi", 19, 0x40200000UL, 65472L, 65535L, 0, 0x616000UL, 0, 65535L, 0x4000001UL, 1 },
    { "xr", 20, 0x40100000UL, 2560, 10751, 8192, 0x60e008UL, 0, 65535L, 0x4000001UL, 1 },
    { "y", 2, 0x20f00000UL, 0, 65535L, 0, 0x200000UL, 0, 65535L, 0x4000001UL, 1 },
    { "ye", 23, 0xc00000UL, 0, 65535L, 0, 0x1606000UL, 0, 65535L, 0x4000001UL, 1 },
    { "yi", 24, 0x20200000UL, 0, 2559, 2560, 0x606000UL, 0, 65535L, 0x4000001UL, 1 },
    { "yr", 25, 0x20100000UL, 2560, 10751, 8192, 0x60e008UL, 0, 65535L, 0x4000001UL, 1 },
    { "l", 3, 0x13e00000UL, 0, 65535L, 0, 0x200000UL, 0, 65535L, 0x800002UL, 1 },
    { "le", 9, 0x13c00000UL, 0, 65535L, 0, 0x1602000UL, 0, 65535L, 0x800002UL, 1 },
    { "li", 10, 0x10200000UL, 0, 2559, 0, 0x602000UL, 0, 65535L, 0x800002UL, 1 },
    { "dm", 285, 0x20000UL, 0, 16777215L, 0, 0x1606000UL, 0, 16777215L, 0x4000001UL, 1 }
};
struct flat_4be42c regions_4be0e8_tail = { /* 004be42c tail of regions_4be0e8 */
    0
};

long d_4be430[260] = { /* 004be430 1040 */
    66575L, 66575L, 393728L, 393728L, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 68, 88,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0
};

struct rec5w_202fb d_4be840[8] = { /* 004be840 160 */
    { "ctrl", 0, 25230848L, 0, 0 },
    { "porta", 1, 65535L, 0, 0 },
    { "addr", 1, 65535L, 0, 0 },
    { "abus", 1, 65535L, 0, 0 },
    { "portd", 4, 16777215L, 0, 0 },
    { "dbus", 4, 16777215L, 0, 0 },
    { "data", 4, 16777215L, 0, 0 },
    { "imc", 0, 7, 0, 0 }
};

struct dev_type dev_56030[1] = { /* 004be8e0 1248 */
    { "56030", 709, 2048, 67108872L, 2, 9, (struct periph_desc *)&periph_4bd3e8, 19, (struct mem_region *)&regions_4be0e8, "DSPMEM", (struct core_vtable *)&core_vtable_56000, 29, 7, (void *)&d_4be430, 101, (void *)&d_4bd670, 8, (void *)&d_4be840, { 0 }, 0 }
};

long d_4bedc0[4] = { /* 004bedc0 16 */
    0, 0, 0, 0
};

long d_4bedd0[286] = { /* 004bedd0 1144 */
    15, 15, 15, 19, 15, 19, 19, 19,
    19, 19, 19, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15
};

const char *d_4bf248[286] = { /* 004bf248 1144 */
    "pe, pi or pr depending upon address and omr value.", "xi, xe or xr depending upon address and omr values", "yi, ye or yr depending upon address and omr values", "li or le depending upon address and omr values",
    0, 0, 0, 0,
    0, "external long data memory", "on-chip long data ram", 0,
    0, "external program memory", (const char *)&d_4bf78c, "internal bootstrap rom",
    0, 0, "external x data memory", "on-chip x data ram",
    "on-chip x data rom", 0, 0, "external y data memory",
    "internal y data ram", "internal y data rom", 0, 0,
    "emi peripheral memory - byte wide or nibble wide", "emi 1X32k SRAM EWL=0 (8 bit data) EBW=0 (nibble)", "emi 1X32k SRAM EWL=0 (8 bit data) EBW=1 (byte)", "emi 1X32k SRAM EWL=1 (16 bit data) EBW=0 (nibble)",
    "emi 1X32k SRAM EWL=1 (16 bit data) EBW=1 (byte)", "emi 1X32k SRAM EWL=2 (24 bit data) EBW=0 (nibble)", "emi 1X32k SRAM EWL=2 (24 bit data) EBW=1 (byte)", "emi 1X32k SRAM EWL=3 (16 bit data/24 bit addr) EBW=0 (nibble)",
    "emi 1X32k SRAM (16 bit data/24 bit addr) EBW=1 (byte)", "emi 1X256k SRAM EWL=0 (8 bit data) EBW=0 (nibble)", "emi 1X256k SRAM EWL=0 (8 bit data) EBW=1 (byte)", "emi 1X256k SRAM EWL=1 (16 bit data) EBW=0 (nibble)",
    "emi 1X256k SRAM EWL=1 (16 bit data) EBW=1 (byte)", "emi 1X256k SRAM EWL=2 (24 bit data) EBW=0 (nibble)", "emi 1X256k SRAM EWL=2 (24 bit data) EBW=1 (byte)", "emi 1X256k SRAM EWL=3 (16 bit data/24 bit addr) EBW=0 (nibble)",
    "emi 1X256k SRAM (16 bit data/24 bit addr) EBW=1 (byte)", "emi 2X128k SRAM EWL=0 (8 bit data) EBW=0 (nibble)", "emi 2X128k SRAM EWL=0 (8 bit data) EBW=1 (byte)", "emi 2X128k SRAM EWL=1 (16 bit data) EBW=0 (nibble)",
    "emi 2X128k SRAM EWL=1 (16 bit data) EBW=1 (byte)", "emi 2X128k SRAM EWL=2 (24 bit data) EBW=0 (nibble)", "emi 2X128k SRAM EWL=2 (24 bit data) EBW=1 (byte)", "emi 2X128k SRAM EWL=3 (16 bit data/24 bit addr) EBW=0 (nibble)",
    "emi 2X128k SRAM (16 bit data/24 bit addr) EBW=1 (byte)", "emi 4X32k SRAM EWL=0 (8 bit data) EBW=0 (nibble)", "emi 4X32k SRAM EWL=0 (8 bit data) EBW=1 (byte)", "emi 4X32k SRAM EWL=1 (16 bit data) EBW=0 (nibble)",
    "emi 4X32k SRAM EWL=1 (16 bit data) EBW=1 (byte)", "emi 4X32k SRAM EWL=2 (24 bit data) EBW=0 (nibble)", "emi 4X32k SRAM EWL=2 (24 bit data) EBW=1 (byte)", "emi 4X32k SRAM EWL=3 (16 bit data/24 bit addr) EBW=0 (nibble)",
    "emi 4X32k SRAM (16 bit data/24 bit addr) EBW=1 (byte)", "emi 64k DRAM EWL=0 (8 bit data) EBW=0 (nibble)", "emi 64k DRAM EWL=0 (8 bit data) EBW=1 (byte)", "emi 64k DRAM EWL=1 (16 bit data) EBW=0 (nibble)",
    "emi 64k DRAM EWL=1 (16 bit data) EBW=1 (byte)", "emi 64k DRAM EWL=2 (24 bit data) EBW=0 (nibble)", "emi 64k DRAM EWL=2 (24 bit data) EBW=1 (byte)", "emi 64k DRAM EWL=3 (16 bit data/24 bit addr) EBW=0 (nibble)",
    "emi 64k DRAM (16 bit data/24 bit addr) EBW=1 (byte)", "emi 256k DRAM EWL=0 (8 bit data) EBW=0 (nibble)", "emi 256k DRAM EWL=0 (8 bit data) EBW=1 (byte)", "emi 256k DRAM EWL=1 (16 bit data) EBW=0 (nibble)",
    "emi 256k DRAM EWL=1 (16 bit data) EBW=1 (byte)", "emi 256k DRAM EWL=2 (24 bit data) EBW=0 (nibble)", "emi 256k DRAM EWL=2 (24 bit data) EBW=1 (byte)", "emi 256k DRAM EWL=3 (16 bit data/24 bit addr) EBW=0 (nibble)",
    "emi 256k DRAM (16 bit data/24 bit addr) EBW=1 (byte)", "emi 1M DRAM EWL=0 (8 bit data) EBW=0 (nibble)", "emi 1M DRAM EWL=0 (8 bit data) EBW=1 (byte)", "emi 1M DRAM EWL=1 (16 bit data) EBW=0 (nibble)",
    "emi 1M DRAM EWL=1 (16 bit data) EBW=1 (byte)", "emi 1M DRAM EWL=2 (24 bit data) EBW=0 (nibble)", "emi 1M DRAM EWL=2 (24 bit data) EBW=1 (byte)", "emi 1M DRAM EWL=3 (16 bit data/24 bit addr) EBW=0 (nibble)",
    "emi 1M DRAM (16 bit data/24 bit addr) EBW=1 (byte)", "emi 4M DRAM EWL=0 (8 bit data) EBW=0 (nibble)", "emi 4M DRAM EWL=0 (8 bit data) EBW=1 (byte)", "emi 4M DRAM EWL=1 (16 bit data) EBW=0 (nibble)",
    "emi 4M DRAM EWL=1 (16 bit data) EBW=1 (byte)", "emi 4M DRAM EWL=2 (24 bit data) EBW=0 (nibble)", "emi 4M DRAM EWL=2 (24 bit data) EBW=1 (byte)", "emi 4M DRAM EWL=3 (16 bit data/24 bit addr) EBW=0 (nibble)",
    "emi 4M DRAM (16 bit data/24 bit addr) EBW=1 (byte)", 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, "emi 64k direct DRAM EWL=0 (8 bit data) EBW=0 (nibble)", "emi 64k direct DRAM EWL=0 (8 bit data) EBW=1 (byte)", "emi 64k direct DRAM EWL=1 (16 bit data) EBW=0 (nibble)",
    "emi 64k direct DRAM EWL=1 (16 bit data) EBW=1 (byte)", "emi 64k direct DRAM EWL=2 (24 bit data) EBW=0 (nibble)", "emi 64k direct DRAM EWL=2 (24 bit data) EBW=1 (byte)", "emi 64k direct DRAM EWL=3 (16 bit data/24 bit addr) EBW=0 (nibble)",
    "emi 64k direct DRAM (16 bit data/24 bit addr) EBW=1 (byte)", "emi 256k direct DRAM EWL=0 (8 bit data) EBW=0 (nibble)", "emi 256k direct DRAM EWL=0 (8 bit data) EBW=1 (byte)", "emi 256k direct DRAM EWL=1 (16 bit data) EBW=0 (nibble)",
    "emi 256k direct DRAM EWL=1 (16 bit data) EBW=1 (byte)", "emi 256k direct DRAM EWL=2 (24 bit data) EBW=0 (nibble)", "emi 256k direct DRAM EWL=2 (24 bit data) EBW=1 (byte)", "emi 256k direct DRAM EWL=3 (16 bit data/24 bit addr) EBW=0 (nibble)",
    "emi 256k direct DRAM (16 bit data/24 bit addr) EBW=1 (byte)", "emi 1M direct DRAM EWL=0 (8 bit data) EBW=0 (nibble)", "emi 1M direct DRAM EWL=0 (8 bit data) EBW=1 (byte)", "emi 1M direct DRAM EWL=1 (16 bit data) EBW=0 (nibble)",
    "emi 1M direct DRAM EWL=1 (16 bit data) EBW=1 (byte)", "emi 1M direct DRAM EWL=2 (24 bit data) EBW=0 (nibble)", "emi 1M direct DRAM EWL=2 (24 bit data) EBW=1 (byte)", "emi 1M direct DRAM EWL=3 (16 bit data/24 bit addr) EBW=0 (nibble)",
    "emi 1M direct DRAM (16 bit data/24 bit addr) EBW=1 (byte)", "emi 4M direct DRAM EWL=0 (8 bit data) EBW=0 (nibble)", "emi 4M direct DRAM EWL=0 (8 bit data) EBW=1 (byte)", "emi 4M direct DRAM EWL=1 (16 bit data) EBW=0 (nibble)",
    "emi 4M direct DRAM EWL=1 (16 bit data) EBW=1 (byte)", "emi 4M direct DRAM EWL=2 (24 bit data) EBW=0 (nibble)", "emi 4M direct DRAM EWL=2 (24 bit data) EBW=1 (byte)", "emi 4M direct DRAM EWL=3 (16 bit data/24 bit addr) EBW=0 (nibble)",
    "emi 4M direct DRAM (16 bit data/24 bit addr) EBW=1 (byte)", 0, 0, "emi 1X32k SRAM EWL=1 (12 bit data) EBW=0 (nibble)",
    "emi 1X32k SRAM EWL=1 (12 bit data) EBW=1 (byte)", "emi 1X32k SRAM EWL=2 (20 bit data) EBW=0 (nibble)", "emi 1X32k SRAM EWL=2 (20 bit data) EBW=1 (byte)", 0,
    0, 0, 0, "emi 1X256k SRAM EWL=1 (12 bit data) EBW=0 (nibble)",
    "emi 1X256k SRAM EWL=1 (12 bit data) EBW=1 (byte)", "emi 1X256k SRAM EWL=2 (20 bit data) EBW=0 (nibble)", "emi 1X256k SRAM EWL=2 (20 bit data) EBW=1 (byte)", 0,
    0, 0, 0, "emi 2X128k SRAM EWL=1 (12 bit data) EBW=0 (nibble)",
    "emi 2X128k SRAM EWL=1 (12 bit data) EBW=1 (byte)", "emi 2X128k SRAM EWL=2 (20 bit data) EBW=0 (nibble)", "emi 2X128k SRAM EWL=2 (20 bit data) EBW=1 (byte)", 0,
    0, 0, 0, "emi 4X32k SRAM EWL=1 (12 bit data) EBW=0 (nibble)",
    "emi 4X32k SRAM EWL=1 (12 bit data) EBW=1 (byte)", "emi 4X32k SRAM EWL=2 (20 bit data) EBW=0 (nibble)", "emi 4X32k SRAM EWL=2 (20 bit data) EBW=1 (byte)", 0,
    0, 0, 0, "emi 64k DRAM EWL=1 (12 bit data) EBW=0 (nibble)",
    "emi 64k DRAM EWL=1 (12 bit data) EBW=1 (byte)", "emi 64k DRAM EWL=2 (20 bit data) EBW=0 (nibble)", "emi 64k DRAM EWL=2 (20 bit data) EBW=1 (byte)", 0,
    0, 0, 0, "emi 256k DRAM EWL=1 (12 bit data) EBW=0 (nibble)",
    "emi 256k DRAM EWL=1 (12 bit data) EBW=1 (byte)", "emi 256k DRAM EWL=2 (20 bit data) EBW=0 (nibble)", "emi 256k DRAM EWL=2 (20 bit data) EBW=1 (byte)", 0,
    0, 0, 0, "emi 1M DRAM EWL=1 (12 bit data) EBW=0 (nibble)",
    "emi 1M DRAM EWL=1 (12 bit data) EBW=1 (byte)", "emi 1M DRAM EWL=2 (20 bit data) EBW=0 (nibble)", "emi 1M DRAM EWL=2 (20 bit data) EBW=1 (byte)", 0,
    0, 0, 0, "emi 4M DRAM EWL=1 (12 bit data) EBW=0 (nibble)",
    "emi 4M DRAM EWL=1 (12 bit data) EBW=1 (byte)", "emi 4M DRAM EWL=2 (20 bit data) EBW=0 (nibble)", "emi 4M DRAM EWL=2 (20 bit data) EBW=1 (byte)", 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, "emi 64k DRAM EWL=1 (12 bit data) EBW=0 (nibble)",
    "emi 64k DRAM EWL=1 (12 bit data) EBW=1 (byte)", "emi 64k DRAM EWL=2 (20 bit data) EBW=0 (nibble)", "emi 64k DRAM EWL=2 (20 bit data) EBW=1 (byte)", 0,
    0, 0, 0, "emi 256k DRAM EWL=1 (12 bit data) EBW=0 (nibble)",
    "emi 256k DRAM EWL=1 (12 bit data) EBW=1 (byte)", "emi 256k DRAM EWL=2 (20 bit data) EBW=0 (nibble)", "emi 256k DRAM EWL=2 (20 bit data) EBW=1 (byte)", 0,
    0, 0, 0, "emi 1M DRAM EWL=1 (12 bit data) EBW=0 (nibble)",
    "emi 1M DRAM EWL=1 (12 bit data) EBW=1 (byte)", "emi 1M DRAM EWL=2 (20 bit data) EBW=0 (nibble)", "emi 1M DRAM EWL=2 (20 bit data) EBW=1 (byte)", 0,
    0, 0, 0, "emi 4M DRAM EWL=1 (12 bit data) EBW=0 (nibble)",
    "emi 4M DRAM EWL=1 (12 bit data) EBW=1 (byte)", "emi 4M DRAM EWL=2 (20 bit data) EBW=0 (nibble)", "emi 4M DRAM EWL=2 (20 bit data) EBW=1 (byte)", 0,
    0, "direct access to memory on the 68000 bus"
};

const char *d_4bf6c0[8] = { /* 004bf6c0 32 */
    "H", (const char *)&d_4b9f90, (const char *)&d_4b91c0, (const char *)&d_4b8170,
    (const char *)&d_4b74c0, (const char *)&d_4b74c0, (const char *)&d_4b7088, 0
};

const char *d_4bf6e0[10] = { /* 004bf6e0 40 */
    "B", (const char *)&d_4ba110, (const char *)&d_4b91c0, (const char *)&d_4b8170,
    (const char *)&d_4b74c0, (const char *)&d_4b74c0, (const char *)&d_4b66b0, (const char *)&d_4b66b0,
    (const char *)&d_4b7088, 0
};

struct rec5w_f2933 d_4bf708[2] = { /* 004bf708 40 */
    { (void *)&d_4bedd0, (const char *)&d_4bf248, (void *)&d_4bf6c0, hid_4243f0, hid_424130 },
    { (void *)&d_4ab450, "\t", 0, 0, 0 }
};

struct rec5w_f2933 d_4bf730[2] = { /* 004bf730 40 */
    { (void *)&d_4bedd0, (const char *)&d_4bf248, (void *)&d_4bf6e0, hid_4243f0, hid_424130 },
    { (void *)&d_4ab458, "\t", 0, 0, 0 }
};

void *keyed_dev_aux[2] = { /* 004bf758 8 */
    (void *)&d_4bf708, (void *)&d_4bf730
};

struct rec4w_c7ccd keyed_dev_table[2] = { /* 004bf760 32 */
    { (void *)&dev_68356, 538976288L, 538976288L, 0 },
    { (void *)&dev_56030, 538976288L, 538976288L, 0 }
};

long keygen_mod = 100000000L; /* 004bf780 4 */

long keygen_base = 10000; /* 004bf784 4 */

long keygen_mult = 31415821L; /* 004bf788 4 */

long d_4bf78c[6] = { /* 004bf78c 24 */
    1702129257L, 1818324594L, 1869770784L, 1835102823L, 1835363616L, 7959151L
};
