/* simd_dec.c - GENERATED by re/scripts/gentab_sim.py from SIM56000.EXE; do not edit. */
#include "simdata.h"

extern void alu_add56();
extern void alu_h_432160();
extern void alu_h_4325f0();
extern void alu_h_432a70();
extern void alu_mac();
extern void alu_mpy();
extern void alu_op_h430880();
extern void alu_op_h430a90();
extern void alu_op_h430cd0();
extern void alu_op_h430e80();
extern void alu_op_h430fc0();
extern void alu_op_h431090();
extern void alu_op_h431170();
extern void alu_op_h431270();
extern void alu_op_h431290();
extern void alu_op_h4312b0();
extern void alu_op_h431300();
extern void alu_op_h4314a0();
extern void alu_op_h431700();
extern void alu_op_h4318a0();
extern void alu_op_h4318e0();
extern void alu_op_h431920();
extern void alu_op_h4319f0();
extern void alu_op_h431ac0();
extern void alu_op_h431b80();
extern void alu_op_h431b90();
extern void alu_op_h431c70();
extern void alu_op_h431d40();
extern void alu_op_h431e10();
extern void alu_op_h431ef0();
extern void alu_op_h431fe0();
extern void alu_op_h432120();
extern void alu_op_h432140();
extern void alu_op_h432290();
extern void alu_op_h432410();
extern void alu_op_h432590();
extern void alu_op_h4335a0();
extern void alu_op_h433650();
extern void alu_shift1();
extern void dec_alu_cc();
extern void dec_alu_imm_long();
extern void dec_alu_imm_short();
extern void dec_c0_enddo();
extern void dec_c100_reset();
extern void dec_c101_rts();
extern void dec_c104_trap();
extern void dec_c105_illegal();
extern void dec_c106_rti();
extern void dec_c107_nop();
extern void dec_c10_doforever();
extern void dec_c11_pm();
extern void dec_c15_pm();
extern void dec_c19_pm();
extern void dec_c1_enddo();
extern void dec_c20_enddo();
extern void dec_c21_pm();
extern void dec_c22_pm();
extern void dec_c26_pm();
extern void dec_c28_btst();
extern void dec_c29_bchg();
extern void dec_c2_doforever();
extern void dec_c30_jsset();
extern void dec_c31_jsclr();
extern void dec_c32_jsset();
extern void dec_c33_jsclr();
extern void dec_c34_btst();
extern void dec_c35_bchg();
extern void dec_c36_jsset();
extern void dec_c37_jsclr();
extern void dec_c38_btst();
extern void dec_c39_bchg();
extern void dec_c40_jsset();
extern void dec_c41_jsclr();
extern void dec_c42_btst();
extern void dec_c43_bchg();
extern void dec_c46_bset();
extern void dec_c47_bclr();
extern void dec_c48_jset();
extern void dec_c49_jclr();
extern void dec_c50_jset();
extern void dec_c51_jclr();
extern void dec_c52_bset();
extern void dec_c53_bclr();
extern void dec_c54_jset();
extern void dec_c55_jclr();
extern void dec_c56_bset();
extern void dec_c57_bclr();
extern void dec_c58_jset();
extern void dec_c59_jclr();
extern void dec_c60_bset();
extern void dec_c61_bclr();
extern void dec_c62_pm();
extern void dec_c63_pm();
extern void dec_c65_pm();
extern void dec_c66_pm();
extern void dec_c67_pm();
extern void dec_c69_enddo();
extern void dec_c70_doforever();
extern void dec_c71_rep();
extern void dec_c73_rep();
extern void dec_c75_rep();
extern void dec_c77_rep();
extern void dec_c79_enddo();
extern void dec_c81_pm();
extern void dec_c83_doforever();
extern void dec_c85_enddo();
extern void dec_c87_lua();
extern void dec_c91_norm();
extern void dec_c93_debug();
extern void dec_c95_ori();
extern void dec_c96_andi();
extern void dec_c97_enddo();
extern void dec_c98_stop();
extern void dec_c99_wait();
extern void dec_c9_enddo();
extern void dec_clb();
extern void dec_cmpu();
extern void dec_div();
extern void dec_do_aa();
extern void dec_do_ea();
extern void dec_do_imm();
extern void dec_do_reg();
extern void dec_extract_imm();
extern void dec_extract_reg();
extern void dec_h41d8d0();
extern void dec_h41d8f0();
extern void dec_h41d950();
extern void dec_h41d970();
extern void dec_h41da80();
extern void dec_h41daa0();
extern void dec_h41dac0();
extern void dec_h41dae0();
extern void dec_h41dc00();
extern void dec_h41dc20();
extern void dec_h41dc40();
extern void dec_h41dc60();
extern void dec_h41dd90();
extern void dec_h41ddb0();
extern void dec_h41ddd0();
extern void dec_h41ddf0();
extern void dec_h41de10();
extern void dec_h41de30();
extern void dec_h41de50();
extern void dec_h41de70();
extern void dec_h41de90();
extern void dec_h41deb0();
extern void dec_h41ded0();
extern void dec_h41def0();
extern void dec_h41e150();
extern void dec_h41e1f0();
extern void dec_h41e2f0();
extern void dec_h41e340();
extern void dec_h41e390();
extern void dec_h41e3f0();
extern void dec_h41f400();
extern void dec_h41f420();
extern void dec_h41f440();
extern void dec_h41f460();
extern void dec_h41f480();
extern void dec_h41f4f0();
extern void dec_h41f540();
extern void dec_h41f580();
extern void dec_h41f5e0();
extern void dec_h41f620();
extern void dec_h41f650();
extern void dec_h41f700();
extern void dec_h41f7b0();
extern void dec_h41f7f0();
extern void dec_h41f890();
extern void dec_h41f8b0();
extern void dec_h41f8d0();
extern void dec_h41f8f0();
extern void dec_h41f910();
extern void dec_h41f940();
extern void dec_incdec();
extern void dec_insert_imm();
extern void dec_insert_reg();
extern void dec_lsl_lsr_imm();
extern void dec_lsl_lsr_reg();
extern void dec_mac_su();
extern void dec_mpy_reg();
extern void dec_mpyi();
extern void dec_normf_merge();
extern void dec_pm_update();
extern void dec_shift_imm();
extern void dec_shift_reg();
extern void dec_tcc();
extern void dis_fmt_c0();
extern void dis_fmt_c1();
extern void dis_fmt_c10();
extern void dis_fmt_c100();
extern void dis_fmt_c101();
extern void dis_fmt_c102();
extern void dis_fmt_c104();
extern void dis_fmt_c105();
extern void dis_fmt_c106();
extern void dis_fmt_c107();
extern void dis_fmt_c109();
extern void dis_fmt_c11();
extern void dis_fmt_c12();
extern void dis_fmt_c13();
extern void dis_fmt_c14();
extern void dis_fmt_c15();
extern void dis_fmt_c18();
extern void dis_fmt_c19();
extern void dis_fmt_c2();
extern void dis_fmt_c20();
extern void dis_fmt_c21();
extern void dis_fmt_c22();
extern void dis_fmt_c23();
extern void dis_fmt_c24();
extern void dis_fmt_c25();
extern void dis_fmt_c26();
extern void dis_fmt_c27();
extern void dis_fmt_c28();
extern void dis_fmt_c29();
extern void dis_fmt_c3();
extern void dis_fmt_c30();
extern void dis_fmt_c31();
extern void dis_fmt_c32();
extern void dis_fmt_c33();
extern void dis_fmt_c34();
extern void dis_fmt_c35();
extern void dis_fmt_c36();
extern void dis_fmt_c37();
extern void dis_fmt_c38();
extern void dis_fmt_c39();
extern void dis_fmt_c4();
extern void dis_fmt_c40();
extern void dis_fmt_c41();
extern void dis_fmt_c42();
extern void dis_fmt_c43();
extern void dis_fmt_c44();
extern void dis_fmt_c45();
extern void dis_fmt_c46();
extern void dis_fmt_c47();
extern void dis_fmt_c48();
extern void dis_fmt_c49();
extern void dis_fmt_c5();
extern void dis_fmt_c50();
extern void dis_fmt_c51();
extern void dis_fmt_c52();
extern void dis_fmt_c53();
extern void dis_fmt_c54();
extern void dis_fmt_c55();
extern void dis_fmt_c56();
extern void dis_fmt_c57();
extern void dis_fmt_c58();
extern void dis_fmt_c59();
extern void dis_fmt_c6();
extern void dis_fmt_c60();
extern void dis_fmt_c61();
extern void dis_fmt_c62();
extern void dis_fmt_c63();
extern void dis_fmt_c64();
extern void dis_fmt_c65();
extern void dis_fmt_c66();
extern void dis_fmt_c67();
extern void dis_fmt_c68();
extern void dis_fmt_c69();
extern void dis_fmt_c7();
extern void dis_fmt_c70();
extern void dis_fmt_c71();
extern void dis_fmt_c72();
extern void dis_fmt_c73();
extern void dis_fmt_c74();
extern void dis_fmt_c75();
extern void dis_fmt_c76();
extern void dis_fmt_c77();
extern void dis_fmt_c78();
extern void dis_fmt_c79();
extern void dis_fmt_c8();
extern void dis_fmt_c80();
extern void dis_fmt_c81();
extern void dis_fmt_c82();
extern void dis_fmt_c83();
extern void dis_fmt_c84();
extern void dis_fmt_c85();
extern void dis_fmt_c86();
extern void dis_fmt_c87();
extern void dis_fmt_c88();
extern void dis_fmt_c89();
extern void dis_fmt_c9();
extern void dis_fmt_c90();
extern void dis_fmt_c91();
extern void dis_fmt_c92();
extern void dis_fmt_c93();
extern void dis_fmt_c95();
extern void dis_fmt_c96();
extern void dis_fmt_c97();
extern void dis_fmt_c98();
extern void dis_fmt_c99();
extern void dis_fmt_h41fb60();
extern void gpio_m_clock();
extern void insn_class_h42f4a0();
extern void insn_class_h42f4b0();
extern void insn_class_h42f4d0();
extern void insn_class_h42f530();
extern void insn_class_h42f570();
extern void insn_class_h42f5c0();
extern void insn_class_h42f5e0();
extern void insn_class_h42f5f0();
extern void insn_class_h42f640();
extern void insn_class_h42f690();
extern void insn_class_h42f6c0();
extern void insn_class_h42f710();
extern void insn_class_h42f770();
extern void insn_class_h42f7a0();
extern void insn_class_h42f850();
extern void insn_class_h42f8b0();
extern void insn_class_h42fba0();
extern void insn_class_h42fbe0();
extern void insn_class_h42fc30();
extern void insn_class_h42fc50();
extern void insn_class_h42fcb0();
extern void insn_class_h42fcd0();
extern void insn_class_h42fd20();
extern void insn_class_h42fd70();
extern void insn_class_h_42fa60();
extern void insn_exec_h42e5c0();
extern void insn_exec_h42e5d0();
extern void insn_exec_h42e600();
extern void insn_exec_h42e670();
extern void insn_exec_h42e6e0();
extern void insn_exec_h42e750();
extern void insn_exec_h42e780();
extern void insn_exec_h42e7b0();
extern void insn_exec_h42e7e0();
extern void insn_exec_h42e7f0();
extern void insn_exec_h42e810();
extern void insn_exec_h42e820();
extern void insn_exec_h42e830();
extern void insn_exec_h42e890();
extern void insn_exec_h42e8f0();
extern void insn_exec_h42e910();
extern void insn_exec_h42e950();
extern void insn_exec_h42e980();
extern void insn_exec_h42e9e0();
extern void insn_exec_h42eaf0();
extern void insn_exec_h42eb90();
extern void insn_exec_h42ec20();
extern void insn_exec_h42ec90();
extern void insn_exec_h42ecc0();
extern void insn_exec_h42ecd0();
extern void insn_exec_h42ece0();
extern void insn_exec_h42ed20();
extern void insn_exec_h42ed40();
extern void insn_exec_h42eda0();
extern void insn_exec_h42edc0();
extern void insn_exec_h42ede0();
extern void insn_exec_h42ee10();
extern void insn_exec_h42ee20();
extern void insn_exec_h42ee40();
extern void insn_exec_h42ee80();
extern void insn_exec_h42ee90();
extern void insn_exec_h42f220();
extern void insn_move_h42ef30();
extern void insn_move_h42ef40();
extern void insn_move_h42ef50();
extern void insn_move_h42ef80();
extern void insn_move_h42ef90();
extern void insn_move_h42efa0();
extern void insn_move_h42efd0();
extern void insn_move_h42f000();
extern void insn_move_h42f010();
extern void insn_move_h42f040();
extern void insn_move_h42f070();
extern void insn_move_h42f0c0();
extern void insn_move_h42f0f0();
extern void insn_move_h42f120();
extern void insn_move_h42f130();
extern void insn_move_h42f140();
extern void insn_move_h42f170();
extern void insn_move_h42f180();
extern void insn_move_h42f1b0();
extern void insn_move_h42f1c0();
extern void insn_move_h42f1f0();
extern void insn_move_h42f200();
extern void insn_move_h42f210();
extern void insn_move_h42f230();
extern void insn_move_h42f240();
extern void insn_move_h42f250();
extern void insn_move_h42f260();
extern void insn_move_h42f270();
extern void insn_move_h42f290();
extern void insn_valid_h42fe50();
extern void insn_valid_h42fe60();
extern void insn_valid_h42ffb0();
extern void insn_valid_h42ffc0();
extern void insn_valid_h4300a0();
extern void insn_valid_h430160();
extern void insn_valid_h430210();
extern void insn_valid_h430410();
extern void insn_valid_h430430();
extern void insn_valid_h430450();
extern void insn_valid_h430480();
extern void insn_valid_h4304b0();
extern void insn_valid_h4304e0();
extern void insn_valid_h430510();
extern void insn_valid_h430550();
extern void insn_valid_h430580();
extern void insn_valid_h4305a0();
extern void insn_valid_h4305e0();
extern void insn_valid_h430630();
extern void insn_valid_h430650();
extern void insn_valid_h4306e0();
extern void insn_valid_h430720();
extern void insn_valid_pm_a();
extern void insn_valid_pm_c();
extern void insn_valid_pm_d();
extern void insn_valid_pm_e();
extern void insn_valid_pm_f();
extern void mem_reg_read();
extern void mem_reg_write();
extern void mem_region_of();
extern void mem_write_n();
extern void omr_remap_56009();
extern void omr_remap_56011();
extern void omr_remap_56012();
extern void reg_read_check();
extern void reg_write_check();

long d_4bf850 = -1; /* 004bf850 4 */

long d_4bf854 = -1; /* 004bf854 4 */

long d_4bf858 = -1; /* 004bf858 4 */

long d_4bf85c = -1; /* 004bf85c 4 */

const char *mnemonic_names[103] = { /* 004bf860 412 */
    "none", "andi", "bchg", "bclr",
    "brkcc", "bset", "btst", "debug",
    "do", "doforever", "dor", "dorforever",
    "enddo", "if", "ifu", "illegal",
    "jmp", "jclr", "jsclr", "jset",
    "jsr", "jsset", "lra", "lua",
    "vsl", "nop", "norm", "ori",
    "pflush", "pflushun", "pfree", "plock",
    "plockr", "punlock", "punlockr", "rep",
    "reset", "rti", "rts", "stop",
    "tcc", "wait", "trap", "bra",
    "bsr", "brclr", "bsclr", "brset",
    "bsset", "abs", "adc", "add",
    "addl", "addr", "and", "asl",
    "asr", "clb", "clr", "cmp",
    "cmpm", "cmpu", "dec", "div",
    "dmac", "eor", "extract", "extractu",
    "inc", "insert", "lsl", "lsr",
    "mac", "maci", "macr", "macri",
    "max", "merge", "mpy", "mpyi",
    "mpyr", "mpyri", "neg", "normf",
    "not", "or", "rnd", "rol",
    "ror", "sbc", "sub", "subl",
    "subr", "tfr", "tst", "ERROR",
    "jcc", "jscc", "bcc", "bscc",
    "movec", "movem", "movep"
};

long dec_cpu_level[2] = { /* 004bfc78 8 */
    1, 0
};

long d_4bfc80[64] = { /* 004bfc80 256 */
    0, 0, 0, 0, 49, 50, 52, 53,
    2, 6, 4, 8, 3, 7, 1, 5,
    33, 34, 35, 36, 37, 38, 39, 40,
    23, 24, 25, 26, 27, 28, 29, 30,
    15, 16, 17, 18, 19, 20, 21, 22,
    0, 0, 10, 0, 0, 0, 0, 0,
    47, 41, 0, 0, 0, 0, 0, 0,
    46, 43, 31, 42, 44, 45, 13, 14
};

long d_4bfd80[128] = { /* 004bfd80 512 */
    0, 5, 5, 0, 0, 5, 5, 5,
    0, 1, 1, 0, 0, 1, 1, 1,
    5, 0, 5, 0, 5, 5, 5, 0,
    1, 0, 1, 0, 1, 1, 1, 0,
    48, 48, 0, 0, 48, 48, 0, 0,
    48, 48, 0, 0, 48, 48, 0, 0,
    51, 51, 0, 0, 51, 51, 0, 0,
    51, 51, 0, 0, 51, 51, 0, 0,
    49, 49, 49, 49, 49, 49, 49, 49,
    49, 49, 49, 49, 49, 49, 49, 49,
    52, 52, 52, 52, 52, 52, 52, 52,
    52, 52, 52, 52, 52, 52, 52, 52,
    50, 50, 50, 50, 50, 50, 50, 50,
    50, 50, 50, 50, 50, 50, 50, 50,
    53, 53, 53, 53, 53, 53, 53, 53,
    53, 53, 53, 53, 53, 53, 53, 53
};

long d_4bff80[8] = { /* 004bff80 32 */
    3, 7, 50, 53, 89, 90, 1, 5
};

long d_4bffa0[8] = { /* 004bffa0 32 */
    2, 6, 49, 52, 91, 92, 5, 1
};

long d_4bffc0[8] = { /* 004bffc0 32 */
    1, 0, 0, 0, 49, 52, 50, 53
};

long d_4bffe0[4] = { /* 004bffe0 16 */
    53, 49, 52, 50
};

long d_4bfff0[4] = { /* 004bfff0 16 */
    49, 52, 50, 53
};

long d_4c0000[2] = { /* 004c0000 8 */
    1, 5
};

long d_4c0008[4] = { /* 004c0008 16 */
    49, 52, 50, 53
};

long d_4c0018[4] = { /* 004c0018 16 */
    81, 80, 93, 94
};

long d_4c0028[8] = { /* 004c0028 32 */
    0, 0, 3, 7, 49, 52, 50, 53
};

long d_4c0048[8] = { /* 004c0048 32 */
    0, 0, 2, 6, 49, 52, 50, 53
};

long d_4c0068 = 1; /* 004c0068 4 */

long d_4c006c[7] = { /* 004c006c 28 */
    0, 0, 0, 49, 52, 50, 53
};

long d_4c0088[4] = { /* 004c0088 16 */
    0, 0, 8, 12
};

long d_4c0098[16] = { /* 004c0098 64 */
    49, 52, 50, 53, 49, 52, 50, 53,
    50, 53, 49, 52, 53, 49, 52, 50
};

long d_4c00d8[16] = { /* 004c00d8 64 */
    49, 52, 49, 52, 53, 49, 52, 50,
    50, 53, 50, 53, 49, 52, 50, 53
};

long d_4c0118[8] = { /* 004c0118 32 */
    51, 0, 85, 65, 90, 59, 54, 0
};

long d_4c0138[4] = { /* 004c0138 16 */
    79, 81, 73, 75
};

long d_4c0148[4] = { /* 004c0148 16 */
    78, 80, 72, 74
};

long d_4c0158[70] = { /* 004c0158 280 */
    0, 93, 53, 94, 0, 59, 92, 60,
    51, 86, 52, 58, 90, 76, 91, 84,
    51, 50, 56, 71, 90, 89, 49, 88,
    51, 50, 55, 70, 90, 89, 82, 87,
    51, 93, 85, 65, 90, 59, 54, 60,
    51, 93, 85, 65, 90, 59, 54, 60,
    51, 93, 85, 65, 90, 59, 54, 60,
    51, 93, 85, 65, 90, 59, 54, 60,
    0, 38, 78, 80, 72, 74
};

long d_4c0270[4] = { /* 004c0270 16 */
    49, 50, 1, 5
};

long d_4c0280[4] = { /* 004c0280 16 */
    52, 53, 1, 5
};

long d_4c0290[4] = { /* 004c0290 16 */
    52, 53, 1, 5
};

long d_4c02a0[4] = { /* 004c02a0 16 */
    49, 50, 1, 5
};

simfn dec_handlers[206] = { /* 004c02b0 824 */
    dec_c0_enddo, dec_c1_enddo, dec_c2_doforever, dec_c1_enddo,
    dec_c2_doforever, dec_c1_enddo, dec_c2_doforever, dec_c1_enddo,
    dec_c2_doforever, dec_c9_enddo, dec_c10_doforever, dec_c11_pm,
    dec_c11_pm, dec_c11_pm, dec_c11_pm, dec_c15_pm,
    dec_c15_pm, dec_c15_pm, dec_pm_update, dec_c19_pm,
    dec_c20_enddo, dec_c21_pm, dec_c22_pm, dec_c22_pm,
    dec_c22_pm, dec_c22_pm, dec_c26_pm, dec_c26_pm,
    dec_c28_btst, dec_c29_bchg, dec_c30_jsset, dec_c31_jsclr,
    dec_c32_jsset, dec_c33_jsclr, dec_c34_btst, dec_c35_bchg,
    dec_c36_jsset, dec_c37_jsclr, dec_c38_btst, dec_c39_bchg,
    dec_c40_jsset, dec_c41_jsclr, dec_c42_btst, dec_c43_bchg,
    dec_c26_pm, dec_c26_pm, dec_c46_bset, dec_c47_bclr,
    dec_c48_jset, dec_c49_jclr, dec_c50_jset, dec_c51_jclr,
    dec_c52_bset, dec_c53_bclr, dec_c54_jset, dec_c55_jclr,
    dec_c56_bset, dec_c57_bclr, dec_c58_jset, dec_c59_jclr,
    dec_c60_bset, dec_c61_bclr, dec_c62_pm, dec_c63_pm,
    dec_c62_pm, dec_c65_pm, dec_c66_pm, dec_c67_pm,
    dec_c63_pm, dec_c69_enddo, dec_c70_doforever, dec_c71_rep,
    dec_do_reg, dec_c73_rep, dec_do_ea, dec_c75_rep,
    dec_do_imm, dec_c77_rep, dec_do_aa, dec_c79_enddo,
    dec_c79_enddo, dec_c81_pm, dec_c81_pm, dec_c83_doforever,
    dec_c83_doforever, dec_c85_enddo, dec_c85_enddo, dec_c87_lua,
    dec_c87_lua, dec_tcc, dec_tcc, dec_c91_norm,
    dec_div, dec_c93_debug, dec_c93_debug, dec_c95_ori,
    dec_c96_andi, dec_c97_enddo, dec_c98_stop, dec_c99_wait,
    dec_c100_reset, dec_c101_rts, dec_incdec, dec_incdec,
    dec_c104_trap, dec_c105_illegal, dec_c106_rti, dec_c107_nop,
    gpio_m_clock, dec_mpy_reg, dec_h41de90, dec_h41deb0,
    dec_h41dd90, dec_h41ddb0, dec_h41d8d0, dec_h41d8f0,
    dec_h41d950, dec_h41d970, dec_h41dc40, dec_h41dc60,
    dec_h41dc00, dec_h41dc20, dec_h41da80, dec_h41daa0,
    dec_h41dac0, dec_h41dae0, dec_h41e2f0, dec_h41e2f0,
    dec_h41e2f0, dec_h41e2f0, dec_h41e340, dec_h41e340,
    dec_h41e340, dec_h41e340, dec_h41e390, dec_h41e390,
    dec_h41e390, dec_h41e390, dec_h41f400, dec_h41f420,
    dec_h41f440, dec_h41f460, dec_h41f480, dec_h41f480,
    dec_h41f4f0, dec_h41f540, dec_h41f580, dec_h41f580,
    dec_h41f5e0, dec_h41f5e0, dec_h41f620, dec_h41f650,
    dec_h41f700, dec_h41f7b0, dec_h41f7b0, dec_mpyi,
    dec_h41f7f0, dec_alu_cc, dec_shift_imm, dec_shift_reg,
    dec_extract_imm, dec_lsl_lsr_imm, dec_extract_reg, dec_insert_imm,
    dec_insert_reg, gpio_m_clock, dec_normf_merge, dec_clb,
    dec_normf_merge, dec_lsl_lsr_reg, dec_alu_imm_short, dec_alu_imm_long,
    dec_c85_enddo, dec_mac_su, dec_mac_su, dec_mac_su,
    dec_h41e150, dec_h41e150, dec_h41e3f0, dec_h41e3f0,
    dec_h41e1f0, dec_h41de50, dec_h41de70, dec_h41ddd0,
    dec_h41ddf0, dec_h41f890, dec_h41f8b0, dec_h41f8d0,
    dec_h41f8f0, dec_h41ded0, dec_h41def0, dec_h41de10,
    dec_h41de30, dec_c85_enddo, dec_c79_enddo, dec_c79_enddo,
    dec_c81_pm, dec_c81_pm, dec_c83_doforever, dec_c83_doforever,
    dec_h41f620, dec_h41f910, dec_h41f910, dec_cmpu,
    dec_h41f580, dec_h41f940
};

const char *hex_digits[2] = { /* 004c05e8 8 */
    "0123456789abcdef", 0
};

struct rec10w_68cf8 dis_token_strings[25] = { /* 004c05f0 1024 */
    { (const char *)&empty_str, "abs", "adc", "add", "addl", "addr", "and", "and", "asl", "asr" },
    { "bchg", "bclr", "bset", "btst", "clr", "cmp", "cmpm", "div", "do", "enddo" },
    { "eor", "j", "jclr", "jmp", "js", "jsclr", "jset", "jsr", "jsset", "lsl" },
    { "lsr", "lua", "mac", "macr", "move", "move", "movep", "mpy", "mpyr", "neg" },
    { "nop", "norm", "not", "or", "or", "rep", "reset", "rnd", "rol", "ror" },
    { "rti", "rts", "sbc", "start", "stop", "sub", "subl", "subr", "swi", "t" },
    { "tfr", "tst", "wait", "U", "illegal", "inc", "dec", "debug", "asrr", "sra" },
    { "srar", "cc", "ge", "ne", "pl", "nn", "ec", "lc", "gt", "cs" },
    { "lt", "eq", "mi", "nr", "es", "ls", "le", (const char *)&empty_str, "x0", "x1" },
    { "y0", "y1", "a0", "b0", "a2", "b2", "a1", "b1", "a", "b" },
    { "r0", "r1", "r2", "r3", "r4", "r5", "r6", "r7", "n0", "n1" },
    { "n2", "n3", "n4", "n5", "n6", "n7", "m0", "m1", "m2", "m3" },
    { "m4", "m5", "m6", "m7", "U", "sr", "omr", "sp", "ssh", "ssl" },
    { "la", "lc", "a10", "b10", "x", "y", "a", "b", "ab", "ba" },
    { "U", "-x0", "-x1", "-y0", "-y1", "x0", "x1", "a", "b", "y0" },
    { "y1", "a", "b", ",", " ", "\t", "mr", "ccr", "omr", "U" },
    { "b", "b", "x", "y", "x0", "y0", "x1", "y1", "a", "a" },
    { "x", "y", "x0", "y0", "x1", "y1", "(r0)-n0", "(r1)-n1", "(r2)-n2", "(r3)-n3" },
    { "(r4)-n4", "(r5)-n5", "(r6)-n6", "(r7)-n7", "(r0)+n0", "(r1)+n1", "(r2)+n2", "(r3)+n3", "(r4)+n4", "(r5)+n5" },
    { "(r6)+n6", "(r7)+n7", "(r0)-", "(r1)-", "(r2)-", "(r3)-", "(r4)-", "(r5)-", "(r6)-", "(r7)-" },
    { "(r0)+", "(r1)+", "(r2)+", "(r3)+", "(r4)+", "(r5)+", "(r6)+", "(r7)+", "(r0)", "(r1)" },
    { "(r2)", "(r3)", "(r4)", "(r5)", "(r6)", "(r7)", "(r0+n0)", "(r1+n1)", "(r2+n2)", "(r3+n3)" },
    { "(r4+n4)", "(r5+n5)", "(r6+n6)", "(r7+n7)", ">", "U", "U", "U", "#>", "U" },
    { "U", "U", "-(r0)", "-(r1)", "-(r2)", "-(r3)", "-(r4)", "-(r5)", "-(r6)", "-(r7)" },
    { "<", "<<", "#", "#<", "#>", ">", "x:", "y:", "l:", "p:" }
};
struct flat_4c09d8 dis_token_strings_tail = { /* 004c09d8 tail of dis_token_strings */
    34, 60, 5, 61,
    50, 15
};

long d_4c09f0[60] = { /* 004c09f0 240 */
    57, 16, 3, 47, 4, 14, 55, 63,
    56, 42, 3, 2, 9, 30, 55, 52,
    1, 49, 3, 2, 8, 29, 55, 52,
    39, 48, 3, 60, 43, 20, 55, 15,
    6, 16, 3, 60, 43, 20, 55, 15,
    6, 16, 3, 60, 43, 20, 55, 15,
    6, 16, 3, 60, 43, 20, 55, 15,
    6, 16, 63, 51
};

long d_4c0ae0[4] = { /* 004c0ae0 16 */
    37, 38, 32, 33
};

long d_4c0af0[128] = { /* 004c0af0 512 */
    0, 12, 12, 0, 0, 12, 12, 12,
    0, 11, 11, 0, 0, 11, 11, 11,
    12, 0, 12, 0, 12, 0, 12, 0,
    11, 0, 11, 0, 11, 0, 11, 0,
    47, 47, 0, 0, 47, 47, 0, 0,
    47, 47, 0, 0, 47, 47, 0, 0,
    48, 48, 0, 0, 48, 48, 0, 0,
    48, 48, 0, 0, 48, 48, 0, 0,
    1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1,
    3, 3, 3, 3, 3, 3, 3, 3,
    3, 3, 3, 3, 3, 3, 3, 3,
    2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2,
    4, 4, 4, 4, 4, 4, 4, 4,
    4, 4, 4, 4, 4, 4, 4, 4
};

long d_4c0cf0[128] = { /* 004c0cf0 512 */
    0, 1, 1, 0, 0, 0, 1, 0,
    0, 1, 1, 0, 0, 0, 1, 0,
    1, 1, 1, 1, 1, 0, 1, 1,
    1, 1, 1, 1, 1, 0, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 0, 1, 0,
    1, 1, 1, 1, 1, 0, 1, 0,
    1, 1, 1, 1, 1, 0, 1, 0,
    1, 1, 1, 1, 1, 0, 1, 0,
    1, 1, 1, 1, 1, 0, 1, 0,
    1, 1, 1, 1, 1, 0, 1, 0,
    1, 1, 1, 1, 1, 0, 1, 0,
    1, 1, 1, 1, 1, 0, 1, 0
};

long d_4c0ef0[128] = { /* 004c0ef0 512 */
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 1,
    0, 0, 0, 0, 0, 0, 0, 1,
    0, 0, 0, 1, 0, 0, 0, 1,
    0, 0, 0, 1, 0, 0, 0, 1,
    0, 0, 0, 1, 0, 0, 0, 1,
    0, 0, 0, 1, 0, 0, 0, 1,
    0, 0, 1, 1, 0, 0, 1, 0,
    0, 0, 1, 1, 0, 0, 1, 0,
    0, 0, 1, 1, 0, 0, 1, 0,
    0, 0, 1, 1, 0, 0, 1, 0,
    0, 0, 1, 1, 0, 0, 1, 0,
    0, 0, 1, 1, 0, 0, 1, 0,
    0, 0, 1, 1, 0, 0, 1, 0,
    0, 0, 1, 1, 0, 0, 1, 0
};

long d_4c10f0[70] = { /* 004c10f0 280 */
    0, 1, 1, 1, 0, 1, 1, 1,
    1, 1, 1, 1, 1, 0, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1,
    0, 0, 1, 1, 1, 1
};

long d_4c1208[16] = { /* 004c1208 64 */
    1, 3, 2, 4, 1, 3, 2, 4,
    54, 56, 55, 57, 54, 56, 55, 57
};

long d_4c1248[8] = { /* 004c1248 32 */
    1, 3, 1, 3, 4, 1, 3, 2
};

long d_4c1268[4] = { /* 004c1268 16 */
    37, 38, 32, 33
};

long d_4c1278[4] = { /* 004c1278 16 */
    4, 1, 3, 2
};

long d_4c1288[4] = { /* 004c1288 16 */
    57, 54, 56, 55
};

simfn dis_fmt_handlers[110] = { /* 004c1298 440 */
    dis_fmt_c0, dis_fmt_c1, dis_fmt_c2, dis_fmt_c3,
    dis_fmt_c4, dis_fmt_c5, dis_fmt_c6, dis_fmt_c7,
    dis_fmt_c8, dis_fmt_c9, dis_fmt_c10, dis_fmt_c11,
    dis_fmt_c12, dis_fmt_c13, dis_fmt_c14, dis_fmt_c15,
    dis_fmt_c15, dis_fmt_c15, dis_fmt_c18, dis_fmt_c19,
    dis_fmt_c20, dis_fmt_c21, dis_fmt_c22, dis_fmt_c23,
    dis_fmt_c24, dis_fmt_c25, dis_fmt_c26, dis_fmt_c27,
    dis_fmt_c28, dis_fmt_c29, dis_fmt_c30, dis_fmt_c31,
    dis_fmt_c32, dis_fmt_c33, dis_fmt_c34, dis_fmt_c35,
    dis_fmt_c36, dis_fmt_c37, dis_fmt_c38, dis_fmt_c39,
    dis_fmt_c40, dis_fmt_c41, dis_fmt_c42, dis_fmt_c43,
    dis_fmt_c44, dis_fmt_c45, dis_fmt_c46, dis_fmt_c47,
    dis_fmt_c48, dis_fmt_c49, dis_fmt_c50, dis_fmt_c51,
    dis_fmt_c52, dis_fmt_c53, dis_fmt_c54, dis_fmt_c55,
    dis_fmt_c56, dis_fmt_c57, dis_fmt_c58, dis_fmt_c59,
    dis_fmt_c60, dis_fmt_c61, dis_fmt_c62, dis_fmt_c63,
    dis_fmt_c64, dis_fmt_c65, dis_fmt_c66, dis_fmt_c67,
    dis_fmt_c68, dis_fmt_c69, dis_fmt_c70, dis_fmt_c71,
    dis_fmt_c72, dis_fmt_c73, dis_fmt_c74, dis_fmt_c75,
    dis_fmt_c76, dis_fmt_c77, dis_fmt_c78, dis_fmt_c79,
    dis_fmt_c80, dis_fmt_c81, dis_fmt_c82, dis_fmt_c83,
    dis_fmt_c84, dis_fmt_c85, dis_fmt_c86, dis_fmt_c87,
    dis_fmt_c88, dis_fmt_c89, dis_fmt_c90, dis_fmt_c91,
    dis_fmt_c92, dis_fmt_c93, dis_fmt_c93, dis_fmt_c95,
    dis_fmt_c96, dis_fmt_c97, dis_fmt_c98, dis_fmt_c99,
    dis_fmt_c100, dis_fmt_c101, dis_fmt_c102, dis_fmt_c102,
    dis_fmt_c104, dis_fmt_c105, dis_fmt_c106, dis_fmt_c107,
    dis_fmt_h41fb60, dis_fmt_c109
};

struct mnem_entry asm_mnem_table[140] = { /* 004c16f0 1680 */
    { "abs", 515, 38 },
    { "adc", 548, 33 },
    { "add", 546, 0 },
    { "addl", 513, 18 },
    { "addr", 513, 2 },
    { "and", 772, 0 },
    { "andi", 37, 184 },
    { "asl", 515, 50 },
    { "asr", 515, 34 },
    { "bchg", 5, 720896L },
    { "bclr", 5, 655360L },
    { "bset", 5, 655392L },
    { "btst", 5, 720928L },
    { "clr", 515, 19 },
    { "cmp", 519, 5 },
    { "cmpm", 519, 7 },
    { "debug", 41, 512 },
    { "debugcc", 41, 768 },
    { "debugcs", 41, 776 },
    { "debugec", 41, 773 },
    { "debugeq", 41, 778 },
    { "debuges", 41, 781 },
    { "debugge", 41, 769 },
    { "debuggt", 41, 775 },
    { "debughs", 41, 768 },
    { "debuglc", 41, 774 },
    { "debugle", 41, 783 },
    { "debuglo", 41, 776 },
    { "debugls", 41, 782 },
    { "debuglt", 41, 777 },
    { "debugmi", 41, 779 },
    { "debugne", 41, 770 },
    { "debugneq", 41, 770 },
    { "debugnn", 41, 772 },
    { "debugnr", 41, 780 },
    { "debugpl", 41, 771 },
    { "dec", 2, 10 },
    { "div", 8, 98368L },
    { "do", 9, 393216L },
    { "enddo", 10, 140 },
    { "eor", 544, 67 },
    { "illegal", 11, 5 },
    { "inc", 2, 8 },
    { "jcc", 14, 655360L },
    { "jclr", 15, 655488L },
    { "jcs", 14, 688128L },
    { "jec", 14, 675840L },
    { "jeq", 14, 696320L },
    { "jes", 14, 708608L },
    { "jge", 14, 659456L },
    { "jgt", 14, 684032L },
    { "jhs", 14, 655360L },
    { "jlc", 14, 679936L },
    { "jle", 14, 716800L },
    { "jlo", 14, 688128L },
    { "jls", 14, 712704L },
    { "jlt", 14, 692224L },
    { "jmi", 14, 700416L },
    { "jmp", 19, 524288L },
    { "jne", 14, 663552L },
    { "jneq", 14, 663552L },
    { "jnn", 14, 671744L },
    { "jnr", 14, 704512L },
    { "jpl", 14, 667648L },
    { "jscc", 16, 720896L },
    { "jsclr", 17, 721024L },
    { "jscs", 16, 753664L },
    { "jsec", 16, 741376L },
    { "jseq", 16, 761856L },
    { "jses", 16, 774144L },
    { "jset", 15, 655520L },
    { "jsge", 16, 724992L },
    { "jsgt", 16, 749568L },
    { "jshs", 16, 720896L },
    { "jslc", 16, 745472L },
    { "jsle", 16, 782336L },
    { "jslo", 16, 753664L },
    { "jsls", 16, 778240L },
    { "jslt", 16, 757760L },
    { "jsmi", 16, 765952L },
    { "jsne", 16, 729088L },
    { "jsneq", 16, 729088L },
    { "jsnn", 16, 737280L },
    { "jsnr", 16, 770048L },
    { "jspl", 16, 733184L },
    { "jsr", 18, 589824L },
    { "jsset", 17, 721056L },
    { "lea", 20, 278544L },
    { "lsl", 552, 51 },
    { "lsr", 552, 35 },
    { "lua", 20, 278544L },
    { "mac", 789, 130 },
    { "macr", 810, 131 },
    { "move", 279, 0 },
    { "movec", 278, 262144L },
    { "movem", 280, 458752L },
    { "movep", 25, 540672L },
    { "mpy", 794, 128 },
    { "mpyr", 811, 129 },
    { "neg", 515, 54 },
    { "nop", 27, 0 },
    { "norm", 28, 120853L },
    { "not", 552, 23 },
    { "or", 772, 64 },
    { "ori", 37, 248 },
    { "rep", 29, 393248L },
    { "reset", 12, 132 },
    { "rnd", 515, 17 },
    { "rol", 552, 55 },
    { "ror", 552, 39 },
    { "rti", 30, 4 },
    { "rts", 31, 12 },
    { "sbc", 548, 37 },
    { "stop", 12, 135 },
    { "sub", 546, 4 },
    { "subl", 513, 22 },
    { "subr", 513, 6 },
    { "swi", 13, 6 },
    { "tcc", 38, 131072L },
    { "tcs", 38, 163840L },
    { "tec", 38, 151552L },
    { "teq", 38, 172032L },
    { "tes", 38, 184320L },
    { "tfr", 547, 1 },
    { "tge", 38, 135168L },
    { "tgt", 38, 159744L },
    { "ths", 38, 131072L },
    { "tlc", 38, 155648L },
    { "tle", 38, 192512L },
    { "tlo", 38, 163840L },
    { "tls", 38, 188416L },
    { "tlt", 38, 167936L },
    { "tmi", 38, 176128L },
    { "tne", 38, 139264L },
    { "tneq", 38, 139264L },
    { "tnn", 38, 147456L },
    { "tnr", 38, 180224L },
    { "tpl", 38, 143360L },
    { "tst", 551, 3 },
    { "wait", 12, 134 }
};

long asm_mnem_count = 140; /* 004c1d80 4 */

long d_4c28e0 = 0; /* 004c28e0 4 */

long d_4c28e4[3] = { /* 004c28e4 12 */
    1, 2, 3
};

long d_4c28f0 = 2; /* 004c28f0 4 */

long d_4c28f4[5] = { /* 004c28f4 20 */
    3, 4, 5, 6, 7
};

long d_4c2908[4] = { /* 004c2908 16 */
    1, 2, 3, 0
};

long d_4c2918[4] = { /* 004c2918 16 */
    4, 5, 6, 7
};

long d_4c2928[2] = { /* 004c2928 8 */
    2, 3
};

long d_4c2930[8] = { /* 004c2930 32 */
    2, 1, 4, 2, 6, 3, 4, 2
};

long d_4c2950[4] = { /* 004c2950 16 */
    5, 3, 3, 2
};

long d_4c2960[4] = { /* 004c2960 16 */
    65535L, 262143L, 1048575L, 4194303L
};

long d_4c2970[43] = { /* 004c2970 172 */
    32767, 32767, 32767, 32767, 32767, 32767, 32767, 32767,
    131071L, 262143L, 65535L, 131071L, 32767, 65535L, 32767, 65535L,
    131071L, 262143L, 65535L, 131071L, 32767, 65535L, 32767, 65535L,
    65535L, 131071L, 32767, 65535L, 16383, 32767, 16383, 32767,
    32767, 65535L, 16383, 32767, 8191, 16383, 8191, 16383,
    131071L, 262143L, 65535L
};

long d_4c2a1c[21] = { /* 004c2a1c 84 */
    131071L, 32767, 65535L, 32767, 65535L, 524287L, 1048575L, 262143L,
    524287L, 131071L, 262143L, 131071L, 262143L, 2097151L, 4194303L, 1048575L,
    2097151L, 524287L, 1048575L, 524287L, 1048575L
};

long d_4c2a70[4] = { /* 004c2a70 16 */
    255, 511, 1023, 2047
};

long d_4c2a80 = 1; /* 004c2a80 4 */

long d_4c2a84 = 2; /* 004c2a84 4 */

long d_4c2a88[10] = { /* 004c2a88 40 */
    4, 0, 2, 1, 4, 2, 6, 3,
    4, 2
};

struct core_vtable core_vtable_56000[1] = { /* 004c2ab0 28 */
    { mem_reg_read, mem_reg_write, mem_write_n, mem_region_of, 0, reg_write_check, reg_read_check }
};

long d_4c2acc[9] = { /* 004c2acc 36 */
    0, 0, 0, 0, 0, 0, 0, 0,
    0
};

struct core_vtable core_vtable_56009[1] = { /* 004c2af0 28 */
    { mem_reg_read, mem_reg_write, mem_write_n, mem_region_of, omr_remap_56009, reg_write_check, reg_read_check }
};

long d_4c2b0c[9] = { /* 004c2b0c 36 */
    0, 0, 0, 0, 0, 0, 0, 0,
    0
};

struct core_vtable core_vtable_56011[1] = { /* 004c2b30 28 */
    { mem_reg_read, mem_reg_write, mem_write_n, mem_region_of, omr_remap_56011, reg_write_check, reg_read_check }
};

long d_4c2b4c[9] = { /* 004c2b4c 36 */
    0, 0, 0, 0, 0, 0, 0, 0,
    0
};

struct core_vtable core_vtable_56012[1] = { /* 004c2b70 28 */
    { mem_reg_read, mem_reg_write, mem_write_n, mem_region_of, omr_remap_56012, reg_write_check, reg_read_check }
};

long d_4c2b8c[9] = { /* 004c2b8c 36 */
    0, 0, 0, 0, 0, 0, 0, 0,
    0
};

long insn_exec_records[688] = { /* 004c2bb0 2752 */
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 1,
    0, 0, 0, 0, 0, 0, 1, 0,
    0, 0, 0, 0, 0, 0, 3, 0,
    0, 0, 0, 0, 0, 9, 2, 0,
    0, 0, 0, 0, 1, 0, 3, 0,
    0, 0, 0, 0, 2, 0, 1, 0,
    0, 0, 0, 0, 4, 0, 3, 0,
    0, 0, 0, 0, 8, 0, 1, 0,
    0, 0, 0, 0, 8, 0, 1, 1,
    0, 0, 0, 0, 8, 0, 3, 0,
    0, 0, 0, 0, 16, 0, 3, 0,
    0, 0, 0, 0, 32, 0, 1, 0,
    0, 0, 0, 0, 32, 0, 1, 1,
    0, 0, 0, 0, 32, 0, 3, 0,
    0, 0, 0, 20, 8, 0, 3, 0,
    0, 0, 20, 0, 4, 0, 3, 0,
    0, 2, 0, 2, 40, 0, 3, 0,
    0, 3, 0, 3, 40, 0, 3, 0,
    0, 5, 0, 4, 40, 0, 3, 0,
    0, 7, 0, 6, 40, 0, 3, 0,
    0, 12, 0, 8, 40, 0, 3, 0,
    0, 13, 0, 9, 40, 0, 3, 0,
    0, 14, 0, 15, 40, 0, 3, 0,
    0, 15, 0, 14, 40, 0, 3, 0,
    0, 57, 0, 0, 0, 3, 3, 0,
    0, 58, 0, 0, 0, 3, 3, 0,
    0, 63, 0, 0, 0, 5, 3, 0,
    0, 63, 0, 0, 8, 0, 3, 0,
    0, 63, 0, 0, 32, 0, 3, 0,
    0, 129, 0, 17, 40, 0, 3, 0,
    0, 129, 17, 0, 36, 0, 3, 0,
    0, 129, 18, 18, 0, 9, 3, 0,
    0, 129, 18, 18, 32, 0, 3, 0,
    0, 132, 0, 0, 0, 9, 3, 0,
    0, 132, 0, 0, 8, 0, 3, 0,
    0, 132, 0, 0, 32, 0, 3, 0,
    0, 136, 0, 0, 0, 17, 3, 0,
    0, 136, 0, 0, 0, 33, 3, 0,
    0, 160, 0, 0, 0, 0, 3, 0,
    0, 192, 0, 0, 0, 0, 3, 0,
    0, 192, 0, 0, 0, 9, 3, 0,
    0, 192, 0, 0, 0, 33, 3, 0,
    0, 192, 0, 0, 8, 0, 3, 0,
    0, 192, 0, 0, 32, 0, 3, 0,
    2, 0, 2, 0, 20, 0, 3, 0,
    3, 0, 3, 0, 20, 0, 3, 0,
    5, 0, 4, 0, 20, 0, 3, 0,
    7, 0, 6, 0, 20, 0, 3, 0,
    12, 0, 8, 0, 20, 0, 3, 0,
    13, 0, 9, 0, 20, 0, 3, 0,
    14, 0, 15, 0, 20, 0, 3, 0,
    15, 0, 14, 0, 20, 0, 3, 0,
    40, 192, 0, 0, 0, 0, 3, 0,
    129, 0, 0, 17, 24, 0, 3, 0,
    129, 0, 17, 0, 20, 0, 3, 0,
    129, 0, 18, 18, 16, 0, 3, 0,
    130, 130, 0, 17, 0, 9, 3, 0,
    130, 130, 0, 17, 8, 0, 3, 0,
    130, 130, 17, 0, 4, 0, 3, 0,
    132, 0, 0, 0, 4, 0, 3, 0,
    132, 0, 0, 0, 16, 0, 3, 0,
    136, 144, 0, 0, 0, 0, 3, 0,
    144, 0, 0, 0, 0, 0, 1, 0,
    144, 63, 0, 0, 0, 0, 3, 0,
    144, 192, 0, 0, 0, 0, 3, 0,
    160, 0, 0, 0, 0, 0, 1, 0,
    160, 0, 0, 0, 4, 0, 3, 0,
    160, 0, 0, 0, 16, 0, 3, 0,
    160, 160, 0, 0, 0, 0, 3, 0,
    192, 128, 0, 0, 0, 0, 3, 0,
    0, 0, 0, 0, 2, 0, 1, 1,
    160, 0, 0, 0, 0, 0, 1, 1,
    41, 192, 0, 0, 0, 0, 3, 0,
    144, 0, 0, 0, 0, 0, 3, 0,
    144, 0, 0, 0, 4, 0, 3, 0,
    144, 0, 0, 0, 16, 0, 3, 0,
    0, 160, 0, 0, 8, 0, 3, 0,
    0, 160, 0, 0, 32, 0, 3, 0,
    6, 15, 15, 0, 4, 0, 3, 0,
    6, 14, 14, 0, 4, 0, 3, 0,
    15, 0, 4, 15, 16, 0, 3, 0,
    14, 0, 4, 14, 16, 0, 3, 0,
    0, 0, 0, 0, 4, 9, 3, 0,
    0, 0, 0, 0, 16, 9, 3, 0
};

long d_4c3670[16] = { /* 004c3670 64 */
    50, 51, 48, 49, 46, 47, 52, 53,
    22, 23, 20, 21, 18, 19, 24, 25
};

long d_4c36b0[16] = { /* 004c36b0 64 */
    50, 51, 48, 49, 46, 47, 52, 53,
    22, 23, 20, 21, 18, 19, 24, 25
};

simfn insn_exec_handlers[110] = { /* 004c36f0 440 */
    insn_exec_h42e5d0, insn_exec_h42e600, insn_exec_h42e750, insn_exec_h42e600,
    insn_exec_h42e750, insn_exec_h42e670, insn_exec_h42e780, insn_exec_h42e670,
    insn_exec_h42e780, insn_exec_h42e6e0, insn_exec_h42e7b0, insn_exec_h42e7e0,
    insn_exec_h42e7e0, insn_exec_h42e7f0, insn_exec_h42e810, insn_exec_h42e820,
    insn_exec_h42e820, insn_exec_h42e820, insn_exec_h42e5c0, insn_exec_h42e5c0,
    insn_exec_h42e830, insn_exec_h42e890, insn_exec_h42e5c0, insn_exec_h42e5c0,
    insn_exec_h42e5c0, insn_exec_h42e5c0, insn_exec_h42e5c0, insn_exec_h42e5c0,
    insn_exec_h42ee90, insn_exec_h42ee90, insn_exec_h42ee80, insn_exec_h42ee80,
    insn_exec_h42e8f0, insn_exec_h42e8f0, insn_exec_h42e950, insn_exec_h42e950,
    insn_exec_h42e910, insn_exec_h42e910, insn_exec_h42e980, insn_exec_h42e980,
    insn_exec_h42e8f0, insn_exec_h42e8f0, insn_exec_h42e950, insn_exec_h42e950,
    insn_exec_h42e5c0, insn_exec_h42e5c0, insn_exec_h42ee90, insn_exec_h42ee90,
    insn_exec_h42ee80, insn_exec_h42ee80, insn_exec_h42e8f0, insn_exec_h42e8f0,
    insn_exec_h42e950, insn_exec_h42e950, insn_exec_h42e910, insn_exec_h42e910,
    insn_exec_h42e980, insn_exec_h42e980, insn_exec_h42e8f0, insn_exec_h42e8f0,
    insn_exec_h42e950, insn_exec_h42e950, insn_exec_h42ee40, insn_exec_h42ee40,
    insn_exec_h42ee40, insn_exec_h42e9e0, insn_exec_h42eaf0, insn_exec_h42eb90,
    insn_exec_h42ee40, insn_exec_h42ec20, insn_exec_h42ec90, insn_exec_h42ecd0,
    insn_exec_h42ecd0, insn_exec_h42ece0, insn_exec_h42ece0, insn_exec_h42ecc0,
    insn_exec_h42ecc0, insn_exec_h42ed20, insn_exec_h42ed20, insn_exec_h42ed40,
    insn_exec_h42ed40, insn_exec_h42f220, insn_exec_h42f220, insn_exec_h42eda0,
    insn_exec_h42eda0, insn_exec_h42edc0, insn_exec_h42edc0, insn_exec_h42ede0,
    insn_exec_h42ede0, insn_exec_h42ee10, insn_exec_h42e5c0, insn_exec_h42e5c0,
    insn_exec_h42e5c0, insn_exec_h42e5c0, insn_exec_h42e5c0, insn_exec_h42ee20,
    insn_exec_h42ee20, insn_exec_h42e5c0, insn_exec_h42e5c0, insn_exec_h42e5c0,
    insn_exec_h42e5c0, insn_exec_h42e5c0, insn_exec_h42e5c0, insn_exec_h42e5c0,
    insn_exec_h42e5c0, insn_exec_h42e5c0, insn_exec_h42e5c0, insn_exec_h42e5c0,
    insn_exec_h42e5c0, insn_exec_h42e5c0
};

long insn_move_records[138] = { /* 004c38a8 552 */
    0, 0, 0, 0, 1, 8, 0, 1,
    16, 0, 2, 2, 0, 2, 8, 0,
    2, 14, 0, 2, 16, 0, 801, 6,
    0, 802, 6, 0, 51202L, 4, 352, 910,
    0, 32, 8970, 8, 96, 910, 0, 98,
    905, 16, 98, 906, 16, 104, 909, 0,
    104, 910, 0, 2048, 2, 8, 512, 1802,
    15, 640, 1802, 15, 768, 1802, 15, 1536,
    1802, 15, 2048, 2, 8, 8192, 2, 8,
    8192, 2, 16, 8306, 938, 5, 12288, 770,
    1, 12288, 770, 12, 16482, 906, 1, 16482,
    906, 16, 16482, 906, 15, 96, 910, 0,
    33, 39818L, 8, 96, 39310L, 0, 4096, 870,
    0, 0, 1, 13, 0, 1, 12, 4096,
    1, 11, 4128, 9, 10, 100, 141, 0,
    0, 1, 7, 96, 157, 0, 16482, 906,
    17, 32, 910, 0, 12288, 2, 12, 98,
    905, 8
};

simfn insn_move_handlers[110] = { /* 004c3ad0 440 */
    insn_move_h42ef40, insn_move_h42ef50, insn_move_h42ef40, insn_move_h42ef50,
    insn_move_h42ef40, insn_move_h42ef50, insn_move_h42ef40, insn_move_h42ef50,
    insn_move_h42ef40, insn_move_h42ef50, insn_move_h42ef40, insn_move_h42ef40,
    insn_move_h42ef40, insn_move_h42ef40, insn_move_h42ef40, insn_move_h42ef40,
    insn_move_h42ef40, insn_move_h42ef40, insn_move_h42ef40, insn_move_h42ef40,
    insn_move_h42ef50, insn_move_h42ef50, insn_move_h42ef80, insn_move_h42ef80,
    insn_move_h42ef90, insn_move_h42ef90, insn_move_h42efa0, insn_move_h42efd0,
    insn_move_h42f290, insn_move_h42f290, insn_move_h42f000, insn_move_h42f000,
    insn_move_h42f000, insn_move_h42f000, insn_move_h42f290, insn_move_h42f290,
    insn_move_h42f010, insn_move_h42f010, insn_move_h42f040, insn_move_h42f040,
    insn_move_h42f000, insn_move_h42f000, insn_move_h42f290, insn_move_h42f290,
    insn_move_h42efa0, insn_move_h42efd0, insn_move_h42f290, insn_move_h42f290,
    insn_move_h42f000, insn_move_h42f000, insn_move_h42f000, insn_move_h42f000,
    insn_move_h42f290, insn_move_h42f290, insn_move_h42f010, insn_move_h42f010,
    insn_move_h42f040, insn_move_h42f040, insn_move_h42f000, insn_move_h42f000,
    insn_move_h42f290, insn_move_h42f290, insn_move_h42f270, insn_move_h42f270,
    insn_move_h42f270, insn_move_h42f070, insn_move_h42f0c0, insn_move_h42f0f0,
    insn_move_h42f270, insn_move_h42f0c0, insn_move_h42f120, insn_move_h42f130,
    insn_move_h42f170, insn_move_h42f140, insn_move_h42f180, insn_move_h42f130,
    insn_move_h42f170, insn_move_h42f130, insn_move_h42f170, insn_move_h42f1c0,
    insn_move_h42f1c0, insn_move_h42f1b0, insn_move_h42f1b0, insn_move_h42f1b0,
    insn_move_h42f1b0, insn_move_h42f1b0, insn_move_h42f1b0, insn_move_h42f1f0,
    insn_move_h42f1f0, insn_move_h42f200, insn_move_h42f200, insn_move_h42f210,
    insn_move_h42f210, insn_move_h42f1b0, insn_move_h42f1b0, insn_move_h42f1b0,
    insn_move_h42f1b0, insn_exec_h42f220, insn_move_h42f230, insn_move_h42f230,
    insn_move_h42f240, insn_move_h42f260, insn_move_h42f210, insn_move_h42f210,
    insn_move_h42f250, insn_move_h42ef30, insn_move_h42f260, insn_move_h42f1b0,
    insn_move_h42ef30, insn_move_h42f210
};

simfn insn_class_handlers[110] = { /* 004c3c88 440 */
    insn_class_h42f4b0, insn_class_h42f4d0, insn_class_h42f530, insn_class_h42f4d0,
    insn_class_h42f530, insn_class_h42f4d0, insn_class_h42f530, insn_class_h42f4d0,
    insn_class_h42f530, insn_class_h42f570, insn_class_h42f5c0, insn_class_h42f4a0,
    insn_class_h42f4a0, insn_class_h42f4a0, insn_class_h42f4a0, insn_class_h42f4a0,
    insn_class_h42f4a0, insn_class_h42f4a0, insn_class_h42f5e0, insn_class_h42f4a0,
    insn_class_h42f5f0, insn_class_h42f640, insn_class_h42f690, insn_class_h42f690,
    insn_class_h42f690, insn_class_h42f690, insn_class_h42f6c0, insn_class_h42f6c0,
    insn_class_h42f4a0, insn_class_h42f4a0, insn_class_h42fd70, insn_class_h42fd70,
    insn_class_h42f710, insn_class_h42f710, insn_class_h42f770, insn_class_h42f770,
    insn_class_h42f7a0, insn_class_h42f7a0, insn_class_h42f850, insn_class_h42f850,
    insn_class_h42f710, insn_class_h42f710, insn_class_h42f770, insn_class_h42f770,
    insn_class_h42f6c0, insn_class_h42f6c0, insn_class_h42f4a0, insn_class_h42f4a0,
    insn_class_h42fd70, insn_class_h42fd70, insn_class_h42f710, insn_class_h42f710,
    insn_class_h42f770, insn_class_h42f770, insn_class_h42f7a0, insn_class_h42f7a0,
    insn_class_h42f850, insn_class_h42f850, insn_class_h42f710, insn_class_h42f710,
    insn_class_h42f770, insn_class_h42f770, insn_class_h42fd20, insn_class_h42fcd0,
    insn_class_h42fd20, insn_class_h42f8b0, insn_class_h_42fa60, insn_class_h42fba0,
    insn_class_h42fcd0, insn_class_h42fbe0, insn_class_h42fc30, insn_class_h42f4a0,
    insn_class_h42fd70, insn_class_h42fc50, insn_class_h42f7a0, insn_class_h42f4a0,
    insn_class_h42fd70, insn_class_h42f770, insn_class_h42f710, insn_class_h42f850,
    insn_class_h42f850, insn_class_h42f4a0, insn_class_h42f4a0, insn_class_h42f770,
    insn_class_h42f770, insn_class_h42f4a0, insn_class_h42f4a0, insn_class_h42fcb0,
    insn_class_h42fcb0, insn_class_h42f4a0, insn_class_h42f4a0, insn_class_h42f5e0,
    insn_class_h42f4a0, insn_class_h42f4a0, insn_class_h42f4a0, insn_class_h42f4a0,
    insn_class_h42f4a0, insn_class_h42f4a0, insn_class_h42f4a0, insn_class_h42f4a0,
    insn_class_h42f4a0, insn_class_h42f4a0, insn_class_h42f4a0, insn_class_h42f4a0,
    insn_class_h42f4a0, insn_class_h42f4a0, insn_class_h42f4a0, insn_class_h42f4a0,
    insn_class_h42f4a0, insn_class_h42f4a0
};

long d_4c3e40[104] = { /* 004c3e40 416 */
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 8192, 8192,
    8192, 8192, 4, 4, 0, 0, 0, 0,
    16384, 16384, 17408, 16384, 0, 0, 1024, 0,
    0, 0, 1024, 0, 4, 4, 0, 0,
    0, 0, 16384, 16384, 16384, 16384, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 4096, 4096, 4096, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 520, 512, 2048, 0, 0, 0, 32,
    64, 256, 1, 2, 16, 0, 0, 0
};

long d_4c3fe0[6] = { /* 004c3fe0 24 */
    128, 32896L, 0, 0, 32896L, 0
};

long d_4c3ff8[110] = { /* 004c3ff8 440 */
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 4, 4, 0, 0, 0, 0,
    16384, 16384, 17408, 16384, 0, 0, 1024, 0,
    0, 0, 1024, 0, 4, 4, 0, 0,
    0, 0, 16384, 16384, 16384, 16384, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 4096, 4096, 4096, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 520, 512, 2048, 0, 0, 0, 32,
    64, 256, 0, 0, 0, 0, 0, 0,
    128, 32896L, 0, 0, 32896L, 0
};

long d_4c41b0[128] = { /* 004c41b0 512 */
    0, 1, 1, 0, 0, 0, 1, 0,
    0, 1, 1, 0, 0, 0, 1, 0,
    1, 1, 1, 1, 1, 0, 1, 1,
    1, 1, 1, 1, 1, 0, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 0, 1, 0,
    1, 1, 1, 1, 1, 0, 1, 0,
    1, 1, 1, 1, 1, 0, 1, 0,
    1, 1, 1, 1, 1, 0, 1, 0,
    1, 1, 1, 1, 1, 0, 1, 0,
    1, 1, 1, 1, 1, 0, 1, 0,
    1, 1, 1, 1, 1, 0, 1, 0,
    1, 1, 1, 1, 1, 0, 1, 0
};

long d_4c43b0[128] = { /* 004c43b0 512 */
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 1,
    0, 0, 0, 0, 0, 0, 0, 1,
    0, 0, 0, 1, 0, 0, 0, 1,
    0, 0, 0, 1, 0, 0, 0, 1,
    0, 0, 0, 1, 0, 0, 0, 1,
    0, 0, 0, 1, 0, 0, 0, 1,
    0, 0, 1, 1, 0, 0, 1, 0,
    0, 0, 1, 1, 0, 0, 1, 0,
    0, 0, 1, 1, 0, 0, 1, 0,
    0, 0, 1, 1, 0, 0, 1, 0,
    0, 0, 1, 1, 0, 0, 1, 0,
    0, 0, 1, 1, 0, 0, 1, 0,
    0, 0, 1, 1, 0, 0, 1, 0,
    0, 0, 1, 1, 0, 0, 1, 0
};

struct opclass_entry opclass_table[109] = { /* 004c45b0 1744 */
    { 0x800000UL, 0x800000UL, 0, 0 },
    { 0xf04000UL, 0x704000UL, 1, 0 },
    { 0xf04000UL, 0x700000UL, 2, 0 },
    { 0xf04000UL, 0x604000UL, 3, 0 },
    { 0xf04000UL, 0x600000UL, 4, 0 },
    { 0xf04000UL, 0x504000UL, 5, 0 },
    { 0xf04000UL, 0x500000UL, 6, 0 },
    { 0xf44000UL, 0x444000UL, 7, 0 },
    { 0xf44000UL, 0x440000UL, 8, 0 },
    { 0xf44000UL, 0x404000UL, 9, 0 },
    { 0xf44000UL, 0x400000UL, 10, 0 },
    { 0xf80000UL, 0x380000UL, 11, 0 },
    { 0xf80000UL, 0x300000UL, 12, 0 },
    { 0xf80000UL, 0x280000UL, 13, 0 },
    { 0xfc0000UL, 0x240000UL, 14, 0 },
    { 0xfe0000UL, 0x220000UL, 15, 0 },
    { 0xfd0000UL, 0x210000UL, 16, 0 },
    { 0xfc8000UL, 0x208000UL, 17, 0 },
    { 0xffe000UL, 0x204000UL, 18, 0 },
    { 0xffc000UL, 0x200000UL, 19, 0 },
    { 0xf04000UL, 0x104000UL, 20, 0 },
    { 0xf04000UL, 0x100000UL, 21, 0 },
    { 0xff0000UL, 0xf0000UL, 22, 0 },
    { 0xff0000UL, 0xe0000UL, 23, 0 },
    { 0xff0000UL, 0xd0000UL, 24, 0 },
    { 0xff0000UL, 0xc0000UL, 25, 0 },
    { 0xffc0a0UL, 0xbc0a0UL, 26, 0 },
    { 0xffc0a0UL, 0xbc080UL, 27, 0 },
    { 0xffc0e0UL, 0xbc060UL, 28, 0 },
    { 0xffc0e0UL, 0xbc040UL, 29, 0 },
    { 0xffc0e0UL, 0xbc020UL, 30, 0 },
    { 0xffc0e0UL, 0xbc000UL, 31, 0 },
    { 0xffc0a0UL, 0xb80a0UL, 32, 0 },
    { 0xffc0a0UL, 0xb8080UL, 33, 0 },
    { 0xffc0a0UL, 0xb8020UL, 34, 0 },
    { 0xffc0a0UL, 0xb8000UL, 35, 0 },
    { 0xffc0a0UL, 0xb40a0UL, 36, 0 },
    { 0xffc0a0UL, 0xb4080UL, 37, 0 },
    { 0xffc0a0UL, 0xb4020UL, 38, 0 },
    { 0xffc0a0UL, 0xb4000UL, 39, 0 },
    { 0xffc0a0UL, 0xb00a0UL, 40, 0 },
    { 0xffc0a0UL, 0xb0080UL, 41, 0 },
    { 0xffc0a0UL, 0xb0020UL, 42, 0 },
    { 0xffc0a0UL, 0xb0000UL, 43, 0 },
    { 0xffc0a0UL, 0xac0a0UL, 44, 0 },
    { 0xffc0a0UL, 0xac080UL, 45, 0 },
    { 0xffc0e0UL, 0xac060UL, 46, 0 },
    { 0xffc0e0UL, 0xac040UL, 47, 0 },
    { 0xffc0e0UL, 0xac020UL, 48, 0 },
    { 0xffc0e0UL, 0xac000UL, 49, 0 },
    { 0xffc0a0UL, 0xa80a0UL, 50, 0 },
    { 0xffc0a0UL, 0xa8080UL, 51, 0 },
    { 0xffc0a0UL, 0xa8020UL, 52, 0 },
    { 0xffc0a0UL, 0xa8000UL, 53, 0 },
    { 0xffc0a0UL, 0xa40a0UL, 54, 0 },
    { 0xffc0a0UL, 0xa4080UL, 55, 0 },
    { 0xffc0a0UL, 0xa4020UL, 56, 0 },
    { 0xffc0a0UL, 0xa4000UL, 57, 0 },
    { 0xffc0a0UL, 0xa00a0UL, 58, 0 },
    { 0xffc0a0UL, 0xa0080UL, 59, 0 },
    { 0xffc0a0UL, 0xa0020UL, 60, 0 },
    { 0xffc0a0UL, 0xa0000UL, 61, 0 },
    { 0xffc000UL, 0x98000UL, 62, 0 },
    { 0xffc000UL, 0x90000UL, 63, 0 },
    { 0xffc000UL, 0x88000UL, 64, 0 },
    { 0xfe4080UL, 0x84080UL, 65, 0 },
    { 0xfe40c0UL, 0x84040UL, 66, 0 },
    { 0xfe40c0UL, 0x84000UL, 67, 0 },
    { 0xffc000UL, 0x80000UL, 68, 0 },
    { 0xff4080UL, 0x74080UL, 69, 0 },
    { 0xff4080UL, 0x70000UL, 70, 0 },
    { 0xffc0a0UL, 0x6c020UL, 71, 0 },
    { 0xffc0a0UL, 0x6c000UL, 72, 0 },
    { 0xffc0a0UL, 0x64020UL, 73, 0 },
    { 0xffc0a0UL, 0x64000UL, 74, 0 },
    { 0xff00a0UL, 0x600a0UL, 75, 0 },
    { 0xff00a0UL, 0x60080UL, 76, 0 },
    { 0xffc0a0UL, 0x60020UL, 77, 0 },
    { 0xffc0a0UL, 0x60000UL, 78, 0 },
    { 0xff40b8UL, 0x54038UL, 79, 0 },
    { 0xff40b8UL, 0x54020UL, 80, 0 },
    { 0xff00b8UL, 0x500b8UL, 81, 0 },
    { 0xff00b8UL, 0x500a0UL, 82, 0 },
    { 0xff40b8UL, 0x50038UL, 83, 0 },
    { 0xff40b8UL, 0x50020UL, 84, 0 },
    { 0xff40b8UL, 0x440b8UL, 85, 0 },
    { 0xff40b8UL, 0x440a0UL, 86, 0 },
    { 0xff60b8UL, 0x44018UL, 87, 0 },
    { 0xff60b8UL, 0x44010UL, 88, 0 },
    { 0xff0080UL, 0x30000UL, 89, 0 },
    { 0xff0080UL, 0x20000UL, 90, 0 },
    { 0xfff8f7UL, 0x1d815UL, 91, 0 },
    { 0xffc0c0UL, 0x18040UL, 92, 0 },
    { 0xff00c0UL, 0x100c0UL, 109, 4 },
    { 0xfffff0UL, 0x300UL, 93, 4 },
    { 0xffffffUL, 0x200UL, 94, 4 },
    { 0xff00fcUL, 0xf8UL, 95, 0 },
    { 0xff00fcUL, 0xb8UL, 96, 0 },
    { 0xff00afUL, 0x8cUL, 97, 0 },
    { 0xff00afUL, 0x87UL, 98, 0 },
    { 0xff00afUL, 0x86UL, 99, 0 },
    { 0xff00afUL, 0x84UL, 100, 0 },
    { 0xffffffUL, 0xcUL, 101, 0 },
    { 0xfffffeUL, 0xaUL, 102, 4 },
    { 0xfffffeUL, 8UL, 103, 4 },
    { 0xffffffUL, 6UL, 104, 0 },
    { 0xffffffUL, 5UL, 105, 0 },
    { 0xffffffUL, 4UL, 106, 0 },
    { 0xffffffUL, 0, 107, 0 }
};

long d_4c4c80[4] = { /* 004c4c80 16 */
    0, 0, 108, 0
};

simfn insn_valid_handlers[109] = { /* 004c4c90 436 */
    insn_valid_h42fe60, insn_valid_pm_a, insn_valid_h42ffb0, insn_valid_pm_a,
    insn_valid_h42ffb0, insn_valid_h42ffc0, insn_valid_h42ffc0, insn_valid_pm_a,
    insn_valid_h42ffb0, insn_valid_h4300a0, insn_valid_h4300a0, insn_valid_h42ffb0,
    insn_valid_h42ffb0, insn_valid_h430160, insn_valid_h42ffb0, insn_valid_h430210,
    insn_valid_h430210, insn_valid_h430210, insn_valid_h42ffb0, insn_valid_pm_c,
    insn_valid_pm_d, insn_valid_pm_e, insn_exec_h42e5c0, insn_exec_h42e5c0,
    insn_exec_h42e5c0, insn_exec_h42e5c0, insn_valid_h430410, insn_valid_h430410,
    insn_valid_h4306e0, insn_valid_h4306e0, insn_valid_h4306e0, insn_valid_h4306e0,
    insn_valid_h430430, insn_valid_h430430, insn_valid_h430430, insn_valid_h430430,
    insn_valid_h430450, insn_valid_h430450, insn_valid_h430480, insn_valid_h430480,
    insn_valid_h430430, insn_valid_h430430, insn_valid_h430430, insn_valid_h430430,
    insn_valid_h430410, insn_valid_h430410, insn_valid_h4306e0, insn_valid_h4306e0,
    insn_valid_h4306e0, insn_valid_h4306e0, insn_valid_h430430, insn_valid_h430430,
    insn_valid_h430430, insn_valid_h430430, insn_valid_h430450, insn_valid_h430450,
    insn_valid_h430480, insn_valid_h430480, insn_valid_h430430, insn_valid_h430430,
    insn_valid_h430430, insn_valid_h430430, insn_valid_pm_f, insn_valid_pm_f,
    insn_valid_pm_f, insn_valid_h4304b0, insn_valid_h4304b0, insn_valid_h4304e0,
    insn_valid_pm_f, insn_valid_h430510, insn_valid_h430550, insn_valid_h4304e0,
    insn_valid_h4305a0, insn_valid_h430580, insn_valid_h430580, insn_exec_h42e5c0,
    insn_exec_h42e5c0, insn_exec_h42e5c0, insn_exec_h42e5c0, insn_valid_h4304b0,
    insn_valid_h4304b0, insn_exec_h42e5c0, insn_exec_h42e5c0, insn_exec_h42e5c0,
    insn_exec_h42e5c0, insn_valid_h4305e0, insn_valid_h4304e0, insn_exec_h42e5c0,
    insn_exec_h42e5c0, insn_valid_h430630, insn_valid_h430630, insn_exec_h42e5c0,
    insn_valid_h42ffb0, insn_exec_h42e5c0, insn_exec_h42e5c0, insn_valid_h430650,
    insn_valid_h430650, insn_exec_h42e5c0, insn_exec_h42e5c0, insn_exec_h42e5c0,
    insn_exec_h42e5c0, insn_exec_h42e5c0, insn_exec_h42e5c0, insn_exec_h42e5c0,
    insn_exec_h42e5c0, insn_exec_h42e5c0, insn_exec_h42e5c0, insn_exec_h42e5c0,
    insn_valid_h42fe50
};

simfn d_4c4e44 = insn_valid_h430720; /* 004c4e44 4 */

long opclass_last_any = 107; /* 004c4e48 4 */

long opclass_last = 107; /* 004c4e4c 4 */

long d_4c4e50[24] = { /* 004c4e50 96 */
    0, 4194304L, 2097152L, 1048576L, 524288L, 262144L, 131072L, 65536L,
    32768L, 16384, 8192, 4096, 2048, 1024, 512, 256,
    128, 64, 32, 16, 8, 4, 2, 1
};

struct rec64w_3a8a1 alu_handlers[1] = { /* 004c4eb0 256 */
    { 0, alu_op_h430880, alu_op_h430a90, alu_add56, alu_op_h430cd0, alu_op_h430e80, alu_op_h430fc0, alu_op_h431090, alu_op_h431170, alu_op_h4312b0, alu_op_h431300, alu_op_h4314a0, alu_op_h431700, alu_op_h431920, alu_op_h4319f0, alu_op_h431ac0, alu_h_4325f0, alu_h_432a70, alu_op_h431b80, alu_mpy, alu_mac, alu_op_h431b90, alu_shift1, alu_op_h431c70, alu_op_h431d40, alu_op_h433650, alu_op_h431e10, alu_op_h431ef0, alu_op_h431fe0, alu_h_432160, alu_op_h432290, alu_op_h432410, alu_op_h432590, alu_op_h4335a0, alu_op_h4318e0, alu_op_h4318a0, alu_op_h431270, alu_op_h431290, alu_op_h432120, alu_op_h432140, 18, 32, 5, 33, -1, 10, 31, 11, 3, 25, 4, 9, 29, -1, 30, 23, 3, 2, 8, 15, 29, 28, 1, 27 }
};
