/* simd_b.c - GENERATED by re/scripts/gentab_sim.py from SIM56000.EXE; do not edit. */
#include "simdata.h"

extern void cdb_snapshot_write();
extern void core_m_clock();
extern void core_m_io_read();
extern void core_m_io_write();
extern void core_m_irq_ack();
extern void core_m_peek();
extern void core_m_reset();
extern void core_write_reg();
extern void dax_m_clock();
extern void dax_m_io_read();
extern void dax_m_io_write();
extern void dax_m_irq_ack();
extern void dax_m_irq_poll();
extern void dax_m_poke();
extern void dax_m_reset();
extern void device_install();
extern void emi1_m_clock();
extern void emi1_m_io_read();
extern void emi1_m_io_write();
extern void emi1_m_irq_ack();
extern void emi1_m_irq_poll();
extern void emi1_m_poke();
extern void emi1_m_reset();
extern void gpio_m_clock();
extern void gpio_m_io_read();
extern void gpio_m_io_write();
extern void gpio_m_peek();
extern void gpio_m_poke();
extern void gpio_m_reset();
extern void periph_read_reg();
extern void snap_restore();

struct cmd_ptr command_entries[39] = { /* 004a8c90 156 */
    { (struct command_entry *)&cmd_entry_asm },
    { (struct command_entry *)&cmd_entry_break },
    { (struct command_entry *)&cmd_entry_change },
    { (struct command_entry *)&cmd_entry_copy },
    { (struct command_entry *)&cmd_entry_device },
    { (struct command_entry *)&cmd_entry_disassemble },
    { (struct command_entry *)&cmd_entry_display },
    { (struct command_entry *)&cmd_entry_down },
    { (struct command_entry *)&cmd_entry_evaluate },
    { (struct command_entry *)&cmd_entry_finish },
    { (struct command_entry *)&cmd_entry_frame },
    { (struct command_entry *)&cmd_entry_go },
    { (struct command_entry *)&cmd_entry_help },
    { (struct command_entry *)&cmd_entry_history },
    { (struct command_entry *)&cmd_entry_input },
    { (struct command_entry *)&cmd_entry_list },
    { (struct command_entry *)&cmd_entry_load },
    { (struct command_entry *)&cmd_entry_log },
    { (struct command_entry *)&cmd_entry_more },
    { (struct command_entry *)&cmd_entry_next },
    { (struct command_entry *)&cmd_entry_output },
    { (struct command_entry *)&cmd_entry_path },
    { (struct command_entry *)&cmd_entry_quit },
    { (struct command_entry *)&cmd_entry_radix },
    { (struct command_entry *)&cmd_entry_redirect },
    { (struct command_entry *)&cmd_entry_reset },
    { (struct command_entry *)&cmd_entry_save },
    { (struct command_entry *)&cmd_entry_step },
    { (struct command_entry *)&cmd_entry_streams },
    { (struct command_entry *)&cmd_entry_system },
    { (struct command_entry *)&cmd_entry_trace },
    { (struct command_entry *)&cmd_entry_type },
    { (struct command_entry *)&cmd_entry_until },
    { (struct command_entry *)&cmd_entry_unlock },
    { (struct command_entry *)&cmd_entry_up },
    { (struct command_entry *)&cmd_entry_view },
    { (struct command_entry *)&cmd_entry_wait },
    { (struct command_entry *)&cmd_entry_watch },
    { (struct command_entry *)&cmd_entry_where }
};

long d_4a8d2c = 0; /* 004a8d2c 4 */

const char *d_4a8d30[8] = { /* 004a8d30 32 */
    "{a}sm    {b}reak    {c}hange    {co}py    {de}vice    {di}sassemble    <{space}>=more", "{d}isplay     {do}wn     {e}valuate     {f}inish     {fr}ame     {g}o     {h}elp", "{hi}story      {i}nput      {li}st      {l}oad      {lo}g      {m}ore      {n}ext", "{o}utput     {p}ath     {q}uit     {r}adix     {red}irect     {re}set     {s}ave",
    "{st}ep     {str}eams     {sy}stem     {t}race     {ty}pe     {un}lock     {u}ntil", "{up}      {v}iew      {w}ait     {wat}ch     {wh}ere", 0, 0
};

void *d_4a8d50[14] = { /* 004a8d50 56 */
    (void *)&d_4a6568, (void *)&d_4a6568,
    (void *)&d_4a6590, (void *)&d_4a65b8,
    (void *)&d_4a65e0, (void *)&d_4a6540,
    (void *)&d_4a6518, (void *)&d_4a6518,
    (void *)&d_4a64f0, (void *)&d_4a64f0,
    0, 0,
    0, 0
};

simfn d_4a8d88[4] = { /* 004a8d88 16 */
    0, cdb_snapshot_write, snap_restore, 0
};

struct sim_state **dev_state_tab = (struct sim_state **)&bss_4dba88; /* 004a8d98 4 */

long cmdstack_size = 10; /* 004a8d9c 4 */

long history_size = 32; /* 004a8da0 4 */

long scrollback_lines = 100; /* 004a8da4 4 */

long screen_rows = 24; /* 004a8da8 4 */

long screen_cols = 80; /* 004a8dac 4 */

long text_rows = 21; /* 004a8db0 4 */

void *itype_tab = (void *)&d_4a8d50; /* 004a8db4 4 */

long num_commands = 39; /* 004a8db8 4 */

void *command_table = (void *)&command_entries; /* 004a8dbc 4 */

void *default_help_lines = (void *)&d_4a8d30; /* 004a8dc0 4 */

void *cmdstack_buf = (void *)&d_4db088; /* 004a8dc4 4 */

void *profiler_hook = (void *)&d_4a8d88; /* 004a8dc8 4 */

long cur_dev_index = 0; /* 004a8dcc 4 */

char * parm_errmsg = 0; /* 004a8dd0 4 */

unsigned char status1_buf[256] = { /* 004a8dd4 256 */
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

long status2_buf[25] = { /* 004a8ed4 100 */
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0
};

unsigned char d_4a8f38[155] = { /* 004a8f38 155 */
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

unsigned char d_4a8fd3 = 0; /* 004a8fd3 1 */

long cmd_linebuf[64] = { /* 004a8fd4 256 */
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0
};

long run_dev_index = 0; /* 004a90d4 4 */

long cmdlog_fp = 0; /* 004a90d8 4 */

long cmdlog_name[64] = { /* 004a90dc 256 */
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0
};

long macro_active = 0; /* 004a91dc 4 */

long macro_fp = 0; /* 004a91e0 4 */

long macro_stack = 0; /* 004a91e4 4 */

long cmd_tokbuf[64] = { /* 004a91e8 256 */
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0
};

long g_cmdline[64] = { /* 004a92e8 256 */
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0
};

signed char g_tok_type = 0; /* 004a93e8 1 */

unsigned char d_4a93e9 = 0; /* 004a93e9 1 */

signed char d_4a93ea = 0; /* 004a93ea 1 */

signed char d_4a93eb = 0; /* 004a93eb 1 */

unsigned char d_4a93ec[124] = { /* 004a93ec 124 */
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

long g_tok_start = 0; /* 004a9468 4 */

long d_4a946c = 0; /* 004a946c 4 */

long d_4a9470 = 0; /* 004a9470 4 */

long d_4a9474[125] = { /* 004a9474 500 */
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0
};

long d_4a9668[2] = { /* 004a9668 8 */
    0, 0
};

long g_tok_val = 0; /* 004a9670 4 */

long d_4a9674[6] = { /* 004a9674 24 */
    0, 0, 0, 0, 0, 0
};

unsigned short d_4a968c[6] = { /* 004a968c 12 */
    0, 0, 0, 0, 0, 0
};

long d_4a9698[8] = { /* 004a9698 32 */
    0, 0, 0, 0, 0, 0, 0, 0
};

long d_4a96b8[2] = { /* 004a96b8 8 */
    0, 0
};

long d_4a96c0 = 0; /* 004a96c0 4 */

long g_io_id_arg[2] = { /* 004a96c4 8 */
    0, 0
};

long d_4a96cc = 0; /* 004a96cc 4 */

long d_4a96d0[2] = { /* 004a96d0 8 */
    0, 0
};

long d_4a96d8 = 0; /* 004a96d8 4 */

long d_4a96dc = 0; /* 004a96dc 4 */

long d_4a96e0[2] = { /* 004a96e0 8 */
    0, 0
};

long d_4a96e8[7] = { /* 004a96e8 28 */
    0, 0, 0, 0, 0, 0, 0
};

long d_4a9704[3] = { /* 004a9704 12 */
    0, 0, 0
};

long d_4a9710[1238] = { /* 004a9710 4952 */
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0
};

long parm_cmdline = 0; /* 004aaa68 4 */

long g_err_tok = 0; /* 004aaa6c 4 */

long help_mode = 0; /* 004aaa70 4 */

long help_index = 0; /* 004aaa74 4 */

long help_lines_cur = 0; /* 004aaa78 4 */

long help_lines_alt = 0; /* 004aaa7c 4 */

long cursor_row = 0; /* 004aaa80 4 */

long cursor_col = 0; /* 004aaa84 4 */

long screen_hold_cnt = 0; /* 004aaa88 4 */

long overwrite_mode = 0; /* 004aaa8c 4 */

long gui_mode[2] = { /* 004aaa90 8 */
    0, 0
};

long prompt_text[3] = { /* 004aaa98 12 */
    0, 0, 0
};

long source_path_list = 0; /* 004aaaa4 4 */

long g_win_buf = 0; /* 004aaaa8 4 */

long more_flag = 0; /* 004aaaac 4 */

long more_line_count = 0; /* 004aaab0 4 */

long quit_on_error = 0; /* 004aaab4 4 */

long on_error_active = 0; /* 004aaab8 4 */

long last_error_code[3] = { /* 004aaabc 12 */
    0, 0, 0
};

struct dev_type *d_4aaac8[14] = { /* 004aaac8 56 */
    (struct dev_type *)&dev_56000, (struct dev_type *)&dev_56001,
    (struct dev_type *)&dev_56002, (struct dev_type *)&dev_56004,
    (struct dev_type *)&dev_56004rom, (struct dev_type *)&dev_56005,
    (struct dev_type *)&dev_56007, (struct dev_type *)&dev_56009,
    (struct dev_type *)&dev_56011, (struct dev_type *)&dev_56012,
    0, 0,
    0, 0
};

const char *banner_ptr = "MOTOROLA DSP56000 SIMULATOR:  VERSION 6.3.0 01-15-1999"; /* 004aab00 4 */

long num_chiptypes = 13; /* 004aab04 4 */

struct dev_type **chiptype_tab = (struct dev_type **)&d_4aaac8; /* 004aab08 4 */

long max_devices = 32; /* 004aab0c 4 */

struct dev_inst **dev_tab = (struct dev_inst **)&bss_4dbb08; /* 004aab10 4 */

long abort_flag = 0; /* 004aab14 4 */

long bit_mask_tab[16] = { /* 004aab18 64 */
    1, 2, 4, 8, 16, 32, 64, 128,
    256, 512, 1024, 2048, 4096, 8192, 16384, 32768L
};

unsigned long d_4aab58[16] = { /* 004aab58 64 */
    0x10000UL, 0x20000UL, 0x40000UL, 0x80000UL, 0x100000UL, 0x200000UL, 0x400000UL, 0x800000UL,
    0x1000000UL, 0x2000000UL, 0x4000000UL, 0x8000000UL, 0x10000000UL, 0x20000000UL, 0x40000000UL, 0x80000000UL
};

simfn devtype_find_hook = device_install; /* 004aab98 4 */

long no_console = 0; /* 004aab9c 4 */

const char *d_4aadb8[6] = { /* 004aadb8 24 */
    "addr or abus or porta :Port A address", "data or dbus or portd :Port A data", "imc                   :Interrupt and Mode Control Pins", "ctrl                  :Bus Control Signals",
    0, 0
};

const char *d_4aadd0[14] = { /* 004aadd0 56 */
    "     Interrupt Start Addresses and Interrupt Source", "$e000  Hardware Reset                 $0016  SCI Receive with Exception", "$0000  Hardware Reset                 $0018  SCI Transmit Data", "$0002  Stack Error                    $001A  SCI Idle Line",
    "$0004  Trace                          $001C  SCI Timer", "$0006  SWI                            $001E  NMI", "$0008  IRQA                           $0020  Host Receive Data", "$000A  IRQB                           $0022  Host Transmit Data",
    "$000C  SSI Receive Data               $0024  Host Command (default)", "$000E  SSI Receive with Exception     $003E  Illegal Instruction", "$0010  SSI Transmit Data              ", "$0012  SSI Transmit with Exception    ",
    "$0014  SCI Receive Data               ", 0
};

const char *d_4aae08[14] = { /* 004aae08 56 */
    "     Interrupt Start Addresses and Interrupt Source", "$e000  Hardware Reset                 $0016  SCI Receive with Exception", "$0000  Hardware Reset                 $0018  SCI Transmit Data", "$0002  Stack Error                    $001A  SCI Idle Line",
    "$0004  Trace                          $001C  SCI Timer", "$0006  SWI                            $001E  NMI", "$0008  IRQA                           $0020  Host Receive Data", "$000A  IRQB                           $0022  Host Transmit Data",
    "$000C  SSI Receive Data               $0024  Host Command (default)", "$000E  SSI Receive with Exception     $003C  Timer Interrupt", "$0010  SSI Transmit Data              $003E  Illegal Instruction", "$0012  SSI Transmit with Exception    ",
    "$0014  SCI Receive Data               ", 0
};

const char *d_4aae40[16] = { /* 004aae40 64 */
    "     Interrupt Start Addresses and Interrupt Source", "$0000  Hardware Reset                 $001C  Reserved", "$0002  Stack Error                    $001E  NMI", "$0004  Trace                          $0020  SHI Transmit Data",
    "$0006  SWI                            $0022  SHI Transmit Underrun", "$0008  IRQA                           $0024  SHI Rec FIFO not empty", "$000A  IRQB                           $0028  SHI Rec FIFO full", "$000C  Reserved                       $002A  SHI Rec Overrun Error",
    "$000E  Reserved                       $002C  SHI Bus Error", "$0010  SAI Left Channel Transmitter   $002E  Reserved", "$0012  SAI Right Channel Transmitter  $0030  EMI Write", "$0014  SAI Transmitter Exception      $0032  EMI Read",
    "$0016  SAI Left Channel Receiver      $0034..$003C Reserved", "$0018  SAI Right Channel Rec          $003E  Illegal Instruction", "$001A  SAI Rec Exception              $0040..$007E Reserved", 0
};

const char *d_4aae80[20] = { /* 004aae80 80 */
    "     Interrupt Start Addresses and Interrupt Source", "$0000  Hardware Reset                $0024  SHI Rec FIFO not empty", "$0002  Stack Error                   $0028  SHI Rec FIFO full", "$0004  Trace                         $002A  SHI Rec Overrun Error",
    "$0006  SWI                           $002C  SHI Bus Error", "$0008  IRQA                          $002E  Reserved", "$000A  IRQB                          $0030  EMI Write", "$000C  Reserved                      $0032  EMI Read",
    "$000E  Reserved                      $0034  EMI EBAR0 Memory Wrap", "$0010  SAI Left Channel Transmitter  $0036  EMI EBAR1 Memory Wrap", "$0012  SAI Right Channel Transmitter $0038..$003C Reserved", "$0014  SAI Transmitter Exception     $003E  Illegal Instruction",
    "$0016  SAI Left Channel Receiver     $0040  SAI Left Channel Transmitter", "$0018  SAI Right Channel Rec         $0042  SAI Right Channel Transmitter", "$001A  SAI Rec Exception             $0044  SAI Transmitter Exception", "$001C  Reserved                      $0046  SAI Left Channel Receiver",
    "$001E  NMI                           $0048  SAI Right Channel Rec", "$0020  SHI Transmit Data             $004A  SAI Rec Exception", "$0022  SHI Transmit Underrun         $004C..$007E Reserved", 0
};

const char *d_4aaed0[14] = { /* 004aaed0 56 */
    "     Interrupt Start Addresses and Interrupt Source", "$e000  Hardware Reset                 $0016  SCI Receive with Exception", "$0000  Hardware Reset                 $0018  SCI Transmit Data", "$0002  Stack Error                    $001A  SCI Idle Line",
    "$0004  Trace                          $001C  SCI Timer", "$0006  SWI                            $001E  NMI", "$0008  IRQA                           $0020  Host Receive Data", "$000A  IRQB                           $0022  Host Transmit Data",
    "$000C  SSI Receive Data               $0024  Host Command (default)", "$000E  SSI Receive with Exception     $003A  Timer1 Interrupt", "$0010  SSI Transmit Data              $003C  Timer0 Interrupt", "$0012  SSI Transmit with Exception    $003E  Illegal Instruction",
    "$0014  SCI Receive Data               ", 0
};

const char *d_4aaf08[20] = { /* 004aaf08 80 */
    "     Interrupt Start Addresses and Interrupt Source", "$0000  Hardware Reset                 $0022  Host Transmit Data", "$0002  Stack Error                    $0024  Host Command (default)", "$0004  Trace                          $0026  Host Command",
    "$0006  SWI                            $0028  Host Command", "$0008  IRQA                           $002A  Host Command ", "$000A  IRQB                           $002C  IRQC", "$000C  SSI Receive Data               $002E  IRQD",
    "$000E  SSI Receive with Exception     $0030  PWMA0 Ready", "$0010  SSI Transmit Data              $0032  PWMA1 Ready", "$0012  SSI Transmit with Exception    $0034  PWMA2 Ready", "$0014  SCI Receive Data               $0036  PWMB0 Ready ",
    "$0016  SCI Receive with Exception     $0038  PWMB1 Ready", "$0018  SCI Transmit Data              $003A  PWM Error", "$001A  SCI Idle Line                  $003C  Timer Interrupt", "$001C  SCI Timer                      $003E  Illegal Instruction",
    "$001E  NMI                            $0040..$007E Host Command", "$0020  Host Receive Data", 0, 0
};

const char *d_4aaf58[26] = { /* 004aaf58 104 */
    "     Interrupt Start Addresses and Interrupt Source", "$0000  Hardware Reset                 $0030 HOST Receive Data", "$0002  Stack Error                    $0032 HOST Transmit Data", "$0004  Trace                          $0034 HOST Command (default)",
    "$0006  SWI                            $0036 Reserved", "$0008  IRQA                           $003E ILLEGAL Instruction", "$000A  IRQB                           $0040 SAI Left Ch Tx TXIL=1", "$000C  Reserved                       $0042 SAI Right Ch Tx TXIL=1",
    "$000E  Reserved                       $0044 SAI Tx Exception TXIL=1", "$0010  SAI Left Ch Tx TXIL=0          $0046 SAI Left Ch Rx TXIL=1", "$0012  SAI Right Ch Tx TXIL=0         $0048 SAI Right Ch Rx TXIL=1", "$0014  SAI Tx Exception TXIL=0        $004A SAI Rx Exception TXIL=1",
    "$0016  SAI Left Ch Rx TXIL=0          $0050 DAX Tx Underrun Error", "$0018  SAI Right Ch Rx TXIL=0         $0052 DAX Block Transferred", "$001A  SAI Rx Exception TXIL=0        $0056 DAX Tx Register Empty", "$001C  Reserved",
    "$001E  NMI", "$0020  SHI Transmit Data", "$0022  SHI Transmit Underrun", "$0024  SHI Rec FIFO not empty",
    "$0028  SHI Rec FIFO full", "$002A  SHI Rec Overrun Error", "$002C  SHI Bus Error", "$002E  Reserved",
    0, 0
};

const char *d_4aafc0[12] = { /* 004aafc0 48 */
    "  Mode   MC MB MA     Initial Chip Operating Mode", "+------+----------+-----------------------------------------------+", "   0      0  0  0     PRAM enabled, reset @ $0000", "   1      0  0  1     Bootstrap from EPROM",
    "   2      0  1  0     PRAM enabled, reset @ $E000", "   3      0  1  1     PRAM disabled, reset @ $0000", "   4      1  0  0     Reserved for bootstrap", "   5      1  0  1     Bootstrap from Host",
    "   6      1  1  0     Bootstrap from SCI (ext. clock)", "   7      1  1  1     Reserved for bootstrap", 0, 0
};

const char *d_4aaff0[16] = { /* 004aaff0 64 */
    "  MMMM   Address Calculation Arithmetic", "+------+-------------------------------------+", "  0000   Reverse Carry (Bit Reversed Update)", "  0001   Modulo      2  ",
    "  0002   Modulo      3  ", "     .         .         .", "     n   Modulo     n+1 ", "     .         .         .",
    "  7FFF   Modulo   32,768", "  8000   Reserved", "  8001   Multiple Wrap-Around Modulo   2 ", "     .   Reserved",
    "  8000+(2**n)-1   Multiple Wrap-Around Modulo 2**n", "     .   Reserved", "  FFFF   Linear   (Modulo 65536)", 0
};

const char *d_4ab030[12] = { /* 004ab030 48 */
    "  Mode   MC MB MA     Initial Chip Operating Mode", "+------+----------+-----------------------------------------------+", "   0      0  0  0     Single-Chip Nonexpanded", "   1      0  0  1     Bootstrap Mode (56001 or 56002 only)",
    "   2      0  1  0     Normal Expanded", "   3      0  1  1     Development Expanded", "   4      1  0  0     Bootstrap From Host (56002 only)", "   5      1  0  1     reserved",
    "   6      1  1  0     Bootstrap From SCI (56002 only)", "   7      1  1  1     reserved", 0, 0
};

const char *d_4ab060[12] = { /* 004ab060 48 */
    "  Mode   MC MB MA     Initial Chip Operating Mode", "+------+----------+-----------------------------------------------+", "   0      0  0  0     Bootstrap ROM disabled, PRAM enabled", "   1      0  0  1     Bootstrap ROM enabled, boot through emi",
    "   2      0  1  0     Reserved for bootstrap, default mode 1", "   3      0  1  1     Reserved, default mode 1", "   4      1  0  0     Reserved for bootstrap, default mode 5", "   5      1  0  1     Bootstrap ROM enabled, boot from SHI in SPI slave mode",
    "   6      1  1  0     Reserved for bootstrap, default mode 7", "   7      1  1  1     Bootstrap ROM enabled, boot from SHI in I2C slave mode", 0, 0
};

const char *d_4ab090[12] = { /* 004ab090 48 */
    "  Mode   MC MB MA     Initial Chip Operating Mode", "+------+----------+-----------------------------------------------+", "   0      0  0  0     Bootstrap ROM disabled, start at P:0", "   1      0  0  1     Bootstrap ROM enabled, boot through emi",
    "   2      0  1  0     Bootstrap ROM enabled, jumps to P:$400", "   3      0  1  1     Reserved, default mode 1", "   4      1  0  0     Reserved for bootstrap, default mode 2", "   5      1  0  1     Bootstrap ROM enabled, boot from SHI in SPI slave mode",
    "   6      1  1  0     Reserved for bootstrap, default mode 2", "   7      1  1  1     Bootstrap ROM enabled, boot from SHI in I2C slave mode", 0, 0
};

const char *d_4ab0c0[12] = { /* 004ab0c0 48 */
    "  Mode   MC MB MA     Initial Chip Operating Mode", "+------+----------+-----------------------------------------------+", "   0      0  0  0     Bootstrap ROM disabled, PRAM enabled", "   1      0  0  1     Bootstrap ROM enabled, boot through emi",
    "   2      0  1  0     Wake up in PROM address", "   3      0  1  1     Reserved, default mode 1", "   4      1  0  0     Reserved for bootstrap, default mode 5", "   5      1  0  1     Bootstrap ROM enabled, boot from SHI in SPI slave mode",
    "   6      1  1  0     Reserved for bootstrap, default mode 7", "   7      1  1  1     Bootstrap ROM enabled, boot from SHI in I2C slave mode", 0, 0
};

const char *d_4ab0f0[12] = { /* 004ab0f0 48 */
    "  Mode   MC MB MA     Initial Chip Operating Mode", "+------+----------+-----------------------------------------------+", "   0      0  0  0     Bootstrap ROM disabled, PRAM enabled", "   1      0  0  1     Bootstrap ROM enabled, boot through host port",
    "   2      0  1  0     Wake up in PROM address", "   3      0  1  1     Reserved, default mode 1", "   4      1  0  0     Reserved for bootstrap, default mode 5", "   5      1  0  1     Bootstrap ROM enabled, boot from SHI in SPI slave mode",
    "   6      1  1  0     Reserved for bootstrap, default mode 7", "   7      1  1  1     Bootstrap ROM enabled, boot from SHI in I2C slave mode", 0, 0
};

const char *d_4ab120[12] = { /* 004ab120 48 */
    "  MMMM   Address Calculation Arithmetic", "+------+-------------------------------------+", "  0000   Reverse Carry (Bit Reversed Update)", "  0001   Modulo      2  ",
    "  0002   Modulo      3  ", "     .         .         .", "     n   Modulo     n+1 ", "     .         .         .",
    "  7FFF   Modulo   32,768", "     .   Reserved    .", "  FFFF   Linear   (Modulo 65536)", 0
};

const char *d_4ab150[20] = { /* 004ab150 80 */
    "int", (const char *)&d_4aadd0, "list of interrupt vector addresses", 0,
    0, "mod", (const char *)&d_4ab120, "summary of address alu modifier modes",
    0, 0, "mode", (const char *)&d_4ab030,
    "initial chip operating mode summary", 0, 0, "port",
    (const char *)&d_4aadb8, "list of port names with index and mask", 0, 0
};

const char *d_4ab1a0[20] = { /* 004ab1a0 80 */
    "int", (const char *)&d_4aae08, "list of interrupt vector addresses", 0,
    0, "mod", (const char *)&d_4ab120, "summary of address alu modifier modes",
    0, 0, "mode", (const char *)&d_4ab030,
    "initial chip operating mode summary", 0, 0, "port",
    (const char *)&d_4aadb8, "list of port names with index and mask", 0, 0
};

const char *d_4ab1f0[20] = { /* 004ab1f0 80 */
    "int", (const char *)&d_4aae40, "list of interrupt vector addresses", 0,
    0, "mod", (const char *)&d_4ab120, "summary of address alu modifier modes",
    0, 0, "mode", (const char *)&d_4ab060,
    "initial chip operating mode summary", 0, 0, "port",
    (const char *)&d_4aadb8, "list of port names with index and mask", 0, 0
};

const char *d_4ab240[20] = { /* 004ab240 80 */
    "int", (const char *)&d_4aae40, "list of interrupt vector addresses", 0,
    0, "mod", (const char *)&d_4ab120, "summary of address alu modifier modes",
    0, 0, "mode", (const char *)&d_4ab090,
    "initial chip operating mode summary", 0, 0, "port",
    (const char *)&d_4aadb8, "list of port names with index and mask", 0, 0
};

const char *d_4ab290[20] = { /* 004ab290 80 */
    "int", (const char *)&d_4aae80, "list of interrupt vector addresses", 0,
    0, "mod", (const char *)&d_4ab120, "summary of address alu modifier modes",
    0, 0, "mode", (const char *)&d_4ab0c0,
    "initial chip operating mode summary", 0, 0, "port",
    (const char *)&d_4aadb8, "list of port names with index and mask", 0, 0
};

const char *d_4ab2e0[20] = { /* 004ab2e0 80 */
    "int", (const char *)&d_4aaf58, "list of interrupt vector addresses", 0,
    0, "mod", (const char *)&d_4ab120, "summary of address alu modifier modes",
    0, 0, "mode", (const char *)&d_4ab0f0,
    "initial chip operating mode summary", 0, 0, "port",
    (const char *)&d_4aadb8, "list of port names with index and mask", 0, 0
};

const char *d_4ab330[20] = { /* 004ab330 80 */
    "int", (const char *)&d_4aaf08, "list of interrupt vector addresses", 0,
    0, "mod", (const char *)&d_4aaff0, "summary of address alu modifier modes",
    0, 0, "mode", (const char *)&d_4aafc0,
    "initial chip operating mode summary", 0, 0, "port",
    (const char *)&d_4aadb8, "list of port names with index and mask", 0, 0
};

const char *d_4ab380[20] = { /* 004ab380 80 */
    "int", (const char *)&d_4aadd0, "list of interrupt vector addresses", 0,
    0, "mod", (const char *)&d_4ab120, "summary of address alu modifier modes",
    0, 0, "mode", (const char *)&d_4ab030,
    "initial chip operating mode summary", 0, 0, "port",
    (const char *)&d_4aadb8, "list of port names with index and mask", 0, 0
};

const char *d_4ab3d0[20] = { /* 004ab3d0 80 */
    "int", (const char *)&d_4aaed0, "list of interrupt vector addresses", 0,
    0, "mod", (const char *)&d_4ab120, "summary of address alu modifier modes",
    0, 0, "mode", (const char *)&d_4ab030,
    "initial chip operating mode summary", 0, 0, "port",
    (const char *)&d_4aadb8, "list of port names with index and mask", 0, 0
};

struct rec2w_bfa51 d_4ab420[1] = { /* 004ab420 8 */
    { 4, (void *)&d_4ab150 }
};

struct rec2w_bfa51 d_4ab428[1] = { /* 004ab428 8 */
    { 4, (void *)&d_4ab1a0 }
};

struct rec2w_bfa51 d_4ab430[1] = { /* 004ab430 8 */
    { 4, (void *)&d_4ab1f0 }
};

struct rec2w_bfa51 d_4ab438[1] = { /* 004ab438 8 */
    { 4, (void *)&d_4ab240 }
};

struct rec2w_bfa51 d_4ab440[1] = { /* 004ab440 8 */
    { 4, (void *)&d_4ab290 }
};

struct rec2w_bfa51 d_4ab448[1] = { /* 004ab448 8 */
    { 4, (void *)&d_4ab330 }
};

struct rec2w_bfa51 d_4ab450[1] = { /* 004ab450 8 */
    { 4, (void *)&d_4ab380 }
};

struct rec2w_bfa51 d_4ab458[1] = { /* 004ab458 8 */
    { 4, (void *)&d_4ab3d0 }
};

struct rec2w_bfa51 d_4ab460[1] = { /* 004ab460 8 */
    { 4, (void *)&d_4ab2e0 }
};

const char *d_4ad310[10] = { /* 004ad310 40 */
    "Multiplication", "Arithmetic/Logic", "Bit manipulation", "Bit field & Multi-bit shift",
    "Bit control", "Control", "Loop", "Move source",
    "Move target", 0
};

const char *d_4ad338[10] = { /* 004ad338 40 */
    "(mac,mpy,macr,mpyr)", "(add,sub,and,or,eor,cmp)", "(bset,bclr,btst,bchg)", "(asl,asr)",
    "(jclr,jset,jsclr,jsset)", "(jmp,jsr,jcc,jscc)", "(do)", (const char *)&empty_str,
    (const char *)&empty_str, 0
};

unsigned short d_4ad362[31] = { /* 004ad362 62 */
    0, 102, 0, 54032, 74, 54072, 74, 4416, 64, 4688, 64, 4704, 64, 4992, 64, 5888,
    64, 6240, 64, 6320, 64, 6416, 64, 6512, 64, 6672, 64, 6544, 64, 50320, 65
};

long d_4ad738[42] = { /* 004ad738 168 */
    0, 17, 6, 1, 17, 6, 2, 17,
    6, 8, 17, 6, -2, 0, 0, 4,
    17, 6, 5, 17, 6, 6, 17, 6,
    9, 17, 6, -2, 0, 0, 10, 17,
    6, 3, 17, 6, 7, 17, 6, -2,
    0, 0
};

const char *d_4ad7e0[44] = { /* 004ad7e0 176 */
    "When assigned to a DSP56004 EMI peripheral, the input file data", "value represents the byte or nibble associated with a single memory", "reference.  Note that in most cases multiple memory references are", "required in order to build a full word for transfer to one of the",
    "EMI data read registers.", (const char *)&empty_str, "A timed input data value with an absolute time value becomes", "available at the cycle count specified in the time value.  A timed",
    "input data value specified with a relative time (+time) becomes", "available at the specified number of transfers since the previous", "word; for example, a relative time count of +2 means that the", "associated data value becomes available for the second transfer",
    "after the preceding word.", (const char *)&empty_str, "If a lower case letter t is placed in a data position of the input", "file, the user will be prompted for the next input data value.",
    (const char *)&empty_str, "Storage of data to an EMI output file occurs each time transmit data", "is transfered to the output shift register, at the start of the", "transmission.  In the timed output mode, the simulator cycle count",
    "and a data value are stored each time a word begins transmission.", "In the untimed output mode, a single data value is stored each time", "a word begins transmission.  The value stored is shifted according", "to the word size selected by the EMI control register.",
    (const char *)&empty_str, "EXAMPLES", (const char *)&empty_str, "The following untimed input file will cause the data sequence",
    "7F 3F 5D C3 to appear on the EMI data bus during consecutive byte", "transfers.", (const char *)&empty_str, "7F 3F 5D C3",
    (const char *)&empty_str, "The following untimed input file will cause the data sequence 1F 01", "to appear repeatedly on consecutive byte reads by the EMI", (const char *)&empty_str,
    "(1F 01)", (const char *)&empty_str, "The following timed input file will cause the byte values 15 and 33", "to be read alternately each 10 transfers.",
    (const char *)&empty_str, "(+10 15 +10 33)", 0, 0
};

const char *d_4ad890[6] = { /* 004ad890 24 */
    "emi", (const char *)&d_4ad7e0, "I/O file format for emi peripheral", 0,
    0, 0
};

struct rec2w_bfa51 d_4ad8a8[1] = { /* 004ad8a8 8 */
    { 1, (void *)&d_4ad890 }
};

struct rec2w_bfa51 d_4ad8b0[3] = { /* 004ad8b0 24 */
    { 14, (void *)&d_4ad738 },
    { 0, 0 },
    { 0, (void *)&d_4ad8a8 }
};

const char *d_4ad8c8[2] = { /* 004ad8c8 8 */
    "Base Address Register", 0
};

const char *d_4ad8d0[8] = { /* 004ad8d0 32 */
    "Control/Status Register", "   E E E E", "   S S S S E E   E E E E   E E E E   E E E E E", " E T T T T D R   B B D D   I I I I   A A A W W E",
    " M M M M M T T   S D R W   S S N N   M M M L L B", " E 3 2 1 0 M S   Y F F E   1 0 W R   2 1 0 1 0 W", 0, 0
};

const char *d_4ad8f0[2] = { /* 004ad8f0 8 */
    "Offset Register", 0
};

const char *d_4ad8f8[2] = { /* 004ad8f8 8 */
    "Write Offset Register", 0
};

const char *d_4ad900[2] = { /* 004ad900 8 */
    "Data Write Register", 0
};

const char *d_4ad908[6] = { /* 004ad908 24 */
    "Refresh Control Register", " E E   E E E                     E E E E E E E E", " R R   O P P                     C C C C C C C C", " E E   S S S                     D D D D D D D D",
    " F D   R 1 0                     7 6 5 4 3 2 1 0", 0
};

const char *d_4ad920[2] = { /* 004ad920 8 */
    "Data Read Register", 0
};

struct reg_desc regs_4ad928[11] = { /* 004ad928 312 */
    { "ebar0", 0xffffffUL, 0, 0x4000UL, 0x4001061UL, (void *)&d_4ad8c8, 0 },
    { "eor0", 0xffffffUL, 1, 0x4000UL, 0x4001061UL, (void *)&d_4ad8f0, 1 },
    { "edrr0", 0xffffffUL, 2, 0x4000UL, 0x4000021UL, (void *)&d_4ad920, 2 },
    { "ecsr", 0xfef7bfUL, 3, 0x4000UL, 0x4001061UL, (void *)&d_4ad8d0, 3 },
    { "ebar1", 0xffffffUL, 4, 0x4000UL, 0x4001061UL, (void *)&d_4ad8c8, 4 },
    { "eor1", 0xffffffUL, 5, 0x4000UL, 0x4001061UL, (void *)&d_4ad8f0, 5 },
    { "edrr1", 0xffffffUL, 6, 0x4000UL, 0x4001021UL, (void *)&d_4ad920, 6 },
    { "ercr", 0xdc00ffUL, 7, 0x4000UL, 0x4001061UL, (void *)&d_4ad908, 7 },
    { "edwr0", 0xffffffUL, 2, 0x4000UL, 0x4001041UL, (void *)&d_4ad900, 8 },
    { "edwr1", 0xffffffUL, 6, 0x4000UL, 0x4001041UL, (void *)&d_4ad900, 9 },
    { "ewor", 0xffffffUL, 14, 0x4000UL, 0x4001061UL, (void *)&d_4ad8f8, 10 }
};
struct flat_4ada5c regs_4ad928_tail = { /* 004ada5c tail of regs_4ad928 */
    0
};

struct group_def grpdef_4ada60[1] = { /* 004ada60 64 */
    { periph_read_reg, emi1_m_poke, emi1_m_io_read, emi1_m_io_write, emi1_m_clock, emi1_m_reset, emi1_m_irq_poll, emi1_m_irq_ack, 36, 40, 11, (struct reg_desc *)&regs_4ad928, { 0 } }
};

long emi1_timing_tab_a[8] = { /* 004adaa0 32 */
    2, 1, 4, 2, 6, 3, 4, 2
};

long emi1_timing_tab_b[8] = { /* 004adac0 32 */
    0, 0, 0, 0, 2, 1, 4, 2
};

long emi1_timing_tab_c[4] = { /* 004adae0 16 */
    16, 8, 0, 8
};

unsigned short d_4ae482[395] = { /* 004ae482 790 */
    0, 24, 0, 3, 0, 45, 0, 24, 0, 2, 0, 65534, 65535, 0, 0, 0,
    0, 0, 0, 24, 0, 3, 0, 4, 0, 24, 0, 2, 0, 65534, 65535, 0,
    0, 0, 0, 65535, 65535, 10, 0, 0, 0, 44, 0, 14, 0, 3, 0, 43,
    0, 16, 0, 5, 0, 37, 0, 13, 0, 5, 0, 27, 0, 13, 0, 5,
    0, 19, 0, 13, 0, 5, 0, 65534, 65535, 0, 0, 0, 0, 65535, 65535, 10,
    0, 0, 0, 47, 0, 14, 0, 3, 0, 46, 0, 16, 0, 5, 0, 36,
    0, 13, 0, 5, 0, 26, 0, 13, 0, 5, 0, 18, 0, 13, 0, 5,
    0, 65534, 65535, 0, 0, 0, 0, 3, 0, 10, 0, 3, 0, 2, 0, 14,
    0, 3, 0, 1, 0, 16, 0, 5, 0, 35, 0, 13, 0, 5, 0, 25,
    0, 13, 0, 5, 0, 17, 0, 13, 0, 5, 0, 65534, 65535, 0, 0, 0,
    0, 7, 0, 10, 0, 3, 0, 6, 0, 14, 0, 3, 0, 5, 0, 16,
    0, 5, 0, 34, 0, 13, 0, 5, 0, 24, 0, 13, 0, 5, 0, 16,
    0, 13, 0, 5, 0, 65534, 65535, 0, 0, 0, 0, 65535, 65535, 10, 0, 0,
    0, 65535, 65535, 14, 0, 0, 0, 65535, 65535, 16, 0, 0, 0, 33, 0, 13,
    0, 5, 0, 23, 0, 13, 0, 5, 0, 15, 0, 13, 0, 5, 0, 65534,
    65535, 0, 0, 0, 0, 29, 0, 10, 0, 3, 0, 39, 0, 14, 0, 6,
    0, 28, 0, 16, 0, 5, 0, 32, 0, 13, 0, 5, 0, 22, 0, 13,
    0, 5, 0, 14, 0, 13, 0, 5, 0, 65534, 65535, 0, 0, 0, 0, 10,
    0, 10, 0, 3, 0, 11, 0, 14, 0, 6, 0, 65535, 65535, 16, 0, 0,
    0, 31, 0, 13, 0, 5, 0, 21, 0, 13, 0, 5, 0, 13, 0, 13,
    0, 5, 0, 65534, 65535, 0, 0, 0, 0, 40, 0, 10, 0, 3, 0, 41,
    0, 14, 0, 6, 0, 38, 0, 16, 0, 5, 0, 30, 0, 13, 0, 5,
    0, 20, 0, 13, 0, 5, 0, 12, 0, 13, 0, 5, 0, 65534, 65535, 0,
    0, 0, 0, 9, 0, 12, 0, 3, 0, 8, 0, 14, 0, 6, 0, 49,
    0, 15, 0, 6, 0, 65534, 65535, 0, 0, 0, 0
};

unsigned short d_4ae79a[431] = { /* 004ae79a 862 */
    0, 24, 0, 3, 0, 45, 0, 24, 0, 2, 0, 65534, 65535, 0, 0, 0,
    0, 0, 0, 24, 0, 3, 0, 4, 0, 24, 0, 2, 0, 65534, 65535, 0,
    0, 0, 0, 65535, 65535, 10, 0, 0, 0, 44, 0, 14, 0, 3, 0, 43,
    0, 16, 0, 5, 0, 37, 0, 13, 0, 5, 0, 27, 0, 13, 0, 5,
    0, 19, 0, 13, 0, 5, 0, 65534, 65535, 0, 0, 0, 0, 65535, 65535, 10,
    0, 0, 0, 47, 0, 14, 0, 3, 0, 46, 0, 16, 0, 5, 0, 36,
    0, 13, 0, 5, 0, 26, 0, 13, 0, 5, 0, 18, 0, 13, 0, 5,
    0, 65534, 65535, 0, 0, 0, 0, 3, 0, 10, 0, 3, 0, 2, 0, 14,
    0, 3, 0, 1, 0, 16, 0, 5, 0, 35, 0, 13, 0, 5, 0, 25,
    0, 13, 0, 5, 0, 17, 0, 13, 0, 5, 0, 65534, 65535, 0, 0, 0,
    0, 7, 0, 10, 0, 3, 0, 6, 0, 14, 0, 3, 0, 5, 0, 16,
    0, 5, 0, 34, 0, 13, 0, 5, 0, 24, 0, 13, 0, 5, 0, 16,
    0, 13, 0, 5, 0, 65534, 65535, 0, 0, 0, 0, 65535, 65535, 10, 0, 0,
    0, 65535, 65535, 14, 0, 0, 0, 65535, 65535, 16, 0, 0, 0, 33, 0, 13,
    0, 5, 0, 23, 0, 13, 0, 5, 0, 15, 0, 13, 0, 5, 0, 65534,
    65535, 0, 0, 0, 0, 29, 0, 10, 0, 3, 0, 39, 0, 14, 0, 6,
    0, 28, 0, 16, 0, 5, 0, 32, 0, 13, 0, 5, 0, 22, 0, 13,
    0, 5, 0, 14, 0, 13, 0, 5, 0, 65534, 65535, 0, 0, 0, 0, 10,
    0, 10, 0, 3, 0, 11, 0, 14, 0, 6, 0, 65535, 65535, 16, 0, 0,
    0, 31, 0, 13, 0, 5, 0, 21, 0, 13, 0, 5, 0, 13, 0, 13,
    0, 5, 0, 65534, 65535, 0, 0, 0, 0, 40, 0, 10, 0, 3, 0, 41,
    0, 14, 0, 6, 0, 38, 0, 16, 0, 5, 0, 30, 0, 13, 0, 5,
    0, 20, 0, 13, 0, 5, 0, 12, 0, 13, 0, 5, 0, 65534, 65535, 0,
    0, 0, 0, 9, 0, 10, 0, 3, 0, 8, 0, 14, 0, 6, 0, 49,
    0, 16, 0, 5, 0, 65534, 65535, 0, 0, 0, 0, 52, 0, 10, 0, 4,
    0, 53, 0, 14, 0, 6, 0, 54, 0, 16, 0, 6, 0, 50, 0, 14,
    0, 8, 0, 51, 0, 14, 0, 8, 0, 65534, 65535, 0, 0, 0, 0
};

unsigned short d_4aeafa[11] = { /* 004aeafa 22 */
    0, 59288, 74, 0, 0, 0, 0, 0, 0, 0, 0
};

unsigned short d_4aeb12[391] = { /* 004aeb12 782 */
    0, 24, 0, 3, 0, 45, 0, 24, 0, 2, 0, 65534, 65535, 0, 0, 0,
    0, 0, 0, 24, 0, 3, 0, 4, 0, 24, 0, 2, 0, 65534, 65535, 0,
    0, 0, 0, 65535, 65535, 10, 0, 0, 0, 44, 0, 14, 0, 3, 0, 43,
    0, 16, 0, 5, 0, 37, 0, 13, 0, 5, 0, 27, 0, 13, 0, 5,
    0, 19, 0, 13, 0, 5, 0, 65534, 65535, 0, 0, 0, 0, 65535, 65535, 10,
    0, 0, 0, 47, 0, 14, 0, 3, 0, 46, 0, 16, 0, 5, 0, 36,
    0, 13, 0, 5, 0, 26, 0, 13, 0, 5, 0, 18, 0, 13, 0, 5,
    0, 65534, 65535, 0, 0, 0, 0, 3, 0, 10, 0, 3, 0, 2, 0, 14,
    0, 3, 0, 1, 0, 16, 0, 5, 0, 35, 0, 13, 0, 5, 0, 25,
    0, 13, 0, 5, 0, 17, 0, 13, 0, 5, 0, 65534, 65535, 0, 0, 0,
    0, 7, 0, 10, 0, 3, 0, 6, 0, 14, 0, 3, 0, 5, 0, 16,
    0, 5, 0, 34, 0, 13, 0, 5, 0, 24, 0, 13, 0, 5, 0, 16,
    0, 13, 0, 5, 0, 65534, 65535, 0, 0, 0, 0, 65535, 65535, 10, 0, 0,
    0, 65535, 65535, 14, 0, 0, 0, 65535, 65535, 16, 0, 0, 0, 33, 0, 13,
    0, 5, 0, 23, 0, 13, 0, 5, 0, 15, 0, 13, 0, 5, 0, 65534,
    65535, 0, 0, 0, 0, 29, 0, 10, 0, 3, 0, 39, 0, 14, 0, 6,
    0, 28, 0, 16, 0, 5, 0, 32, 0, 13, 0, 5, 0, 22, 0, 13,
    0, 5, 0, 14, 0, 13, 0, 5, 0, 65534, 65535, 0, 0, 0, 0, 10,
    0, 10, 0, 3, 0, 11, 0, 14, 0, 6, 0, 65535, 65535, 16, 0, 0,
    0, 31, 0, 13, 0, 5, 0, 21, 0, 13, 0, 5, 0, 13, 0, 13,
    0, 5, 0, 65534, 65535, 0, 0, 0, 0, 40, 0, 10, 0, 3, 0, 41,
    0, 14, 0, 6, 0, 38, 0, 16, 0, 5, 0, 30, 0, 13, 0, 5,
    0, 20, 0, 13, 0, 5, 0, 12, 0, 13, 0, 5, 0, 65534, 65535, 0,
    0, 0, 0, 9, 0, 10, 0, 3, 0, 8, 0, 14, 0, 6, 0, 65534,
    65535, 0, 0, 0, 0, 0, 0
};

unsigned short d_4aee22[395] = { /* 004aee22 790 */
    0, 24, 0, 3, 0, 45, 0, 24, 0, 2, 0, 65534, 65535, 0, 0, 0,
    0, 0, 0, 24, 0, 3, 0, 4, 0, 24, 0, 2, 0, 65534, 65535, 0,
    0, 0, 0, 65535, 65535, 10, 0, 0, 0, 44, 0, 14, 0, 3, 0, 43,
    0, 16, 0, 5, 0, 37, 0, 13, 0, 5, 0, 27, 0, 13, 0, 5,
    0, 19, 0, 13, 0, 5, 0, 65534, 65535, 0, 0, 0, 0, 65535, 65535, 10,
    0, 0, 0, 47, 0, 14, 0, 3, 0, 46, 0, 16, 0, 5, 0, 36,
    0, 13, 0, 5, 0, 26, 0, 13, 0, 5, 0, 18, 0, 13, 0, 5,
    0, 65534, 65535, 0, 0, 0, 0, 3, 0, 10, 0, 3, 0, 2, 0, 14,
    0, 3, 0, 1, 0, 16, 0, 5, 0, 35, 0, 13, 0, 5, 0, 25,
    0, 13, 0, 5, 0, 17, 0, 13, 0, 5, 0, 65534, 65535, 0, 0, 0,
    0, 7, 0, 10, 0, 3, 0, 6, 0, 14, 0, 3, 0, 5, 0, 16,
    0, 5, 0, 34, 0, 13, 0, 5, 0, 24, 0, 13, 0, 5, 0, 16,
    0, 13, 0, 5, 0, 65534, 65535, 0, 0, 0, 0, 65535, 65535, 10, 0, 0,
    0, 65535, 65535, 14, 0, 0, 0, 65535, 65535, 16, 0, 0, 0, 33, 0, 13,
    0, 5, 0, 23, 0, 13, 0, 5, 0, 15, 0, 13, 0, 5, 0, 65534,
    65535, 0, 0, 0, 0, 29, 0, 10, 0, 3, 0, 39, 0, 14, 0, 6,
    0, 28, 0, 16, 0, 5, 0, 32, 0, 13, 0, 5, 0, 22, 0, 13,
    0, 5, 0, 14, 0, 13, 0, 5, 0, 65534, 65535, 0, 0, 0, 0, 10,
    0, 10, 0, 3, 0, 11, 0, 14, 0, 6, 0, 65535, 65535, 16, 0, 0,
    0, 31, 0, 13, 0, 5, 0, 21, 0, 13, 0, 5, 0, 13, 0, 13,
    0, 5, 0, 65534, 65535, 0, 0, 0, 0, 40, 0, 10, 0, 3, 0, 41,
    0, 14, 0, 6, 0, 38, 0, 16, 0, 5, 0, 30, 0, 13, 0, 5,
    0, 20, 0, 13, 0, 5, 0, 12, 0, 13, 0, 5, 0, 65534, 65535, 0,
    0, 0, 0, 9, 0, 10, 0, 3, 0, 8, 0, 14, 0, 6, 0, 49,
    0, 16, 0, 5, 0, 65534, 65535, 0, 0, 0, 0
};

unsigned short d_4af13a[11] = { /* 004af13a 22 */
    0, 58496, 74, 0, 0, 0, 0, 0, 0, 0, 0
};

unsigned short d_4af152[11] = { /* 004af152 22 */
    0, 60176, 74, 0, 0, 0, 0, 0, 0, 0, 0
};

unsigned short d_4af16a[11] = { /* 004af16a 22 */
    0, 60960, 74, 0, 0, 0, 0, 0, 0, 0, 0
};

const char *d_4af180[2] = { /* 004af180 8 */
    "Data Alu Accumulator Register", 0
};

const char *d_4af188[2] = { /* 004af188 8 */
    "Data Alu Register", 0
};

const char *d_4af190[2] = { /* 004af190 8 */
    "Address Alu Address Register", 0
};

const char *d_4af198[2] = { /* 004af198 8 */
    "Address Alu Offset Register", 0
};

const char *d_4af1a0[2] = { /* 004af1a0 8 */
    "Address Alu Modulo Register", 0
};

const char *d_4af1a8[2] = { /* 004af1a8 8 */
    "Program Controller Loop Address Register", 0
};

const char *d_4af1b0[2] = { /* 004af1b0 8 */
    "Program Controller Loop Count Register", 0
};

const char *d_4af1b8[4] = { /* 004af1b8 16 */
    "Port A Bus Control Register", " { X mem }|{ Y mem }|{ P mem }|{ Y I/O }", 0, 0
};

const char *d_4af1c8[6] = { /* 004af1c8 24 */
    "Interrupt Priority Register.", " {S S S S H H}         {I I I I I I}", " {C C S S P P}         {B B B A A A}", " {L L L L L L}         {L L L L L L}",
    " {1 0 1 0 1 0} * * * * {2 1 0 2 1 0}", 0
};

const char *d_4af1e0[6] = { /* 004af1e0 24 */
    "Interrupt Priority Register.", "             {T T S S S S H H}         {I I I I I I}", "             {I I C C S S P P}         {B B B A A A}", "             {L L L L L L L L}         {L L L L L L}",
    "             {1 0 1 0 1 0 1 0} * * * * {2 1 0 2 1 0}", 0
};

const char *d_4af1f8[6] = { /* 004af1f8 24 */
    "Interrupt Priority Register.", "         {T T T T S S S S H H}         {I I I I I I}", "         {B B A A C C S S P P}         {B B B A A A}", "         {L L L L L L L L L L}         {L L L L L L}",
    "         {1 0 1 0 1 0 1 0 1 0} * * * * {2 1 0 2 1 0}", 0
};

const char *d_4af210[6] = { /* 004af210 24 */
    "Interrupt Priority Register.", " {E E S S S S}         {I I I I I I}", " {M M H H A A}         {B B B A A A}", " {L L L L L L}         {L L L L L L}",
    " {1 0 1 0 1 0} * * * * {2 1 0 2 1 0}", 0
};

const char *d_4af228[6] = { /* 004af228 24 */
    "Interrupt Priority Register.", "             {D D E E S S S S}         {I I I I I I}", "             {T T M M H H A A}         {B B B A A A}", "             {L L L L L L L L}         {L L L L L L}",
    "             {1 0 1 0 1 0 1 0} * * * * {2 1 0 2 1 0}", 0
};

const char *d_4af240[6] = { /* 004af240 24 */
    "Interrupt Priority Register.", "         {P P T T S S S S H H I I I I I I I I I I}", "         {W W I I C C S S P P D D C C B B B A A A}", "         {L L L L L L L L L L L L L L L L L L L L}",
    "         {1 0 1 0 1 0 1 0 1 0 1 0 1 0 2 1 0 2 1 0}", 0
};

const char *d_4af258[2] = { /* 004af258 8 */
    "PLL Control Register.", 0
};

const char *d_4af260[2] = { /* 004af260 8 */
    "Program Controller Program Counter Register", 0
};

const char *d_4af268[4] = { /* 004af268 16 */
    "Program Controller Operating Mode Register", "   {S}   {M Y D M M}", " * {D} * {C D E B A}", 0
};

const char *d_4af278[4] = { /* 004af278 16 */
    "Program Controller Operating Mode Register", "   S   M     M M", " * D * C * * B A", 0
};

const char *d_4af288[4] = { /* 004af288 16 */
    "Program Controller Operating Mode Register", "   S   M   P M M", " * D * C * E B A", 0
};

const char *d_4af298[6] = { /* 004af298 24 */
    "Program Controller Operating Mode Register", "         P P    ", "   S   M E E M M", " * D * C B A B A",
    0, 0
};

const char *d_4af2b0[4] = { /* 004af2b0 16 */
    "Program Controller Operating Mode Register", " {M E}       {D M M}", " {R C} * * * {E B A}", 0
};

const char *d_4af2c0[2] = { /* 004af2c0 8 */
    "Program Controller Stack Pointer Register", 0
};

const char *d_4af2c8[6] = { /* 004af2c8 24 */
    "Program Controller Status Register", " {      MR       }|{    CCR        }", " {L D}     {S S I I}", " {F M T} * {1 0 1 0 S L E U N Z V C}",
    0, 0
};

const char *d_4af2e0[6] = { /* 004af2e0 24 */
    "Program Controller Status Register", " {      MR       }|{    CCR        }", " {L}       {S S I I}", " {F} * {T} * {1 0 1 0} * {L E U N Z V C}",
    0, 0
};

const char *d_4af2f8[2] = { /* 004af2f8 8 */
    "Program Controller System Stack High", 0
};

const char *d_4af300[2] = { /* 004af300 8 */
    "Program Controller System Stack Low", 0
};

const char *d_4af308[2] = { /* 004af308 8 */
    "Once GDB Register - unimplemented", 0
};

const char *d_4af310[2] = { /* 004af310 8 */
    "PLL Control - unimplemented", 0
};

const char *d_4af318[8] = { /* 004af318 32 */
    "Address Compare Register.", "       C C C C", "       B B B B       M M M M M", "       A A A A R     X A A A A",
    "       1 1 1 1 D B   / 1 1 1 1 E", " * * * 5 4 3 2 Y R * Y 5 4 3 2 N", 0, 0
};

const char *d_4af338[6] = { /* 004af338 24 */
    "Base Address Register.", " B B B B B B B B", " A A A A A A A A         F F F", " 2 2 2 2 1 1 1 1         C C C",
    " 3 2 1 0 9 8 7 6 * * * * 2 1 0 *", 0
};

const char *d_4af350[4] = { /* 004af350 16 */
    "Read (rtime) or write (wtime) memory access cycles.", "16 bit counter value sets the number of cycles", "the DSPACR indicates BUSY during a direct memory access.", 0
};

const char *d_4af360[6] = { /* 004af360 24 */
    "Internal Connections Register.", " S S S S M M M", " E E E E O O O R", " L L L L D D D S",
    " C B A R C B A T", 0
};

struct reg_desc regs_4af378[48] = { /* 004af378 1344 */
    { "a", 0xffffffUL, 0, 0x4010UL, 0x101004UL, (void *)&d_4af180, 0 },
    { "a0", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 1 },
    { "a1", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 2 },
    { "a2", 0xffUL, 0, 0x4010UL, 0x40001001UL, (void *)&d_4af188, 3 },
    { "b", 0xffffffUL, 0, 0x4010UL, 0x101004UL, (void *)&d_4af180, 4 },
    { "b0", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 5 },
    { "b1", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 6 },
    { "b2", 0xffUL, 0, 0x4010UL, 0x40001001UL, (void *)&d_4af188, 7 },
    { "bcr", 0xffffUL, 65534L, 0x204010UL, 0x10001061UL, (void *)&d_4af1b8, 8 },
    { "ipr", 0xfc3fUL, 65535L, 0x204010UL, 0x10001061UL, (void *)&d_4af1c8, 9 },
    { "la", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a8, 10 },
    { "lc", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1b0, 11 },
    { "m0", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 12 },
    { "m1", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 13 },
    { "m2", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 14 },
    { "m3", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 15 },
    { "m4", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 16 },
    { "m5", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 17 },
    { "m6", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 18 },
    { "m7", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 19 },
    { "n0", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 20 },
    { "n1", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 21 },
    { "n2", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 22 },
    { "n3", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 23 },
    { "n4", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 24 },
    { "n5", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 25 },
    { "n6", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 26 },
    { "n7", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 27 },
    { "omr", 0xc7UL, 0, 0x204010UL, 0x40001001UL, (void *)&d_4af2b0, 28 },
    { "pc", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af260, 29 },
    { "r0", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 30 },
    { "r1", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 31 },
    { "r2", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 32 },
    { "r3", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 33 },
    { "r4", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 34 },
    { "r5", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 35 },
    { "r6", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 36 },
    { "r7", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 37 },
    { "sp", 0x3fUL, 0, 0x204010UL, 0x40001001UL, (void *)&d_4af2c0, 38 },
    { "sr", 0xaf7fUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af2e0, 39 },
    { "ssh", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af2f8, 40 },
    { "ssl", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af300, 41 },
    { "x", 0xffffffUL, 0, 0x4010UL, 0x801002UL, (void *)&d_4af188, 42 },
    { "x0", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 43 },
    { "x1", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 44 },
    { "y", 0xffffffUL, 0, 0x4010UL, 0x801002UL, (void *)&d_4af188, 45 },
    { "y0", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 46 },
    { "y1", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 47 }
};

struct reg_desc regs_4af8b8[50] = { /* 004af8b8 1400 */
    { "a", 0xffffffUL, 0, 0x4010UL, 0x101004UL, (void *)&d_4af180, 0 },
    { "a0", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 1 },
    { "a1", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 2 },
    { "a2", 0xffUL, 0, 0x4010UL, 0x40001001UL, (void *)&d_4af188, 3 },
    { "b", 0xffffffUL, 0, 0x4010UL, 0x101004UL, (void *)&d_4af180, 4 },
    { "b0", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 5 },
    { "b1", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 6 },
    { "b2", 0xffUL, 0, 0x4010UL, 0x40001001UL, (void *)&d_4af188, 7 },
    { "bcr", 0xffffUL, 65534L, 0x204010UL, 0x10001061UL, (void *)&d_4af1b8, 8 },
    { "ipr", 0x3fc3fUL, 65535L, 0x204010UL, 0x1061UL, (void *)&d_4af1e0, 9 },
    { "la", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a8, 10 },
    { "lc", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1b0, 11 },
    { "m0", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 12 },
    { "m1", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 13 },
    { "m2", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 14 },
    { "m3", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 15 },
    { "m4", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 16 },
    { "m5", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 17 },
    { "m6", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 18 },
    { "m7", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 19 },
    { "n0", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 20 },
    { "n1", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 21 },
    { "n2", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 22 },
    { "n3", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 23 },
    { "n4", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 24 },
    { "n5", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 25 },
    { "n6", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 26 },
    { "n7", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 27 },
    { "omr", 0x5fUL, 0, 0x205010UL, 0x40000001UL, (void *)&d_4af268, 28 },
    { "pc", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af260, 29 },
    { "r0", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 30 },
    { "r1", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 31 },
    { "r2", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 32 },
    { "r3", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 33 },
    { "r4", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 34 },
    { "r5", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 35 },
    { "r6", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 36 },
    { "r7", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 37 },
    { "sp", 0x3fUL, 0, 0x204010UL, 0x40001001UL, (void *)&d_4af2c0, 38 },
    { "sr", 0xefffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af2c8, 39 },
    { "ssh", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af2f8, 40 },
    { "ssl", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af300, 41 },
    { "x", 0xffffffUL, 0, 0x4010UL, 0x801002UL, (void *)&d_4af188, 42 },
    { "x0", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 43 },
    { "x1", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 44 },
    { "y", 0xffffffUL, 0, 0x4010UL, 0x801002UL, (void *)&d_4af188, 45 },
    { "y0", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 46 },
    { "y1", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 47 },
    { "gdb", 0xffffffUL, 65532L, 0x204000UL, 0x4001071UL, (void *)&d_4af308, 49 },
    { "pctl", 0xffffffUL, 65533L, 0x204010UL, 0x4001061UL, (void *)&d_4af310, 48 }
};

struct reg_desc regs_4afe30[50] = { /* 004afe30 1400 */
    { "a", 0xffffffUL, 0, 0x4010UL, 0x101004UL, (void *)&d_4af180, 0 },
    { "a0", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 1 },
    { "a1", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 2 },
    { "a2", 0xffUL, 0, 0x4010UL, 0x40001001UL, (void *)&d_4af188, 3 },
    { "b", 0xffffffUL, 0, 0x4010UL, 0x101004UL, (void *)&d_4af180, 4 },
    { "b0", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 5 },
    { "b1", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 6 },
    { "b2", 0xffUL, 0, 0x4010UL, 0x40001001UL, (void *)&d_4af188, 7 },
    { "bcr", 0xffffUL, 65534L, 0x204010UL, 0x10001061UL, (void *)&d_4af1b8, 8 },
    { "ipr", 0xffc3fUL, 65535L, 0x204010UL, 0x1061UL, (void *)&d_4af1f8, 9 },
    { "la", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a8, 10 },
    { "lc", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1b0, 11 },
    { "m0", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 12 },
    { "m1", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 13 },
    { "m2", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 14 },
    { "m3", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 15 },
    { "m4", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 16 },
    { "m5", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 17 },
    { "m6", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 18 },
    { "m7", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 19 },
    { "n0", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 20 },
    { "n1", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 21 },
    { "n2", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 22 },
    { "n3", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 23 },
    { "n4", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 24 },
    { "n5", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 25 },
    { "n6", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 26 },
    { "n7", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 27 },
    { "omr", 0x5fUL, 0, 0x205010UL, 0x40000001UL, (void *)&d_4af268, 28 },
    { "pc", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af260, 29 },
    { "r0", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 30 },
    { "r1", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 31 },
    { "r2", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 32 },
    { "r3", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 33 },
    { "r4", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 34 },
    { "r5", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 35 },
    { "r6", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 36 },
    { "r7", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 37 },
    { "sp", 0x3fUL, 0, 0x204010UL, 0x40001001UL, (void *)&d_4af2c0, 38 },
    { "sr", 0xefffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af2c8, 39 },
    { "ssh", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af2f8, 40 },
    { "ssl", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af300, 41 },
    { "x", 0xffffffUL, 0, 0x4010UL, 0x801002UL, (void *)&d_4af188, 42 },
    { "x0", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 43 },
    { "x1", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 44 },
    { "y", 0xffffffUL, 0, 0x4010UL, 0x801002UL, (void *)&d_4af188, 45 },
    { "y0", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 46 },
    { "y1", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 47 },
    { "gdb", 0xffffffUL, 65532L, 0x204000UL, 0x4001071UL, (void *)&d_4af308, 49 },
    { "pctl", 0xffffffUL, 65533L, 0x204010UL, 0x4001061UL, (void *)&d_4af310, 48 }
};

struct reg_desc regs_4b03a8[50] = { /* 004b03a8 1400 */
    { "a", 0xffffffUL, 0, 0x4010UL, 0x101004UL, (void *)&d_4af180, 0 },
    { "a0", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 1 },
    { "a1", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 2 },
    { "a2", 0xffUL, 0, 0x4010UL, 0x40001001UL, (void *)&d_4af188, 3 },
    { "b", 0xffffffUL, 0, 0x4010UL, 0x101004UL, (void *)&d_4af180, 4 },
    { "b0", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 5 },
    { "b1", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 6 },
    { "b2", 0xffUL, 0, 0x4010UL, 0x40001001UL, (void *)&d_4af188, 7 },
    { "bcr", 0xffffUL, 0, 0x4000UL, 0x10001011UL, (void *)&d_4af1b8, 8 },
    { "ipr", 0xfc3fUL, 65535L, 0x204010UL, 0x10001061UL, (void *)&d_4af210, 9 },
    { "la", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a8, 10 },
    { "lc", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1b0, 11 },
    { "m0", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 12 },
    { "m1", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 13 },
    { "m2", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 14 },
    { "m3", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 15 },
    { "m4", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 16 },
    { "m5", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 17 },
    { "m6", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 18 },
    { "m7", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 19 },
    { "n0", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 20 },
    { "n1", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 21 },
    { "n2", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 22 },
    { "n3", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 23 },
    { "n4", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 24 },
    { "n5", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 25 },
    { "n6", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 26 },
    { "n7", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 27 },
    { "omr", 0x57UL, 0, 0x204010UL, 0x40001001UL, (void *)&d_4af278, 28 },
    { "pc", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af260, 29 },
    { "r0", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 30 },
    { "r1", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 31 },
    { "r2", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 32 },
    { "r3", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 33 },
    { "r4", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 34 },
    { "r5", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 35 },
    { "r6", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 36 },
    { "r7", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 37 },
    { "sp", 0x3fUL, 0, 0x204010UL, 0x40001001UL, (void *)&d_4af2c0, 38 },
    { "sr", 0xefffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af2c8, 39 },
    { "ssh", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af2f8, 40 },
    { "ssl", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af300, 41 },
    { "x", 0xffffffUL, 0, 0x4010UL, 0x801002UL, (void *)&d_4af188, 42 },
    { "x0", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 43 },
    { "x1", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 44 },
    { "y", 0xffffffUL, 0, 0x4010UL, 0x801002UL, (void *)&d_4af188, 45 },
    { "y0", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 46 },
    { "y1", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 47 },
    { "gdb", 0xffffffUL, 65532L, 0x204000UL, 0x4001071UL, (void *)&d_4af308, 49 },
    { "pctl", 0xffffffUL, 65533L, 0x204010UL, 0x4001061UL, (void *)&d_4af310, 48 }
};

struct reg_desc regs_4b0920[50] = { /* 004b0920 1400 */
    { "a", 0xffffffUL, 0, 0x4010UL, 0x101004UL, (void *)&d_4af180, 0 },
    { "a0", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 1 },
    { "a1", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 2 },
    { "a2", 0xffUL, 0, 0x4010UL, 0x40001001UL, (void *)&d_4af188, 3 },
    { "b", 0xffffffUL, 0, 0x4010UL, 0x101004UL, (void *)&d_4af180, 4 },
    { "b0", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 5 },
    { "b1", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 6 },
    { "b2", 0xffUL, 0, 0x4010UL, 0x40001001UL, (void *)&d_4af188, 7 },
    { "bcr", 0xffffUL, 0, 0x4000UL, 0x10001011UL, (void *)&d_4af1b8, 8 },
    { "ipr", 0xfc3fUL, 65535L, 0x204010UL, 0x10001061UL, (void *)&d_4af210, 9 },
    { "la", 0xffffUL, 0, 0x204010UL, 0x14001001UL, (void *)&d_4af1a8, 10 },
    { "lc", 0xffffUL, 0, 0x204010UL, 0x14001001UL, (void *)&d_4af1b0, 11 },
    { "m0", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 12 },
    { "m1", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 13 },
    { "m2", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 14 },
    { "m3", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 15 },
    { "m4", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 16 },
    { "m5", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 17 },
    { "m6", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 18 },
    { "m7", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 19 },
    { "n0", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 20 },
    { "n1", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 21 },
    { "n2", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 22 },
    { "n3", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 23 },
    { "n4", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 24 },
    { "n5", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 25 },
    { "n6", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 26 },
    { "n7", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 27 },
    { "omr", 0x57UL, 0, 0x204010UL, 0x40001001UL, (void *)&d_4af288, 28 },
    { "pc", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af260, 29 },
    { "r0", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 30 },
    { "r1", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 31 },
    { "r2", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 32 },
    { "r3", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 33 },
    { "r4", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 34 },
    { "r5", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 35 },
    { "r6", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 36 },
    { "r7", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 37 },
    { "sp", 0x3fUL, 0, 0x204010UL, 0x40001001UL, (void *)&d_4af2c0, 38 },
    { "sr", 0xefffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af2c8, 39 },
    { "ssh", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af2f8, 40 },
    { "ssl", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af300, 41 },
    { "x", 0xffffffUL, 0, 0x4010UL, 0x801002UL, (void *)&d_4af188, 42 },
    { "x0", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 43 },
    { "x1", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 44 },
    { "y", 0xffffffUL, 0, 0x4010UL, 0x801002UL, (void *)&d_4af188, 45 },
    { "y0", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 46 },
    { "y1", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 47 },
    { "gdb", 0xffffffUL, 65532L, 0x204000UL, 0x4001071UL, (void *)&d_4af308, 49 },
    { "pctl", 0xffffffUL, 65533L, 0x204010UL, 0x4001061UL, (void *)&d_4af310, 48 }
};

struct reg_desc regs_4b0e98[50] = { /* 004b0e98 1400 */
    { "a", 0xffffffUL, 0, 0x4010UL, 0x101004UL, (void *)&d_4af180, 0 },
    { "a0", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 1 },
    { "a1", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 2 },
    { "a2", 0xffUL, 0, 0x4010UL, 0x40001001UL, (void *)&d_4af188, 3 },
    { "b", 0xffffffUL, 0, 0x4010UL, 0x101004UL, (void *)&d_4af180, 4 },
    { "b0", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 5 },
    { "b1", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 6 },
    { "b2", 0xffUL, 0, 0x4010UL, 0x40001001UL, (void *)&d_4af188, 7 },
    { "bcr", 0xffffUL, 0, 0x4000UL, 0x10001011UL, (void *)&d_4af1b8, 8 },
    { "ipr", 0xfc3fUL, 65535L, 0x204010UL, 0x10001061UL, (void *)&d_4af210, 9 },
    { "la", 0xffffUL, 0, 0x204010UL, 0x14001001UL, (void *)&d_4af1a8, 10 },
    { "lc", 0xffffUL, 0, 0x204010UL, 0x14001001UL, (void *)&d_4af1b0, 11 },
    { "m0", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 12 },
    { "m1", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 13 },
    { "m2", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 14 },
    { "m3", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 15 },
    { "m4", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 16 },
    { "m5", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 17 },
    { "m6", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 18 },
    { "m7", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 19 },
    { "n0", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 20 },
    { "n1", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 21 },
    { "n2", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 22 },
    { "n3", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 23 },
    { "n4", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 24 },
    { "n5", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 25 },
    { "n6", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 26 },
    { "n7", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 27 },
    { "omr", 0x5fUL, 0, 0x204010UL, 0x40001001UL, (void *)&d_4af298, 28 },
    { "pc", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af260, 29 },
    { "r0", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 30 },
    { "r1", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 31 },
    { "r2", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 32 },
    { "r3", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 33 },
    { "r4", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 34 },
    { "r5", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 35 },
    { "r6", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 36 },
    { "r7", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 37 },
    { "sp", 0x3fUL, 0, 0x204010UL, 0x40001001UL, (void *)&d_4af2c0, 38 },
    { "sr", 0xefffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af2c8, 39 },
    { "ssh", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af2f8, 40 },
    { "ssl", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af300, 41 },
    { "x", 0xffffffUL, 0, 0x4010UL, 0x801002UL, (void *)&d_4af188, 42 },
    { "x0", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 43 },
    { "x1", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 44 },
    { "y", 0xffffffUL, 0, 0x4010UL, 0x801002UL, (void *)&d_4af188, 45 },
    { "y0", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 46 },
    { "y1", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 47 },
    { "gdb", 0xffffffUL, 65532L, 0x204000UL, 0x4001071UL, (void *)&d_4af308, 49 },
    { "pctl", 0xffffffUL, 65533L, 0x204010UL, 0x4001061UL, (void *)&d_4af310, 48 }
};

struct reg_desc regs_4b1410[50] = { /* 004b1410 1400 */
    { "a", 0xffffffUL, 0, 0x4010UL, 0x101004UL, (void *)&d_4af180, 0 },
    { "a0", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 1 },
    { "a1", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 2 },
    { "a2", 0xffUL, 0, 0x4010UL, 0x40001001UL, (void *)&d_4af188, 3 },
    { "b", 0xffffffUL, 0, 0x4010UL, 0x101004UL, (void *)&d_4af180, 4 },
    { "b0", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 5 },
    { "b1", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 6 },
    { "b2", 0xffUL, 0, 0x4010UL, 0x40001001UL, (void *)&d_4af188, 7 },
    { "bcr", 0xffffUL, 0, 0x4000UL, 0x10001011UL, (void *)&d_4af1b8, 8 },
    { "ipr", 0x3fc3fUL, 65535L, 0x204010UL, 0x4001061UL, (void *)&d_4af228, 9 },
    { "la", 0xffffUL, 0, 0x204010UL, 0x14001001UL, (void *)&d_4af1a8, 10 },
    { "lc", 0xffffUL, 0, 0x204010UL, 0x14001001UL, (void *)&d_4af1b0, 11 },
    { "m0", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 12 },
    { "m1", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 13 },
    { "m2", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 14 },
    { "m3", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 15 },
    { "m4", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 16 },
    { "m5", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 17 },
    { "m6", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 18 },
    { "m7", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 19 },
    { "n0", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 20 },
    { "n1", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 21 },
    { "n2", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 22 },
    { "n3", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 23 },
    { "n4", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 24 },
    { "n5", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 25 },
    { "n6", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 26 },
    { "n7", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 27 },
    { "omr", 0x5fUL, 0, 0x204010UL, 0x40001001UL, (void *)&d_4af298, 28 },
    { "pc", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af260, 29 },
    { "r0", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 30 },
    { "r1", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 31 },
    { "r2", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 32 },
    { "r3", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 33 },
    { "r4", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 34 },
    { "r5", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 35 },
    { "r6", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 36 },
    { "r7", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 37 },
    { "sp", 0x3fUL, 0, 0x204010UL, 0x40001001UL, (void *)&d_4af2c0, 38 },
    { "sr", 0xefffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af2c8, 39 },
    { "ssh", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af2f8, 40 },
    { "ssl", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af300, 41 },
    { "x", 0xffffffUL, 0, 0x4010UL, 0x801002UL, (void *)&d_4af188, 42 },
    { "x0", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 43 },
    { "x1", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 44 },
    { "y", 0xffffffUL, 0, 0x4010UL, 0x801002UL, (void *)&d_4af188, 45 },
    { "y0", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 46 },
    { "y1", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 47 },
    { "gdb", 0xffffffUL, 65532L, 0x204000UL, 0x4001071UL, (void *)&d_4af308, 49 },
    { "pctl", 0xffffffUL, 65533L, 0x204010UL, 0x4001061UL, (void *)&d_4af310, 48 }
};

struct reg_desc regs_4b1988[50] = { /* 004b1988 1400 */
    { "a", 0xffffffUL, 0, 0x4010UL, 0x101004UL, (void *)&d_4af180, 0 },
    { "a0", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 1 },
    { "a1", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 2 },
    { "a2", 0xffUL, 0, 0x4010UL, 0x40001001UL, (void *)&d_4af188, 3 },
    { "b", 0xffffffUL, 0, 0x4010UL, 0x101004UL, (void *)&d_4af180, 4 },
    { "b0", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 5 },
    { "b1", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 6 },
    { "b2", 0xffUL, 0, 0x4010UL, 0x40001001UL, (void *)&d_4af188, 7 },
    { "bcr", 0xffffUL, 65534L, 0x204010UL, 0x10001061UL, (void *)&d_4af1b8, 8 },
    { "ipr", 0xfffffUL, 65535L, 0x204010UL, 0x4001061UL, (void *)&d_4af240, 9 },
    { "la", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a8, 10 },
    { "lc", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1b0, 11 },
    { "m0", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 12 },
    { "m1", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 13 },
    { "m2", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 14 },
    { "m3", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 15 },
    { "m4", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 16 },
    { "m5", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 17 },
    { "m6", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 18 },
    { "m7", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 19 },
    { "n0", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 20 },
    { "n1", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 21 },
    { "n2", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 22 },
    { "n3", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 23 },
    { "n4", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 24 },
    { "n5", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 25 },
    { "n6", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 26 },
    { "n7", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 27 },
    { "omr", 0x5fUL, 0, 0x204010UL, 0x40001001UL, (void *)&d_4af2b0, 28 },
    { "pc", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af260, 29 },
    { "r0", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 30 },
    { "r1", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 31 },
    { "r2", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 32 },
    { "r3", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 33 },
    { "r4", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 34 },
    { "r5", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 35 },
    { "r6", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 36 },
    { "r7", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 37 },
    { "sp", 0x3fUL, 0, 0x204010UL, 0x40001001UL, (void *)&d_4af2c0, 38 },
    { "sr", 0xefffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af2c8, 39 },
    { "ssh", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af2f8, 40 },
    { "ssl", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af300, 41 },
    { "x", 0xffffffUL, 0, 0x4010UL, 0x801002UL, (void *)&d_4af188, 42 },
    { "x0", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 43 },
    { "x1", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 44 },
    { "y", 0xffffffUL, 0, 0x4010UL, 0x801002UL, (void *)&d_4af188, 45 },
    { "y0", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 46 },
    { "y1", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 47 },
    { "gdb", 0xffffffUL, 65532L, 0x204000UL, 0x4001071UL, (void *)&d_4af308, 49 },
    { "pctl", 0x7fffffUL, 65533L, 0x204010UL, 0x4001061UL, (void *)&d_4af258, 48 }
};

struct reg_desc regs_4b1f00[55] = { /* 004b1f00 1544 */
    { "a", 0xffffffUL, 0, 0x4010UL, 0x101004UL, (void *)&d_4af180, 0 },
    { "a0", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 1 },
    { "a1", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 2 },
    { "a2", 0xffUL, 0, 0x4010UL, 0x40001001UL, (void *)&d_4af188, 3 },
    { "b", 0xffffffUL, 0, 0x4010UL, 0x101004UL, (void *)&d_4af180, 4 },
    { "b0", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 5 },
    { "b1", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 6 },
    { "b2", 0xffUL, 0, 0x4010UL, 0x40001001UL, (void *)&d_4af188, 7 },
    { "bcr", 0xffffUL, 65534L, 0x204010UL, 0x10001061UL, (void *)&d_4af1b8, 8 },
    { "ipr", 0xfc3fUL, 65535L, 0x204010UL, 0x10001061UL, (void *)&d_4af1c8, 9 },
    { "la", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a8, 10 },
    { "lc", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1b0, 11 },
    { "m0", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 12 },
    { "m1", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 13 },
    { "m2", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 14 },
    { "m3", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 15 },
    { "m4", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 16 },
    { "m5", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 17 },
    { "m6", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 18 },
    { "m7", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af1a0, 19 },
    { "n0", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 20 },
    { "n1", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 21 },
    { "n2", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 22 },
    { "n3", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 23 },
    { "n4", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 24 },
    { "n5", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 25 },
    { "n6", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 26 },
    { "n7", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af198, 27 },
    { "omr", 0x5fUL, 0, 0x204010UL, 0x40001001UL, (void *)&d_4af268, 28 },
    { "pc", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af260, 29 },
    { "r0", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 30 },
    { "r1", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 31 },
    { "r2", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 32 },
    { "r3", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 33 },
    { "r4", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 34 },
    { "r5", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 35 },
    { "r6", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 36 },
    { "r7", 0xffffUL, 0, 0x4010UL, 0x10001001UL, (void *)&d_4af190, 37 },
    { "sp", 0x3fUL, 0, 0x204010UL, 0x40001001UL, (void *)&d_4af2c0, 38 },
    { "sr", 0xefffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af2c8, 39 },
    { "ssh", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af2f8, 40 },
    { "ssl", 0xffffUL, 0, 0x204010UL, 0x10001001UL, (void *)&d_4af300, 41 },
    { "x", 0xffffffUL, 0, 0x4010UL, 0x801002UL, (void *)&d_4af188, 42 },
    { "x0", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 43 },
    { "x1", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 44 },
    { "y", 0xffffffUL, 0, 0x4010UL, 0x801002UL, (void *)&d_4af188, 45 },
    { "y0", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 46 },
    { "y1", 0xffffffUL, 0, 0x4010UL, 0x4001001UL, (void *)&d_4af188, 47 },
    { "gdb", 0xffffffUL, 65532L, 0x204000UL, 0x4001071UL, (void *)&d_4af308, 49 },
    { "pctl", 0xffffffUL, 65533L, 0x204010UL, 0x4001061UL, (void *)&d_4af310, 48 },
    { "dspacr", 0xffffUL, 65510L, 0x204010UL, 0x10001061UL, (void *)&d_4af318, 50 },
    { "dspbar", 0xffffUL, 65511L, 0x204010UL, 0x10001061UL, (void *)&d_4af338, 51 },
    { "icrl", 0xffUL, 0, 0x204010UL, 0x40000801UL, (void *)&d_4af360, 52 },
    { "rtime", 0xffffUL, 0, 0x204010UL, 0x10000801UL, (void *)&d_4af350, 53 },
    { "wtime", 0xffffUL, 0, 0x204010UL, 0x10000801UL, (void *)&d_4af350, 54 }
};
struct flat_4b2504 regs_4b1f00_tail = { /* 004b2504 tail of regs_4b1f00 */
    0
};

struct group_def grpdef_4b2508[1] = { /* 004b2508 64 */
    { core_m_peek, core_write_reg, core_m_io_read, core_m_io_write, core_m_clock, core_m_reset, 0, core_m_irq_ack, 0, 297, 48, (struct reg_desc *)&regs_4af378, { 0 } }
};

struct group_def grpdef_4b2548[1] = { /* 004b2548 64 */
    { core_m_peek, core_write_reg, core_m_io_read, core_m_io_write, core_m_clock, core_m_reset, 0, core_m_irq_ack, 0, 297, 50, (struct reg_desc *)&regs_4af8b8, { 0 } }
};

struct group_def grpdef_4b2588[1] = { /* 004b2588 64 */
    { core_m_peek, core_write_reg, core_m_io_read, core_m_io_write, core_m_clock, core_m_reset, 0, core_m_irq_ack, 0, 297, 50, (struct reg_desc *)&regs_4b03a8, { 0 } }
};

struct group_def grpdef_4b25c8[1] = { /* 004b25c8 64 */
    { core_m_peek, core_write_reg, core_m_io_read, core_m_io_write, core_m_clock, core_m_reset, 0, core_m_irq_ack, 0, 297, 50, (struct reg_desc *)&regs_4b0920, { 0 } }
};

struct group_def grpdef_4b2608[1] = { /* 004b2608 64 */
    { core_m_peek, core_write_reg, core_m_io_read, core_m_io_write, core_m_clock, core_m_reset, 0, core_m_irq_ack, 0, 297, 50, (struct reg_desc *)&regs_4b0e98, { 0 } }
};

struct group_def grpdef_4b2648[1] = { /* 004b2648 64 */
    { core_m_peek, core_write_reg, core_m_io_read, core_m_io_write, core_m_clock, core_m_reset, 0, core_m_irq_ack, 0, 297, 50, (struct reg_desc *)&regs_4b1410, { 0 } }
};

struct group_def grpdef_4b2688[1] = { /* 004b2688 64 */
    { core_m_peek, core_write_reg, core_m_io_read, core_m_io_write, core_m_clock, core_m_reset, 0, core_m_irq_ack, 0, 297, 50, (struct reg_desc *)&regs_4b1988, { 0 } }
};

struct group_def grpdef_4b26c8[1] = { /* 004b26c8 64 */
    { core_m_peek, core_write_reg, core_m_io_read, core_m_io_write, core_m_clock, core_m_reset, 0, core_m_irq_ack, 0, 297, 55, (struct reg_desc *)&regs_4b1f00, { 0 } }
};

struct group_def grpdef_4b2708[1] = { /* 004b2708 64 */
    { core_m_peek, core_write_reg, core_m_io_read, core_m_io_write, core_m_clock, core_m_reset, 0, core_m_irq_ack, 0, 297, 50, (struct reg_desc *)&regs_4afe30, { 0 } }
};

long regsel_tab[84] = { /* 004b2748 336 */
    -2, -1, 298, 299, 43, 44, 46, 47,
    1, 5, 3, 7, 2, 6, 300, 301,
    30, 31, 32, 33, 34, 35, 36, 37,
    20, 21, 22, 23, 24, 25, 26, 27,
    12, 13, 14, 15, 16, 17, 18, 19,
    89, 88, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1,
    -1, 39, 28, 38, 40, 41, 10, 11,
    303, 302, 28, -1, 301, 300, -1, -1,
    -1, -1, -1, -1, 43, 43, 46, 46,
    44, 44, 47, 47
};

long agu_wrap_mask_tab[16] = { /* 004b2898 64 */
    1, 3, 7, 15, 31, 63, 127, 255,
    511, 1023, 2047, 4095, 8191, 16383, 32767, 65535L
};

long d_4b3430[16] = { /* 004b3430 64 */
    0, 17, 6, 1, 17, 6, 2, 17,
    6, 3, 17, 6, -2, 0, 0, 0
};

const char *d_4b3470[10] = { /* 004b3470 40 */
    "Storage of data to an DAX output file occurs each time transmit", "data is transfered to the output shift register, at the start of", "the transmission.  In the timed output mode, the simulator cycle", "count and a data value are stored each time a word begins",
    "transmission.  In the untimed output mode, a single data value is", "stored each time a word begins transmission.  The value stored", "contains the audio and extension data in bits 0 to 23.  Bit 24", "contains the V bit, bit 25 the U bit and bit 26 the C bit.",
    0, 0
};

const char *d_4b3498[6] = { /* 004b3498 24 */
    "dax", (const char *)&d_4b3470, "Output file format for dax peripheral", 0,
    0, 0
};

struct rec2w_bfa51 d_4b34b0[1] = { /* 004b34b0 8 */
    { 1, (void *)&d_4b3498 }
};

struct rec2w_bfa51 d_4b34b8[3] = { /* 004b34b8 24 */
    { 5, (void *)&d_4b3430 },
    { 0, 0 },
    { 0, (void *)&d_4b34b0 }
};

const char *d_4b34d0[6] = { /* 004b34d0 24 */
    "Control Register", "                       X X X X  ", " X X X X X X           C C S I X", " C U V C U V           S S T E E",
    " B B B A A A           1 0 P N N", 0
};

const char *d_4b34e8[6] = { /* 004b34e8 24 */
    "Status Register", "       X X X   X", "       T B A   A", "       I L U   D",
    "       P K R   E", 0
};

const char *d_4b3500[2] = { /* 004b3500 8 */
    "Transmit Audio Data Register", 0
};

struct reg_desc regs_4b3508[4] = { /* 004b3508 112 */
    { "xadra", 0xffffffUL, 0, 0x4000UL, 0x4001061UL, (void *)&d_4b3500, 0 },
    { "xadrb", 0xffffffUL, 0, 0x4000UL, 0x4001061UL, (void *)&d_4b3500, 1 },
    { "xctr", 0xfc1fUL, 2, 0x4000UL, 0x10001061UL, (void *)&d_4b34d0, 2 },
    { "xstr", 0x1dUL, 3, 0x4000UL, 0x40001021UL, (void *)&d_4b34e8, 3 }
};

struct group_def grpdef_4b3578[1] = { /* 004b3578 64 */
    { periph_read_reg, dax_m_poke, dax_m_io_read, dax_m_io_write, dax_m_clock, dax_m_reset, dax_m_irq_poll, dax_m_irq_ack, 36, 36, 4, (struct reg_desc *)&regs_4b3508, { 0 } }
};

long d_4b3928[6] = { /* 004b3928 24 */
    0, 17, 6, -2, 0, 0
};

const char *d_4b3940[52] = { /* 004b3940 208 */
    "Two methods are provided for file input to the GPIO port.", "Untimed input files will use an input data value each time the", "port is read by the processor.  Timed input files will apply", "a new data value as the clock cycle count for the associated data",
    "value becomes valid, regardless if the processor is reading the", "port.", (const char *)&empty_str, "A timed input data value with an absolute time value is applied",
    "at the cycle count specified in the time value.  A timed input", "data value specified with a relative time (+time) is applied", "at the specified number of cycles since the previous data value.", "For example, a relative time count of +20 will cause the associated",
    "data value to be applied  20 cycles after the previous data.", (const char *)&empty_str, "If a lower case letter t is placed in a data position of the input", "file, the user will be prompted for the next input data value.",
    (const char *)&empty_str, "Storage of data to a GPIO output file occurs each time the port", "data register is written.  In the timed output mode, the simulator", "cycle count and a data value are stored, while in the untimed",
    "output mode only the data value is stored.", (const char *)&empty_str, "EXAMPLES", (const char *)&empty_str,
    "The following untimed GPIO input file will cause the GPIO to", "receive the word sequence 4 F 6 C  2  during consecutive port", "reads.", (const char *)&empty_str,
    "4  F  6 C  2", (const char *)&empty_str, "The following untimed GPIO input file will cause the GPIO to", "receive the word sequence 4  3  1  9 repeatedly.",
    (const char *)&empty_str, "(4   3  1  9)", (const char *)&empty_str, "The following timed GPIO input file will cause the value 2 to be",
    "applied to the GPIO during the first cycle, and the value F to", "be applied to the port 30 cycles later.", (const char *)&empty_str, "+0 2 +30 F",
    (const char *)&empty_str, "The following timed GPIO input file will cause the sequence of", "values 4 2 6  to be applied to the GPIO port ten times.", (const char *)&empty_str,
    "(+0 4  +0 2  +0  6)#10", (const char *)&empty_str, "The following timed GPIO input file will cause the value 3 to be", "applied to the GPIO at cycle 2000, and the value 6 at cycle 12000.",
    (const char *)&empty_str, "2000 3 12000 6", 0, 0
};

const char *d_4b3a10[6] = { /* 004b3a10 24 */
    "gpio", (const char *)&d_4b3940, "I/O file format for gpio port", 0,
    0, 0
};

struct rec2w_bfa51 d_4b3a28[1] = { /* 004b3a28 8 */
    { 1, (void *)&d_4b3a10 }
};

struct rec2w_bfa51 d_4b3a30[3] = { /* 004b3a30 24 */
    { 2, (void *)&d_4b3928 },
    { 0, 0 },
    { 0, (void *)&d_4b3a28 }
};

const char *d_4b3a48[6] = { /* 004b3a48 24 */
    "Control/Data Register", "                         G G G G", "         G G G G         D D D D         G G G G", "         C C C C         D D D D         D D D D",
    "         3 2 1 0         3 2 1 0         3 2 1 0", 0
};

const char *d_4b3a60[6] = { /* 004b3a60 24 */
    "Control/Data Register", "                 G G G G G G G G", " G G G G G G G G D D D D D D D D G G G G G G G G", " C C C C C C C C D D D D D D D D D D D D D D D D",
    " 7 6 5 4 3 2 1 0 7 6 5 4 3 2 1 0 7 6 5 4 3 2 1 0", 0
};

struct reg_desc regs_4b3a78[1] = { /* 004b3a78 32 */
    { "gpior", 0xf0f0fUL, 0, 0x4000UL, 0x4001061UL, (void *)&d_4b3a48, 0 }
};
struct flat_4b3a94 regs_4b3a78_tail = { /* 004b3a94 tail of regs_4b3a78 */
    0
};

struct reg_desc regs_4b3a98[1] = { /* 004b3a98 32 */
    { "gpior", 0xffffffUL, 0, 0x4000UL, 0x4001061UL, (void *)&d_4b3a60, 0 }
};
struct flat_4b3ab4 regs_4b3a98_tail = { /* 004b3ab4 tail of regs_4b3a98 */
    0
};

struct group_def grpdef_4b3ab8[1] = { /* 004b3ab8 64 */
    { gpio_m_peek, gpio_m_poke, gpio_m_io_read, gpio_m_io_write, gpio_m_clock, gpio_m_reset, 0, 0, 36, 1, 1, (struct reg_desc *)&regs_4b3a78, { 0 } }
};

struct group_def grpdef_4b3af8[1] = { /* 004b3af8 64 */
    { gpio_m_peek, gpio_m_poke, gpio_m_io_read, gpio_m_io_write, gpio_m_clock, gpio_m_reset, 0, 0, 36, 1, 1, (struct reg_desc *)&regs_4b3a98, { 0 } }
};
