/* simd_e.c - GENERATED by re/scripts/gentab_sim.py from SIM56000.EXE; do not edit. */
#include "simdata.h"

extern void avl_cmp_h43de70();
extern void avl_cmp_h46b6c0();
extern void avl_cmp_h46b7c0();
extern void avl_cmp_h46b870();
extern void avl_cmp_h46bc60();
extern void avl_cmp_h46bd80();
extern void avl_cmp_h46bda0();
extern void avl_cmp_h46bdc0();
extern void avl_cmp_h46bf00();
extern void avl_cmp_h46bf30();
extern void cmd_asm_h0();
extern void cmd_asm_h1();
extern void cmd_asm_parse();
extern void cmd_break_h0();
extern void cmd_break_h1();
extern void cmd_break_h2();
extern void cmd_break_h3();
extern void cmd_break_h4();
extern void cmd_break_h5();
extern void cmd_break_parse();
extern void cmd_change_h0();
extern void cmd_change_h1();
extern void cmd_change_h2();
extern void cmd_change_parse();
extern void cmd_copy_h0();
extern void cmd_copy_parse();
extern void cmd_device_h0();
extern void cmd_device_h1();
extern void cmd_device_h2();
extern void cmd_device_h3();
extern void cmd_device_h4();
extern void cmd_device_h5();
extern void cmd_device_parse();
extern void cmd_disassemble_h0();
extern void cmd_disassemble_parse();
extern void cmd_display_h0();
extern void cmd_display_h1();
extern void cmd_display_h3();
extern void cmd_display_h4();
extern void cmd_display_h5();
extern void cmd_display_h6();
extern void cmd_display_h_450210();
extern void cmd_display_parse();
extern void cmd_down_h0();
extern void cmd_down_parse();
extern void cmd_evaluate_h0();
extern void cmd_evaluate_parse();
extern void cmd_finish_h0();
extern void cmd_finish_parse();
extern void cmd_frame_h0();
extern void cmd_frame_h1();
extern void cmd_frame_parse();
extern void cmd_go_h0();
extern void cmd_go_parse();
extern void cmd_help_h0();
extern void cmd_help_h1();
extern void cmd_help_h2();
extern void cmd_help_h3();
extern void cmd_help_h4();
extern void cmd_help_parse();
extern void cmd_history_h0();
extern void cmd_history_parse();
extern void cmd_input_h0();
extern void cmd_input_h1();
extern void cmd_input_h3();
extern void cmd_input_open();
extern void cmd_input_parse();
extern void cmd_list_h0();
extern void cmd_list_h1();
extern void cmd_list_h2();
extern void cmd_list_h3();
extern void cmd_list_h4();
extern void cmd_list_parse();
extern void cmd_load_h0();
extern void cmd_load_h1();
extern void cmd_load_h2();
extern void cmd_load_h3();
extern void cmd_load_parse();
extern void cmd_log_h0();
extern void cmd_log_h1();
extern void cmd_log_h2();
extern void cmd_log_h3();
extern void cmd_log_h4();
extern void cmd_log_h5();
extern void cmd_log_h6();
extern void cmd_log_parse();
extern void cmd_more_h0();
extern void cmd_more_h1();
extern void cmd_more_parse();
extern void cmd_next_h0();
extern void cmd_next_h1();
extern void cmd_next_h2();
extern void cmd_next_h3();
extern void cmd_next_h4();
extern void cmd_next_h5();
extern void cmd_next_parse();
extern void cmd_output_h0();
extern void cmd_output_h1();
extern void cmd_output_h2();
extern void cmd_output_h3();
extern void cmd_output_parse();
extern void cmd_path_h0();
extern void cmd_path_h1();
extern void cmd_path_h2();
extern void cmd_path_h3();
extern void cmd_path_parse();
extern void cmd_quit_h0();
extern void cmd_quit_h1();
extern void cmd_quit_h2();
extern void cmd_quit_parse();
extern void cmd_radix_h0();
extern void cmd_radix_h1();
extern void cmd_radix_parse();
extern void cmd_redirect_h0();
extern void cmd_redirect_h1();
extern void cmd_redirect_h2();
extern void cmd_redirect_parse();
extern void cmd_reset_h0();
extern void cmd_reset_parse();
extern void cmd_save_h0();
extern void cmd_save_h1();
extern void cmd_save_parse();
extern void cmd_step_h0();
extern void cmd_step_h1();
extern void cmd_step_h2();
extern void cmd_step_h3();
extern void cmd_step_h4();
extern void cmd_step_h5();
extern void cmd_step_h6();
extern void cmd_step_h7();
extern void cmd_step_parse();
extern void cmd_streams_h0();
extern void cmd_streams_h1();
extern void cmd_streams_h2();
extern void cmd_streams_parse();
extern void cmd_system_h0();
extern void cmd_system_h1();
extern void cmd_system_h2();
extern void cmd_system_parse();
extern void cmd_trace_h0();
extern void cmd_trace_h1();
extern void cmd_trace_h2();
extern void cmd_trace_h3();
extern void cmd_trace_h4();
extern void cmd_trace_h5();
extern void cmd_trace_h6();
extern void cmd_trace_h7();
extern void cmd_trace_parse();
extern void cmd_type_h0();
extern void cmd_type_parse();
extern void cmd_unlock_h0();
extern void cmd_unlock_parse();
extern void cmd_until_h0();
extern void cmd_until_h1();
extern void cmd_until_parse();
extern void cmd_up_h0();
extern void cmd_up_parse();
extern void cmd_view_h0();
extern void cmd_view_parse();
extern void cmd_wait_h0();
extern void cmd_wait_parse();
extern void cmd_watch_h0();
extern void cmd_watch_h1();
extern void cmd_watch_h2();
extern void cmd_watch_parse();
extern void cmd_where_h0();
extern void cmd_where_h1();
extern void cmd_where_parse();
extern void disassemble();
extern void hid_43a3f0();
extern void main();
extern void parm_nop();
extern void prof_cmp_name_nocase();
extern void prof_cmp_srcloc();
extern void prof_cmp_ulong();

long d_4c4fb0[42] = { /* 004c4fb0 168 */
    3, 2, 7, 14, 29, 28, 21, 26,
    3, 32, 24, 13, 29, 10, 6, 11,
    3, 32, 24, 13, 29, 10, 6, 11,
    3, 32, 24, 13, 29, 10, 6, 11,
    3, 32, 24, 13, 29, 10, 6, 11,
    -1, -1
};

long d_4c5058[4] = { /* 004c5058 16 */
    19, 20, 16, 17
};

long d_4c5068[128] = { /* 004c5068 512 */
    -2, 301, 301, -2, -2, 301, 301, 301,
    -2, 300, 300, -2, -2, 300, 300, 300,
    301, -2, 301, -2, 301, -2, 301, -2,
    300, -2, 300, -2, 300, -2, 300, -2,
    304, 304, -2, -2, 304, 304, -2, -2,
    304, 304, -2, -2, 304, 304, -2, -2,
    305, 305, -2, -2, 305, 305, -2, -2,
    305, 305, -2, -2, 305, 305, -2, -2,
    43, 43, 43, 43, 43, 43, 43, 43,
    43, 43, 43, 43, 43, 43, 43, 43,
    46, 46, 46, 46, 46, 46, 46, 46,
    46, 46, 46, 46, 46, 46, 46, 46,
    44, 44, 44, 44, 44, 44, 44, 44,
    44, 44, 44, 44, 44, 44, 44, 44,
    47, 47, 47, 47, 47, 47, 47, 47,
    47, 47, 47, 47, 47, 47, 47, 47
};

unsigned char d_4c5268[72] = { /* 004c5268 72 */
    0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    0, 0, 1, 1, 1, 1, 0, 0
};

long d_4c52b0[128] = { /* 004c52b0 512 */
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 1,
    0, 0, 0, 0, 0, 0, 0, 1,
    0, 0, 0, 1, 0, 0, 0, 1,
    0, 0, 0, 1, 0, 0, 0, 1,
    0, 0, 0, 1, 0, 0, 0, 1,
    0, 0, 0, 1, 0, 0, 0, 1,
    0, 0, 1, 1, 0, 0, 1, 0,
    0, 0, 1, 1, 0, 0, 1, 0,
    0, 0, 1, 1, 0, 0, 1, 0,
    0, 0, 1, 1, 0, 0, 1, 0,
    0, 0, 1, 1, 0, 0, 1, 0,
    0, 0, 1, 1, 0, 0, 1, 0,
    0, 0, 1, 1, 0, 0, 1, 0,
    0, 0, 1, 1, 0, 0, 1, 0
};

long d_4c54b0[8] = { /* 004c54b0 32 */
    43, 46, 44, 47, 43, 46, 44, 47
};

long d_4c54d0[8] = { /* 004c54d0 32 */
    43, 46, 43, 46, 47, 43, 46, 44
};

long d_4c54f0[4] = { /* 004c54f0 16 */
    36, 37, 38, 39
};

const char *d_4c5500[6] = { /* 004c5500 24 */
    "blockdata", "comment", "data", "end",
    "start", (const char *)&d_4c5530
};

long d_4c5518 = 6; /* 004c5518 4 */

long d_4c5520 = -1; /* 004c5520 4 */

long d_4c5524 = -1; /* 004c5524 4 */

long d_4c5528 = -1; /* 004c5528 4 */

long d_4c552c = -1; /* 004c552c 4 */

long d_4c5530[2] = { /* 004c5530 8 */
    1651341683L, 27759
};

const char *d_4c5ce8[6] = { /* 004c5ce8 24 */
    "{^U}=ln-up    {^N}=ln-dn    {^T}=pg-up    {^V}=pg-dn    {^R}=right    {^L}=left", "{^H}=del-lft    {^K}=del-rt    {^O}=overwrite/insert    {Esc}=clear command line", "{^I}=tab-rt    {^E}=eol    {^Z}=del-eol    {CR}=execute    {\?}=more help", "{^B}=back in command stack   {^F}=forward in command stack {^W}=toggle window",
    0, 0
};

const char *d_4c5d00[2] = { /* 004c5d00 8 */
    "{^A}=sel-ln", 0
};

const char *d_4c5d08[4] = { /* 004c5d08 16 */
    "{\?}=help {^T}=pg-up    {^V}=pg-dn    {^R}=right    {^L}=left", "{ESC}=terminate  {^H}=del-lft    {^K}=del-rt    {^O}=overwrite/insert  ", "{^I}=tab-rt    {^E}=eol    {^Z}=del-eol  ", 0
};

const char *d_4c5d18[2] = { /* 004c5d18 8 */
    "{;}comment string entry", 0
};

const char *d_4c5d20[2] = { /* 004c5d20 8 */
    "{Macro filename}", 0
};

const char *d_4c5d28[4] = { /* 004c5d28 16 */
    "macros", (const char *)&d_4c5d20, 0, 0
};

const char *d_4c5d38[3] = { /* 004c5d38 12 */
    "comments", (const char *)&d_4c5d18, 0
};

const char *d_4c5d44 = "                                                  "; /* 004c5d44 4 */

const char *d_4c63b8[2] = { /* 004c63b8 8 */
    "{WH}ERE [[+/-]n]", 0
};

const char *d_4c63c0[14] = { /* 004c63c0 56 */
    "  {----------- WHERE: Display C Function Call Stack -----------}", (const char *)&empty_str, "  {WH}ERE [[+/-]n]", (const char *)&empty_str,
    "  {where}", "  Display the call stack.", (const char *)&empty_str, "  {where 3}",
    "  Display the three innermost frames in the call stack.", (const char *)&empty_str, "  {where -5}", "  Display the five outermost frames in the call stack.",
    0, 0
};

simfn d_4c63f8[2] = { /* 004c63f8 8 */
    cmd_where_h0, 0
};

simfn d_4c6400[2] = { /* 004c6400 8 */
    cmd_where_h1, 0
};

struct command_entry cmd_entry_where[1] = { /* 004c6408 32 */
    { "where", "wh", "where", (void *)&d_4c63b8, (void *)&d_4c63c0, cmd_where_parse, 2, 0 }
};

const char *d_4c6578[4] = { /* 004c6578 16 */
    "{WAT}CH [{#}wn] [radix] reg/addr/expression/{${}c_expression{$}}", "{WAT}CH [{#}wn] {OFF}", 0, 0
};

const char *d_4c6588[32] = { /* 004c6588 128 */
    "  {----------- WATCH: Set, Modify, View, or Clear Watch Item -----------}", (const char *)&empty_str, "  {WAT}CH [{#}wn] [radix] reg/addr/expression/{${}c_expression{$}}", "  {WAT}CH [{#}wn] {OFF}",
    (const char *)&empty_str, "  {watch r0}", "  Add register r0 to the watch list.", (const char *)&empty_str,
    "  {watch x:0}", "  Add x:0 to the watch list.", (const char *)&empty_str, "  {watch ${(count+1)%total$}}",
    "  Add the given C expression to the watch list.", (const char *)&empty_str, "  {watch h ${count/2$}}", "  Add the given C expression to the watch list, with radix hex.",
    (const char *)&empty_str, "  {watch b ${flag$}}", "  Add the given C variable to the watch list, with radix binary.", (const char *)&empty_str,
    "  {watch r0+x:0}", "  Add the expression r0+x:0 to the watch list.", (const char *)&empty_str, "  {watch}",
    "  Display the watch list.", (const char *)&empty_str, "  {watch #3 off}", "  Remove item number three from the watch list.",
    (const char *)&empty_str, "  {watch off}", "  Remove all items from the watch list.", 0
};

const char *d_4c6608[16] = { /* 004c6608 64 */
    "0000", "0001", "0010", "0011",
    "0100", "0101", "0110", "0111",
    "1000", "1001", "1010", "1011",
    "1100", "1101", "1110", "1111"
};

simfn d_4c6648[6] = { /* 004c6648 24 */
    cmd_watch_h0, 0, cmd_watch_h1, 0,
    cmd_watch_h2, 0
};

struct command_entry cmd_entry_watch[1] = { /* 004c6660 32 */
    { "watch", "wat", "watch", (void *)&d_4c6578, (void *)&d_4c6588, cmd_watch_parse, 2, 0 }
};

const char *d_4c6af0[2] = { /* 004c6af0 8 */
    "{W}AIT [count(seconds)]", 0
};

const char *d_4c6af8[10] = { /* 004c6af8 40 */
    "  {----------- WAIT: Wait Specified Time -----------}", (const char *)&empty_str, "  {W}AIT [count(seconds)]", (const char *)&empty_str,
    "  The wait command pauses for count seconds or until the user types <return>", "  before continuing to the next command.  If the wait command is entered", "  without a count parameter,  the command will only terminate if the user", "  types <return>.",
    0, 0
};

simfn d_4c6b20[2] = { /* 004c6b20 8 */
    cmd_wait_h0, 0
};

struct command_entry cmd_entry_wait[1] = { /* 004c6b28 32 */
    { "wait", "w", "wait", (void *)&d_4c6af0, (void *)&d_4c6af8, cmd_wait_parse, 0, 1 }
};

const char *g_space_names[30] = { /* 004c6d10 120 */
    "p", "x", "y", "l",
    "n", "laa", "lab", "lba",
    "lbb", "le", "li", "pa",
    "pb", "pe", "pi", "pr",
    "xa", "xb", "xe", "xi",
    "xr", "ya", "yb", "ye",
    "yi", "yr", "pt", "pf",
    "em", 0
};

const char *d_4c6e48[2] = { /* 004c6e48 8 */
    "{N}EXT [count][{LI}(lines)/{IN}(inst)] [{H}(halt at breakpoints)]", 0
};

const char *d_4c6e50[16] = { /* 004c6e50 64 */
    "  {----------- NEXT: Step Over Subroutine Calls -----------}", (const char *)&empty_str, "  {N}EXT [count][{LI}(lines)/{IN}(inst)] [{H}(halt at breakpoints)]", (const char *)&empty_str,
    "  {next }", "  If the next instruction is a jsr or bsr, go until return to the", "  address following that instruction. Otherwise just execute the", "  next instruction.  Display the enabled registers and memory",
    "  when execution terminates. Ignore breakpoints", (const char *)&empty_str, "  {next 3 h}", "  Execute 3 instructions. If any one of them is a jsr or bsr, go",
    "  until return to the address following that instruction.  Display", "  the enabled registers and memory when execution terminates.", "  Halt at breakpoints.", 0
};

simfn d_4c6e90[12] = { /* 004c6e90 48 */
    cmd_next_h0, 0, cmd_next_h1, 0,
    cmd_next_h2, 0, cmd_next_h3, 0,
    cmd_next_h4, 0, cmd_next_h5, 0
};

struct command_entry cmd_entry_next[1] = { /* 004c6ec0 32 */
    { "next", "n", "next", (void *)&d_4c6e48, (void *)&d_4c6e50, cmd_next_parse, 2, 0 }
};

const char *d_4c6ee0[2] = { /* 004c6ee0 8 */
    "{U}NTIL line/addr [{H}(halt at breakpoints)]", 0
};

const char *d_4c6ee8[22] = { /* 004c6ee8 88 */
    "  {----------- UNTIL: Go Until Address -----------}", (const char *)&empty_str, "  {U}NTIL line/addr [{H}(halt at breakpoints)]", (const char *)&empty_str,
    "  {until 5}", "  Go until the execution address is at the first instruction", "  of line 5 in the current sourcefile. Ignore breakpoints.", (const char *)&empty_str,
    "  {until myfile.asm@4}", "  Go until the execution address is at the first instruction", "  of line 4 in the source file myfile.asm.", (const char *)&empty_str,
    "  {until p:50 h}", "  Go until the execution address is p:50. Halt at breakpoints.", (const char *)&empty_str, "  {until lab_d}",
    "  Go until the execution address is at symbolic label lab_d.", (const char *)&empty_str, "  {until sec3@lab_c}", "  Go until the execution address is at symbolic label lab_c",
    "  in section sec3.", 0
};

simfn d_4c6f40[4] = { /* 004c6f40 16 */
    cmd_until_h0, 0, cmd_until_h1, 0
};

struct command_entry cmd_entry_until[1] = { /* 004c6f50 32 */
    { "until", "u", "until", (void *)&d_4c6ee0, (void *)&d_4c6ee8, cmd_until_parse, 2, 0 }
};

const char *d_4c6f70[2] = { /* 004c6f70 8 */
    "{V}IEW [{A}(assembly)/{S}(source)/{R}(register)]", 0
};

const char *d_4c6f78[16] = { /* 004c6f78 64 */
    "  {----------- VIEW: Select Display Mode -----------}", (const char *)&empty_str, "  {V}IEW [{A}(assembly/{S}(source)/{R}(register)]", (const char *)&empty_str,
    "  {view a}", "  Select assembly display mode.", (const char *)&empty_str, "  {view s}",
    "  Select source file display mode.", (const char *)&empty_str, "  {view r}", "  Select register display mode.",
    (const char *)&empty_str, "  {view}", "  Toggle to next display mode.", 0
};

simfn d_4c6fb8[2] = { /* 004c6fb8 8 */
    cmd_view_h0, 0
};

struct command_entry cmd_entry_view[1] = { /* 004c6fc0 32 */
    { "view", "v", "view", (void *)&d_4c6f70, (void *)&d_4c6f78, cmd_view_parse, 0, 0 }
};

const char *d_4c6fe0[2] = { /* 004c6fe0 8 */
    "{LI}ST [{+}/{-}/{.}/addr]", 0
};

const char *d_4c6fe8[26] = { /* 004c6fe8 104 */
    "  {----------- LIST: List Source File Lines ----------}", (const char *)&empty_str, "  {LI}ST {+}/{-}/{.}/addr", (const char *)&empty_str,
    "  {list myfile.asm}", "  Display file myfile.asm beginning at start of file", (const char *)&empty_str, "  {list myfile.asm@4}",
    "  Display myfile.asm beginning at line 4", (const char *)&empty_str, "  {list 50}", "  Display current file begginning at line 50",
    (const char *)&empty_str, "  {list +}", "  Display next page of current file", (const char *)&empty_str,
    "  {list -}", "  Display previous page of current file", (const char *)&empty_str, "  {list .}",
    "  Display page corresponding to current execution address", (const char *)&empty_str, "  {list p:50}", "  Display source page corresponding to address p:50",
    0, 0
};

simfn d_4c7050[10] = { /* 004c7050 40 */
    cmd_list_h0, 0, cmd_list_h1, 0,
    cmd_list_h2, 0, cmd_list_h3, 0,
    cmd_list_h4, 0
};

struct command_entry cmd_entry_list[1] = { /* 004c7078 32 */
    { "list", "li", "list", (void *)&d_4c6fe0, (void *)&d_4c6fe8, cmd_list_parse, 0, 0 }
};

const char *d_4c7098[2] = { /* 004c7098 8 */
    "{F}INISH ", 0
};

const char *d_4c70a0[8] = { /* 004c70a0 32 */
    "  {----------- FINISH: Step Until Return From Subroutine -----------}", (const char *)&empty_str, "  {F}INISH", (const char *)&empty_str,
    "  {finish}", "  Step until an rts instruction is encountered for the current level.", 0, 0
};

simfn d_4c70c0[2] = { /* 004c70c0 8 */
    cmd_finish_h0, 0
};

struct command_entry cmd_entry_finish[1] = { /* 004c70c8 32 */
    { "finish", "f", "finish", (void *)&d_4c7098, (void *)&d_4c70a0, cmd_finish_parse, 2, 0 }
};

const char *d_4c7e38[2] = { /* 004c7e38 8 */
    "{UP} [n]", 0
};

const char *d_4c7e40[10] = { /* 004c7e40 40 */
    "  {----------- UP: Move Up the C Function Call Stack -----------}", (const char *)&empty_str, "  {UP} [n]", (const char *)&empty_str,
    "  {up}", "  Move up the call stack by one stack frame.", (const char *)&empty_str, "  {up 3}",
    "  Move up the call stack by three stack frames.", 0
};

simfn d_4c7e68[2] = { /* 004c7e68 8 */
    cmd_up_h0, 0
};

struct command_entry cmd_entry_up[1] = { /* 004c7e70 32 */
    { "up", "up", "up", (void *)&d_4c7e38, (void *)&d_4c7e40, cmd_up_parse, 2, 0 }
};

const char *d_4c7f98[2] = { /* 004c7f98 8 */
    "{UN}LOCK device_type password", 0
};

const char *d_4c7fa0[8] = { /* 004c7fa0 32 */
    "{----------- UNLOCK: Device Type Enable ----------}", (const char *)&empty_str, "{UN}LOCK device_type password", (const char *)&empty_str,
    "  {unlock 56001 x51-234}", "  Provide password to enable operation of device type 56001.", "  Passwords are required only for hidden device types. ", 0
};

simfn d_4c7fc0[2] = { /* 004c7fc0 8 */
    cmd_unlock_h0, 0
};

struct command_entry cmd_entry_unlock[1] = { /* 004c7fc8 32 */
    { "unlock", "un", "unlock", (void *)&d_4c7f98, (void *)&d_4c7fa0, cmd_unlock_parse, 0, 1 }
};

const char *d_4c8100[2] = { /* 004c8100 8 */
    "{TY}PE {${}c_expression{$}}", 0
};

const char *d_4c8108[10] = { /* 004c8108 40 */
    "  {----------- TYPE: Display The Result Type of C Expression -----------}", (const char *)&empty_str, "  {TY}PE {${}c_expression{$}}", (const char *)&empty_str,
    "  {type ${count$}}", "  Display the type and location of the variable count.", (const char *)&empty_str, "  {type ${0.5+i$}}",
    "  Display the type of the given expression.", 0
};

simfn d_4c8130[2] = { /* 004c8130 8 */
    cmd_type_h0, 0
};

struct command_entry cmd_entry_type[1] = { /* 004c8138 32 */
    { "type", "ty", "type", (void *)&d_4c8100, (void *)&d_4c8108, cmd_type_parse, 2, 0 }
};

const char *d_4c8310[2] = { /* 004c8310 8 */
    "{T}RACE [count] [{CY}(cycles)/{LI}(lines)/{IN}(inst)] [{H}(halt at breakpoints)]", 0
};

const char *d_4c8318[32] = { /* 004c8318 128 */
    "  {----------- TRACE: Trace Through DSP Program -----------}", (const char *)&empty_str, "  {T}RACE [count] [{CY}(cycles)/{LI}(lines)/{IN}(inst)] [{H}(halt at breakpoints)]", (const char *)&empty_str,
    "  {trace }", "  Execute one instruction or source line, depending on display mode.", "  Display the enabled registers and memory blocks.", (const char *)&empty_str,
    "  {trace 20}", "  Execute 20 instructions or source lines, depending on display mode.", "  Ignores breakpoints during execution (use h option to halt at breakpoints).", "  Display the enabled registers and memory blocks after each instruction.",
    (const char *)&empty_str, "  {trace 20 h}", "  Execute up to 20 instructions or source lines, depending on display", "  mode.  Display the enabled registers and memory blocks after each",
    "  instruction.  Halt at enabled breakpoints.", (const char *)&empty_str, "  {trace 10 cy}", "  Execute 10 clock cycles and display the enabled registers and memory",
    "  blocks after each clock cycle.", (const char *)&empty_str, "  {trace 10 li}", "  Execute instructions corresponding to 10 source lines. Ignore breakpoints",
    "  during execution (use h option to halt at breakpoints).  Display the", "  enabled registers and memory blocks after each instruction.", (const char *)&empty_str, "  {trace 10 in}",
    "  Execute 10 instructions. Ignore breakpoints during execution (use h", "  option to halt at breakpoints).  Display the enabled registers and memory", "  blocks after each instruction.", 0
};

simfn d_4c8398[16] = { /* 004c8398 64 */
    cmd_trace_h0, 0, cmd_trace_h1, 0,
    cmd_trace_h2, 0, cmd_trace_h3, 0,
    cmd_trace_h4, 0, cmd_trace_h5, 0,
    cmd_trace_h6, 0, cmd_trace_h7, 0
};

struct command_entry cmd_entry_trace[1] = { /* 004c83d8 32 */
    { "trace", "t", "trace", (void *)&d_4c8310, (void *)&d_4c8318, cmd_trace_parse, 2, 0 }
};

const char *d_4c8960[2] = { /* 004c8960 8 */
    "{SY}STEM [[{-c}] system_command [parameter_list]]", 0
};

const char *d_4c8968[22] = { /* 004c8968 88 */
    "  {----------- SYSTEM: Execute System Command -----------}", (const char *)&empty_str, "  {SY}STEM [[{-c}] system_command [parameter_list]]", (const char *)&empty_str,
    "  {system dir}", "  Execute the system 'dir' command and immediately return to the simulator.", (const char *)&empty_str, "  {system dir *.io}",
    "  Execute the system 'dir *.io' command", (const char *)&empty_str, "  {system -c dir *.io}", "  Execute the system 'dir *.io' command and continue",
    (const char *)&empty_str, "  {system }", "  {dir *.io}", "  {del he.io}",
    "  {exit}", "  Leave the simulator temporarily.  Execute the system 'dir *.io' and", "  'del he.io' commands.  Return to the simulator when the system 'exit'", "  command is executed.",
    0, 0
};

simfn d_4c89c0[6] = { /* 004c89c0 24 */
    cmd_system_h0, 0, cmd_system_h1, 0,
    cmd_system_h2, 0
};

struct command_entry cmd_entry_system[1] = { /* 004c89d8 32 */
    { "system", "sy", "system", (void *)&d_4c8960, (void *)&d_4c8968, cmd_system_parse, 0, 1 }
};

const char *d_4c8cf8[2] = { /* 004c8cf8 8 */
    "{STR}EAMS [{E}(enable)/{D}(disable)]", 0
};

const char *d_4c8d00[16] = { /* 004c8d00 64 */
    "  {----------- STREAMS: Enable/Disable Handling of I/O for C Programs -----------}", (const char *)&empty_str, "  {STR}EAMS [{E}(enable)/{D}(disable)]", (const char *)&empty_str,
    "  {streams e}", "  Enable handling of C input/output.  All input/output calls done", "  in a C program running on the DSP will be handled by the", "  host software (e.g. fopen(), fwrite(), printf(), etc.).",
    (const char *)&empty_str, "  {streams d}", "  Disable handling of C input/output.", (const char *)&empty_str,
    "  {NOTE:} By default, handling of input/output is enabled.", "  Do {help redirect} for more information on redirecting", "  stdin, stdout, and stderr.", 0
};

simfn d_4c8d40[6] = { /* 004c8d40 24 */
    cmd_streams_h0, 0, cmd_streams_h1, 0,
    cmd_streams_h2, 0
};

struct command_entry cmd_entry_streams[1] = { /* 004c8d58 32 */
    { "streams", "str", "streams", (void *)&d_4c8cf8, (void *)&d_4c8d00, cmd_streams_parse, 2, 0 }
};

const char *d_4c8ff8[2] = { /* 004c8ff8 8 */
    "{ST}EP [count] [{CY}(cycles)/{LI}(lines)/{IN}(inst)] [{H}(halt at breakpoints)]", 0
};

const char *d_4c9000[28] = { /* 004c9000 112 */
    "  {----------- STEP: Step Through DSP Program -----------}", (const char *)&empty_str, "  {ST}EP [count] [{CY}(cycles)/{LI}(lines)/{IN}(inst)] [{H}(halt at breakpoints)]", (const char *)&empty_str,
    "  {step }", "  Step one instruction or source line, depending on display mode.", "  Display the enabled registers and memory blocks after last instruction.", (const char *)&empty_str,
    "  {step $50}", "  Execute hex 50 instructions or source lines, depending on display mode.", "  Ignores breakpoints during execution (use h option to halt at breakpoints).", "  Display the enabled registers and memory blocks after the last instruction.",
    (const char *)&empty_str, "  {step 20 cy}", "  Execute 20 clock cycles. Display the enabled registers and memory", "  blocks at the end of the 20th clock cycle.",
    (const char *)&empty_str, "  {step 20 li h}", "  Execute instructions corresponding to 20 source lines. Halt at enabled", "  breakpoints. Display the enabled registers and memory blocks after the",
    "  last instruction.", (const char *)&empty_str, "  {step 20 in h}", "  Execute 20 instructions. Halt at enabled breakpoints. Display the enabled",
    "  registers and memory blocks after the last instruction.", (const char *)&empty_str, 0, 0
};

simfn d_4c9070[16] = { /* 004c9070 64 */
    cmd_step_h0, 0, cmd_step_h1, 0,
    cmd_step_h2, 0, cmd_step_h3, 0,
    cmd_step_h4, 0, cmd_step_h5, 0,
    cmd_step_h6, 0, cmd_step_h7, 0
};

struct command_entry cmd_entry_step[1] = { /* 004c90b0 32 */
    { "step", "st", "step", (void *)&d_4c8ff8, (void *)&d_4c9000, cmd_step_parse, 2, 0 }
};

const char *d_4c94e8[2] = { /* 004c94e8 8 */
    "{S}AVE {S}(state)/addr_block... filename [{-A}/{-O}/{-C}]", 0
};

const char *d_4c94f0[16] = { /* 004c94f0 64 */
    "  {----------- SAVE: Save Simulator File -----------}", (const char *)&empty_str, "  {S}AVE {S}(state)/addr_block... filename [{-A}/{-O}/{-C}]", (const char *)&empty_str,
    "  {save p:0..$ff x:0..$20 session1 -a}", "  Save both memory maps to OMF file 'session1.lod'.", "  If the file already exists, append to it.", (const char *)&empty_str,
    "  {save s lunchbrk -o}", "  Save the simulator state to filename 'lunchbrk.sim'.", "  If the file already exists, overwrite it.", (const char *)&empty_str,
    "  {save s lunchbrk.b -c}", "  Save the simulator state to filename 'lunchbrk.b'. if it doesn't exist", "  If the file already exists, cancel this command.", 0
};

const char *d_4c9530[2] = { /* 004c9530 8 */
    "w", "r+"
};

simfn d_4c9538[4] = { /* 004c9538 16 */
    cmd_save_h0, 0, cmd_save_h1, 0
};

struct command_entry cmd_entry_save[1] = { /* 004c9548 32 */
    { "save", "s", "save", (void *)&d_4c94e8, (void *)&d_4c94f0, cmd_save_parse, 1, 0 }
};

const char *d_4c9848[2] = { /* 004c9848 8 */
    "{RE}SET {S}(state)/{D}(device) [{M}n]", 0
};

const char *d_4c9850[14] = { /* 004c9850 56 */
    "  {----------- RESET: Reset Device or Simulator State -----------", (const char *)&empty_str, "  {RE}SET {S}(state)/{D}(device) [{M}n]", (const char *)&empty_str,
    "  {reset d m2}", "  Reset all device registers to the defined reset conditions.  The", "  device operating mode will be redefined as mode 2 in response to a", "  subsequent simulated hardware reset.",
    (const char *)&empty_str, "  {reset s}", "  Reset the entire simulator state to the start-up condition.  All", "  breakpoints are cleared, the memory is initialized, and all logging and",
    "  I/O files are closed.", 0
};

const char *d_4c9888[2] = { /* 004c9888 8 */
    "d", "s"
};

simfn d_4c9890[2] = { /* 004c9890 8 */
    cmd_reset_h0, 0
};

struct command_entry cmd_entry_reset[1] = { /* 004c9898 32 */
    { "reset", "re", "reset", (void *)&d_4c9848, (void *)&d_4c9850, cmd_reset_parse, 2, 1 }
};

const char *d_4c9ac8[4] = { /* 004c9ac8 16 */
    "{RED}IRECT {STDIN} {OFF}/file", "{RED}IRECT {STDOUT}/{STDERR} {OFF}/file [{-A}/{-O}/{-C}]", "{RED}IRECT [{OFF}]", 0
};

const char *d_4c9ad8[34] = { /* 004c9ad8 136 */
    "  {----------- REDIRECT: Redirect stdin/stdout/stderr for C Programs -----------}", (const char *)&empty_str, "  {RED}IRECT {STDIN} {OFF}/file", "  {RED}IRECT {STDOUT}/{STDERR} {OFF}/file [{-A}/{-O}/{-C}]",
    "  {RED}IRECT [{OFF}]", (const char *)&empty_str, "  {redirect stdin input}", "  Redirect the C stdin (standard input) stream from the file",
    "  input.cio (.cio is the default extension).", (const char *)&empty_str, "  {redirect stdout output.txt}", "  Redirect the C stdout (standard output) stream to the file",
    "  output.txt.", (const char *)&empty_str, "  {redirect stderr errors}", "  Redirect the C stderr (standard error) stream to the file",
    "  errors.cio.", (const char *)&empty_str, "  {redirect stdout output -o}", "  Redirect the C stdout stream to the file output.cio,",
    "  overwriting the file if it already exists.", (const char *)&empty_str, "  {redirect stdout output -a}", "  Redirect the C stdout stream to the file output.cio,",
    "  appending to the end of the file if it already exists.", (const char *)&empty_str, "  {redirect stdout output -c}", "  Redirect the C stdout stream to the file output.cio,",
    "  but don't redirect if the file already exists.", (const char *)&empty_str, "  {NOTE:}  No I/O processing or handling of redirection occurs if", "  the {streams} option has been disabled.  Do {help streams}",
    "  for more information.", 0
};

const char *d_4c9b60[2] = { /* 004c9b60 8 */
    "w", "a"
};

simfn d_4c9b68[6] = { /* 004c9b68 24 */
    cmd_redirect_h0, 0, cmd_redirect_h1, 0,
    cmd_redirect_h2, 0
};

struct command_entry cmd_entry_redirect[1] = { /* 004c9b80 32 */
    { "redirect", "red", "redirect", (void *)&d_4c9ac8, (void *)&d_4c9ad8, cmd_redirect_parse, 2, 1 }
};

const char *d_4ca078[2] = { /* 004ca078 8 */
    "{R}ADIX [{B}(bin)/{D}(dec)/{F}(frc or flt)/{H}(hex)/{U}(uns)] [reg[_block]/addr[_block]]...", 0
};

const char *d_4ca080[22] = { /* 004ca080 88 */
    "  {----------- RADIX: Change Input or Display Radix --------}", (const char *)&empty_str, "  {R}ADIX [{B}(bin)/{D}(dec)/{F}(frc or flt)/{H}(hex)/{U}(uns)] [reg[_block]/addr[_block]]...", (const char *)&empty_str,
    "  {radix}", "  Display the default radix currently enabled.", (const char *)&empty_str, "  {radix h}",
    "  Change input radix to hexadecimal.  Hexadecimal constant entries", "  no longer require a preceding dollar sign, but any decimal constants will", "  require a preceding grave accent.", (const char *)&empty_str,
    "  {radix f x0  x1}", "  Change display radix for registers x0 and x1 to floating point.", (const char *)&empty_str, "  {radix d x:0..10 p:0..10}",
    "  Change display radix for specified memory locations to decimal.", (const char *)&empty_str, "  {radix u x0 x1}", "  Change display radix for x0 and x1 to unsigned decimal.",
    0, 0
};

const char *d_4ca0d8[6] = { /* 004ca0d8 24 */
    "binary", "decimal", "fractional", "hexadecimal",
    "unsigned", 0
};

long d_4ca0f0[6] = { /* 004ca0f0 24 */
    16384, 4096, 8192, 16384, 32768L, 0
};

simfn d_4ca108[4] = { /* 004ca108 16 */
    cmd_radix_h0, 0, cmd_radix_h1, 0
};

struct command_entry cmd_entry_radix[1] = { /* 004ca118 32 */
    { "radix", "r", "radix", (void *)&d_4ca078, (void *)&d_4ca080, cmd_radix_parse, 2, 1 }
};

const char *d_4ca498[2] = { /* 004ca498 8 */
    "{Q}UIT [{E}(enable)/{D}(disable)]", 0
};

const char *d_4ca4a0[16] = { /* 004ca4a0 64 */
    "  {----------- QUIT: Quit Simulator Session -----------}", (const char *)&empty_str, "  {Q}UIT [{E}/{D}]", "  {----------- Examples -----------}",
    (const char *)&empty_str, "  {quit}", "  Exit simulator with status 0.", (const char *)&empty_str,
    "  {quit e}", "  Enables immediate quit and return of a non-zero exit status", "  if an error occurs during macro execution.", (const char *)&empty_str,
    "  {quit d}", "  Disables quit on error feature.", 0, 0
};

simfn d_4ca4e0[6] = { /* 004ca4e0 24 */
    cmd_quit_h0, 0, cmd_quit_h1, 0,
    cmd_quit_h2, 0
};

struct command_entry cmd_entry_quit[1] = { /* 004ca4f8 32 */
    { "quit", "q", "quit", (void *)&d_4ca498, (void *)&d_4ca4a0, cmd_quit_parse, 0, 1 }
};

const char *d_4ca6a8[4] = { /* 004ca6a8 16 */
    "{P}ATH [pathname]", "{P}ATH + [pathname][,pathname,...]", "{P}ATH -", 0
};

const char *d_4ca6b8[18] = { /* 004ca6b8 72 */
    "  {----------- PATH: Specify Default Pathname -----------}", (const char *)&empty_str, "  {P}ATH [pathname]", "  {P}ATH + [pathname][,pathname,...]",
    "  {P}ATH -", (const char *)&empty_str, "  {path \\sim}", "  Define the default directory for simulator files as '\\sim'.",
    (const char *)&empty_str, "  {path + \\sim}", "  Add '\\sim' to the list of multiple search paths for source files", (const char *)&empty_str,
    "  {path}", "  Show the current default pathname and multiple source path list.", (const char *)&empty_str, "  {path -}",
    "  Clear the multiple source path list.", 0
};

simfn d_4ca700[8] = { /* 004ca700 32 */
    cmd_path_h0, 0, cmd_path_h1, 0,
    cmd_path_h2, 0, cmd_path_h3, 0
};

struct command_entry cmd_entry_path[1] = { /* 004ca720 32 */
    { "path", "p", "path", (void *)&d_4ca6a8, (void *)&d_4ca6b8, cmd_path_parse, 2, 1 }
};

const char *d_4ca9b0[4] = { /* 004ca9b0 16 */
    "{O}UTPUT [#n] [{T}] addr/port/pin[_group] {OFF}/{TERM}/file [{-RD}/{-RF}/{-RH}/{-RU}/{-RS}] [{-A}/{-O}/{-C}]", "{O}UTPUT [#n] [{T}] history {OFF}/{TERM}/file [{-A}/{-O}/{-C}]", "{O}UTPUT [#n] [{T}] ehistory {OFF}/{TERM}/file [{-A}/{-O}/{-C}]", 0
};

const char *d_4ca9c0[42] = { /* 004ca9c0 168 */
    "{----------- OUTPUT: Assign Output File -----------}", (const char *)&empty_str, "{O}UTPUT [#n] [{T}] addr/port/pin[_group] {OFF}/{TERM}/file [{-RD}/{-RF}/{-RH}/{-RU}/{-RS}] [{-A}/{-O}/{-C}]", "{O}UTPUT [#n] [{T}] history {OFF}/{TERM}/file [{-A}/{-O}/{-C}]",
    "{O}UTPUT [#n] [{T}] ehistory {OFF}/{TERM}/file [{-A}/{-O}/{-C}]", (const char *)&empty_str, "  {output x:$0 xfile}", "  Store values written to memory location x:0 in output file 'xfile.io'.",
    (const char *)&empty_str, "  {output host hfile -a}", "  Store values from the Host peripheral to output file 'hfile.io'.", "  Append to the file if it already exists.",
    (const char *)&empty_str, "  {output pd0..pd7 adfile}", "  Store output values for pins PD0 through PD7 to output file 'adfile.io'.", (const char *)&empty_str,
    "  {output rw rwfile -o}", "  Output values for the RW pin to file 'rwfile.io'.", "  Overwrite the file if it already exists.", (const char *)&empty_str,
    "  {output t bg term}", "  Output time and data pairs from the device BG pin to the terminal.", (const char *)&empty_str, "  {output t dbus dfile -rf}",
    "  Output time and data pairs from Port A data bus to file 'adfile.tio'.", "  The data portion of the time-data pair will be output in floating point.", (const char *)&empty_str, "  {output t x:$ffcf xfile -rd}",
    "  Output time and data pairs for memory location X:$FFCF to 'xfile.tio'.", "  The data portion of the time-data pair will be output in decimal form.", (const char *)&empty_str, "  {output history histfile}",
    "  Output execution history to file 'histfile.io' .", (const char *)&empty_str, "  {output t ehistory histfile}", "  Output extended execution history to timed file 'histfile.tio' .",
    "  The output may include additional information relating to wait", "  states or pipeline stalls.", (const char *)&empty_str, "  {output #3 off}",
    " Delete output file assignment number 3.", 0
};

const char *d_4caa68[2] = { /* 004caa68 8 */
    ".io", ".tio"
};

const char *d_4caa70[2] = { /* 004caa70 8 */
    "w", "a"
};

simfn d_4caa80[8] = { /* 004caa80 32 */
    cmd_output_h0, 0, cmd_output_h1, 0,
    cmd_output_h2, 0, cmd_output_h3, 0
};

struct command_entry cmd_entry_output[1] = { /* 004caaa0 32 */
    { "output", "o", "output", (void *)&d_4ca9b0, (void *)&d_4ca9c0, cmd_output_parse, 2, 0 }
};

long d_4cb138 = 1836213620L; /* 004cb138 4 */

unsigned char d_4cb13c[4] = { /* 004cb13c 4 */
    0, 0, 0, 0
};

const char *d_4cb290[2] = { /* 004cb290 8 */
    "{M}ORE [{OFF}]", 0
};

const char *d_4cb298[12] = { /* 004cb298 48 */
    "  {----------- MORE: Session Paging Control -----------}", (const char *)&empty_str, "  {M}ORE [{OFF}]", (const char *)&empty_str,
    " {more}", " Turn on session display paging control.", (const char *)&empty_str, " {more off}",
    " Disable session display paging control (reset state).", (const char *)&empty_str, 0, 0
};

simfn d_4cb2c8[4] = { /* 004cb2c8 16 */
    cmd_more_h0, 0, cmd_more_h1, 0
};

struct command_entry cmd_entry_more[1] = { /* 004cb2d8 32 */
    { "more", "m", "more", (void *)&d_4cb290, (void *)&d_4cb298, cmd_more_parse, 0, 1 }
};

const char *d_4cb3e0[4] = { /* 004cb3e0 16 */
    "{LO}G [{OFF}] [{C}(commands)/{S}(session)/{P}(profile) [filename [{-A}/{-O}/{-C}]]]", "{LO}G [{OFF}] {V}(source display status line)", 0, 0
};

const char *d_4cb3f0[34] = { /* 004cb3f0 136 */
    "  {----------- LOG: Log Commands and/or Session -----------", (const char *)&empty_str, "  {LO}G [{OFF}] [{C}(commands)/{S}(session)/{P}(profile) [filename [{-A}/{-O}/{-C}]]]", "  {LO}G [{OFF}] {V}(source display status line)",
    (const char *)&empty_str, "  {log }", "  Display currently opened log files.", (const char *)&empty_str,
    "  {log s \\debugger\\session1}", "  Log all display entries to filename 'session1.log' in directory 'debugger'", (const char *)&empty_str, "  {log c macro1 -a}",
    "  Log commands to filename 'macro1.cmd'.  Append if it already exists.", (const char *)&empty_str, "  {log off c}", "  Terminate command logging.",
    (const char *)&empty_str, "  {log off}", "  Terminate all logging.", (const char *)&empty_str,
    "  {log v}", "  Enable logging of display status line during session logging.", "  This is primarily intended for testing of the debugger.", (const char *)&empty_str,
    "  {log off v}", "  Disable logging of display status line during session logging.", (const char *)&empty_str, "  {log p}",
    "  Enable logging of profile information during session.", (const char *)&empty_str, "  {log off p}", "  Generate profile and stop logging of profile information.",
    0, 0
};

const char *d_4cb478[3] = { /* 004cb478 12 */
    "w", "r+", ".cmd"
};

const char *d_4cb484 = ".log"; /* 004cb484 4 */

const char *d_4cb488[2] = { /* 004cb488 8 */
    ".cmd", ".log"
};

simfn d_4cb490[14] = { /* 004cb490 56 */
    cmd_log_h0, 0, cmd_log_h1, 0,
    cmd_log_h2, 0, cmd_log_h3, 0,
    cmd_log_h4, 0, cmd_log_h5, 0,
    cmd_log_h6, 0
};

struct command_entry cmd_entry_log[1] = { /* 004cb4c8 32 */
    { "log", "lo", "log", (void *)&d_4cb3e0, (void *)&d_4cb3f0, cmd_log_parse, 2, 1 }
};

const char *d_4cb9f8[2] = { /* 004cb9f8 8 */
    "{L}OAD [{S}(state)|{M}(memory-only)|{D}(debug symbols-only)] (from) filename", 0
};

const char *d_4cba00[22] = { /* 004cba00 88 */
    "  {----------- LOAD: Load Simulator File -----------}", (const char *)&empty_str, "  {L}OAD [{S}(state)|{M}(memory-only)|{D}(debug symbols-only)] (from) filename", "  {load \\source\\testloop.obj}",
    "  Load 'testloop.obj' file from directory 'source'.", (const char *)&empty_str, "  {load lasttest}", "  Load 'lasttest.lod' file from current directory.",
    (const char *)&empty_str, "  {load test.cld}", "  Load memory and debug contents from file 'test.cld' in current directory.", (const char *)&empty_str,
    "  {load m test.cld}", "  Load memory contents only from file 'test.cld' in current directory.", (const char *)&empty_str, "  {load d test.cld}",
    "  Load debug symbol contents only from file 'test.cld' in current directory.", (const char *)&empty_str, "  {load s lunchbrk}", "  Load 'lunchbrk.sim', replacing the entire current simulator state.",
    0, 0
};

simfn d_4cba58[8] = { /* 004cba58 32 */
    cmd_load_h0, 0, cmd_load_h1, 0,
    cmd_load_h2, 0, cmd_load_h3, 0
};

struct command_entry cmd_entry_load[1] = { /* 004cba78 32 */
    { "load", "l", "load", (void *)&d_4cb9f8, (void *)&d_4cba00, cmd_load_parse, 2, 0 }
};

const char *d_4cbe48[4] = { /* 004cbe48 16 */
    "{I}NPUT [#n] [{T}(timed)] addr/port/pin[_group] {OFF}/{TERM}/file [{-RD}/{-RF}/{-RH}/{-RU}]", "{I}NPUT [#n] pin [{DVn:}]pin", "{I}NPUT [#n] addr [{DVn:}]addr", 0
};

const char *d_4cbe58[26] = { /* 004cbe58 104 */
    "  {----------- INPUT: Assign Input File -----------}", (const char *)&empty_str, "  {I}NPUT [#n] [{T}(timed)] addr/port/pin[_group] {OFF}/{TERM}/file [{-RD}/{-RF}/{-RH}/{-RU}]", "  {I}NPUT [#n] pin [{DVn:}]pin",
    "  {I}NPUT [#n] addr [{DVn:}]addr", (const char *)&empty_str, "  {input x:$0 xfile}", "  Get values for memory location x:0 from input file 'xfile.io'.",
    (const char *)&empty_str, "  {input host hfile}", "  Get values for the Host peripheral from input file 'hfile.io'.", (const char *)&empty_str,
    "  {input reset term}", "  Input values for the RESET pin from the terminal.", (const char *)&empty_str, "  {input t irqa term}",
    "  Input time and data pairs from the terminal for the device IRQA pin.", (const char *)&empty_str, "  {input t x:$ffcf xfile -rd}", "  Input time and data pairs for memory location X:$FFCF from 'xfile.tio'.",
    "  The data portion of the time-data pair will be read as a decimal integer.", (const char *)&empty_str, "  {input #3 off}", "  The input file assignment number 3 is deleted.",
    0, 0
};

const char *d_4cbec0[2] = { /* 004cbec0 8 */
    "{CR}=store    {^U}=previous line  {^N}=next line  {ESC}=exit terminal input", 0
};

const char *d_4cbec8[2] = { /* 004cbec8 8 */
    "{CR}=change   {^U}=ln-up    {^N}=ln-dn   {ESC}=exit  <{space}>=more", 0
};

const char *g_radix_names[5] = { /* 004cbed0 20 */
    "binary", "decimal", "float", "hexadecimal",
    "unsigned"
};

long d_4cbee4 = 0; /* 004cbee4 4 */

const char *d_4cbee8[2] = { /* 004cbee8 8 */
    ".io", ".tio"
};

const char *d_4cbef0[2] = { /* 004cbef0 8 */
    "termXXXX.io", "termXXXX.tio"
};

const char *d_4cbef8[2] = { /* 004cbef8 8 */
    "%03d Data: ", 0
};

simfn d_4cbf00[8] = { /* 004cbf00 32 */
    cmd_input_h0, 0, cmd_input_h1, 0,
    cmd_input_open, 0, cmd_input_h3, 0
};

struct command_entry cmd_entry_input[1] = { /* 004cbf20 32 */
    { "input", "i", "input", (void *)&d_4cbe48, (void *)&d_4cbe58, cmd_input_parse, 2, 0 }
};

const char *d_4cc4c8[2] = { /* 004cc4c8 8 */
    "{HI}STORY", 0
};

const char *d_4cc4d0[8] = { /* 004cc4d0 32 */
    "  {----------- HISTORY: Execution History -----------", (const char *)&empty_str, "  {HI}story [dev_list]", (const char *)&empty_str,
    "  {history}", "  Disassemble and display the previous 20 instructions that executed.", 0, 0
};

simfn d_4cc4f0[2] = { /* 004cc4f0 8 */
    cmd_history_h0, 0
};

struct command_entry cmd_entry_history[1] = { /* 004cc4f8 32 */
    { "history", "hi", "history", (void *)&d_4cc4c8, (void *)&d_4cc4d0, cmd_history_parse, 2, 0 }
};

long d_4cc5d0 = 12576; /* 004cc5d0 4 */

long d_4cc5d4 = 12320; /* 004cc5d4 4 */

long d_4cc5d8[4] = { /* 004cc5d8 16 */
    909522486L, 892679477L, 892679477L, 875836725L
};

long d_4cc5e8[4] = { /* 004cc5e8 16 */
    875836468L, 875836468L, 858993459L, 858993459L
};

long d_4cc5f8[12] = { /* 004cc5f8 48 */
    842150707L, 842150450L, 842150450L, 825307441L, 825307441L, 808464689L, 808464432L, 808464432L,
    1109408800L, 1310749801L, 1700949365L, 114
};

long d_4cc628[4] = { /* 004cc628 16 */
    808530483L, 909588537L, 842216501L, 943271985L
};

long d_4cc638[4] = { /* 004cc638 16 */
    875902519L, 808530483L, 909588537L, 842216501L
};

long d_4cc648[10] = { /* 004cc648 40 */
    943271985L, 875902519L, 808530483L, 909588537L, 842216501L, 943271985L, 875902519L, 808530483L,
    0, 0
};

long d_4cc670[20] = { /* 004cc670 80 */
    857748256L, 840970784L, 840970784L, 840970784L, 840970784L, 840970784L, 824193312L, 824193312L,
    824193312L, 824193312L, 824193312L, 807415840L, 807415840L, 807415840L, 807415840L, 807415840L,
    1109408800L, 1310749801L, 1700949365L, 114
};

long d_4cc6c0[18] = { /* 004cc6c0 72 */
    807416096L, 941635872L, 908080928L, 874525984L, 840971040L, 807416096L, 941635872L, 908080928L,
    874525984L, 840971040L, 807416096L, 941635872L, 908080928L, 874525984L, 840971040L, 807416096L,
    0, 0
};

long d_4cc708[4] = { /* 004cc708 16 */
    757935405L, 757935405L, 757935406L, 757935405L
};

long d_4cc718[4] = { /* 004cc718 16 */
    757935406L, 757935405L, 757935406L, 757935405L
};

long d_4cc728[10] = { /* 004cc728 40 */
    757935406L, 757935405L, 757935406L, 757935405L, 757935406L, 757935405L, 757935406L, 757935405L,
    0, 0
};

const char *g_help_misc_topics[14] = { /* 004cc750 56 */
    " {;}comment string entry", " {Macro filename}", "{----------- Other Help Topics ----------------}", " {io}    : list of on-chip io registers and their addresses",
    " {map}   : memory map descriptions for various omr settings", " {mem}   : memory names with block addresses", " {pin}   : list of pin names with index and pin values", " {periph}: list of periperhal names with index",
    " {port}  : list of port names with index and mask", " {reg}   : list of register names,size, and index by peripheral", " {stack} : display of values on device stack", " {sym}   : display of debug symbol information",
    0, 0
};

const char *d_4cc788[12] = { /* 004cc788 48 */
    "{----------- Terminal Input Examples ----------}", " ", "  Untimed inputs consist of simple hexadecimal value separated by spaces.", "  Timed inputs consist of a time-data pairs.  The time is specified first.",
    "  It is in decimal.  The time is considered as relative to the previous", "  data if it is preceded by a + sign.  Otherwise it is considered to be an", "  absolute cycle time.  The following data value is in hexadecimal.", "  Repeat punctuation may be used to repeat a data value or a group of",
    "  values.  For example: (dd ff ec)#5 means repeat the data input sequence", "  {dd ff ec} 5 times before proceeding to the next data.", 0, 0
};

const char *d_4cc7b8[8] = { /* 004cc7b8 32 */
    "{----------- Terminal Input Examples ----------}", " ", "  Input data value may be hexadecimal, decimal, float, or pin data.", "  Hex input just expects hex digits 0-f.  Don't precede with $.",
    "  Decimal input expects decimal integers. Don't use float notation.", "  Float input accepts almost any floating point format.", "  Pin data input expects 1, 0, or x for each pin.  No imbedded blanks.", 0
};

const char *d_4cc7d8[8] = { /* 004cc7d8 32 */
    "  {----------- User Comments -----------}", (const char *)&empty_str, "  {;}comment string entry", (const char *)&empty_str,
    "  Anything on the command line following a semicolon is considered a user", "  comment.  It can be logged to the output log files to document a session.", 0, 0
};

const char *d_4cc7f8[6] = { /* 004cc7f8 24 */
    "  {----------- Macro Commands -----------}", (const char *)&empty_str, "  Any unrecognized mnemonic entry will be interpreted as a macro name.", "  Macro command files may be created using the simulator LOG command.",
    0, 0
};

const char *g_help_topic_tab[20] = { /* 004cc810 80 */
    "tio", (const char *)&d_4cc788, 0, 0,
    0, "tio2", (const char *)&d_4cc7b8, 0,
    0, 0, "comments", (const char *)&d_4cc7d8,
    0, 0, 0, "macros",
    (const char *)&d_4cc7f8, 0, 0, 0
};

const char *d_4cc860 = "                                     "; /* 004cc860 4 */

const char *d_4cc864 = "                        "; /* 004cc864 4 */

const char *d_4cc880[2] = { /* 004cc880 8 */
    "{H}ELP [command/reg/topic]", 0
};

const char *d_4cc888[14] = { /* 004cc888 56 */
    "  {----------- HELP: Simulator Help Text -----------", (const char *)&empty_str, "  {H}ELP [command/reg/topic]", (const char *)&empty_str,
    "  {help}", "  Display a summary of all available commands and their parameters.", (const char *)&empty_str, "  {help asm}",
    "  Display a summary of the assemble command and its parameters.", (const char *)&empty_str, "  {help sym}", "  Display a list of debug symbols from the currently loaded .cld file.",
    0, 0
};

simfn d_4cc8c0[10] = { /* 004cc8c0 40 */
    cmd_help_h0, 0, cmd_help_h1, 0,
    cmd_help_h2, 0, cmd_help_h3, 0,
    cmd_help_h4, 0
};

struct command_entry cmd_entry_help[1] = { /* 004cc8e8 32 */
    { "help", "h", "help", (void *)&d_4cc880, (void *)&d_4cc888, cmd_help_parse, 1, 1 }
};

const char *d_4cd670[2] = { /* 004cd670 8 */
    "{G}O [(from)location/{R}(reset)] [(to break number){#}bn] [(occurrence){:}count]", 0
};

const char *d_4cd678[38] = { /* 004cd678 152 */
    "  {----------- GO: Execute Program -----------}", (const char *)&empty_str, "  {G}O [(from)location/{R}(reset)] [(to break number){#}bn] [(occurrence){:}count]", (const char *)&empty_str,
    "  {go}", "  Start DSP program simulation from the current instruction.  Stop at", "  the first occurrence of any breakpoint.", (const char *)&empty_str,
    "  {go $100}", "  Start DSP program simulation at program memory address hex 100 after", "  clearing the instruction pipeline.  Stop at the first occurrence of any", "  breakpoint.",
    (const char *)&empty_str, "  {go r}", "  Clear the simulator pipeline and start DSP program simulation at", "  the reset vector (address 0).  The simulated machine state is also reset",
    "  according to the DSP microprocessor reset sequence.", (const char *)&empty_str, "  {go #5}", "  Continue execution from the current instruction.  Halt on the first",
    "  occurrence of breakpoint number 5.", (const char *)&empty_str, "  {go #5 :3}", "  Continue execution from the current instruction.  Halt on the third",
    "  occurrence of breakpoint number 5.", (const char *)&empty_str, "  {go 100 #5 :3}", "  Start from address P:100 after clearing the simulator pipeline.  Halt on",
    "  the third occurrence of breakpoint number 5.", (const char *)&empty_str, "  {go @13}", "  Start from the address corresponding to line 13 off the current file",
    "  after clearing the simulator pipeline.", (const char *)&empty_str, "  {go lab_1}", "  Start from the address corresponding to symbolic label lab_1",
    "  after clearing the simulator pipeline.", 0
};

simfn d_4cd710[2] = { /* 004cd710 8 */
    cmd_go_h0, 0
};

struct command_entry cmd_entry_go[1] = { /* 004cd718 32 */
    { "go", "g", "go", (void *)&d_4cd670, (void *)&d_4cd678, cmd_go_parse, 2, 0 }
};

const char *d_4cdc50[2] = { /* 004cdc50 8 */
    "{FR}AME [{#}fn]", 0
};

const char *d_4cdc58[10] = { /* 004cdc58 40 */
    "  {----------- FRAME: Select C Function Call Stack Frame -----------}", (const char *)&empty_str, "  {FR}AME [{#}fn]", (const char *)&empty_str,
    "  {frame #2}", "  Select call stack frame number two.", (const char *)&empty_str, "  {frame #0}",
    "  Select call stack frame number zero (innermost frame).", 0
};

simfn d_4cdc80[2] = { /* 004cdc80 8 */
    cmd_frame_h0, 0
};

simfn d_4cdc88[2] = { /* 004cdc88 8 */
    cmd_frame_h1, 0
};

struct command_entry cmd_entry_frame[1] = { /* 004cdc90 32 */
    { "frame", "fr", "frame", (void *)&d_4cdc50, (void *)&d_4cdc58, cmd_frame_parse, 2, 0 }
};

const char *d_4cddc8[2] = { /* 004cddc8 8 */
    "{E}VALUATE [{B}(bin)/{D}(dec)/{F}(frc or flt)/{H}(hex)/{U}(unsigned)] expression/{${}c_expression{$}}", 0
};

const char *d_4cddd0[36] = { /* 004cddd0 144 */
    "  {----------- EVALUATE: Evaluate an Expression -----------}", (const char *)&empty_str, "  {E}VALUATE [{B}(bin)/{D}(dec)/{F}(frc or flt)/{H}(hex)/{U}(unsigned)] expression/{${}c_expression{$}}", (const char *)&empty_str,
    "  {evaluate r0+p:$50}", "  Add the value in r0 register to the value in program memory address", "  hexadecimal 50 and display the result using the default radix.", (const char *)&empty_str,
    "  {evaluate b $345 }", "  Convert hexadecimal 345 to binary and display the result.", (const char *)&empty_str, "  {evaluate h %10101010&p:r0 }",
    "  Calculate the bitwise AND of the program memory address specified by the", "  value in r0 register and the binary value 10101010 and display the result", "  in hexadecimal.", (const char *)&empty_str,
    "  {evaluate @30}", "  Display the address corresponding to line 30 of the current sourcefile", (const char *)&empty_str, "  {evaluate test.asm@30}",
    "  Display the address corresponding to line 30 of the sourcefile test.asm", (const char *)&empty_str, "  {evaluate lab_1}", "  Display the address corresponding to symbolic label lab_1",
    (const char *)&empty_str, "  {evaluate sec4@lab_1}", "  Display the address corresponding to symbolic label lab_1 in section sec4", (const char *)&empty_str,
    "  {evaluate ${count+max$}}", "  Display the result of adding the C variables count and max.", (const char *)&empty_str, "  {evaluate ${dbl = 3.5$}}",
    "  Assign the value 3.5 to the C variable dbl and display the", "  result of assignment.", 0, 0
};

const char *d_4cde60[16] = { /* 004cde60 64 */
    "0000", "0001", "0010", "0011",
    "0100", "0101", "0110", "0111",
    "1000", "1001", "1010", "1011",
    "1100", "1101", "1110", "1111"
};

simfn d_4cdea0[2] = { /* 004cdea0 8 */
    cmd_evaluate_h0, 0
};

struct command_entry cmd_entry_evaluate[1] = { /* 004cdea8 32 */
    { "evaluate", "e", "evaluate", (void *)&d_4cddc8, (void *)&d_4cddd0, cmd_evaluate_parse, 2, 0 }
};

const char *d_4ce518[2] = { /* 004ce518 8 */
    "{DO}WN [n]", 0
};

const char *d_4ce520[10] = { /* 004ce520 40 */
    "  {----------- DOWN: Move Down the C Function Call Stack -----------}", (const char *)&empty_str, "  {DO}WN [n]", (const char *)&empty_str,
    "  {down}", "  Move down the call stack by one stack frame.", (const char *)&empty_str, "  {down 2}",
    "  Move down the call stack by two stack frames.", 0
};

simfn d_4ce548[2] = { /* 004ce548 8 */
    cmd_down_h0, 0
};

struct command_entry cmd_entry_down[1] = { /* 004ce550 32 */
    { "down", "do", "down", (void *)&d_4ce518, (void *)&d_4ce520, cmd_down_parse, 2, 0 }
};

const char *d_4ce688[4] = { /* 004ce688 16 */
    "{D}ISPLAY [{ON}/{OFF}/{R}/{W}/{RW}] [reg[_block/_group]/addr[_block]]...", "{D}ISPLAY {V}(version)", "{D}ISPLAY {L}(labels) [{OFF}]", 0
};

const char *d_4ce698[62] = { /* 004ce698 248 */
    "  {-----------DISPLAY: Display Register or Memory -----------}", (const char *)&empty_str, "  {D}ISPLAY [{ON}/{OFF}/{R}/{W}/{RW}] [reg[_block/_group]/addr[_block]]...", "  {D}ISPLAY {V}(version)",
    "  {D}ISPLAY {L}(labels) [{OFF}]", (const char *)&empty_str, "  {display v}", "  Display debugger version number and date of release.",
    (const char *)&empty_str, "  {display l}", "  Modifies memory display commands so that labels are displayed.", (const char *)&empty_str,
    "  {----------- Register and Memory Display Modes -----------}", (const char *)&empty_str, "    {ON}  Always display the following registers and memory locations.", "    {OFF} Never display the following registers and memory locations.",
    "    {R}   Display the following registers and memory locations if they were", "        accessed for a read operation since the last display occurred.", "    {W}   Display the following register and memory locations if they were", "        accessed for a write operation since the last display occurred.",
    "    {RW}  Display the following register and memory locations if they were", "        accessed for read or write operations since the last display", "        occurred.", (const char *)&empty_str,
    "  {----------- Examples -----------}", (const char *)&empty_str, "  {display on }", "  Enable all registers for display",
    (const char *)&empty_str, "  {display on p:0..20 x:30..40 x:$100}", "  Display enable p memory address block 0 to 20, x memory address block", "  30 to 40 and x memory address hexadecimal 100.",
    (const char *)&empty_str, "  {display off }", "  display on core host ssi", "  Disable all display, then enable display of the DSP programming model",
    "  registers, the HOST peripheral registers, and the SSI registers.", (const char *)&empty_str, "  {display w r0..r3 io x:0..100}", "  Display conditionally (if they are written) registers r0 through r3, all",
    "  all peripheral registers, and x memory locations 0 through 100.", (const char *)&empty_str, "  {----------- Register Group Names -----------}", (const char *)&empty_str,
    "    {ALL}   all registers.", "    {CORE}  all of the DSP programming model registers.", "    {periph}all registers of the specified peripheral interface.", "    {COUNT} all simulator counter registers (cyc, ictr, cnt1,cnt2,cnt3,cnt4 )",
    (const char *)&empty_str, "  {display}", "  Display all currently enabled registers and memory.", (const char *)&empty_str,
    "  {display p:0..300}", "  Immediate display of p memory addresses 0 through 300.", (const char *)&empty_str, "  {display all}",
    "  Immediate display of all registers plus the enabled memory locations.", (const char *)&empty_str, "  {display xdat..xdat+10}", "  Immediate display of 11 memory addresses beginning at the address corresponding",
    "  to symbolic label xdat.", 0
};

long d_4ce790[6] = { /* 004ce790 24 */
    0, 16, 32, 96, 64, 0
};

simfn d_4ce7a8[14] = { /* 004ce7a8 56 */
    cmd_display_h0, 0, cmd_display_h1, 0,
    cmd_display_h_450210, 0, cmd_display_h3, 0,
    cmd_display_h4, 0, cmd_display_h5, 0,
    cmd_display_h6, 0
};

struct command_entry cmd_entry_display[1] = { /* 004ce7e0 32 */
    { "display", "d", "display", (void *)&d_4ce688, (void *)&d_4ce698, cmd_display_parse, 2, 1 }
};

const char *d_4cf170[2] = { /* 004cf170 8 */
    "{DI}SASSEMBLE [{B}(byte wide)] [addr[_block]]", 0
};

const char *d_4cf178[30] = { /* 004cf178 120 */
    "  {----------- DISASSEMBLE: Object Code Disassembler -----------}", (const char *)&empty_str, "  {DI}SASSEMBLE [{B}(byte wide)] [addr[_block]]", (const char *)&empty_str,
    "  {disassemble }", "  Disassemble 20 instructions beginning at program counter address.", (const char *)&empty_str, "  {disassemble x:5}",
    "  Disassemble 20 instructions beginning at x memory map address 5.", (const char *)&empty_str, "  {disassemble p:0..20}", "  Disassemble program memory address block 0 to 20.",
    (const char *)&empty_str, "  {disassemble x:$50#10}", "  Disassemble 10 instructions starting at x memory map hex 50.", (const char *)&empty_str,
    "  {disassemble lab1..lab2}", "  Disassemble the block of instructions starting at the address", "  of symbolic label lab1 and ending at the address of label lab2.", (const char *)&empty_str,
    "  {disassemble @13..@15}", "  Disassemble the block of instructions starting at the address", "  corresponding to line 13 of the current sourcefile and ending", "  at the address corresponding to line 15 of the current sourcefile",
    (const char *)&empty_str, "  {disassemble b p:$c000}", "  Disassemble the byte-wide program memory beginning at address P:$c000.", (const char *)&empty_str,
    0, 0
};

simfn d_4cf1f0[2] = { /* 004cf1f0 8 */
    cmd_disassemble_h0, 0
};

struct command_entry cmd_entry_disassemble[1] = { /* 004cf1f8 32 */
    { "disassemble", "di", "disassemble", (void *)&d_4cf170, (void *)&d_4cf178, cmd_disassemble_parse, 2, 0 }
};

const char *d_4cf5d0[2] = { /* 004cf5d0 8 */
    "{DE}VICE {DVn} [device_type/{ON}/{OFF}/{X}]", 0
};

const char *d_4cf5d8[24] = { /* 004cf5d8 96 */
    "{----------- DEVICE: Device Type Specification ----------}", (const char *)&empty_str, "{DE}VICE {DVn} [device_type/{ON}/{OFF}/{X}]", (const char *)&empty_str,
    "  {device dv0 56000}", "  Specify that device 0 is a 56000.  The device_type parameter", "  may be any of the device types supported by your simulator -", "  for example: 56001, 56002, 56116, 96002,",
    "  The 'n' may be 0 to 31, since the default simulator now ", "  supports up to 32 devices. This command also turns on the", "  device. ", (const char *)&empty_str,
    "  {device dv1 on}", "  Turns on simulation of device dv1.  If it was not previously", "  on, it is initialized as the default device type.", (const char *)&empty_str,
    "  {device dv2 off}", "  Suspend simulation of device dv2.  Cycles are not executed", "  for the selected device, but it's current state is maintained.", (const char *)&empty_str,
    "  {device dv3 x}", "  Release all the debugger device structures and memory associated ", "  with device dv3.", 0
};

simfn d_4cf638[12] = { /* 004cf638 48 */
    cmd_device_h0, 0, cmd_device_h1, 0,
    cmd_device_h2, 0, cmd_device_h3, 0,
    cmd_device_h4, 0, cmd_device_h5, 0
};

struct command_entry cmd_entry_device[1] = { /* 004cf668 32 */
    { "device", "de", "device", (void *)&d_4cf5d0, (void *)&d_4cf5d8, cmd_device_parse, 0, 1 }
};

const char *d_4cfac8[2] = { /* 004cfac8 8 */
    "{CO}PY (from) addr[_block] (to) addr", 0
};

const char *d_4cfad0[20] = { /* 004cfad0 80 */
    "  {----------- COPY: Copy a Memory Block -----------}", (const char *)&empty_str, "  {CO}PY (from) addr[_block] (to) addr", (const char *)&empty_str,
    "  {copy p:$100..$500 x:$500}", "  Copy the program memory values located from hexadecimal 100 through", "  hexadecimal 500 to x memory starting at hexadecimal 500.", (const char *)&empty_str,
    "  {copy x:0#100 p:0}", "  Copy one hundred memory locations beginning at x memory location 0 to", "  p memory beginning at location 0.", (const char *)&empty_str,
    "  {copy p:0..20 p:40}", "  Copy p memory locations 0 through 20 to p memory locations 40 through 60.", (const char *)&empty_str, "  {copy lab1..lab2 lab3}",
    "  Copy memory locations from the block beginning at symbolic label lab1 and", "  ending at the label lab2 to the destination memory beginning at the label", "  lab3", 0
};

simfn d_4cfb20[2] = { /* 004cfb20 8 */
    cmd_copy_h0, 0
};

struct command_entry cmd_entry_copy[1] = { /* 004cfb28 32 */
    { "copy", "co", "copy", (void *)&d_4cfac8, (void *)&d_4cfad0, cmd_copy_parse, 1, 0 }
};

const char *d_4cfe28[2] = { /* 004cfe28 8 */
    "{CR}=change   {^U}=previous reg   {^N}=next reg   {ESC}=exit register change", 0
};

const char *d_4cfe30[2] = { /* 004cfe30 8 */
    "{CR}=change   {^U}=previous addr   {^N}=next addr   {ESC}=exit memory change", 0
};

const char *d_4cfe38[2] = { /* 004cfe38 8 */
    "Fract", "Flt"
};

const char *d_4cfe40 = "change %s%s= ;Hex:%s  Dec:%s  %s:%s"; /* 004cfe40 4 */

const char *d_4cfe44 = "change %s%s %s ;Dec:%s  %s:%s"; /* 004cfe44 4 */

const char *d_4cfe48 = "change %s:$%s=  ;Hex:%s  Dec:%s  %s:%s"; /* 004cfe48 4 */

const char *d_4cfe4c = "change %s:$%s %s ;Dec:%s  %s:%s"; /* 004cfe4c 4 */

const char *d_4cfe50 = "change %s:$%s=  ;Hex:%s  Dec:%s  %s:%14.14s"; /* 004cfe50 4 */

const char *d_4cfe54 = "change %s:$%s %s ;Dec:%s  %s:%14.14s"; /* 004cfe54 4 */

const char *d_4cfe58 = "change %s:$%s=  ;Hex:%s  %s:%25.25s"; /* 004cfe58 4 */

const char *d_4cfe5c = "change %s:$%s %s ;%s:%25.25s"; /* 004cfe5c 4 */

const char *d_4cfe60[2] = { /* 004cfe60 8 */
    "{C}HANGE [reg[_block]/addr[_block] [expression]]...", 0
};

const char *d_4cfe68[22] = { /* 004cfe68 88 */
    "  {----------- CHANGE: Change Register or Memory Value -----------", (const char *)&empty_str, "  {C}HANGE [reg[_block]/addr[_block] [expression]]...", (const char *)&empty_str,
    "  {change pc}", "  Display register values individually starting with the program counter", "  and prompt the user for new values.", (const char *)&empty_str,
    "  {change x:$55}", "  Display x memory location hexadecimal 55 and prompt the user for a new value.", (const char *)&empty_str, "  {change p:$20 $1234 }",
    "  Change p memory address hexadecimal 20 to hexadecimal 1234.", (const char *)&empty_str, "  {change xdat $44}", "  Change memory address associated with symbolic label xdat to hexadecimal 44.",
    (const char *)&empty_str, "  {change r0..r3 0 p:$30..$300 0 x:$fffe $55 pc 100}", "  Change registers r0 through r3 to 0, p memory addresses hexadecimal 30", "  through 300 to 0, x memory address hex fffe to hex 55 and the program",
    "  counter to 100 decimal.", 0
};

struct rec2w_18d52 d_4cfec0[3] = { /* 004cfec0 24 */
    { cmd_change_h0, 1 },
    { cmd_change_h1, 1 },
    { cmd_change_h2, 0 }
};

struct command_entry cmd_entry_change[1] = { /* 004cfed8 32 */
    { "change", "c", "change", (void *)&d_4cfe60, (void *)&d_4cfe68, cmd_change_parse, 2, 0 }
};

const char *g_bp_action_names[8] = { /* 004d0488 32 */
    "h", "i1", "i2", "i3",
    "i4", "n", "s", "x "
};

const char *g_bp_type_names[13] = { /* 004d04a8 52 */
    "r ", "rw ", "w ", "r ",
    "rw ", "w ", (const char *)&empty_str, (const char *)&empty_str,
    (const char *)&empty_str, "dr ", "drw ", "dw ",
    (const char *)&empty_str
};

const char *d_4d04e0[14] = { /* 004d04e0 56 */
    "r ", "rw ", "w ", "r ",
    "rw ", "w ", (const char *)&empty_str, (const char *)&empty_str,
    (const char *)&empty_str, "dr ", "drw ", "dw ",
    (const char *)&empty_str, 0
};

const char *d_4d0518[6] = { /* 004d0518 24 */
    "{B}REAK [{#}bn] [expression/{${}c_expression{$}}] [break_action]", "  [break_action] = [{H}(halt)/{In}(increment CNTn)/{N}(note)/{S}(show)/{X} [command]]", "{B}REAK [{#}bn] {R}(read)/{W}(write)/{RW}(access) reg/addr[_block] [break_action]]", "{B}REAK [{#}bn[,bn,...]] {OFF}/{E}(enable)/{D}(disable)",
    "{B}REAK [{#}bn] {DR}(dma read)/{DW}(dma write)/{DRW}(dma access) addr[_block] [break_action]", 0
};

const char *d_4d0530[106] = { /* 004d0530 424 */
    "{----------- BREAK: Set, Modify, or Clear Breakpoint -----------}", (const char *)&empty_str, "  {B}REAK [{#}bn] [expression/{${}c_expression{$}}] [break_action]", "    [break_action] = [{H}(halt)/{In}(increment CNTn)/{N}(note)/{S}(show)/{X} [command]]",
    "  {B}REAK [{#}bn] {R}(read)/{W}(write)/{RW}(access) reg/addr[_block] [break_action]", "  {B}REAK [{#}bn[,bn,...]] {OFF}/{E}(enable)/{D}(disable)", "  {B}REAK [{#}bn] {DR}(dma read)/{DW}(dma write)/{DRW}(dma access) addr[_block] [break_action]", (const char *)&empty_str,
    "  A breakpoint expression may be any logical expression that is valid for", "  the DSP Macro Assembler.  The following is a list of", "  operators that may be used in the breakpoint expression:", (const char *)&empty_str,
    "    {<}   less than                 {&&}    logical 'and'", "    {<=}  less than or equal to     {||}    logical 'or'", "    {==}  equal to                   {! }   logical 'negate'", "    {>=}  greater than or equal to   {& }   bitwise 'and'",
    "    {> }  greater than               {| }   bitwise 'or'", "    {!=}  not equal to               {~ }   bitwise one's complement", "    {+ }  addition                   {^ }   bitwise 'exclusive or'", "    {- }  subtraction               {<<}    shift left",
    "    {/ }  division                  {>>}    shift right", (const char *)&empty_str, "  {eof}  Is TRUE if an end-of-file condition occurs in an input file", "       assigned to a peripheral or memory location.",
    (const char *)&empty_str, "  {jump} Is TRUE if a 'jump' change of flow occurs during code execution.", (const char *)&empty_str, "  {----------- Breakpoint Actions -----------}",
    "    {H }    Halt execution.  This is the default.", "    {In}    Increment counter variable CNTn (n=1/2).", "    {N }    Note - display the breakpoint expression and continue.", "    {S }    Show the enabled register/memory set and continue.",
    "    {X }    Execute the following command.", (const char *)&empty_str, "  {----------- Examples -----------}", "  {break}",
    "  Display all currently enabled breakpoints.", (const char *)&empty_str, "  {break off}", "  Remove all currently enabled breakpoints.",
    (const char *)&empty_str, "  {break #1,3,4 off}", "  Remove breakpoints numbers 1,3 and 4.", (const char *)&empty_str,
    "  {break #1..5 d}", "  Disable breakpoints numbers 1 through 5.", (const char *)&empty_str, "  {break #2 e}",
    "  Enable breakpoint number 2.", (const char *)&empty_str, "  {break e}", "  Enable all breakpoints.",
    (const char *)&empty_str, "  {break lab_d}", "  Set a breakpoint at symbolic address label lab_d.", (const char *)&empty_str,
    "  {break sec3@lab_c}", "  Set a breakpoint at symbolic address label lab_c in section sec3.", (const char *)&empty_str, "  {break main}",
    "  Set a breakpoint at the beginning of the C function main.", "  The breakpoint is set after the prologue code in the function.", (const char *)&empty_str, "  {break 20}",
    "  Set a breakpoint at line 20 of the current source file.", (const char *)&empty_str, "  {break test.asm@9}", "  Set a breakpoint at line 9 of source file test.asm.",
    (const char *)&empty_str, "  {break pc>=$500 }", "  Halt DSP program simulation and display enabled registers and memory", "  when the program counter register is greater than or equal to",
    "  hexadecimal 500.", (const char *)&empty_str, "  {break (lc<10)&&(pc>100)}", "  Halt if the loop counter is less than 10 and the program counter is",
    "  greater than 100.", (const char *)&empty_str, "  {break ${i == 30$}}", "  Halt when the C variable i is equal to 30.",
    (const char *)&empty_str, "  {break jump note}", "  Display breakpoint message if a jump change of flow occurs during execution.", (const char *)&empty_str,
    "  {break eof||pc>$fff}", "  Halt if an end of file condition occurs in an assigned peripheral input", "  file or if the program counter is greater that hexadecimal FFF.", (const char *)&empty_str,
    "  {break r0==r1}", "  Halt when the value of register r0 equals the value of register r1.", (const char *)&empty_str, "  {break lc>0&&jump i1}",
    "  Increment variable cnt1 if a jump occurs and the loop counter is greater", "  than 0.", (const char *)&empty_str, "  {break r r0}",
    "  Halt if register r0 is accessed for a read operation.", (const char *)&empty_str, "  {break w lc}", "  Halt if the loop counter register is written during code execution.",
    (const char *)&empty_str, "  {break rw p:30..40 s}", "  Display enabled registers and memory and continue program simulation if", "  any program memory location from decimal 30 to 40 is accessed.",
    0, 0
};

simfn d_4d06d8[12] = { /* 004d06d8 48 */
    cmd_break_h0, 0, cmd_break_h1, 0,
    cmd_break_h2, 0, cmd_break_h3, 0,
    cmd_break_h4, 0, cmd_break_h5, 0
};

struct command_entry cmd_entry_break[1] = { /* 004d0708 32 */
    { "break", "b", "break", (void *)&d_4d0518, (void *)&d_4d0530, cmd_break_parse, 2, 0 }
};

const char *d_4d1808[2] = { /* 004d1808 8 */
    "{A}SM [{B}(byte wide)] [(beginning at) addr] [assembler_mnemonic]", 0
};

const char *d_4d1810[30] = { /* 004d1810 120 */
    "{----------- ASM: Single Line Assembler ----------}", (const char *)&empty_str, "  {A}SM [(beginning at) addr] [assembler_mnemonic]", (const char *)&empty_str,
    "  {asm p:$50}", "  Start interactive assembler at program memory address 50 hex.", (const char *)&empty_str, "  {asm lab_d}",
    "  Start interactive assembler at symbolic address label lab_d.", (const char *)&empty_str, "  {asm sec2@lab_c}", "  Start interactive assembler at symbolic address label lab_c in section sec2.",
    (const char *)&empty_str, "  {asm 50}", "  Start interactive assembler at address corresponding to line 50 in the", "  current source file.",
    (const char *)&empty_str, "  {asm test.asm@9}", "  Start interactive assembler at address corresponding to line 9 in the", "  source file test.asm.",
    (const char *)&empty_str, "  {asm x:0 move r0,x0}", "  Assemble single instruction at x memory address 0.", (const char *)&empty_str,
    "  {asm}", "  Start assembler at current program counter value.", (const char *)&empty_str, "  {asm b p:$c000}",
    "  Assemble byte-wide beginning at program memory address c000 hex.", 0
};

const char *d_4d1888[2] = { /* 004d1888 8 */
    "{CR}=assemble   {^U}=previous addr   {^N}=next addr   {ESC}=exit assembler", 0
};

struct rec2w_18d52 d_4d1890[2] = { /* 004d1890 16 */
    { cmd_asm_h0, 1 },
    { cmd_asm_h1, 0 }
};

struct command_entry cmd_entry_asm[1] = { /* 004d18a0 32 */
    { "asm", "a", "assemble", (void *)&d_4d1808, (void *)&d_4d1810, cmd_asm_parse, 1, 0 }
};

long d_4d1d48[7] = { /* 004d1d48 28 */
    942482816L, 942482803L, 925705587L, 825042291L, 757429042L, 225653041L, 10
};

long d_4d1d70[8] = { /* 004d1d70 32 */
    621415808L, 628308013L, 628308013L, 628307757L, 1932669229L, 825306405L, 858858867L, 658803L
};

long d_4d1dc4[6] = { /* 004d1dc4 24 */
    625181569L, 1935770468L, 1651336563L, 1931508076L, 1668445551L, 101
};

long d_4d1ddc[6] = { /* 004d1ddc 24 */
    625181569L, 1634763620L, 1664054131L, 1600417391L, 1936941424L, 0
};

long d_4d1df4[5] = { /* 004d1df4 20 */
    625181569L, 2036564836L, 1936026723L, 1635021615L, 27756
};

long d_4d1e08[5] = { /* 004d1e08 20 */
    625181569L, 1869382500L, 1663070319L, 1701602169L, 115
};

long d_4d1e1c[4] = { /* 004d1e1c 16 */
    625181569L, 1684112228L, 1936028260L, 115
};

long d_4d1e2c[4] = { /* 004d1e2c 16 */
    625181569L, 1768719204L, 1847616878L, 11887
};

long d_4d1e98[2] = { /* 004d1e98 8 */
    542147456L, 8599603L
};

long d_4d1ea0[3] = { /* 004d1ea0 12 */
    760120111L, 875373876L, 33636L
};

long d_4d1eac[2] = { /* 004d1eac 8 */
    624184963L, 8610868L
};

long d_4d1ebc[3] = { /* 004d1ebc 12 */
    760120111L, 875373876L, 8610924L
};

long d_4d1ec8[2] = { /* 004d1ec8 8 */
    1932666240L, 0
};

long d_4d1ed0[2] = { /* 004d1ed0 8 */
    1932797312L, 0
};

unsigned long d_4d1ed8[3] = { /* 004d1ed8 12 */
    0x25344e83UL, 0x83646c34UL, 0
};

long d_4d1f08[2] = { /* 004d1f08 8 */
    625181569L, 33636L
};

long d_4d1f78[2] = { /* 004d1f78 8 */
    1933059456L, 0
};

unsigned long d_4d1fb4[3] = { /* 004d1fb4 12 */
    0x50830a0dUL, 0x8364252dUL, 0xa0dUL
};

unsigned long d_4d1fc8[3] = { /* 004d1fc8 12 */
    0x83732a25UL, 0x83372050UL, 0
};

long d_4d2018[5] = { /* 004d2018 20 */
    1317233445L, 1966351668L, 1317216387L, 1966351668L, 31875
};

long d_4d206c[2] = { /* 004d206c 8 */
    858607747L, 33584L
};

unsigned long d_4d2074[3] = { /* 004d2074 12 */
    0x50830a0dUL, 0x8330352dUL, 0
};

long d_4d21b4[7] = { /* 004d21b4 28 */
    824201347L, 757433136L, 628305970L, 628437041L, 628437041L, 225783857L, 10
};

unsigned long d_4d21dc[10] = { /* 004d21dc 40 */
    0x31205083UL, 0x2d258330UL, 0x25733032UL, 0x25733031UL, 0x25733031UL, 0xd733031UL, 0x2050830aUL, 0x83833031UL,
    0x30352d50UL, 0xa0d83UL
};

long d_4d2254 = 12; /* 004d2254 4 */

long d_4d2260[4] = { /* 004d2260 16 */
    840978563L, 1931838261L, 623792259L, 33636L
};

long d_4d2278[3] = { /* 004d2278 12 */
    891310211L, 544417155L, 0
};

long d_4d2284[5] = { /* 004d2284 20 */
    891310211L, 841819523L, 757429040L, 225652787L, 10
};

unsigned long d_4d233c[3] = { /* 004d233c 12 */
    0x83733825UL, 0x83322d50UL, 0xa0dUL
};

long d_4d2358[3] = { /* 004d2358 12 */
    824201347L, 757433136L, 7550257L
};

unsigned long d_4d239c[9] = { /* 004d239c 36 */
    0x31205083UL, 0x2d258330UL, 0x25733531UL, 0x25733031UL, 0xd733031UL, 0x2050830aUL, 0x83833031UL, 0x35332d50UL,
    0xa0d83UL
};

long d_4d24c8[2] = { /* 004d24c8 8 */
    841830531L, 33584L
};

long d_4d24d0[2] = { /* 004d24d0 8 */
    858607747L, 33591L
};

long d_4d2588[2] = { /* 004d2588 8 */
    875384963L, 33591L
};

const char *fmt_tab_16[5] = { /* 004d2758 20 */
    "$%04lx", "%05ld", (const char *)&empty_str, "$%04lx",
    "%05lu"
};

long d_4d276c = 0; /* 004d276c 4 */

const char *fmt_tab_24[5] = { /* 004d2770 20 */
    "$%06lx", "%07ld", (const char *)&empty_str, "$%06lx",
    "%07lu"
};

long d_4d2784 = 0; /* 004d2784 4 */

const char *fmt_tab_32[5] = { /* 004d2788 20 */
    "$%08lx", "%11ld", (const char *)&empty_str, "$%08lx",
    "%11lu"
};

const char *d_4d279c[19] = { /* 004d279c 76 */
    0, "$%04lx", "%05ld", (const char *)&empty_str,
    "$%04lx", "%05lu", 0, "$%06lx",
    "%07ld", (const char *)&empty_str, "$%06lx", "%07lu",
    0, "$%08lx", "%11ld", (const char *)&empty_str,
    "$%08lx", "%11lu", 0
};

const char *fmt_tab_16_nosym[5] = { /* 004d27e8 20 */
    (const char *)&empty_str, "%05ld", (const char *)&empty_str, "%04lx",
    "%05lu"
};

long d_4d27fc = 0; /* 004d27fc 4 */

const char *fmt_tab_24_nosym[5] = { /* 004d2800 20 */
    (const char *)&empty_str, "%07ld", (const char *)&empty_str, "%06lx",
    "%07lu"
};

long d_4d2814 = 0; /* 004d2814 4 */

const char *fmt_tab_32_nosym[5] = { /* 004d2818 20 */
    (const char *)&empty_str, "%11ld", (const char *)&empty_str, "%08lx",
    "%11lu"
};

long mdisk_block_bytes = 1024; /* 004d2878 4 */

unsigned long shr_fill_bit[2] = { /* 004d2970 8 */
    0x80000000UL, 0
};

long dec_split_16[4] = { /* 004d2978 16 */
    51712L, 15258, 0, 0
};

long dec_split_24[4] = { /* 004d2988 16 */
    10144256L, 59, 0, 1919973445L
};

unsigned char d_4d2b88[16] = { /* 004d2b88 16 */
    0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0
};

unsigned char d_4d2b9d[51] = { /* 004d2b9d 51 */
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0
};

unsigned char d_4d2bd5[47] = { /* 004d2bd5 47 */
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

long cdb_outcap = 64; /* 004d30a0 4 */

long d_4d3124 = 1768383858L; /* 004d3124 4 */

long d_4d3128 = 1919251571L; /* 004d3128 4 */

unsigned short d_4d312c[2] = { /* 004d312c 4 */
    32, 0
};

unsigned short d_4d32a4 = 30300; /* 004d32a4 2 */

unsigned char d_4d32a6[2] = { /* 004d32a6 2 */
    0, 0
};

unsigned short d_4d32a8 = 29788; /* 004d32a8 2 */

unsigned char d_4d32aa[2] = { /* 004d32aa 2 */
    0, 0
};

unsigned short d_4d32ac = 29276; /* 004d32ac 2 */

unsigned char d_4d32ae[2] = { /* 004d32ae 2 */
    0, 0
};

unsigned short d_4d32b0 = 28252; /* 004d32b0 2 */

unsigned char d_4d32b2[2] = { /* 004d32b2 2 */
    0, 0
};

unsigned short d_4d32b4 = 26204; /* 004d32b4 2 */

unsigned char d_4d32b6[2] = { /* 004d32b6 2 */
    0, 0
};

unsigned short d_4d32b8 = 25180; /* 004d32b8 2 */

unsigned char d_4d32ba[2] = { /* 004d32ba 2 */
    0, 0
};

unsigned short d_4d32bc = 24924; /* 004d32bc 2 */

unsigned char d_4d32be[2] = { /* 004d32be 2 */
    0, 0
};

unsigned short d_4d32c0 = 8796; /* 004d32c0 2 */

unsigned char d_4d32c2[2] = { /* 004d32c2 2 */
    0, 0
};

unsigned short d_4d32c4 = 10076; /* 004d32c4 2 */

unsigned char d_4d32c6[2] = { /* 004d32c6 2 */
    0, 0
};

unsigned short d_4d32c8 = 23644; /* 004d32c8 2 */

unsigned char d_4d32ca[2] = { /* 004d32ca 2 */
    0, 0
};

unsigned short d_4d32dc = 8236; /* 004d32dc 2 */

unsigned char d_4d32de[2] = { /* 004d32de 2 */
    0, 0
};

long d_4d32ec = 662068263L; /* 004d32ec 4 */

unsigned char d_4d32f0[4] = { /* 004d32f0 4 */
    0, 0, 0, 0
};

long d_4d32f4 = 661937191L; /* 004d32f4 4 */

unsigned char d_4d32f8[4] = { /* 004d32f8 4 */
    0, 0, 0, 0
};

long d_4d32fc = 661806119L; /* 004d32fc 4 */

unsigned char d_4d3300[4] = { /* 004d3300 4 */
    0, 0, 0, 0
};

long d_4d3304 = 661543975L; /* 004d3304 4 */

unsigned char d_4d3308[4] = { /* 004d3308 4 */
    0, 0, 0, 0
};

long d_4d330c = 661019687L; /* 004d330c 4 */

unsigned char d_4d3310[4] = { /* 004d3310 4 */
    0, 0, 0, 0
};

long d_4d3314 = 660757543L; /* 004d3314 4 */

unsigned char d_4d3318[4] = { /* 004d3318 4 */
    0, 0, 0, 0
};

long d_4d331c = 660692007L; /* 004d331c 4 */

unsigned char d_4d3320[4] = { /* 004d3320 4 */
    0, 0, 0, 0
};

long d_4d3324 = 656563239L; /* 004d3324 4 */

unsigned char d_4d3328[4] = { /* 004d3328 4 */
    0, 0, 0, 0
};

long d_4d332c = 656890919L; /* 004d332c 4 */

unsigned char d_4d3330[4] = { /* 004d3330 4 */
    0, 0, 0, 0
};

long d_4d3334 = 660364327L; /* 004d3334 4 */

unsigned char d_4d3338[4] = { /* 004d3338 4 */
    0, 0, 0, 0
};

unsigned short d_4d3360[2] = { /* 004d3360 4 */
    61, 0
};

const char *d_4d3448 = "Need more parameters"; /* 004d3448 4 */

const char *d_4d344c = "Invalid parameter"; /* 004d344c 4 */

const char *d_4d3450 = "Too many parameters"; /* 004d3450 4 */

const char *d_4d3454 = "Range of Break Number is 1-99"; /* 004d3454 4 */

const char *d_4d3458[8] = { /* 004d3458 32 */
    "h", "i1", "i2", "i3",
    "i4", "n", "s", "x"
};

const char *d_4d3478[4] = { /* 004d3478 16 */
    "r", "rw", "w", 0
};

const char *d_4d3488[4] = { /* 004d3488 16 */
    "dr", "drw", "dw", 0
};

const char *d_4d3498[4] = { /* 004d3498 16 */
    "!=", "==", "<", ">"
};

const char *d_4d34a8[4] = { /* 004d34a8 16 */
    "and", "or", "then", 0
};

const char *d_4d34b8[6] = { /* 004d34b8 24 */
    "b", "d", "f", "h",
    "u", 0
};

const char *d_4d34d0[10] = { /* 004d34d0 40 */
    "m0", "m1", "m2", "m3",
    "m4", "m5", "m6", "m7",
    "m8", 0
};

const char *d_4d34f8[6] = { /* 004d34f8 24 */
    "off", "on", "r", "rw",
    "w", 0
};

const char *d_4d3510[6] = { /* 004d3510 24 */
    "b", "d", "f", "h",
    "u", 0
};

const char *d_4d3528[5] = { /* 004d3528 20 */
    "-rb", "-rd", "-rf", "-rh",
    "-ru"
};

const char *d_4d353c = "pullup"; /* 004d353c 4 */

const char *d_4d3540[6] = { /* 004d3540 24 */
    "-rb", "-rd", "-rf", "-rh",
    "-ru", "-rs"
};

const char *d_4d3558[4] = { /* 004d3558 16 */
    "-a", "-c", "-o", 0
};

const char *d_4d3568[8] = { /* 004d3568 32 */
    "pcf", "pcm", "pcfm", "pce",
    "pa", "xa", "ya", 0
};

const char *d_4d3588[4] = { /* 004d3588 16 */
    "dma", "pa", "xa", "ya"
};

const char *d_4d3598[4] = { /* 004d3598 16 */
    "pa", "xa", "ya", 0
};

const char *d_4d35a8[4] = { /* 004d35a8 16 */
    "pcf", "pcm", "xab1", "xab2"
};

const char *d_4d35b8[4] = { /* 004d35b8 16 */
    "pcf", "pcm", "xab1", 0
};

const char *d_4d35c8[8] = { /* 004d35c8 32 */
    "pcf", "pcm", "pcfm", "pdma",
    "xa", "ya", "xdma", "ydma"
};

const char *d_4d35e8[18] = { /* 004d35e8 72 */
    "al", "cc", "cs", "ec",
    "eq", "es", "ge", "gt",
    "lc", "le", "ls", "lt",
    "mi", "ne", "pl", "nr",
    "nn", 0
};

const char *d_4d3630[17] = { /* 004d3630 68 */
    "al", "cc", "cs", "ec",
    "eq", "es", "ge", "gt",
    "lc", "le", "ls", "lt",
    "mi", "ne", "pl", "nr",
    "nn"
};

const char *d_4d3674 = "al"; /* 004d3674 4 */

const char *d_4d3678[36] = { /* 004d3678 144 */
    "cc", "cs", "eq", "ge",
    "gt", "hi", "le", "ls",
    "lt", "mi", "ne", "pl",
    "vc", "vs", "al", "fgt",
    "flt", "fge", "fle", "fgl",
    "finf", "fgle", "for", "feq",
    "fpl", "ferr", "fngt", "fnlt",
    "fnge", "fnle", "fngl", "fninf",
    "fngle", "fun", "fne", "fmi"
};

const char *d_4d3708[4] = { /* 004d3708 16 */
    "stdin", "stdout", "stderr", 0
};

simfn d_4d3718[2] = { /* 004d3718 8 */
    parm_nop, 0
};

simfn d_4d3720[2] = { /* 004d3720 8 */
    hid_43a3f0, 0
};

struct rec7w_ecd15 avl_cmp_tab[2] = { /* 004d3b48 68 */
    { avl_cmp_h46b6c0, prof_cmp_ulong, avl_cmp_h46b7c0, avl_cmp_h46b870, prof_cmp_srcloc, avl_cmp_h46bc60, avl_cmp_h46bd80 },
    { avl_cmp_h46bdc0, avl_cmp_h46bda0, prof_cmp_name_nocase, avl_cmp_h46bf00, avl_cmp_h46bf30, avl_cmp_h43de70, 0 }
};
struct flat_4d3b80 avl_cmp_tab_tail = { /* 004d3b80 tail of avl_cmp_tab */
    "OK", "FAILURE", "WARNING"
};

const char *d_4d3b8c[2] = { /* 004d3b8c 8 */
    "*** MAJOR PROFILING ERROR - SIMULATOR ABORTED ***", "Insufficient memory"
};

const char *d_4d3b94 = "No object file loaded"; /* 004d3b94 4 */

const char *d_4d3b98[7] = { /* 004d3b98 28 */
    "Failed to handle COFF file", "Null file name", "File %s does not exist", "Directory %s does not exist",
    "Permissions on %s", "Name %s exceeds length limit (%d)", "Value %d out of range for %s"
};

const char *d_4d3bb4[2] = { /* 004d3bb4 8 */
    "Failed to open file %s", "Failed to open source file %s"
};

const char *d_4d3bbc = "File %s, C sources not supported. suggesting"; /* 004d3bbc 4 */

const char *d_4d3bc0[3] = { /* 004d3bc0 12 */
    "Source file %s more recent than executable", "Failed to close file %s", "Failed to delete file %s"
};

const char *d_4d3bcc[4] = { /* 004d3bcc 16 */
    "Failed to read from file %s", "File %s, line %d: Invalid or missing file name", "File %s, line %d: Cannot open file %s", "File %s, line %d: Line too long"
};

void *d_4d3bdc = (void *)&empty_str; /* 004d3bdc 4 */

const char *d_4d3be0 = "File %s, line %d: Directive %s not allowed here"; /* 004d3be0 4 */

const char *d_4d3be4 = "File %s, line %d: Invalid directive"; /* 004d3be4 4 */

const char *d_4d3be8[2] = { /* 004d3be8 8 */
    "Profiler file not generated", (const char *)&empty_str
};

signed char d_4d3bf0[8] = { /* 004d3bf0 8 */
    0, 120, 121, 112, 108, 0, 0, 0
};

unsigned short d_4d3f0a[69] = { /* 004d3f0a 138 */
    0, 0, 0, 10536, 75, 35180, 74, 35188, 74, 35196, 74, 35204, 74, 35212, 74, 35220,
    74, 35228, 74, 35236, 74, 35244, 74, 35252, 74, 35260, 74, 35272, 74, 35284, 74, 35296,
    74, 35308, 74, 35320, 74, 10568, 75, 10564, 75, 10560, 75, 10556, 75, 10552, 75, 10548,
    75, 10544, 75, 10540, 75, 12252, 77, 12248, 77, 12244, 77, 12240, 77, 12236, 77, 12232,
    77, 12228, 77, 12224, 77
};

long frame_locals_buf_size = 80; /* 004d3f94 4 */

long cdb_lookup_cache_depth = -1; /* 004d4134 4 */

long cdb_lookup_cache_sym = -1; /* 004d4138 4 */

long d_4d413c[3] = { /* 004d413c 12 */
    1700947043L, 778854774L, 99
};

const char *ps_font_names[7] = { /* 004d4ef0 28 */
    "Helvetica", "Helvetica_Oblique", "Helvetica_Bold", "Courier",
    "Courier_Bold", "Courier_Oblique", "Times_Italic"
};

long d_4d54dc = 1919243808L; /* 004d54dc 4 */

long d_4d54e0 = 1852795251L; /* 004d54e0 4 */

unsigned char d_4d54e4[4] = { /* 004d54e4 4 */
    0, 0, 0, 0
};

long d_4d54e8[2] = { /* 004d54e8 8 */
    544240514L, 2573
};

long d_4d557c = 658700L; /* 004d557c 4 */

unsigned long d_4d5738[3] = { /* 004d5738 12 */
    0x50837325UL, 0x83642520UL, 0
};

unsigned long d_4d57c8[3] = { /* 004d57c8 12 */
    0x50837325UL, 0x83642520UL, 0x20UL
};

long d_4d57d4[3] = { /* 004d57d4 12 */
    959271043L, 168657714L, 0
};
