/* simd_dev.c - GENERATED by re/scripts/gentab_sim.py from SIM56000.EXE; do not edit. */
#include "simdata.h"

extern void disassemble_l1();
extern void hid_423ae0();
extern void hid_424130();
extern void hid_4243f0();

unsigned short d_4a0002[63] = { /* 004a0002 126 */
    0, 61, 4, 0, 0, 65535, 15, 0, 0, 24576, 256, 0, 0, 65535, 15, 1,
    1024, 1, 0, 34184, 74, 91, 0, 62, 4, 0, 0, 65535, 7, 0, 0, 24576,
    256, 0, 0, 65535, 7, 1, 4096, 1, 0, 34180, 74, 92, 0, 63, 4, 0,
    0, 65535, 15, 0, 0, 24576, 256, 0, 0, 65535, 15, 1, 4096, 1, 0
};

struct mem_region regions_4a0080[82] = { /* 004a0080 3608 */
    { "p", 0, 0x8c300000UL, 0, 65535L, 0, 0x201000UL, 0, 65535L, 0x4000001UL, 1 },
    { "pe", 13, 0xc000000UL, 0, 65535L, 0, 0x1607004UL, 0, 65535L, 0x4000001UL, 1 },
    { "pi", 14, 0x80200000UL, 0, 255, 256, 0x627000UL, 0, 65535L, 0x4000001UL, 1 },
    { "pi", 14, 0x80200000UL, 1024, 3583, 2560, 0x627008UL, 0, 65535L, 0x4000001UL, 1 },
    { "pr", 15, 0x80100000UL, 0, 31, 32, 0x60f008UL, 4816152L, 65535L, 0x4000001UL, 1 },
    { "x", 1, 0x43300000UL, 0, 65535L, 0, 0x200000UL, 0, 65535L, 0x4000001UL, 1 },
    { "xe", 18, 0x3000000UL, 0, 65535L, 0, 0x1606004UL, 0, 65535L, 0x4000001UL, 1 },
    { "xi", 19, 0x40200000UL, 0, 255, 256, 0x626000UL, 0, 65535L, 0x4000001UL, 1 },
    { "xi", 19, 0x40200000UL, 65472L, 65535L, 0, 0x616000UL, 0, 65535L, 0x4000001UL, 1 },
    { "xr", 20, 0x40100000UL, 256, 511, 256, 0x60e008UL, 4816408L, 65535L, 0x4000001UL, 1 },
    { "y", 2, 0x20f00000UL, 0, 65535L, 0, 0x200000UL, 0, 65535L, 0x4000001UL, 1 },
    { "ye", 23, 0xc00000UL, 0, 65535L, 0, 0x1606004UL, 0, 65535L, 0x4000001UL, 1 },
    { "yi", 24, 0x20200000UL, 0, 255, 256, 0x606000UL, 0, 65535L, 0x4000001UL, 1 },
    { "yr", 25, 0x20100000UL, 256, 511, 256, 0x60e008UL, 4818456L, 65535L, 0x4000001UL, 1 },
    { "l", 3, 0x13e00000UL, 0, 65535L, 0, 0x200000UL, 0, 65535L, 0x800002UL, 1 },
    { "le", 9, 0x13c00000UL, 0, 65535L, 0, 0x1602004UL, 0, 65535L, 0x800002UL, 1 },
    { "li", 10, 0x10200000UL, 0, 255, 0, 0x602000UL, 0, 65535L, 0x800002UL, 1 },
    { "em", 28, 0x40040UL, 0, 4194303L, 0, 0x1606000UL, 0, 8388607L, 0x40000001UL, 1 },
    { "e0", 29, 0x40000UL, 0, 32767, 0, 0x1006000UL, 0, 32767, 0x40000001UL, 2 },
    { "e1", 30, 0x40001UL, 0, 32767, 0, 0x1006000UL, 0, 32767, 0x40000001UL, 1 },
    { "e2", 31, 0x40002UL, 0, 32767, 0, 0x1006000UL, 0, 32767, 0x10000001UL, 4 },
    { "e3", 32, 0x40003UL, 0, 32767, 0, 0x1006000UL, 0, 32767, 0x10000001UL, 2 },
    { "e4", 33, 0x40004UL, 0, 32767, 0, 0x1006000UL, 0, 32767, 0x4000001UL, 6 },
    { "e5", 34, 0x40005UL, 0, 32767, 0, 0x1006000UL, 0, 32767, 0x4000001UL, 3 },
    { "e6", 35, 0x40006UL, 0, 32767, 0, 0x1006000UL, 0, 32767, 0x10000001UL, 4 },
    { "e7", 36, 0x40007UL, 0, 32767, 0, 0x1006000UL, 0, 32767, 0x10000001UL, 2 },
    { "e8", 37, 0x40008UL, 0, 131071L, 0, 0x1006000UL, 0, 131071L, 0x40000001UL, 1 },
    { "e9", 38, 0x40009UL, 0, 262143L, 0, 0x1006000UL, 0, 262143L, 0x40000001UL, 1 },
    { "e10", 39, 0x4000aUL, 0, 65535L, 0, 0x1006000UL, 0, 65535L, 0x10000001UL, 1 },
    { "e11", 40, 0x4000bUL, 0, 131071L, 0, 0x1006000UL, 0, 131071L, 0x10000001UL, 1 },
    { "e12", 41, 0x4000cUL, 0, 32767, 0, 0x1006000UL, 0, 32767, 0x4000001UL, 1 },
    { "e13", 42, 0x4000dUL, 0, 65535L, 0, 0x1006000UL, 0, 65535L, 0x4000001UL, 1 },
    { "e14", 43, 0x4000eUL, 0, 32767, 0, 0x1006000UL, 0, 32767, 0x10000001UL, 1 },
    { "e15", 44, 0x4000fUL, 0, 65535L, 0, 0x1006000UL, 0, 65535L, 0x10000001UL, 1 },
    { "e16", 45, 0x40010UL, 0, 131071L, 0, 0x1006000UL, 0, 131071L, 0x40000001UL, 1 },
    { "e17", 46, 0x40011UL, 0, 262143L, 0, 0x1006000UL, 0, 262143L, 0x40000001UL, 1 },
    { "e18", 47, 0x40012UL, 0, 65535L, 0, 0x1006000UL, 0, 65535L, 0x10000001UL, 1 },
    { "e19", 48, 0x40013UL, 0, 131071L, 0, 0x1006000UL, 0, 131071L, 0x10000001UL, 1 },
    { "e20", 49, 0x40014UL, 0, 32767, 0, 0x1006000UL, 0, 32767, 0x4000001UL, 1 },
    { "e21", 50, 0x40015UL, 0, 65535L, 0, 0x1006000UL, 0, 65535L, 0x4000001UL, 1 },
    { "e22", 51, 0x40016UL, 0, 32767, 0, 0x1006000UL, 0, 32767, 0x10000001UL, 1 },
    { "e23", 52, 0x40017UL, 0, 65535L, 0, 0x1006000UL, 0, 65535L, 0x10000001UL, 1 },
    { "e24", 53, 0x40018UL, 0, 65535L, 0, 0x1006000UL, 0, 65535L, 0x40000001UL, 1 },
    { "e25", 54, 0x40019UL, 0, 131071L, 0, 0x1006000UL, 0, 131071L, 0x40000001UL, 1 },
    { "e26", 55, 0x4001aUL, 0, 32767, 0, 0x1006000UL, 0, 32767, 0x10000001UL, 1 },
    { "e27", 56, 0x4001bUL, 0, 65535L, 0, 0x1006000UL, 0, 65535L, 0x10000001UL, 1 },
    { "e28", 57, 0x4001cUL, 0, 16383, 0, 0x1006000UL, 0, 16383, 0x4000001UL, 1 },
    { "e29", 58, 0x4001dUL, 0, 32767, 0, 0x1006000UL, 0, 32767, 0x4000001UL, 1 },
    { "e30", 59, 0x4001eUL, 0, 16383, 0, 0x1006000UL, 0, 16383, 0x10000001UL, 1 },
    { "e31", 60, 0x4001fUL, 0, 32767, 0, 0x1006000UL, 0, 32767, 0x10000001UL, 1 },
    { "e32", 61, 0x40020UL, 0, 32767, 0, 0x1006000UL, 0, 32767, 0x40000001UL, 1 },
    { "e33", 62, 0x40021UL, 0, 65535L, 0, 0x1006000UL, 0, 65535L, 0x40000001UL, 1 },
    { "e34", 63, 0x40022UL, 0, 16383, 0, 0x1006000UL, 0, 16383, 0x10000001UL, 1 },
    { "e35", 64, 0x40023UL, 0, 32767, 0, 0x1006000UL, 0, 32767, 0x10000001UL, 1 },
    { "e36", 65, 0x40024UL, 0, 8191, 0, 0x1006000UL, 0, 8191, 0x4000001UL, 1 },
    { "e37", 66, 0x40025UL, 0, 16383, 0, 0x1006000UL, 0, 16383, 0x4000001UL, 1 },
    { "e38", 67, 0x40026UL, 0, 8191, 0, 0x1006000UL, 0, 8191, 0x10000001UL, 1 },
    { "e39", 68, 0x40027UL, 0, 16383, 0, 0x1006000UL, 0, 16383, 0x10000001UL, 1 },
    { "e40", 69, 0x40028UL, 0, 131071L, 0, 0x1006000UL, 0, 131071L, 0x40000001UL, 1 },
    { "e41", 70, 0x40029UL, 0, 262143L, 0, 0x1006000UL, 0, 262143L, 0x40000001UL, 1 },
    { "e42", 71, 0x4002aUL, 0, 65535L, 0, 0x1006000UL, 0, 65535L, 0x10000001UL, 1 },
    { "e43", 72, 0x4002bUL, 0, 131071L, 0, 0x1006000UL, 0, 131071L, 0x10000001UL, 1 },
    { "e44", 73, 0x4002cUL, 0, 32767, 0, 0x1006000UL, 0, 32767, 0x4000001UL, 1 },
    { "e45", 74, 0x4002dUL, 0, 65535L, 0, 0x1006000UL, 0, 65535L, 0x4000001UL, 1 },
    { "e46", 75, 0x4002eUL, 0, 32767, 0, 0x1006000UL, 0, 32767, 0x10000001UL, 1 },
    { "e47", 76, 0x4002fUL, 0, 65535L, 0, 0x1006000UL, 0, 65535L, 0x10000001UL, 1 },
    { "e48", 77, 0x40030UL, 0, 524287L, 0, 0x1006000UL, 0, 524287L, 0x40000001UL, 1 },
    { "e49", 78, 0x40031UL, 0, 1048575L, 0, 0x1006000UL, 0, 1048575L, 0x40000001UL, 1 },
    { "e50", 79, 0x40032UL, 0, 262143L, 0, 0x1006000UL, 0, 262143L, 0x10000001UL, 1 },
    { "e51", 80, 0x40033UL, 0, 524287L, 0, 0x1006000UL, 0, 524287L, 0x10000001UL, 1 },
    { "e52", 81, 0x40034UL, 0, 131071L, 0, 0x1006000UL, 0, 131071L, 0x4000001UL, 1 },
    { "e53", 82, 0x40035UL, 0, 262143L, 0, 0x1006000UL, 0, 262143L, 0x4000001UL, 1 },
    { "e54", 83, 0x40036UL, 0, 131071L, 0, 0x1006000UL, 0, 131071L, 0x10000001UL, 1 },
    { "e55", 84, 0x40037UL, 0, 262143L, 0, 0x1006000UL, 0, 262143L, 0x10000001UL, 1 },
    { "e56", 85, 0x40038UL, 0, 2097151L, 0, 0x1006000UL, 0, 2097151L, 0x40000001UL, 1 },
    { "e57", 86, 0x40039UL, 0, 4194303L, 0, 0x1006000UL, 0, 4194303L, 0x40000001UL, 1 },
    { "e58", 87, 0x4003aUL, 0, 1048575L, 0, 0x1006000UL, 0, 1048575L, 0x10000001UL, 1 },
    { "e59", 88, 0x4003bUL, 0, 2097151L, 0, 0x1006000UL, 0, 2097151L, 0x10000001UL, 1 },
    { "e60", 89, 0x4003cUL, 0, 524287L, 0, 0x1006000UL, 0, 524287L, 0x4000001UL, 1 },
    { "e61", 90, 0x4003dUL, 0, 1048575L, 0, 0x1006000UL, 0, 1048575L, 0x4000001UL, 1 },
    { "e62", 91, 0x4003eUL, 0, 524287L, 0, 0x1006000UL, 0, 524287L, 0x10000001UL, 1 },
    { "e63", 92, 0x4003fUL, 0, 1048575L, 0, 0x1006000UL, 0, 1048575L, 0x10000001UL, 1 }
};

long d_4a0e98[186] = { /* 004a0e98 744 */
    66575L, 66575L, 456704L, 262144L, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0
};

long d_4a1180[128] = { /* 004a1180 512 */
    66575L, 66575L, 393728L, 393728L, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0
};

long d_4a1380[94] = { /* 004a1380 376 */
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0
};

long d_4a14f8[260] = { /* 004a14f8 1040 */
    66575L, 66575L, 262144L, 262144L, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 536870656L, 536870656L, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0
};

long d_4a1908[260] = { /* 004a1908 1040 */
    66575L, 66575L, 262144L, 262144L, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0
};

long d_4a1d18[222] = { /* 004a1d18 888 */
    3145743L, 3145743L, 4194304L, 4194304L, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0
};

long d_4a2090[222] = { /* 004a2090 888 */
    3212303L, 3212303L, 4194304L, 4194304L, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0
};

struct rec5w_202fb d_4a2408[8] = { /* 004a2408 160 */
    { "ctrl", 0, 25230848L, 0, 0 },
    { "porta", 1, 65535L, 0, 0 },
    { "addr", 1, 65535L, 0, 0 },
    { "abus", 1, 65535L, 0, 0 },
    { "portd", 4, 16777215L, 0, 0 },
    { "dbus", 4, 16777215L, 0, 0 },
    { "data", 4, 16777215L, 0, 0 },
    { "imc", 0, 7, 0, 0 }
};

struct rec5w_202fb d_4a24a8[2] = { /* 004a24a8 40 */
    { "portd", 4, 15, 0, 0 },
    { "imc", 0, 7, 0, 0 }
};

struct rec5w_202fb d_4a24d0[2] = { /* 004a24d0 40 */
    { "portd", 4, 255, 0, 0 },
    { "imc", 0, 7, 0, 0 }
};

struct dev_type dev_56007[1] = { /* 004a24f8 1248 */
    { "56007", 709, 512, 67108872L, 0, 6, (struct periph_desc *)&periph_495038, 169, (struct mem_region *)&regions_49ca20, "DSPMEM", (struct core_vtable *)&core_vtable_56000, 29, 7, (void *)&d_4a14f8, 51, (void *)&d_499258, 2, (void *)&d_4a24a8, { 0 }, 0 }
};

long d_4a29d8[4] = { /* 004a29d8 16 */
    0, 0, 0, 0
};

struct dev_type dev_56011[1] = { /* 004a29e8 1248 */
    { "56011", 709, 4096, 67108872L, 0, 8, (struct periph_desc *)&periph_495398, 25, (struct mem_region *)&regions_49c1b0, "DSPMEM", (struct core_vtable *)&core_vtable_56011, 29, 7, (void *)&d_4a1908, 43, (void *)&d_499720, 2, (void *)&d_4a24d0, { 0 }, 0 }
};

long d_4a2ec8[4] = { /* 004a2ec8 16 */
    0, 0, 0, 0
};

struct dev_type dev_56012[1] = { /* 004a2ed8 1248 */
    { "56012", 709, 8192, 67108872L, 0, 8, (struct periph_desc *)&periph_495398, 24, (struct mem_region *)&regions_49c600, "DSPMEM", (struct core_vtable *)&core_vtable_56012, 29, 7, (void *)&d_4a1908, 43, (void *)&d_499720, 2, (void *)&d_4a24d0, { 0 }, 0 }
};

long d_4a33b8[4] = { /* 004a33b8 16 */
    0, 0, 0, 0
};

struct dev_type dev_56009[1] = { /* 004a33c8 1248 */
    { "56009", 709, 1024, 67108872L, 0, 6, (struct periph_desc *)&periph_4951e8, 169, (struct mem_region *)&regions_49a4a0, "DSPMEM", (struct core_vtable *)&core_vtable_56009, 29, 7, (void *)&d_4a14f8, 51, (void *)&d_499258, 2, (void *)&d_4a24a8, { 0 }, 0 }
};

struct rec20w_2eab5 d_4a38a8[16] = { /* 004a38a8 1280 */
    { 0, 0, 0, 0, "56003", 709, 36, 67108872L, 2, 10, (void *)&periph_4955d8, 17, (void *)&regions_49e730, "DSPMEM", (void *)&core_vtable_56000, 29, 6, (void *)&d_4a2090, 101, (void *)&d_499b28 },
    { 8, (void *)&d_4a2408, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
    { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
    { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
    { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
    { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
    { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
    { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
    { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
    { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
    { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
    { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
    { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
    { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
    { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
    { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }
};

struct dev_type dev_56002[1] = { /* 004a3da8 1248 */
    { "56002", 709, 4, 67108872L, 2, 8, (struct periph_desc *)&periph_4958a8, 17, (struct mem_region *)&regions_49ea20, "DSPMEM", (struct core_vtable *)&core_vtable_56000, 29, 6, (void *)&d_4a1180, 88, (void *)&d_498a18, 8, (void *)&d_4a2408, { 0 }, 0 }
};

long d_4a4288[4] = { /* 004a4288 16 */
    0, 0, 0, 0
};

struct dev_type dev_56000[1] = { /* 004a4298 1248 */
    { "56000", 709, 1, 67108872L, 2, 7, (struct periph_desc *)&periph_495c98, 15, (struct mem_region *)&regions_49efd0, "DSPMEM", (struct core_vtable *)&core_vtable_56000, 29, 5, (void *)&d_4a0e98, 88, (void *)&d_498a18, 8, (void *)&d_4a2408, { 0 }, 0 }
};

long d_4a4778[4] = { /* 004a4778 16 */
    0, 0, 0, 0
};

struct dev_type dev_56001[1] = { /* 004a4788 1248 */
    { "56001", 709, 2, 67108872L, 2, 7, (struct periph_desc *)&periph_495c98, 16, (struct mem_region *)&regions_49ed10, "DSPMEM", (struct core_vtable *)&core_vtable_56000, 29, 5, (void *)&d_4a0e98, 88, (void *)&d_498a18, 8, (void *)&d_4a2408, { 0 }, 0 }
};

long d_4a4c68[4] = { /* 004a4c68 16 */
    0, 0, 0, 0
};

struct dev_type dev_56004[1] = { /* 004a4c78 1248 */
    { "56004", 709, 8, 67108872L, 0, 6, (struct periph_desc *)&periph_495ae8, 82, (struct mem_region *)&regions_49f268, "DSPMEM", (struct core_vtable *)&core_vtable_56000, 29, 7, (void *)&d_4a14f8, 51, (void *)&d_499258, 2, (void *)&d_4a24a8, { 0 }, 0 }
};

long d_4a5158[4] = { /* 004a5158 16 */
    0, 0, 0, 0
};

struct dev_type dev_56004rom[1] = { /* 004a5168 1248 */
    { "56004rom", 709, 264, 67108872L, 0, 6, (struct periph_desc *)&periph_495ae8, 82, (struct mem_region *)&regions_4a0080, "DSPMEM", (struct core_vtable *)&core_vtable_56000, 29, 7, (void *)&d_4a14f8, 51, (void *)&d_499258, 2, (void *)&d_4a24a8, { 0 }, 0 }
};

long d_4a5648[4] = { /* 004a5648 16 */
    0, 0, 0, 0
};

struct dev_type dev_56005[1] = { /* 004a5658 1248 */
    { "56005", 709, 68, 67108872L, 2, 10, (struct periph_desc *)&periph_4955d8, 17, (struct mem_region *)&regions_49e730, "DSPMEM", (struct core_vtable *)&core_vtable_56000, 29, 6, (void *)&d_4a1d18, 101, (void *)&d_499b28, 8, (void *)&d_4a2408, { 0 }, 0 }
};

long d_4a5b38[4] = { /* 004a5b38 16 */
    0, 0, 0, 0
};

long d_4a5b48[286] = { /* 004a5b48 1144 */
    15, 15, 15, 19, 15, 19, 19, 19,
    19, 19, 19, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15
};

const char *d_4a5fc0[286] = { /* 004a5fc0 1144 */
    "pe, pi or pr depending upon address and omr value.", "xi, xe or xr depending upon address and omr values", "yi, ye or yr depending upon address and omr values", "li or le depending upon address and omr values",
    0, 0, 0, 0,
    0, "external long data memory", "on-chip long data ram", 0,
    0, "external program memory", "internal program ram or program rom", "internal bootstrap rom",
    0, 0, "external x data memory", "on-chip x data ram",
    "on-chip x data rom", 0, 0, "external y data memory",
    "internal y data ram", "internal y data rom", 0, 0,
    "emi peripheral memory - byte wide or nibble wide", "emi 1X32k SRAM EWL=0 (8 bit data) EBW=0 (nibble)", "emi 1X32k SRAM EWL=0 (8 bit data) EBW=1 (byte)", "emi 1X32k SRAM EWL=1 (16 bit data) EBW=0 (nibble)",
    "emi 1X32k SRAM EWL=1 (16 bit data) EBW=1 (byte)", "emi 1X32k SRAM EWL=2 (24 bit data) EBW=0 (nibble)", "emi 1X32k SRAM EWL=2 (24 bit data) EBW=1 (byte)", "emi 1X32k SRAM EWL=3 (16 bit data/24 bit addr) EBW=0 (nibble)",
    "emi 1X32k SRAM (16 bit data/24 bit addr) EBW=1 (byte)", "emi 1X256k SRAM EWL=0 (8 bit data) EBW=0 (nibble)", "emi 1X256k SRAM EWL=0 (8 bit data) EBW=1 (byte)", "emi 1X256k SRAM EWL=1 (16 bit data) EBW=0 (nibble)",
    "emi 1X256k SRAM EWL=1 (16 bit data) EBW=1 (byte)", "emi 1X256k SRAM EWL=2 (24 bit data) EBW=0 (nibble)", "emi 1X256k SRAM EWL=2 (24 bit data) EBW=1 (byte)", "emi 1X256k SRAM EWL=3 (16 bit data/24 bit addr) EBW=0 (nibble)",
    "emi 1X256k SRAM (16 bit data/24 bit addr) EBW=1 (byte)", "emi 2X128k SRAM EWL=0 (8 bit data) EBW=0 (nibble)", "emi 2X128k SRAM EWL=0 (8 bit data) EBW=1 (byte)", "emi 2X128k SRAM EWL=1 (16 bit data) EBW=0 (nibble)",
    "emi 2X128k SRAM EWL=1 (16 bit data) EBW=1 (byte)", "emi 2X128k SRAM EWL=2 (24 bit data) EBW=0 (nibble)", "emi 2X128k SRAM EWL=2 (24 bit data) EBW=1 (byte)", "emi 2X128k SRAM EWL=3 (16 bit data/24 bit addr) EBW=0 (nibble)",
    "emi 2X128k SRAM (16 bit data/24 bit addr) EBW=1 (byte)", "emi 4X32k SRAM EWL=0 (8 bit data) EBW=0 (nibble)", "emi 4X32k SRAM EWL=0 (8 bit data) EBW=1 (byte)", "emi 4X32k SRAM EWL=1 (16 bit data) EBW=0 (nibble)",
    "emi 4X32k SRAM EWL=1 (16 bit data) EBW=1 (byte)", "emi 4X32k SRAM EWL=2 (24 bit data) EBW=0 (nibble)", "emi 4X32k SRAM EWL=2 (24 bit data) EBW=1 (byte)", "emi 4X32k SRAM EWL=3 (16 bit data/24 bit addr) EBW=0 (nibble)",
    "emi 4X32k SRAM (16 bit data/24 bit addr) EBW=1 (byte)", "emi 64k DRAM EWL=0 (8 bit data) EBW=0 (nibble)", "emi 64k DRAM EWL=0 (8 bit data) EBW=1 (byte)", "emi 64k DRAM EWL=1 (16 bit data) EBW=0 (nibble)",
    "emi 64k DRAM EWL=1 (16 bit data) EBW=1 (byte)", "emi 64k DRAM EWL=2 (24 bit data) EBW=0 (nibble)", "emi 64k DRAM EWL=2 (24 bit data) EBW=1 (byte)", "emi 64k DRAM EWL=3 (16 bit data/24 bit addr) EBW=0 (nibble)",
    "emi 64k DRAM (16 bit data/24 bit addr) EBW=1 (byte)", "emi 256k DRAM EWL=0 (8 bit data) EBW=0 (nibble)", "emi 256k DRAM EWL=0 (8 bit data) EBW=1 (byte)", "emi 256k DRAM EWL=1 (16 bit data) EBW=0 (nibble)",
    "emi 256k DRAM EWL=1 (16 bit data) EBW=1 (byte)", "emi 256k DRAM EWL=2 (24 bit data) EBW=0 (nibble)", "emi 256k DRAM EWL=2 (24 bit data) EBW=1 (byte)", "emi 256k DRAM EWL=3 (16 bit data/24 bit addr) EBW=0 (nibble)",
    "emi 256k DRAM (16 bit data/24 bit addr) EBW=1 (byte)", "emi 1M DRAM EWL=0 (8 bit data) EBW=0 (nibble)", "emi 1M DRAM EWL=0 (8 bit data) EBW=1 (byte)", "emi 1M DRAM EWL=1 (16 bit data) EBW=0 (nibble)",
    "emi 1M DRAM EWL=1 (16 bit data) EBW=1 (byte)", "emi 1M DRAM EWL=2 (24 bit data) EBW=0 (nibble)", "emi 1M DRAM EWL=2 (24 bit data) EBW=1 (byte)", "emi 1M DRAM EWL=3 (16 bit data/24 bit addr) EBW=0 (nibble)",
    "emi 1M DRAM (16 bit data/24 bit addr) EBW=1 (byte)", "emi 4M DRAM EWL=0 (8 bit data) EBW=0 (nibble)", "emi 4M DRAM EWL=0 (8 bit data) EBW=1 (byte)", "emi 4M DRAM EWL=1 (16 bit data) EBW=0 (nibble)",
    "emi 4M DRAM EWL=1 (16 bit data) EBW=1 (byte)", "emi 4M DRAM EWL=2 (24 bit data) EBW=0 (nibble)", "emi 4M DRAM EWL=2 (24 bit data) EBW=1 (byte)", "emi 4M DRAM EWL=3 (16 bit data/24 bit addr) EBW=0 (nibble)",
    "emi 4M DRAM (16 bit data/24 bit addr) EBW=1 (byte)", 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, "emi 64k direct DRAM EWL=0 (8 bit data) EBW=0 (nibble)", "emi 64k direct DRAM EWL=0 (8 bit data) EBW=1 (byte)", "emi 64k direct DRAM EWL=1 (16 bit data) EBW=0 (nibble)",
    "emi 64k direct DRAM EWL=1 (16 bit data) EBW=1 (byte)", "emi 64k direct DRAM EWL=2 (24 bit data) EBW=0 (nibble)", "emi 64k direct DRAM EWL=2 (24 bit data) EBW=1 (byte)", "emi 64k direct DRAM EWL=3 (16 bit data/24 bit addr) EBW=0 (nibble)",
    "emi 64k direct DRAM (16 bit data/24 bit addr) EBW=1 (byte)", "emi 256k direct DRAM EWL=0 (8 bit data) EBW=0 (nibble)", "emi 256k direct DRAM EWL=0 (8 bit data) EBW=1 (byte)", "emi 256k direct DRAM EWL=1 (16 bit data) EBW=0 (nibble)",
    "emi 256k direct DRAM EWL=1 (16 bit data) EBW=1 (byte)", "emi 256k direct DRAM EWL=2 (24 bit data) EBW=0 (nibble)", "emi 256k direct DRAM EWL=2 (24 bit data) EBW=1 (byte)", "emi 256k direct DRAM EWL=3 (16 bit data/24 bit addr) EBW=0 (nibble)",
    "emi 256k direct DRAM (16 bit data/24 bit addr) EBW=1 (byte)", "emi 1M direct DRAM EWL=0 (8 bit data) EBW=0 (nibble)", "emi 1M direct DRAM EWL=0 (8 bit data) EBW=1 (byte)", "emi 1M direct DRAM EWL=1 (16 bit data) EBW=0 (nibble)",
    "emi 1M direct DRAM EWL=1 (16 bit data) EBW=1 (byte)", "emi 1M direct DRAM EWL=2 (24 bit data) EBW=0 (nibble)", "emi 1M direct DRAM EWL=2 (24 bit data) EBW=1 (byte)", "emi 1M direct DRAM EWL=3 (16 bit data/24 bit addr) EBW=0 (nibble)",
    "emi 1M direct DRAM (16 bit data/24 bit addr) EBW=1 (byte)", "emi 4M direct DRAM EWL=0 (8 bit data) EBW=0 (nibble)", "emi 4M direct DRAM EWL=0 (8 bit data) EBW=1 (byte)", "emi 4M direct DRAM EWL=1 (16 bit data) EBW=0 (nibble)",
    "emi 4M direct DRAM EWL=1 (16 bit data) EBW=1 (byte)", "emi 4M direct DRAM EWL=2 (24 bit data) EBW=0 (nibble)", "emi 4M direct DRAM EWL=2 (24 bit data) EBW=1 (byte)", "emi 4M direct DRAM EWL=3 (16 bit data/24 bit addr) EBW=0 (nibble)",
    "emi 4M direct DRAM (16 bit data/24 bit addr) EBW=1 (byte)", 0, 0, "emi 1X32k SRAM EWL=1 (12 bit data) EBW=0 (nibble)",
    "emi 1X32k SRAM EWL=1 (12 bit data) EBW=1 (byte)", "emi 1X32k SRAM EWL=2 (20 bit data) EBW=0 (nibble)", "emi 1X32k SRAM EWL=2 (20 bit data) EBW=1 (byte)", 0,
    0, 0, 0, "emi 1X256k SRAM EWL=1 (12 bit data) EBW=0 (nibble)",
    "emi 1X256k SRAM EWL=1 (12 bit data) EBW=1 (byte)", "emi 1X256k SRAM EWL=2 (20 bit data) EBW=0 (nibble)", "emi 1X256k SRAM EWL=2 (20 bit data) EBW=1 (byte)", 0,
    0, 0, 0, "emi 2X128k SRAM EWL=1 (12 bit data) EBW=0 (nibble)",
    "emi 2X128k SRAM EWL=1 (12 bit data) EBW=1 (byte)", "emi 2X128k SRAM EWL=2 (20 bit data) EBW=0 (nibble)", "emi 2X128k SRAM EWL=2 (20 bit data) EBW=1 (byte)", 0,
    0, 0, 0, "emi 4X32k SRAM EWL=1 (12 bit data) EBW=0 (nibble)",
    "emi 4X32k SRAM EWL=1 (12 bit data) EBW=1 (byte)", "emi 4X32k SRAM EWL=2 (20 bit data) EBW=0 (nibble)", "emi 4X32k SRAM EWL=2 (20 bit data) EBW=1 (byte)", 0,
    0, 0, 0, "emi 64k DRAM EWL=1 (12 bit data) EBW=0 (nibble)",
    "emi 64k DRAM EWL=1 (12 bit data) EBW=1 (byte)", "emi 64k DRAM EWL=2 (20 bit data) EBW=0 (nibble)", "emi 64k DRAM EWL=2 (20 bit data) EBW=1 (byte)", 0,
    0, 0, 0, "emi 256k DRAM EWL=1 (12 bit data) EBW=0 (nibble)",
    "emi 256k DRAM EWL=1 (12 bit data) EBW=1 (byte)", "emi 256k DRAM EWL=2 (20 bit data) EBW=0 (nibble)", "emi 256k DRAM EWL=2 (20 bit data) EBW=1 (byte)", 0,
    0, 0, 0, "emi 1M DRAM EWL=1 (12 bit data) EBW=0 (nibble)",
    "emi 1M DRAM EWL=1 (12 bit data) EBW=1 (byte)", "emi 1M DRAM EWL=2 (20 bit data) EBW=0 (nibble)", "emi 1M DRAM EWL=2 (20 bit data) EBW=1 (byte)", 0,
    0, 0, 0, "emi 4M DRAM EWL=1 (12 bit data) EBW=0 (nibble)",
    "emi 4M DRAM EWL=1 (12 bit data) EBW=1 (byte)", "emi 4M DRAM EWL=2 (20 bit data) EBW=0 (nibble)", "emi 4M DRAM EWL=2 (20 bit data) EBW=1 (byte)", 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, "emi 64k DRAM EWL=1 (12 bit data) EBW=0 (nibble)",
    "emi 64k DRAM EWL=1 (12 bit data) EBW=1 (byte)", "emi 64k DRAM EWL=2 (20 bit data) EBW=0 (nibble)", "emi 64k DRAM EWL=2 (20 bit data) EBW=1 (byte)", 0,
    0, 0, 0, "emi 256k DRAM EWL=1 (12 bit data) EBW=0 (nibble)",
    "emi 256k DRAM EWL=1 (12 bit data) EBW=1 (byte)", "emi 256k DRAM EWL=2 (20 bit data) EBW=0 (nibble)", "emi 256k DRAM EWL=2 (20 bit data) EBW=1 (byte)", 0,
    0, 0, 0, "emi 1M DRAM EWL=1 (12 bit data) EBW=0 (nibble)",
    "emi 1M DRAM EWL=1 (12 bit data) EBW=1 (byte)", "emi 1M DRAM EWL=2 (20 bit data) EBW=0 (nibble)", "emi 1M DRAM EWL=2 (20 bit data) EBW=1 (byte)", 0,
    0, 0, 0, "emi 4M DRAM EWL=1 (12 bit data) EBW=0 (nibble)",
    "emi 4M DRAM EWL=1 (12 bit data) EBW=1 (byte)", "emi 4M DRAM EWL=2 (20 bit data) EBW=0 (nibble)", "emi 4M DRAM EWL=2 (20 bit data) EBW=1 (byte)", 0,
    0, "direct access to memory on the 68000 bus"
};

const char *d_4a6438[10] = { /* 004a6438 40 */
    "B", (const char *)&d_4b9f90, (const char *)&d_4b91c0, (const char *)&d_4b8170,
    (const char *)&d_4b74c0, (const char *)&d_4b74c0, (const char *)&d_4b7088, (const char *)&d_4b6ef8,
    (const char *)&d_4b6978, (const char *)&d_4b66b0
};

const char *d_4a6460[6] = { /* 004a6460 24 */
    "A", "\n", (const char *)&d_4b4b10, (const char *)&d_4b44f0,
    (const char *)&d_4b3a30, (const char *)&d_4b7088
};

const char *d_4a6478[8] = { /* 004a6478 32 */
    "A", "\n", (const char *)&d_4b4b10, (const char *)&d_4b9f90,
    (const char *)&d_4b3a30, (const char *)&d_4b34b8, (const char *)&d_4b74c0, (const char *)&d_4b7088
};

const char *d_4a6498[8] = { /* 004a6498 32 */
    "A", (const char *)&d_4b9f90, (const char *)&d_4b91c0, (const char *)&d_4b8170,
    (const char *)&d_4b74c0, (const char *)&d_4b74c0, (const char *)&d_4b7088, 0
};

const char *d_4a64b8[8] = { /* 004a64b8 32 */
    "B", (const char *)&d_4b9f90, (const char *)&d_4b91c0, (const char *)&d_4b8170,
    (const char *)&d_4b74c0, (const char *)&d_4b74c0, (const char *)&d_4b66b0, (const char *)&d_4b7088
};

const char *d_4a64d8[6] = { /* 004a64d8 24 */
    "A", "\n", (const char *)&d_4b4b10, (const char *)&d_4ad8b0,
    (const char *)&d_4b3a30, (const char *)&d_4b7088
};

struct rec5w_f2933 d_4a64f0[2] = { /* 004a64f0 40 */
    { (void *)&d_4a5b48, (const char *)&d_4a5fc0, (void *)&d_4a6478, hid_4243f0, hid_423ae0 },
    { (void *)&d_4ab460, "\t", 0, 0, 0 }
};

struct rec5w_f2933 d_4a6518[2] = { /* 004a6518 40 */
    { (void *)&d_4a5b48, (const char *)&d_4a5fc0, (void *)&d_4a6460, hid_4243f0, hid_423ae0 },
    { (void *)&d_4ab440, "\t", 0, 0, 0 }
};

struct rec5w_f2933 d_4a6540[2] = { /* 004a6540 40 */
    { (void *)&d_4a5b48, (const char *)&d_4a5fc0, (void *)&d_4a6438, hid_4243f0, hid_424130 },
    { (void *)&d_4ab448, "\t", 0, 0, 0 }
};

struct rec5w_f2933 d_4a6568[2] = { /* 004a6568 40 */
    { (void *)&d_4a5b48, (const char *)&d_4a5fc0, (void *)&d_4a6498, hid_4243f0, disassemble_l1 },
    { (void *)&d_4ab420, "\t", 0, 0, 0 }
};

struct rec5w_f2933 d_4a6590[2] = { /* 004a6590 40 */
    { (void *)&d_4a5b48, (const char *)&d_4a5fc0, (void *)&d_4a64b8, hid_4243f0, hid_424130 },
    { (void *)&d_4ab428, "\t", 0, 0, 0 }
};

struct rec5w_f2933 d_4a65b8[2] = { /* 004a65b8 40 */
    { (void *)&d_4a5b48, (const char *)&d_4a5fc0, (void *)&d_4a64d8, hid_4243f0, hid_423ae0 },
    { (void *)&d_4ab430, "\t", 0, 0, 0 }
};

struct rec9w_45e23 d_4a65e0[1] = { /* 004a65e0 36 */
    { (void *)&d_4a5b48, (void *)&d_4a5fc0, (void *)&d_4a64d8, hid_4243f0, hid_423ae0, (void *)&d_4ab438, "\t", 0, 0 }
};
