"""Propagate CRT function/data names between binaries built with the same CRT.

Every function is fingerprinted by its x86 instruction stream with absolute
addresses and call/jump targets masked.  Functions with identical fingerprints
in a named binary and an unnamed binary receive the same name; masked operand
values of matched functions are paired to carry data-object names as well.

usage: crtmatch.py <names file> <src exe> <src export dir> <dst exe> <dst export dir> <out names file>
names file lines: addr<TAB>F|D<TAB>name<TAB>type<TAB>confidence   (# = comment)
"""
import sys, re, hashlib, collections, capstone
sys.path.insert(0, __file__.rsplit("\\", 1)[0].rsplit("/", 1)[0])
from x86dis import load, reader

MD = capstone.Cs(capstone.CS_ARCH_X86, capstone.CS_MODE_32)
HEX = re.compile(r"0x[0-9a-f]+")

def funcs_of(expdir):
    fs = []
    for l in open(expdir + "/functions.txt", encoding="utf-8"):
        p = l.rstrip("\n").split("\t")
        fs.append((int(p[0], 16), p[1], int(p[2][5:])))
    fs.sort()
    return fs

def fingerprint(rd, entry, end, lo, hi):
    """returns (hash, list of masked absolute values in order)"""
    code = rd(entry, end - entry)
    if not code:
        return None, []
    toks, vals = [], []
    for ins in MD.disasm(code, entry):
        op = ins.op_str
        if ins.mnemonic == "call" or ins.mnemonic.startswith("j"):
            m = HEX.fullmatch(op)
            if m:
                t = int(op, 16)
                if entry <= t < end:
                    op = "L%x" % (t - entry)
                else:
                    vals.append(("c", t)); op = "EXT"
        def sub(m):
            v = int(m.group(), 16)
            if lo <= v < hi:
                vals.append(("d", v)); return "ABS"
            return m.group()
        op = HEX.sub(sub, op)
        toks.append(ins.mnemonic + " " + op)
        if ins.mnemonic in ("ret", "jmp") and ins.address + ins.size >= end:
            break
    return hashlib.sha1("\n".join(toks).encode()).hexdigest(), vals

def index(exe, expdir):
    d, base, secs = load(exe)
    rd = reader(d, secs)
    hi = max(s[0] + s[1] for s in secs)
    fs = funcs_of(expdir)
    out = {}
    for i, (a, n, sz) in enumerate(fs):
        nxt = fs[i + 1][0] if i + 1 < len(fs) else a + sz
        end = min(nxt, a + max(sz, 1))
        h, vals = fingerprint(rd, a, end, base, hi)
        out[a] = (n, h, vals, end - a)
    return out

def main():
    namesf, sexe, sdir, dexe, ddir, outf = sys.argv[1:7]
    names = {}
    for l in open(namesf, encoding="utf-8"):
        if l.startswith("#") or not l.strip():
            continue
        p = l.rstrip("\n").split("\t")
        names[int(p[0], 16)] = p
    src, dst = index(sexe, sdir), index(dexe, ddir)
    byhash = collections.defaultdict(list)
    for a, (n, h, vals, sz) in dst.items():
        if h and sz >= 6:
            byhash[h].append(a)
    srccount = collections.Counter(h for n, h, vals, sz in src.values())
    result = {}
    datamap = collections.defaultdict(collections.Counter)
    for a, (n, h, vals, sz) in src.items():
        cands = byhash.get(h, [])
        if len(cands) != 1 or srccount[h] != 1:
            continue
        b = cands[0]
        if a in names and dst[b][0].startswith("FUN_"):
            p = names[a]
            result[b] = [("%08x" % b), p[1], p[2], p[3], p[4] if len(p) > 4 else "", "from %08x" % a]
        for (ka, va), (kb, vb) in zip(vals, dst[b][2]):
            if ka == kb:
                datamap[va][vb] += 1
    # data objects and called functions reached through matched code
    for a, p in names.items():
        if a in datamap:
            b, cnt = datamap[a].most_common(1)[0]
            if b not in result:
                result[b] = [("%08x" % b), p[1], p[2], p[3], p[4] if len(p) > 4 else "", "via refs %08x x%d" % (a, cnt)]
    with open(outf, "w", encoding="utf-8") as fp:
        fp.write("# generated by crtmatch.py from %s\n" % namesf)
        for b in sorted(result):
            fp.write("\t".join(result[b]) + "\n")
    print("%s: %d names propagated (%d of %d source names)" % (outf, len(result), len(result), len(names)))

if __name__ == "__main__":
    main()
