"""Generate src/sim56000/simproto.h: extern prototypes of all named SIM56000 functions,
grouped by the corrected module map (re/notes/SIM56000/filemap.txt).

The prototypes are those of the naming pass (re/names/SIM56000.names.txt); 32-bit `int` of the
original is written `long` (portable rule: anything wider than 16 bits is long).  Functions
without a prototype (the mechanically named table handlers) are listed in a comment only.
usage: genproto_sim.py [--check]
"""
import os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.join(ROOT, "re", "scripts"))

mods = []
for l in open(os.path.join(ROOT, "re", "notes", "SIM56000", "filemap.txt")):
    if l.startswith("#") or not l.strip():
        continue
    p = l.rstrip("\n").split("\t")
    mods.append((int(p[0], 16), p[1], p[4]))
mods.sort()


def modof(a):
    m = None
    for s, n, _ in mods:
        if a >= s:
            m = n
    return m


funcs = {}
for l in open(os.path.join(ROOT, "re", "names", "SIM56000.names.txt"), encoding="utf-8"):
    if l.startswith("#") or not l.strip():
        continue
    p = l.rstrip("\n").split("\t")
    if p[1] == "F":
        funcs[int(p[0], 16)] = (p[2], p[3] if len(p) > 3 else "")


def conv(proto):
    proto = re.sub(r"\bunsigned int\b", "unsigned long", proto)
    proto = re.sub(r"\bint\b", "long", proto)
    return proto


out = ["/* simproto.h - GENERATED by re/scripts/genproto_sim.py from the naming pass; do not edit.",
       "   Draft prototypes of every named SIM56000 function, grouped by module.  The original's 32-bit",
       "   `int` is written `long`.  Argument names are Ghidra's; refine them when translating. */",
       "#ifndef SIMPROTO_H", "#define SIMPROTO_H", ""]
bymod = {}
for a in sorted(funcs):
    if a >= 0x483400 or funcs[a][0] == "main":
        continue
    bymod.setdefault(modof(a), []).append(a)
for s, n, desc in mods:
    if n == "crt" or n not in bymod:
        continue
    out.append("/* ---- module %s (0x%06x): %s */" % (n, s, desc))
    noproto = []
    for a in bymod[n]:
        name, proto = funcs[a]
        if not proto:
            noproto.append("%s@%06x" % (name, a))
            continue
        out.append("extern %s; /* %06x */" % (conv(proto), a))
    if noproto:
        out.append("/* no prototype yet: %s */" % " ".join(noproto))
    out.append("")
out.append("#endif")
text = "\n".join(out) + "\n"
path = os.path.join(ROOT, "src", "sim56000", "simproto.h")
if len(sys.argv) > 1 and sys.argv[1] == "--check":
    sys.exit(0 if os.path.exists(path) and open(path, encoding="latin-1").read() == text else 1)
open(path, "w", encoding="latin-1", newline="\n").write(text)
print("wrote", path, sum(len(v) for v in bymod.values()), "functions")
