"""Generate src/dsplnk/abilextb.h and src/dsplnk/abipartb.h from DSPLNK.EXE.

The flex (abilex.c) and yacc (abiparse.c) tables of the ABI expression
parser are read from the .data section of re/bin/DSPLNK.EXE.
usage: gentab_abi.py            write the two headers
       gentab_abi.py --check    compare instead of writing
"""
import os, struct, sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.join(ROOT, "re", "scripts"))
from x86dis import load, reader        # noqa: E402

EXE = os.path.join(ROOT, "re", "bin", "DSPLNK.EXE")
OUT = os.path.join(ROOT, "src", "dsplnk")
_d, _base, _secs = load(EXE)
rd = reader(_d, _secs)


def s16(a): return struct.unpack("<h", rd(a, 2))[0]
def s32(a): return struct.unpack("<i", rd(a, 4))[0]


def arr(name, ctype, vals, per=10):
    out = ["static const %s %s[%d] = {" % (ctype, name, len(vals))]
    for i in range(0, len(vals), per):
        out.append("    " + ", ".join(str(v) for v in vals[i:i + per]) + ",")
    out[-1] = out[-1].rstrip(",")
    out.append("};")
    return "\n".join(out) + "\n"


def tab16(a, n): return [s16(a + 2 * i) for i in range(n)]
def tab32(a, n): return [s32(a + 4 * i) for i in range(n)]


HDR = """/*
 * DSPLNK linker (CLAS56 v6.3, DSP Linker 6.3.7), %s
 * GENERATED by re/scripts/gentab_abi.py from re/bin/DSPLNK.EXE - do not edit.
 * %s
 */
"""


def lextb():
    s = HDR % ("abilextb.h", "Flex scanner tables of the ABI expression language (.data 0x45bf70-0x45ceb8).")
    s += "\n#define YY_JAM_BASE 335\n#define YY_LAST_DFA 171\n\n"
    s += arr("yy_accept", "short", tab16(0x45bf70, 172), 12)
    ec = tab32(0x45c0c8, 256)
    assert all(0 <= v < 256 for v in ec)
    s += arr("yy_ec", "unsigned char", ec, 16)
    meta = tab32(0x45c4c8, 60)
    assert all(0 <= v < 256 for v in meta)
    s += arr("yy_meta", "unsigned char", meta, 16)
    s += arr("yy_base", "short", tab16(0x45c5b8, 180), 12)
    s += arr("yy_def", "short", tab16(0x45c720, 180), 12)
    s += arr("yy_nxt", "short", tab16(0x45c888, 792), 12)
    s += arr("yy_chk", "short", tab16(0x45cba0, 792), 12)
    return s


def partb():
    s = HDR % ("abipartb.h", "Yacc parser tables of the ABI expression language (.data 0x4500c0-0x451f80).")
    s += "\n#define YYLAST 1242\n#define YYFLAG (-10000000L)\n#define YYERRCODE 256\n#define YYNSTATES 178\n#define YYNRULES 78\n\n"
    s += arr("yyexca", "short", tab32(0x4500c0, 6), 6)
    s += arr("yyact", "short", tab32(0x4500d8, 1242), 12)
    s += arr("yypact", "long", tab32(0x451440, 178), 8)
    s += arr("yypgo", "short", tab32(0x451708, 30), 12)
    s += arr("yyr1", "short", tab32(0x451780, 78), 12)
    s += arr("yyr2", "short", tab32(0x4518b8, 78), 12)
    s += arr("yychk", "long", tab32(0x4519f0, 178), 12)
    s += arr("yydef", "short", tab32(0x451cb8, 178), 12)
    return s


def main():
    files = {"abilextb.h": lextb(), "abipartb.h": partb()}
    bad = 0
    for n, t in files.items():
        p = os.path.join(OUT, n)
        if "--check" in sys.argv:
            if not os.path.exists(p) or open(p).read() != t:
                print("differs:", n); bad = 1
        else:
            open(p, "w", newline="\n").write(t)
    return bad


sys.exit(main())
