; data ALU instructions, no parallel moves, every operand combination
        opt     cex
        org     p:$40
        abs     a
        abs     b
        adc     x,a
        adc     y,a
        adc     x,b
        adc     y,b
        add     x0,a
        add     x1,a
        add     y0,a
        add     y1,a
        add     x,a
        add     y,a
        add     b,a
        add     x0,b
        add     x1,b
        add     y0,b
        add     y1,b
        add     x,b
        add     y,b
        add     a,b
        addl    b,a
        addl    a,b
        addr    b,a
        addr    a,b
        and     x0,a
        and     x1,a
        and     y0,a
        and     y1,a
        and     x0,b
        and     x1,b
        and     y0,b
        and     y1,b
        asl     a
        asl     b
        asr     a
        asr     b
        clr     a
        clr     b
        cmp     x0,a
        cmp     x1,a
        cmp     y0,a
        cmp     y1,a
        cmp     b,a
        cmp     x0,b
        cmp     x1,b
        cmp     y0,b
        cmp     y1,b
        cmp     a,b
        cmpm    x0,a
        cmpm    x1,a
        cmpm    y0,a
        cmpm    y1,a
        cmpm    b,a
        cmpm    x0,b
        cmpm    y1,b
        cmpm    a,b
        eor     x0,a
        eor     x1,a
        eor     y0,b
        eor     y1,b
        lsl     a
        lsl     b
        lsr     a
        lsr     b
        neg     a
        neg     b
        not     a
        not     b
        or      x0,a
        or      x1,a
        or      y0,b
        or      y1,b
        rnd     a
        rnd     b
        rol     a
        rol     b
        ror     a
        ror     b
        sbc     x,a
        sbc     y,a
        sbc     x,b
        sbc     y,b
        sub     x0,a
        sub     x1,a
        sub     y0,a
        sub     y1,a
        sub     x,a
        sub     y,a
        sub     b,a
        sub     x0,b
        sub     x1,b
        sub     y0,b
        sub     y1,b
        sub     x,b
        sub     y,b
        sub     a,b
        subl    b,a
        subl    a,b
        subr    b,a
        subr    a,b
        tfr     x0,a
        tfr     x1,a
        tfr     y0,a
        tfr     y1,a
        tfr     b,a
        tfr     x0,b
        tfr     x1,b
        tfr     y0,b
        tfr     y1,b
        tfr     a,b
        tst     a
        tst     b
; multiplier: every QQQ pair, both signs, both destinations
        mpy     x0,x0,a
        mpy     y0,y0,a
        mpy     x1,x0,a
        mpy     y1,y0,a
        mpy     x0,y1,a
        mpy     y0,x0,a
        mpy     x1,y0,a
        mpy     y1,x1,a
        mpy     x0,x1,b
        mpy     y0,y1,b
        mpy     y1,x0,b
        mpy     x0,y0,b
        mpy     y0,x1,b
        mpy     x1,y1,b
        mpy     -x0,x0,a
        mpy     +y1,x1,b
        mpy     -x1,y0,b
        mpyr    x0,x0,a
        mpyr    -y1,x1,b
        mpyr    +x1,y0,a
        mac     x0,x0,a
        mac     y0,y0,b
        mac     x1,x0,a
        mac     -y1,y0,b
        mac     +x0,y1,a
        mac     -y0,x0,b
        mac     x1,y0,a
        mac     y1,x1,b
        macr    x0,x0,a
        macr    -y0,y0,b
        macr    x1,x0,b
        macr    +y1,x1,a
        end
