        section T
        xdef    lab
lab     nop
        dc      lab+0
        dc      lab+1
        dc      lab+2
        dc      lab+3
        dc      lab+4
        dc      lab+5
        dc      lab+6
        dc      lab+7
        dc      lab+8
        dc      lab+9
        dc      lab+10
        dc      lab+11
        dc      lab+12
        dc      lab+13
        dc      lab+14
        dc      lab+15
        dc      lab+16
        dc      lab+17
        dc      lab+18
        dc      lab+19
        dc      lab+20
        dc      lab+21
        dc      lab+22
        dc      lab+23
        dc      lab+24
        dc      lab+25
        dc      lab+26
        dc      lab+27
        dc      lab+28
        dc      lab+29
        dc      lab+30
        dc      lab+31
        dc      lab+32
        dc      lab+33
        dc      lab+34
        dc      lab+35
        dc      lab+36
        dc      lab+37
        dc      lab+38
        dc      lab+39
        dc      lab+40
        dc      lab+41
        dc      lab+42
        dc      lab+43
        dc      lab+44
        dc      lab+45
        dc      lab+46
        dc      lab+47
        dc      lab+48
        dc      lab+49
        dc      lab+50
        dc      lab+51
        dc      lab+52
        dc      lab+53
        dc      lab+54
        dc      lab+55
        dc      lab+56
        dc      lab+57
        dc      lab+58
        dc      lab+59
        dc      lab+60
        dc      lab+61
        dc      lab+62
        dc      lab+63
        endsec
        end
